Repository kubernetes-sigs/azurefile-csi-driver, pull requests merged in 2019-03, with the labels that each got.

#35 add owners
  OWNERS
  OWNERS_ALIASES
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, size/S

#47 enhance(version): Add version flag in azurefile plugin
  Gopkg.lock
  Makefile
  pkg/azurefile/azurefile.go
  pkg/azurefile/version.go
  pkg/azurefileplugin/main.go
Labels: approved, cncf-cla: yes, kind/feature, lgtm, size/L

#46 fix(klog): fix info values not getting printed with klog
  pkg/azurefileplugin/main.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, size/XS
