Repository kubernetes-sigs/azurefile-csi-driver, pull requests merged in 2019-12, with the labels that each got.

#141 Keep helm chart in sync with manifests in deploy folder
  Makefile
  charts/latest/azurefile-csi-driver/templates/csi-azurefile-controller.yaml
  charts/latest/azurefile-csi-driver/templates/csi-azurefile-node.yaml
  charts/latest/azurefile-csi-driver/values.yaml
  deploy/csi-azurefile-node.yaml
  hack/verify-all.sh
  hack/verify-helm-chart.sh
Labels: approved, cncf-cla: yes, kind/test, lgtm, size/L

#144 test: Run e2e test suite with JUnit reporter
  test/e2e/suite_test.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#145 Enable spell checking and fix spelling issues
  docs/dependency-management.md
  hack/verify-all.sh
  hack/verify-spelling.sh
  pkg/azurefile/azurefile.go
  test/utils/credentials/credentials.go
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, size/M

#146 Enable leader election in csi components
  .gitignore
  charts/README.md
  charts/latest/azurefile-csi-driver/templates/csi-azurefile-controller.yaml
  charts/latest/azurefile-csi-driver/templates/rbac-csi-azurefile-controller.yaml
  charts/latest/azurefile-csi-driver/values.yaml
  deploy/csi-azurefile-controller.yaml
  deploy/rbac-csi-azurefile-controller.yaml
Labels: approved, cncf-cla: yes, kind/feature, lgtm, ok-to-test, size/M

#147 test: remove travis CI since already have test-infra CI
  .travis.yml
Labels: approved, cncf-cla: yes, kind/test, size/S

#149 fix: Rename test suites to pass linting
  test/e2e/dynamic_provisioning_test.go
  test/e2e/pre_provisioning_test.go
Labels: approved, cncf-cla: yes, kind/failing-test, lgtm, size/XS

#148 chore: use base-ubuntu image from mcr and tiny docs change
  docs/install-csi-driver-master.md
  docs/install-csi-driver-v0.2.0.md
  docs/install-csi-driver-v0.3.0.md
  pkg/azurefileplugin/Dockerfile
Labels: approved, cncf-cla: yes, kind/flake, lgtm, ok-to-test, size/S
