Repository kubernetes-sigs/azurefile-csi-driver, pull requests merged in 2019-04, with the labels that each got.

#50 refactor(version): remove injection of driver name from makefile
  Makefile
  pkg/azurefile/azurefile.go
  pkg/azurefile/version.go
Labels: approved, cncf-cla: yes, kind/feature, lgtm, size/XS

#51 fix sanity test DeleteVolume failure
  pkg/azurefile/controllerserver.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, size/XS

#52 fix the wrong unit in CreateVolume
  pkg/azurefile/controllerserver.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, size/XS

#56 use GetStorageAccesskey from azure lib
  pkg/azurefile/azure.go
  pkg/azurefile/controllerserver.go
  pkg/azurefile/nodeserver.go
Labels: approved, cncf-cla: yes, kind/cleanup, size/M

#58 enhance(MakeFile): adds `e2e-test` target in MakeFile
  Makefile
  hack/run-e2e-test.sh
Labels: approved, cncf-cla: yes, kind/feature, lgtm, size/M

#63 refactor(makefile): rename `test-update` target to `verify-modules`
  .travis.yml
  Makefile
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, size/L
