Repository kubernetes-sigs/azurefile-csi-driver, pull requests merged in 2019-10, with the labels that each got.

#122 chore: Update csi-sanity
  go.mod
  pkg/azurefile/nodeserver.go
  test/sanity/run-test.sh
  test/sanity/run-tests-all-clouds.sh
Labels: approved, cncf-cla: yes, kind/bug, kind/flake, lgtm, ok-to-test, size/S

#120 Enable E2E tests on kubernetes/test-infra
  .travis.yml
  Makefile
  hack/template/azure.json
  test/e2e/README.md
  test/e2e/dynamic_provisioning.go
  test/e2e/pre_provisioning.go
  test/e2e/run-test.sh
  test/e2e/suite_test.go
  test/integration/integration_test.go
  test/integration/run-test.sh
  test/integration/run-tests-all-clouds.sh
  test/sanity/run-test.sh
  test/sanity/run-tests-all-clouds.sh
  test/sanity/sanity_test.go
  test/utils/azure/azure_helpers.go
  test/utils/credentials/credentials.go
  test/utils/credentials/credentials_test.go
  test/utils/testutil/testutil.go
Labels: approved, cncf-cla: yes, kind/cleanup, kind/test, lgtm, ok-to-test, size/L

#121 feat: support VolumeExpansion in OFFLINE scenario
  pkg/azurefile/azurefile.go
  pkg/azurefile/controllerserver.go
Labels: approved, cncf-cla: yes, kind/feature, lgtm, ok-to-test, size/M

#123 feat: support VolumeExpansion in ONLINE scenario
  pkg/azurefile/azurefile.go
  pkg/azurefile/controllerserver.go
  pkg/azurefile/nodeserver.go
  pkg/csi-common/driver.go
Labels: approved, cncf-cla: yes, kind/feature, lgtm, ok-to-test, size/M

#124 doc: add build-push make command
  Makefile
  README.md
Labels: approved, cncf-cla: yes, kind/documentation, size/S

#126 fix: use secure ubuntu image
  pkg/azurefileplugin/Dockerfile
Labels: approved, cncf-cla: yes, kind/bug, lgtm, size/XS

#127 Change repo address name
  .travis.yml
  Makefile
  charts/README.md
  go.mod
  pkg/azurefile/azurefile.go
  pkg/azurefile/controllerserver.go
  pkg/azurefileplugin/main.go
  test/e2e/driver/azurefile_csi_driver.go
  test/e2e/dynamic_provisioning.go
  test/e2e/pre_provisioning.go
  test/e2e/suite_test.go
  test/e2e/testsuites/dynamically_provisioned_cmd_volume_tester.go
  test/e2e/testsuites/dynamically_provisioned_collocated_pod_tester.go
  test/e2e/testsuites/dynamically_provisioned_delete_pod_tester.go
  test/e2e/testsuites/dynamically_provisioned_read_only_volume_tester.go
  test/e2e/testsuites/dynamically_provisioned_reclaim_policy_tester.go
  test/e2e/testsuites/pre_provisioned_read_only_volume_tester.go
  test/e2e/testsuites/pre_provisioned_reclaim_policy_tester.go
  test/e2e/testsuites/specs.go
  test/e2e/testsuites/testsuites.go
  test/integration/integration_test.go
  test/sanity/sanity_test.go
  test/utils/credentials/credentials.go
Labels: approved, cncf-cla: yes, lgtm, size/L
