Repository kubernetes-sigs/azurefile-csi-driver, pull requests merged in 2019-09, with the labels that each got.

#114 Fix and Improve CI
  .travis.yml
  Makefile
  go.mod
  go.sum
  hack/verify-all.sh
  hack/verify-golint.sh
Labels: approved, cncf-cla: yes, kind/test, lgtm, size/S

#113 fix: check the snapshot if it exists
  pkg/azurefile/azurefile.go
  pkg/azurefile/controllerserver.go
  test/sanity/run-test.sh
Labels: approved, cncf-cla: yes, kind/bug, lgtm, size/M

#117 doc: add volume snapshot example
  charts/latest/azurefile-csi-driver/templates/csi-azurefile-controller.yaml
  deploy/csi-azurefile-controller.yaml
  deploy/example/snapshot/README.md
  deploy/example/snapshot/volumesnapshot-azurefile.yaml
  deploy/example/snapshot/volumesnapshotclass-azurefile.yaml
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, size/M
