Repository kubernetes-sigs/azurefile-csi-driver, pull requests merged in 2019-08, with the labels that each got.

#102 Fix travis badge
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#107 doc: cut off v0.3.0 beta release
  README.md
  deploy/v0.3.0/crd-csi-driver-registry.yaml
  deploy/v0.3.0/crd-csi-node-info.yaml
  deploy/v0.3.0/csi-azurefile-controller.yaml
  deploy/v0.3.0/csi-azurefile-node.yaml
  deploy/v0.3.0/rbac-csi-azurefile-controller.yaml
  docs/install-azurefile-csi-driver.md
  docs/install-csi-driver-v0.3.0.md
  test/e2e/README.md
Labels: approved, cncf-cla: yes, kind/documentation, size/L

#108 chore: switch to v0.4.0 for master branch
  Makefile
  deploy/csi-azurefile-controller.yaml
  deploy/csi-azurefile-node.yaml
Labels: approved, cncf-cla: yes, kind/design, size/XS

#109 feat: set priority class to system critical
  deploy/csi-azurefile-controller.yaml
  deploy/csi-azurefile-node.yaml
  deploy/v0.2.0/csi-azurefile-controller.yaml
  deploy/v0.2.0/csi-azurefile-node.yaml
  deploy/v0.3.0/csi-azurefile-controller.yaml
  deploy/v0.3.0/csi-azurefile-node.yaml
Labels: approved, cncf-cla: yes, kind/feature, lgtm, size/XS

#112 feat: implement DeleteSnapshot
  .travis.yml
  Makefile
  pkg/azurefile/azurefile.go
  pkg/azurefile/azurefile_test.go
  pkg/azurefile/controllerserver.go
  test/sanity/run-test.sh
  test/sanity/run-tests-all-clouds.sh
Labels: approved, cncf-cla: yes, kind/feature, lgtm, size/L
