Repository kubernetes-sigs/azurefile-csi-driver, pull requests merged in 2020-05, with the labels that each got.

#262 chore: lower the cpu/memory limits
  charts/latest/azurefile-csi-driver/templates/csi-azurefile-controller.yaml
  charts/latest/azurefile-csi-driver/templates/csi-azurefile-node.yaml
  deploy/csi-azurefile-controller.yaml
  deploy/csi-azurefile-node.yaml
Labels: approved, cncf-cla: yes, kind/feature, size/M

#263 chore: upgrade csi-attacher to v2.2.0
  charts/latest/azurefile-csi-driver/templates/csi-azurefile-controller.yaml
  charts/latest/azurefile-csi-driver/templates/rbac-csi-azurefile-controller.yaml
  charts/latest/azurefile-csi-driver/values.yaml
  deploy/csi-azurefile-controller.yaml
  deploy/rbac-csi-azurefile-controller.yaml
Labels: approved, cncf-cla: yes, kind/feature, size/S

#269 test: remove "storageProfile" field in test config
  test/e2e/manifest/in-tree-vmss.json
  test/e2e/manifest/in-tree.json
  test/e2e/manifest/linux-vmss.json
  test/e2e/manifest/linux.json
Labels: approved, cncf-cla: yes, kind/test, size/S

#272 doc: add mountOptions
  deploy/example/pv-azurefile-csi.yaml
  hack/verify-spelling.sh
Labels: approved, cncf-cla: yes, kind/documentation, size/S

#274 fix: allow unknown parameters in CreateVolume
  pkg/azurefile/controllerserver.go
Labels: approved, cncf-cla: yes, kind/feature, size/XS

#275 Tests:Improve Unit Tests for driver and identityserver
  pkg/csi-common/driver_test.go
  pkg/csi-common/identityserver-default_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#273 chore(dockerfile/makefile): Update build process
  Makefile
  pkg/azurefileplugin/Dockerfile
  pkg/azurefileplugin/Windows.Dockerfile
Labels: approved, cncf-cla: yes, kind/feature, lgtm, ok-to-test, size/M

#276 test: change publish image script
  Makefile
  test/e2e/dynamic_provisioning_test.go
  test/e2e/suite_test.go
Labels: approved, cncf-cla: yes, size/M

#277 tests: Add unit tests
  pkg/azurefile/azurefile_test.go
  pkg/azurefile/identityserver_test.go
  pkg/csi-common/controllerserver-default_test.go
  pkg/csi-common/utils_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#284 feat: use `azure-cred-file` configmap in `kube-system` namespace to specify azure-cred-file path
  README.md
  charts/latest/azurefile-csi-driver/templates/csi-azurefile-controller.yaml
  charts/latest/azurefile-csi-driver/templates/csi-azurefile-node-windows.yaml
  charts/latest/azurefile-csi-driver/templates/csi-azurefile-node.yaml
  deploy/csi-azurefile-controller.yaml
  deploy/csi-azurefile-node-windows.yaml
  deploy/csi-azurefile-node.yaml
  pkg/azurefile/azure.go
  pkg/azurefile/azure_test.go
Labels: approved, cncf-cla: yes, kind/feature, lgtm, size/M

#285 fix: empty azure cred file env var issue
  pkg/azurefile/azure.go
Labels: approved, cncf-cla: yes, kind/bug, size/S

#287 fix: Remove redundant check for target path
  pkg/azurefile/nodeserver.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#289 Test: Add tests for azurefile
  go.mod
  pkg/azurefile/azurefile_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#288 Tests: Add unit test and run tests with root privileges
  .github/workflows/go.yml
  .travis.yml
  Makefile
  pkg/azurefile/nodeserver.go
  pkg/azurefile/nodeserver_test.go
  pkg/mounter/safe_mounter_unix_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#292 doc: set Standard_LRS as default in example
  deploy/example/storageclass-azurefile-csi-mountoptions.yaml
  deploy/example/storageclass-azurefile-csi.yaml
Labels: approved, cncf-cla: yes, kind/documentation, size/XS

#294 Charts: Refine helm installation
  charts/README.md
  charts/index.yaml
  charts/v0.2.0/azurefile-csi-driver-0.2.0.tgz
  charts/v0.3.0/azurefile-csi-driver-0.3.0.tgz
  charts/v0.4.0/azurefile-csi-driver-v0.4.0.tgz
  charts/v0.5.0/azurefile-csi-driver-v0.5.0.tgz
  charts/v0.6.0/azurefile-csi-driver-v0.6.0.tgz
  charts/v0.7.0/azurefile-csi-driver-v0.7.0.tgz
  deploy/example/snapshot/README.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#295 Tests: Add tests for Version
  pkg/azurefile/version_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#297 doc: update windows docs
  deploy/example/windows/README.md
  deploy/example/windows/deployment.yaml
  deploy/example/windows/statefulset.yaml
Labels: approved, cncf-cla: yes, kind/documentation, size/M
