Repository kubernetes-sigs/azurefile-csi-driver, pull requests merged in 2020-04, with the labels that each got.

#230 test: deflake deployment test case
  test/e2e/dynamic_provisioning_test.go
  test/e2e/testsuites/dynamically_provisioned_delete_pod_tester.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#231 chore: remove cluster driver registrar
  charts/latest/azurefile-csi-driver/templates/crd-csi-driver-registry.yaml
  charts/latest/azurefile-csi-driver/templates/csi-azurefile-controller.yaml
  charts/latest/azurefile-csi-driver/templates/csi-azurefile-driver.yaml
  charts/latest/azurefile-csi-driver/values.yaml
  deploy/crd-csi-driver-registry.yaml
  deploy/csi-azurefile-controller.yaml
  deploy/csi-azurefile-driver.yaml
  deploy/install-driver.sh
  deploy/uninstall-driver.sh
  hack/verify-helm-chart.sh
  pkg/util/util.go
  test/e2e/testsuites/testsuites.go
Labels: cncf-cla: yes, kind/cleanup, size/L

#233 fix: set cpu,memory limit to a higher value
  charts/latest/azurefile-csi-driver/templates/csi-azurefile-controller.yaml
  charts/latest/azurefile-csi-driver/templates/csi-azurefile-node.yaml
  deploy/csi-azurefile-controller.yaml
  deploy/csi-azurefile-node-windows.yaml
  deploy/csi-azurefile-node.yaml
Labels: approved, cncf-cla: yes, kind/bug, lgtm, size/M

#232 test: run CSI driver e2e tests on Windows clusters
  Makefile
  charts/README.md
  charts/latest/azurefile-csi-driver/templates/csi-azurefile-controller.yaml
  charts/latest/azurefile-csi-driver/templates/csi-azurefile-node-windows.yaml
  charts/latest/azurefile-csi-driver/templates/csi-azurefile-node.yaml
  charts/latest/azurefile-csi-driver/values.yaml
  deploy/csi-azurefile-controller.yaml
  docs/csi-debug.md
  test/e2e/dynamic_provisioning_test.go
  test/e2e/pre_provisioning_test.go
  test/e2e/testsuites/dynamically_provisioned_read_only_volume_tester.go
  test/e2e/testsuites/pre_provisioned_read_only_volume_tester.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#234 chore: add linux.enabled parameter to helm chart
  Makefile
  charts/README.md
  charts/latest/azurefile-csi-driver/templates/csi-azurefile-node.yaml
  charts/latest/azurefile-csi-driver/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#235 doc: cut v0.6.0 release
  README.md
  charts/v0.6.0/azurefile-csi-driver/Chart.yaml
  charts/v0.6.0/azurefile-csi-driver/templates/NOTES.txt
  charts/v0.6.0/azurefile-csi-driver/templates/_helpers.tpl
  charts/v0.6.0/azurefile-csi-driver/templates/crd-csi-node-info.yaml
  charts/v0.6.0/azurefile-csi-driver/templates/csi-azurefile-controller.yaml
  charts/v0.6.0/azurefile-csi-driver/templates/csi-azurefile-driver.yaml
  charts/v0.6.0/azurefile-csi-driver/templates/csi-azurefile-node-windows.yaml
  charts/v0.6.0/azurefile-csi-driver/templates/csi-azurefile-node.yaml
  charts/v0.6.0/azurefile-csi-driver/templates/rbac-csi-azurefile-controller.yaml
  charts/v0.6.0/azurefile-csi-driver/templates/serviceaccount-csi-azurefile-controller.yaml
  charts/v0.6.0/azurefile-csi-driver/values.yaml
  deploy/example/disk/README.md
  deploy/v0.6.0/crd-csi-node-info.yaml
  deploy/v0.6.0/csi-azurefile-controller.yaml
  deploy/v0.6.0/csi-azurefile-driver.yaml
  deploy/v0.6.0/csi-azurefile-node-windows.yaml
  deploy/v0.6.0/csi-azurefile-node.yaml
  deploy/v0.6.0/rbac-csi-azurefile-controller.yaml
  docs/install-azurefile-csi-driver.md
  docs/install-csi-driver-v0.6.0.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, size/XXL

#237 feat: add nostrictsync option
  pkg/azurefile/nodeserver.go
Labels: approved, cncf-cla: yes, kind/feature, lgtm, size/XS

#245 Do not install golangci-lint with 'go get'
  hack/verify-golint.sh
Labels: approved, cncf-cla: yes, kind/flake, lgtm, ok-to-test, size/XS

#248 test: fix windows e2e test failure
  test/e2e/testsuites/testsuites.go
Labels: approved, cncf-cla: yes, kind/test, size/XS

#249 fix: remove unnecessary SharedInformerFactory in unit tests
  pkg/azurefile/utils_test.go
Labels: cncf-cla: yes, kind/bug, lgtm, size/S

#244 Remove deprecated csi-provisioner args
  charts/latest/azurefile-csi-driver/templates/csi-azurefile-controller.yaml
  charts/v0.4.0/azurefile-csi-driver/templates/csi-azurefile-controller.yaml
  charts/v0.5.0/azurefile-csi-driver/templates/csi-azurefile-controller.yaml
  charts/v0.6.0/azurefile-csi-driver/templates/csi-azurefile-controller.yaml
  deploy/csi-azurefile-controller.yaml
  deploy/v0.4.0/csi-azurefile-controller.yaml
  deploy/v0.5.0/csi-azurefile-controller.yaml
  deploy/v0.6.0/csi-azurefile-controller.yaml
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, ok-to-test, size/S

#243 test: add the e2e test "use existing credentials in k8s cluster"
  pkg/azurefile/azurefile.go
  pkg/azurefile/controllerserver.go
  pkg/azurefile/nodeserver.go
  test/e2e/driver/azurefile_driver.go
  test/e2e/driver/driver.go
  test/e2e/pre_provisioning_test.go
  test/e2e/testsuites/pre_provisioned_existing_credentials_tester.go
Labels: approved, cncf-cla: yes, kind/test, lgtm, size/L

#250 test: add the e2e test "should use provided credentials"
  test/e2e/driver/azurefile_driver.go
  test/e2e/driver/driver.go
  test/e2e/pre_provisioning_test.go
  test/e2e/testsuites/pre_provisioned_existing_credentials_tester.go
  test/e2e/testsuites/pre_provisioned_provided_credentials_tester.go
  test/e2e/testsuites/specs.go
  test/e2e/testsuites/testsuites.go
Labels: approved, cncf-cla: yes, kind/test, lgtm, size/L

#251 test: switch to use busybox
  test/e2e/dynamic_provisioning_test.go
  test/e2e/testsuites/testsuites.go
Labels: approved, cncf-cla: yes, kind/test, size/S

#252 test: run e2e tests on Ubuntu 18.04
  test/e2e/manifest/linux-vmss.json
Labels: approved, cncf-cla: yes, kind/test, lgtm, size/XS

#255 chore: separate secret RBAC
  charts/latest/azurefile-csi-driver/templates/rbac-csi-azurefile-controller.yaml
  charts/latest/azurefile-csi-driver/templates/rbac-csi-azurefile-node.yaml
  deploy/install-driver.sh
  deploy/rbac-csi-azurefile-controller.yaml
  deploy/rbac-csi-azurefile-node.yaml
  deploy/rbac-csi-azurefile-secret.yaml
  deploy/uninstall-driver.sh
Labels: approved, cncf-cla: yes, kind/flake, lgtm, size/L

#257 fix: disable IMDS in controller to support MSI
  Makefile
  charts/latest/azurefile-csi-driver/templates/csi-azurefile-controller.yaml
  deploy/csi-azurefile-controller.yaml
  pkg/azurefile/azurefile.go
  pkg/azurefileplugin/main.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, size/S
