Repository kubernetes-sigs/azurefile-csi-driver, pull requests merged in 2020-03, with the labels that each got.

#172 fix boilerplate issue
  CHANGELOG-v0.1.0-alpha.md
  CHANGELOG-v0.2.0-alpha.md
  Makefile
  deploy/example/deployment.yaml
  deploy/example/pvc-azurefile-csi.yaml
  deploy/example/statefulset.yaml
  deploy/example/storageclass-azurefile-csi-mountoptions.yaml
  deploy/example/storageclass-azurefile-csi.yaml
  test/e2e/pre_provisioning_test.go
  test/e2e/testsuites/dynamically_provisioned_collocated_pod_tester.go
  test/e2e/testsuites/dynamically_provisioned_delete_pod_tester.go
  test/e2e/testsuites/dynamically_provisioned_read_only_volume_tester.go
  test/e2e/testsuites/dynamically_provisioned_reclaim_policy_tester.go
  test/e2e/testsuites/pre_provisioned_read_only_volume_tester.go
  test/e2e/testsuites/pre_provisioned_reclaim_policy_tester.go
  test/utils/azure/azure_helpers.go
  test/utils/credentials/credentials.go
  test/utils/credentials/credentials_test.go
  test/utils/testutil/testutil.go
Labels: approved, cncf-cla: yes, kind/test, lgtm, size/L

#173 fix: correct the behavior of deleting the target direcotory
  pkg/azurefile/nodeserver.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, size/S

#174 fix: support corrupted mount
  charts/latest/azurefile-csi-driver/templates/csi-azurefile-controller.yaml
  deploy/csi-azurefile-controller.yaml
  docs/csi-dev.md
  pkg/azurefile/azurefile.go
  pkg/azurefile/azurefile_test.go
  pkg/azurefile/nodeserver.go
  test/utils/azurefile_log.sh
Labels: approved, cncf-cla: yes, kind/feature, lgtm, size/M

#175 test: add the e2e test "should create a volume on demand and resize it"
  test/e2e/driver/driver.go
  test/e2e/dynamic_provisioning_test.go
  test/e2e/testsuites/dynamically_provisioned_resize_volume_tester.go
Labels: approved, cncf-cla: yes, kind/test, lgtm, size/L

#176 feat: provides initial support for vhd disk mount on azure file
  charts/latest/azurefile-csi-driver/templates/csi-azurefile-node.yaml
  deploy/csi-azurefile-node.yaml
  pkg/azurefile/azurefile.go
  pkg/azurefile/controllerserver.go
  pkg/azurefile/nodeserver.go
Labels: approved, cncf-cla: yes, kind/feature, lgtm, size/L

#177 fix: only mount dir when not mounted in NodeStage
  pkg/azurefile/nodeserver.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, size/M

#178 feat: add dynamic VHD disk support
  go.mod
  pkg/azurefile/azurefile.go
  pkg/azurefile/controllerserver.go
  pkg/azurefile/nodeserver.go
Labels: approved, cncf-cla: yes, kind/feature, lgtm, size/L

#179 test: add vhd disk e2e test
  Makefile
  hack/verify-all.sh
  pkg/azurefile/azurefile.go
  pkg/azurefile/controllerserver.go
  test/e2e/dynamic_provisioning_test.go
  test/e2e/testsuites/dynamically_provisioned_cmd_volume_tester.go
  test/e2e/testsuites/dynamically_provisioned_collocated_pod_tester.go
  test/e2e/testsuites/dynamically_provisioned_invalid_mount_options.go
  test/e2e/testsuites/dynamically_provisioned_read_only_volume_tester.go
  test/e2e/testsuites/dynamically_provisioned_reclaim_policy_tester.go
  test/e2e/testsuites/dynamically_provisioned_resize_volume_tester.go
  test/e2e/testsuites/specs.go
Labels: approved, cncf-cla: yes, kind/test, size/L

#180 fix: create vhd pipline timeout issue
  pkg/azurefile/azurefile.go
  pkg/azurefile/controllerserver.go
  pkg/azurefile/nodeserver.go
  pkg/azurefileplugin/Dockerfile
  test/e2e/dynamic_provisioning_test.go
Labels: approved, cncf-cla: yes, kind/bug, size/L

#187 test: add one negative e2e case for vhd disk feature
  test/e2e/dynamic_provisioning_test.go
Labels: approved, cncf-cla: yes, kind/test, lgtm, size/M

#189 chore: change volumeid format to include diskname
  pkg/azurefile/azurefile.go
  pkg/azurefile/azurefile_test.go
  pkg/azurefile/controllerserver.go
  pkg/azurefile/nodeserver.go
Labels: approved, cncf-cla: yes, kind/feature, size/L

#190 test: add deployment e2e test
  deploy/example/disk/README.md
  deploy/example/disk/pvc-azurefile-disk.yaml
  test/e2e/dynamic_provisioning_test.go
  test/e2e/testsuites/dynamically_provisioned_delete_pod_tester.go
  test/e2e/testsuites/specs.go
Labels: approved, cncf-cla: yes, kind/test, lgtm, size/M

#191 fix: use PVC size for vhd disk
  pkg/azurefile/controllerserver.go
Labels: approved, cncf-cla: yes, size/XS

#192 chore: refactor createDisk func
  pkg/azurefile/azurefile.go
  pkg/azurefile/controllerserver.go
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, size/M

#194 test: remove fsType parameter for one test case
  test/e2e/dynamic_provisioning_test.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#195 Fast attach disk doc
  README.md
  deploy/example/disk/README.md
  deploy/example/disk/statefulset-stress.yaml
Labels: approved, cncf-cla: yes, kind/documentation, size/M

#196 fix: add retry in create file share
  pkg/azurefile/azurefile.go
  pkg/azurefile/controllerserver.go
Labels: approved, cncf-cla: yes, kind/bug, size/S

#197 feat: add lock for create storage account
  deploy/example/disk/README.md
  deploy/example/disk/statefulset-stress.yaml
  deploy/install-driver-standalone.sh
  deploy/uninstall-driver-standalone.sh
  docs/install-csi-driver-master.md
  pkg/azurefile/controllerserver.go
Labels: approved, cncf-cla: yes, kind/bug, size/L

#198 fix: set vhd name as fileshare name
  README.md
  deploy/example/disk/README.md
  deploy/example/disk/statefulset-stress.yaml
  pkg/azurefile/controllerserver.go
Labels: approved, cncf-cla: yes, kind/bug, size/M

#199 fix: throttling issue when creating file share
  pkg/azurefile/azurefile.go
  pkg/azurefile/controllerserver.go
Labels: approved, cncf-cla: yes, kind/bug, size/S

#206 chore: cut v0.5.0 release
  README.md
  charts/v0.5.0/azurefile-csi-driver/Chart.yaml
  charts/v0.5.0/azurefile-csi-driver/templates/NOTES.txt
  charts/v0.5.0/azurefile-csi-driver/templates/_helpers.tpl
  charts/v0.5.0/azurefile-csi-driver/templates/crd-csi-driver-registry.yaml
  charts/v0.5.0/azurefile-csi-driver/templates/crd-csi-node-info.yaml
  charts/v0.5.0/azurefile-csi-driver/templates/csi-azurefile-controller.yaml
  charts/v0.5.0/azurefile-csi-driver/templates/csi-azurefile-node.yaml
  charts/v0.5.0/azurefile-csi-driver/templates/rbac-csi-azurefile-controller.yaml
  charts/v0.5.0/azurefile-csi-driver/templates/serviceaccount-csi-azurefile-controller.yaml
  charts/v0.5.0/azurefile-csi-driver/values.yaml
  deploy/install-driver-standalone.sh
  deploy/uninstall-driver-standalone.sh
  deploy/v0.5.0/crd-csi-driver-registry.yaml
  deploy/v0.5.0/crd-csi-node-info.yaml
  deploy/v0.5.0/csi-azurefile-controller.yaml
  deploy/v0.5.0/csi-azurefile-node.yaml
  deploy/v0.5.0/rbac-csi-azurefile-controller.yaml
  docs/install-azurefile-csi-driver.md
  docs/install-csi-driver-v0.5.0.md
  test/e2e/dynamic_provisioning_test.go
  test/integration/run-test.sh
  test/integration/run-tests-all-clouds.sh
Labels: approved, cncf-cla: yes, kind/feature, lgtm, size/XXL

#207 test: enable sanity test for vhd disk feature
  pkg/azurefile/azurefile.go
  pkg/azurefile/controllerserver.go
  test/integration/run-test.sh
  test/integration/run-tests-all-clouds.sh
  test/sanity/run-test.sh
  test/sanity/run-tests-all-clouds.sh
Labels: approved, cncf-cla: yes, kind/test, lgtm, size/M

#212 feat: support multi-node readonly
  pkg/azurefile/controllerserver.go
Labels: approved, cncf-cla: yes, do-not-merge/hold, kind/feature, size/M

#214 fix: volumeid compatibility issue
  pkg/azurefile/azurefile.go
  pkg/azurefile/azurefile_test.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, size/S

#216 fix: make node daemonset ignore taint
  charts/latest/azurefile-csi-driver/templates/csi-azurefile-node.yaml
  deploy/csi-azurefile-node.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#215 Add e2e test support for Windows clusters
  Makefile
  test/e2e/README.md
  test/e2e/driver/azurefile_driver.go
  test/e2e/driver/driver.go
  test/e2e/dynamic_provisioning_test.go
  test/e2e/manifest/in-tree-vmss.json
  test/e2e/manifest/in-tree.json
  test/e2e/manifest/linux-vmss.json
  test/e2e/manifest/linux.json
  test/e2e/pre_provisioning_test.go
  test/e2e/suite_test.go
  test/e2e/testsuites/dynamically_provisioned_read_only_volume_tester.go
  test/e2e/testsuites/specs.go
  test/e2e/testsuites/testsuites.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#217 chore: replace beta label to GA label for kubernetes.io/os
  charts/latest/azurefile-csi-driver/templates/csi-azurefile-controller.yaml
  charts/latest/azurefile-csi-driver/templates/csi-azurefile-node.yaml
  charts/v0.2.0/azurefile-csi-driver/templates/csi-azurefile-controller.yaml
  charts/v0.2.0/azurefile-csi-driver/templates/csi-azurefile-node.yaml
  charts/v0.3.0/azurefile-csi-driver/templates/csi-azurefile-controller.yaml
  charts/v0.3.0/azurefile-csi-driver/templates/csi-azurefile-node.yaml
  charts/v0.4.0/azurefile-csi-driver/templates/csi-azurefile-controller.yaml
  charts/v0.4.0/azurefile-csi-driver/templates/csi-azurefile-node.yaml
  charts/v0.5.0/azurefile-csi-driver/templates/csi-azurefile-controller.yaml
  charts/v0.5.0/azurefile-csi-driver/templates/csi-azurefile-node.yaml
  deploy/csi-azurefile-controller.yaml
  deploy/csi-azurefile-node.yaml
  deploy/v0.2.0/csi-azurefile-controller.yaml
  deploy/v0.2.0/csi-azurefile-node.yaml
  deploy/v0.3.0/csi-azurefile-controller.yaml
  deploy/v0.3.0/csi-azurefile-node.yaml
  deploy/v0.4.0/csi-azurefile-controller.yaml
  deploy/v0.4.0/csi-azurefile-node.yaml
  deploy/v0.5.0/csi-azurefile-controller.yaml
  deploy/v0.5.0/csi-azurefile-node.yaml
  test/e2e/testsuites/testsuites.go
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, size/M

#218 chore: upgrade node-driver-registrar version
  charts/latest/azurefile-csi-driver/values.yaml
  deploy/csi-azurefile-node.yaml
Labels: approved, cncf-cla: yes, kind/feature, lgtm, size/XS

#219 fix: change imagePullPolicy to IfNotPresent
  charts/latest/azurefile-csi-driver/templates/csi-azurefile-controller.yaml
  charts/latest/azurefile-csi-driver/templates/csi-azurefile-node.yaml
  charts/latest/azurefile-csi-driver/values.yaml
  charts/v0.2.0/azurefile-csi-driver/templates/csi-azurefile-controller.yaml
  charts/v0.2.0/azurefile-csi-driver/templates/csi-azurefile-node.yaml
  charts/v0.2.0/azurefile-csi-driver/values.yaml
  charts/v0.3.0/azurefile-csi-driver/templates/csi-azurefile-controller.yaml
  charts/v0.3.0/azurefile-csi-driver/templates/csi-azurefile-node.yaml
  charts/v0.3.0/azurefile-csi-driver/values.yaml
  charts/v0.4.0/azurefile-csi-driver/templates/csi-azurefile-controller.yaml
  charts/v0.4.0/azurefile-csi-driver/templates/csi-azurefile-node.yaml
  charts/v0.4.0/azurefile-csi-driver/values.yaml
  charts/v0.5.0/azurefile-csi-driver/templates/csi-azurefile-controller.yaml
  charts/v0.5.0/azurefile-csi-driver/templates/csi-azurefile-node.yaml
  charts/v0.5.0/azurefile-csi-driver/values.yaml
  deploy/csi-azurefile-controller.yaml
  deploy/csi-azurefile-node.yaml
  deploy/v0.2.0/csi-azurefile-controller.yaml
  deploy/v0.2.0/csi-azurefile-node.yaml
  deploy/v0.3.0/csi-azurefile-controller.yaml
  deploy/v0.3.0/csi-azurefile-node.yaml
  deploy/v0.4.0/csi-azurefile-controller.yaml
  deploy/v0.4.0/csi-azurefile-node.yaml
  deploy/v0.5.0/csi-azurefile-controller.yaml
  deploy/v0.5.0/csi-azurefile-node.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#220 doc: add windows feature doc
  README.md
  deploy/csi-azurefile-node-windows.yaml
  deploy/example/windows/README.md
  deploy/example/windows/deployment.yaml
  deploy/example/windows/statefulset.yaml
  deploy/install-driver-standalone.sh
  docs/install-csi-driver-master.md
  hack/verify-yamllint.sh
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, size/L

#225 feat: support read cloud config from secret
  charts/latest/azurefile-csi-driver/templates/rbac-csi-azurefile-controller.yaml
  deploy/rbac-csi-azurefile-controller.yaml
Labels: approved, cncf-cla: yes, kind/feature, lgtm, size/M

#226 fix: add read cloud config from secret permission for node
  charts/README.md
  charts/latest/azurefile-csi-driver/templates/csi-azurefile-node.yaml
  charts/latest/azurefile-csi-driver/templates/rbac-csi-azurefile-controller.yaml
  charts/latest/azurefile-csi-driver/templates/serviceaccount-csi-azurefile-controller.yaml
  deploy/csi-azurefile-node-windows.yaml
  deploy/csi-azurefile-node.yaml
  deploy/install-driver.sh
  deploy/rbac-csi-azurefile-controller.yaml
  deploy/uninstall-driver.sh
Labels: approved, cncf-cla: yes, kind/feature, size/L

#227 doc: read cloud config from secret doc
  README.md
  deploy/install-driver-standalone.sh
  deploy/uninstall-driver-standalone.sh
  docs/install-csi-driver-master.md
  docs/read-from-secret.md
Labels: approved, cncf-cla: yes, size/M

#228 doc: refine windows doc
  Makefile
  deploy/csi-azurefile-node-windows.yaml
  deploy/example/windows/README.md
  docs/install-csi-driver-master.md
  pkg/azurefileplugin/README.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, size/M

#229 test: add install/uninstall deployment script test
  deploy/example/windows/README.md
  deploy/install-driver.sh
  deploy/uninstall-driver.sh
  docs/install-csi-driver-master.md
  test/e2e/suite_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M
