Repository kubernetes-sigs/azurefile-csi-driver, pull requests merged in 2020-09, with the labels that each got.

#390 add daemonset.yaml example
  deploy/example/daemonset.yaml
Labels: approved, cncf-cla: yes, kind/documentation, size/M

#392 Update debian base image to v2.1.3
  pkg/azurefileplugin/Dockerfile
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, ok-to-test, size/XS

#391 Nit: Fix build on darwin
  Makefile
  pkg/azurefile/azure_common_darwin.go
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, ok-to-test, size/L

#389 feat: bring your own account key for dynamic provisioning
  deploy/example/storageclass-azurefile-secret.yaml
  pkg/azurefile/azurefile.go
  pkg/azurefile/azurefile_client.go
  pkg/azurefile/azurefile_test.go
  pkg/azurefile/controllerserver.go
Labels: approved, cncf-cla: yes, kind/feature, size/L

#372 Add value in Helm chart for secret used to pull Docker images
  charts/latest/azurefile-csi-driver/templates/_helpers.tpl
  charts/latest/azurefile-csi-driver/templates/csi-azurefile-controller.yaml
  charts/latest/azurefile-csi-driver/templates/csi-azurefile-node-windows.yaml
  charts/latest/azurefile-csi-driver/templates/csi-azurefile-node.yaml
  charts/latest/azurefile-csi-driver/templates/csi-snapshot-controller.yaml
  charts/latest/azurefile-csi-driver/values.yaml
Labels: approved, cncf-cla: yes, kind/feature, lgtm, ok-to-test, size/S

#393 test: add new judgment in resize e2e-test
  test/e2e/testsuites/dynamically_provisioned_resize_volume_tester.go
  test/e2e/testsuites/testsuites.go
  test/utils/azure/azure_helpers.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#399 fix: don't create account if secret is provided
  pkg/azurefile/azurefile.go
  pkg/azurefile/azurefile_test.go
  pkg/azurefile/controllerserver.go
Labels: approved, cncf-cla: yes, kind/bug, size/M

#400 doc: add allowVolumeExpansion in storage class
  deploy/example/storageclass-azurefile-nfs.yaml
  deploy/example/storageclass-azurefile-secret.yaml
Labels: approved, cncf-cla: yes, kind/documentation, size/XS

#398 feat: Add value in Helm chart for secret used to pull Docker images
  charts/README.md
  charts/latest/azurefile-csi-driver/values.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#402 test: fix in-tree resize e2e test failure
  test/e2e/testsuites/dynamically_provisioned_resize_volume_tester.go
Labels: approved, cncf-cla: yes, kind/test, size/XS

#401 chore: refactor checkFileShare func
  pkg/azurefile/azurefile.go
  pkg/azurefile/azurefile_test.go
  pkg/azurefile/controllerserver.go
  pkg/azurefile/controllerserver_test.go
  test/e2e/dynamic_provisioning_test.go
Labels: approved, cncf-cla: yes, kind/cleanup, size/L

#405 test: add windows unit test pipeline
  .github/ISSUE_TEMPLATE/feature-request.md
  .github/workflows/windows.yml
  pkg/mounter/safe_mounter_windows.go
Labels: approved, cncf-cla: yes, kind/test, size/S

#395 doc: change image repo address
  README.md
  charts/README.md
  charts/latest/azurefile-csi-driver/values.yaml
  deploy/csi-azurefile-controller.yaml
  deploy/csi-azurefile-node-windows.yaml
  deploy/csi-azurefile-node.yaml
Labels: approved, cncf-cla: yes, do-not-merge/hold, kind/documentation, size/S

#406 fix: unit tests on windows and add to pipeline
  .github/workflows/windows.yml
  pkg/azurefile/azure_test.go
  pkg/azurefile/azurefile_test.go
  pkg/azurefile/controllerserver_test.go
  pkg/azurefile/nodeserver_test.go
Labels: approved, cncf-cla: yes, kind/cleanup, kind/test, lgtm, ok-to-test, size/S

#411 Add metrics for azure file attach and detach operations
  go.mod
  go.sum
  pkg/azurefile/controllerserver.go
  vendor/k8s.io/legacy-cloud-providers/azure/azure_controller_standard.go
  vendor/k8s.io/legacy-cloud-providers/azure/azure_controller_vmss.go
  vendor/k8s.io/legacy-cloud-providers/azure/azure_loadbalancer.go
  vendor/k8s.io/legacy-cloud-providers/azure/azure_routes.go
  vendor/k8s.io/legacy-cloud-providers/azure/azure_standard.go
  vendor/k8s.io/legacy-cloud-providers/azure/azure_vmss.go
  vendor/k8s.io/legacy-cloud-providers/azure/cache/azure_cache.go
  vendor/k8s.io/legacy-cloud-providers/azure/clients/armclient/azure_armclient.go
  vendor/k8s.io/legacy-cloud-providers/azure/metrics/azure_metrics.go
  vendor/k8s.io/legacy-cloud-providers/azure/retry/azure_error.go
  vendor/modules.txt
Labels: approved, cncf-cla: yes, kind/feature, lgtm, size/L

#412 test: enable resize e2e test for in-tree driver
  test/e2e/testsuites/dynamically_provisioned_resize_volume_tester.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#413 test: add unit-test for azurefile_client
  pkg/azurefile/azurefile_client_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#414 test: add one volume with multiple pods e2e test
  test/e2e/pre_provisioning_test.go
  test/e2e/testsuites/pre_provisioned_multiple_pods.go
Labels: approved, cncf-cla: yes, size/M

#415 chore: switch to use k8s/csi repo for master branch
  README.md
  charts/README.md
  charts/index.yaml
  charts/latest/azurefile-csi-driver/values.yaml
  deploy/csi-azurefile-controller.yaml
  deploy/csi-azurefile-node-windows.yaml
  deploy/csi-azurefile-node.yaml
Labels: approved, cncf-cla: yes, kind/documentation, size/M

#417 doc: set ReadWriteMany accessMode
  README.md
  deploy/example/daemonset.yaml
  deploy/example/deployment.yaml
  deploy/example/statefulset.yaml
Labels: approved, cncf-cla: yes, kind/documentation, size/S

#418 fix: set timeout(30s) for csi-provisioner
  charts/latest/azurefile-csi-driver/templates/csi-azurefile-controller.yaml
  deploy/csi-azurefile-controller.yaml
  deploy/example/nfs/README.md
Labels: approved, cncf-cla: yes, kind/bug, size/XS

#423 fix: add lock to prevent list account throttling
  pkg/azurefile/controllerserver.go
Labels: approved, cncf-cla: yes, kind/bug, size/S

#422 doc: cut v0.9.0 release
  README.md
  charts/README.md
  charts/index.yaml
  charts/v0.9.0/azurefile-csi-driver-v0.9.0.tgz
  charts/v0.9.0/azurefile-csi-driver/Chart.yaml
  charts/v0.9.0/azurefile-csi-driver/templates/NOTES.txt
  charts/v0.9.0/azurefile-csi-driver/templates/_helpers.tpl
  charts/v0.9.0/azurefile-csi-driver/templates/crd-csi-snapshot.yaml
  charts/v0.9.0/azurefile-csi-driver/templates/csi-azurefile-controller.yaml
  charts/v0.9.0/azurefile-csi-driver/templates/csi-azurefile-driver.yaml
  charts/v0.9.0/azurefile-csi-driver/templates/csi-azurefile-node-windows.yaml
  charts/v0.9.0/azurefile-csi-driver/templates/csi-azurefile-node.yaml
  charts/v0.9.0/azurefile-csi-driver/templates/csi-snapshot-controller.yaml
  charts/v0.9.0/azurefile-csi-driver/templates/rbac-csi-azurefile-controller.yaml
  charts/v0.9.0/azurefile-csi-driver/templates/rbac-csi-azurefile-node.yaml
  charts/v0.9.0/azurefile-csi-driver/templates/rbac-csi-snapshot-controller.yaml
  charts/v0.9.0/azurefile-csi-driver/templates/serviceaccount-csi-azurefile-controller.yaml
  charts/v0.9.0/azurefile-csi-driver/templates/serviceaccount-csi-azurefile-node.yaml
  charts/v0.9.0/azurefile-csi-driver/templates/serviceaccount-csi-snapshot-controller.yaml
  charts/v0.9.0/azurefile-csi-driver/values.yaml
  deploy/v0.9.0/crd-csi-snapshot.yaml
  deploy/v0.9.0/csi-azurefile-controller.yaml
  deploy/v0.9.0/csi-azurefile-driver.yaml
  deploy/v0.9.0/csi-azurefile-node-windows.yaml
  deploy/v0.9.0/csi-azurefile-node.yaml
  deploy/v0.9.0/csi-snapshot-controller.yaml
  deploy/v0.9.0/rbac-csi-azurefile-controller.yaml
  deploy/v0.9.0/rbac-csi-azurefile-node.yaml
  deploy/v0.9.0/rbac-csi-snapshot-controller.yaml
  docs/install-azurefile-csi-driver.md
  docs/install-csi-driver-v0.9.0.md
Labels: approved, cncf-cla: yes, kind/documentation, size/XXL

#424 fix version to cut v0.9.0
  deploy/csi-azurefile-controller.yaml
  deploy/csi-azurefile-node-windows.yaml
  deploy/csi-azurefile-node.yaml
Labels: approved, cncf-cla: yes, kind/documentation, size/XS

#425 doc: use latest version for master branch
  deploy/csi-azurefile-controller.yaml
  deploy/csi-azurefile-node-windows.yaml
  deploy/csi-azurefile-node.yaml
Labels: cncf-cla: yes, kind/documentation

#421 tests: fix unit tests' file path compatibility and error message assertion across Windows and Linux platforms
  pkg/azurefile/azure_test.go
  pkg/azurefile/azurefile_test.go
  pkg/azurefile/nodeserver_test.go
  test/utils/testutil/testutil.go
Labels: approved, cncf-cla: yes, kind/test, lgtm, ok-to-test, size/L

#419 feat: upgrade to csi-provisioner 2.0.1
  charts/latest/azurefile-csi-driver/templates/csi-azurefile-controller.yaml
  charts/latest/azurefile-csi-driver/values.yaml
  deploy/csi-azurefile-controller.yaml
Labels: approved, cncf-cla: yes, kind/feature, size/S

#427 test: add migration test
  test/e2e/suite_test.go
Labels: approved, cncf-cla: yes, kind/test, size/S

#428 fix: optimize file creation speed using account key
  pkg/azurefile/controllerserver.go
Labels: approved, cncf-cla: yes, kind/bug, size/XS

#433 fix: account list throttling issue in CreateVolume
  pkg/azurefile/azurefile.go
  pkg/azurefile/controllerserver.go
Labels: approved, cncf-cla: yes, kind/bug, size/M

#434 chore: leverage wait.ErrWaitTimeout
  pkg/azurefile/nodeserver.go
Labels: approved, cncf-cla: yes, kind/cleanup, size/S

#435 chore: set kubeclient refactor
  pkg/azurefile/azure.go
  pkg/azurefile/azurefile.go
Labels: approved, cncf-cla: yes, kind/cleanup, size/M

#437 fix: only lock when account is not provided
  pkg/azurefile/controllerserver.go
  pkg/azurefile/controllerserver_test.go
Labels: approved, cncf-cla: yes, kind/bug, size/XS

#438 Upgrade azure lib
  go.mod
  go.sum
  pkg/azurefile/controllerserver.go
  vendor/k8s.io/legacy-cloud-providers/azure/azure_storageaccount.go
  vendor/k8s.io/legacy-cloud-providers/azure/metrics/azure_metrics.go
  vendor/modules.txt
Labels: approved, cncf-cla: yes, kind/feature, size/M

#440 test: switch to use mcr nginx image
  Makefile
  deploy/example/daemonset.yaml
  deploy/example/deployment.yaml
  deploy/example/disk/statefulset-stress.yaml
  deploy/example/nginx-pod-azurefile.yaml
  deploy/example/statefulset.yaml
  test/e2e/suite_test.go
  test/utils/azurefile_log.sh
Labels: approved, cncf-cla: yes, kind/test, size/M

#441 CI: Add golangci-linter to github actions
  .github/workflows/static.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#442 test: add bring own key e2e test
  pkg/azurefile/controllerserver.go
  test/e2e/dynamic_provisioning_test.go
  test/e2e/suite_test.go
  test/utils/get_storage_account_secret_name.sh
Labels: approved, cncf-cla: yes, kind/test, size/M

#445 chore: field name refactor
  Makefile
  deploy/example/e2e_usage.md
  deploy/example/windows/deployment.yaml
  deploy/example/windows/statefulset.yaml
  pkg/azurefile/azurefile.go
  pkg/azurefile/controllerserver.go
  pkg/azurefile/controllerserver_test.go
  test/e2e/dynamic_provisioning_test.go
  test/e2e/pre_provisioning_test.go
  test/utils/check_driver_pods_restart.sh
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, size/L

#439 fix: create nonroot user in Dockerfile
  charts/latest/azurefile-csi-driver/templates/csi-azurefile-controller.yaml
  charts/latest/azurefile-csi-driver/templates/csi-azurefile-node.yaml
  deploy/csi-azurefile-controller.yaml
  deploy/csi-azurefile-node.yaml
  pkg/azurefileplugin/Dockerfile
  pkg/azurefileplugin/dev.Dockerfile
Labels: approved, cncf-cla: yes, kind/bug, size/S

#446 test: only print restart pod logs once
  .github/workflows/ubuntu.yml
  .github/workflows/windows.yml
  test/e2e/suite_test.go
  test/utils/azurefile_log.sh
  test/utils/check_driver_pods_restart.sh
Labels: approved, cncf-cla: yes, kind/test, size/M
