Repository kubernetes-sigs/azurefile-csi-driver, pull requests merged in 2020-07, with the labels that each got.

#328 test: Add unit tests
  pkg/azurefile/azurefile_test.go
  pkg/azurefile/controllerserver_test.go
  pkg/azurefile/nodeserver_test.go
  pkg/azurefile/utils_test.go
  pkg/csi-common/controllerserver-default_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#325 feat: add NFS support
  README.md
  deploy/example/deployment.yaml
  deploy/example/disk/README.md
  deploy/example/nfs/README.md
  deploy/example/statefulset.yaml
  deploy/example/storageclass-azurefile-existing-share.yaml
  deploy/example/storageclass-azurefile-nfs.yaml
  docs/driver-parameters.md
  pkg/azurefile/azurefile.go
  pkg/azurefile/controllerserver.go
  pkg/azurefile/controllerserver_test.go
  pkg/azurefile/nodeserver.go
  pkg/azurefile/nodeserver_test.go
  pkg/azurefile/utils.go
  pkg/azurefile/utils_test.go
  pkg/azurefileplugin/Dockerfile
  test/e2e/dynamic_provisioning_test.go
Labels: approved, cncf-cla: yes, kind/feature, lgtm, size/L

#331 fix: installation issue
  deploy/install-driver.sh
Labels: approved, cncf-cla: yes, kind/bug, size/XS

#332 fix: remove "proto=tcp" in nfs mount
  deploy/example/nfs/README.md
  pkg/azurefile/nodeserver.go
Labels: approved, cncf-cla: yes, kind/bug, size/XS

#333 test: Improve UTs for nodeserver
  .github/workflows/go.yml
  .travis.yml
  pkg/azurefile/fake_mounter.go
  pkg/azurefile/fake_mounter_test.go
  pkg/azurefile/nodeserver_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XL

#335 fix: logging missing due to klog/v2 change
  go.mod
  go.sum
  pkg/azurefile/azure.go
  pkg/azurefile/azure_common_windows.go
  pkg/azurefile/azurefile.go
  pkg/azurefile/controllerserver.go
  pkg/azurefile/identityserver.go
  pkg/azurefile/nodeserver.go
  pkg/azurefile/utils.go
  pkg/azurefileplugin/main.go
  pkg/csi-common/controllerserver-default.go
  pkg/csi-common/driver.go
  pkg/csi-common/identityserver-default.go
  pkg/csi-common/nodeserver-default.go
  pkg/csi-common/server.go
  pkg/csi-common/utils.go
  pkg/csi-common/utils_test.go
  pkg/mounter/safe_mounter_windows.go
  vendor/github.com/go-logr/logr/README.md
  vendor/github.com/go-logr/logr/go.mod
  vendor/github.com/go-logr/logr/logr.go
  vendor/k8s.io/klog/v2/go.mod
  vendor/k8s.io/klog/v2/go.sum
  vendor/k8s.io/klog/v2/klog.go
  vendor/k8s.io/utils/exec/testing/fake_exec.go
  vendor/modules.txt
Labels: approved, cncf-cla: yes, kind/bug, size/XL

#337 chore: upgrade to csi v1.3.0
  go.mod
  go.sum
  pkg/azurefile/controllerserver.go
  vendor/github.com/container-storage-interface/spec/lib/go/csi/csi.pb.go
  vendor/modules.txt
Labels: approved, cncf-cla: yes, kind/feature, size/XXL

#338 fix: expose GET_VOLUME_STATS
  pkg/azurefile/azurefile.go
  pkg/azurefile/nodeserver.go
  pkg/azurefile/nodeserver_test.go
Labels: approved, cncf-cla: yes, kind/feature, lgtm, ok-to-test, size/S

#339 chore: add hack/release-image.sh
  hack/release-image.sh
  pkg/azurefile/controllerserver_test.go
Labels: approved, cncf-cla: yes, kind/test, size/M

#341 test: add dev.Dockerfile
  .travis.yml
  Makefile
  deploy/uninstall-driver.sh
  pkg/azurefileplugin/dev.Dockerfile
Labels: approved, cncf-cla: yes, kind/test, size/M

#343 fix: initial delay(5s) when mount azure file
  pkg/azurefile/controllerserver.go
  pkg/azurefile/nodeserver.go
Labels: approved, cncf-cla: yes, kind/bug, size/XS

#340 fix: retry on EnsureStorageAccount if it is throttled
  deploy/example/windows/statefulset.yaml
  pkg/azurefile/azurefile.go
  pkg/azurefile/controllerserver.go
  pkg/azurefile/controllerserver_test.go
  pkg/azurefile/utils.go
  pkg/azurefile/utils_test.go
  test/utils/credentials/credentials.go
  test/utils/credentials/credentials_test.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, size/L

#346 test: add mount options e2e test
  test/e2e/dynamic_provisioning_test.go
Labels: approved, cncf-cla: yes, kind/test, size/S

#348 ci: remove az command
  Makefile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#349 feat: switch snapshot CRDs from alpha to beta
  charts/README.md
  charts/latest/azurefile-csi-driver/templates/crd-csi-snapshot.yaml
  charts/latest/azurefile-csi-driver/templates/csi-azurefile-controller.yaml
  charts/latest/azurefile-csi-driver/templates/csi-azurefile-node.yaml
  charts/latest/azurefile-csi-driver/templates/csi-snapshot-controller.yaml
  charts/latest/azurefile-csi-driver/templates/rbac-csi-azurefile-controller.yaml
  charts/latest/azurefile-csi-driver/templates/rbac-csi-snapshot-controller.yaml
  charts/latest/azurefile-csi-driver/templates/serviceaccount-csi-snapshot-controller.yaml
  charts/latest/azurefile-csi-driver/values.yaml
  deploy/crd-csi-snapshot.yaml
  deploy/csi-azurefile-controller.yaml
  deploy/csi-snapshot-controller.yaml
  deploy/example/snapshot/README.md
  deploy/example/snapshot/volumesnapshot-azurefile.yaml
  deploy/example/snapshot/volumesnapshotclass-azurefile.yaml
  deploy/install-driver.sh
  deploy/rbac-csi-azurefile-controller.yaml
  deploy/rbac-csi-snapshot-controller.yaml
  deploy/uninstall-driver.sh
  go.mod
  go.sum
  hack/verify-helm-chart.sh
  hack/verify-yamllint.sh
  test/e2e/driver/azurefile_driver.go
  test/e2e/driver/driver.go
  test/e2e/dynamic_provisioning_test.go
  test/e2e/testsuites/dynamically_provisioned_volume_snapshot_tester.go
  test/e2e/testsuites/specs.go
  test/e2e/testsuites/testsuites.go
  vendor/github.com/evanphx/json-patch/patch.go
  vendor/github.com/golang/mock/gomock/call.go
  vendor/github.com/golang/mock/gomock/callset.go
  vendor/github.com/golang/mock/gomock/controller.go
  vendor/github.com/golang/mock/gomock/matchers.go
  vendor/github.com/googleapis/gnostic/OpenAPIv2/OpenAPIv2.go
  vendor/github.com/googleapis/gnostic/OpenAPIv2/OpenAPIv2.pb.go
  vendor/github.com/googleapis/gnostic/compiler/reader.go
  vendor/github.com/googleapis/gnostic/extensions/extension.pb.go
  vendor/github.com/googleapis/gnostic/extensions/extension.proto
  vendor/github.com/imdario/mergo/.deepsource.toml
  vendor/github.com/imdario/mergo/.travis.yml
  vendor/github.com/imdario/mergo/README.md
  vendor/github.com/imdario/mergo/map.go
  vendor/github.com/imdario/mergo/merge.go
  vendor/github.com/kubernetes-csi/external-snapshotter/v2/LICENSE
  vendor/github.com/kubernetes-csi/external-snapshotter/v2/pkg/apis/volumesnapshot/v1beta1/doc.go
  vendor/github.com/kubernetes-csi/external-snapshotter/v2/pkg/apis/volumesnapshot/v1beta1/register.go
  vendor/github.com/kubernetes-csi/external-snapshotter/v2/pkg/apis/volumesnapshot/v1beta1/types.go
  vendor/github.com/kubernetes-csi/external-snapshotter/v2/pkg/apis/volumesnapshot/v1beta1/zz_generated.deepcopy.go
  vendor/github.com/kubernetes-csi/external-snapshotter/v2/pkg/client/clientset/versioned/clientset.go
  vendor/github.com/kubernetes-csi/external-snapshotter/v2/pkg/client/clientset/versioned/doc.go
  vendor/github.com/kubernetes-csi/external-snapshotter/v2/pkg/client/clientset/versioned/scheme/doc.go
  vendor/github.com/kubernetes-csi/external-snapshotter/v2/pkg/client/clientset/versioned/scheme/register.go
  vendor/github.com/kubernetes-csi/external-snapshotter/v2/pkg/client/clientset/versioned/typed/volumesnapshot/v1beta1/doc.go
  vendor/github.com/kubernetes-csi/external-snapshotter/v2/pkg/client/clientset/versioned/typed/volumesnapshot/v1beta1/generated_expansion.go
  vendor/github.com/kubernetes-csi/external-snapshotter/v2/pkg/client/clientset/versioned/typed/volumesnapshot/v1beta1/volumesnapshot.go
  vendor/github.com/kubernetes-csi/external-snapshotter/v2/pkg/client/clientset/versioned/typed/volumesnapshot/v1beta1/volumesnapshot_client.go
  vendor/github.com/kubernetes-csi/external-snapshotter/v2/pkg/client/clientset/versioned/typed/volumesnapshot/v1beta1/volumesnapshotclass.go
  vendor/github.com/kubernetes-csi/external-snapshotter/v2/pkg/client/clientset/versioned/typed/volumesnapshot/v1beta1/volumesnapshotcontent.go
  vendor/modules.txt
Labels: approved, cncf-cla: yes, kind/feature, lgtm, size/XXL

#351 fix: ignore the NotFound error when patching pv
  test/e2e/testsuites/testsuites.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, size/XS

#355 fix: remove InstanceID check in ControllerPublishVolume
  pkg/azurefile/controllerserver.go
  pkg/azurefile/controllerserver_test.go
  test/sanity/run-test.sh
Labels: approved, cncf-cla: yes, kind/bug, size/M

#356 chore: set default imagePullPolicy
  deploy/csi-azurefile-controller.yaml
  deploy/csi-azurefile-node-windows.yaml
  deploy/csi-azurefile-node.yaml
Labels: approved, cncf-cla: yes, kind/cleanup, size/XS

#358 doc: fix snapshot doc
  README.md
  deploy/example/snapshot/README.md
Labels: approved, cncf-cla: yes, kind/documentation, size/XS
