Repository kubernetes-sigs/azurefile-csi-driver, pull requests merged in 2020-01, with the labels that each got.

#150 Build windows container image for azurefile plugin
  Makefile
  pkg/azurefileplugin/Windows.Dockerfile
Labels: approved, cncf-cla: yes, kind/feature, lgtm, size/S

#129 Azure files - add support to run the tests for in-tree
  test/e2e/README.md
  test/e2e/driver/azurefile_driver.go
  test/e2e/driver/driver.go
  test/e2e/dynamic_provisioning_test.go
  test/e2e/pre_provisioning_test.go
  test/e2e/suite_test.go
Labels: approved, cncf-cla: yes, kind/test, lgtm, size/L

#152 Setting cpu/memory requests/limits for csi file driver containers
  charts/latest/azurefile-csi-driver/templates/csi-azurefile-controller.yaml
  charts/latest/azurefile-csi-driver/templates/csi-azurefile-node.yaml
  deploy/csi-azurefile-controller.yaml
  deploy/csi-azurefile-node.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#153 chore: switch to mcr
  charts/latest/azurefile-csi-driver/values.yaml
  deploy/csi-azurefile-controller.yaml
  deploy/csi-azurefile-node.yaml
  pkg/azurefile/nodeserver.go
  test/e2e/suite_test.go
  test/utils/azurefile_log.sh
Labels: approved, cncf-cla: yes, kind/cleanup, size/M

#155 chore: set larger CPU/Memory limit
  charts/latest/azurefile-csi-driver/templates/csi-azurefile-controller.yaml
  charts/latest/azurefile-csi-driver/templates/csi-azurefile-node.yaml
  deploy/csi-azurefile-controller.yaml
  deploy/csi-azurefile-node.yaml
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, size/S

#157 chore: set replica of controller as 2
  charts/latest/azurefile-csi-driver/templates/csi-azurefile-controller.yaml
  charts/latest/azurefile-csi-driver/templates/csi-azurefile-node.yaml
  charts/latest/azurefile-csi-driver/templates/rbac-csi-azurefile-controller.yaml
  charts/latest/azurefile-csi-driver/values.yaml
  deploy/csi-azurefile-controller.yaml
  deploy/csi-azurefile-node.yaml
Labels: approved, cncf-cla: yes, kind/cleanup, size/S

#158 chore: fix broken coverage
  .travis.yml
Labels: approved, cncf-cla: yes, kind/flake, lgtm, size/S

#160 chore: add driver pods check
  test/e2e/dynamic_provisioning_test.go
  test/e2e/pre_provisioning_test.go
  test/e2e/suite_test.go
  test/utils/check_driver_pods_restart.sh
Labels: approved, cncf-cla: yes, kind/flake, lgtm, size/L

#159 feat: use StageVolume for pv sharing on one node
  pkg/azurefile/azurefile.go
  pkg/azurefile/nodeserver.go
  test/integration/run-test.sh
  test/integration/run-tests-all-clouds.sh
Labels: approved, cncf-cla: yes, kind/feature, size/L

#161 doc: use nodeStageSecretRef instead of nodePublishSecretRef
  deploy/example/pv-azurefile-csi.yaml
  docs/driver-parameters.md
Labels: approved, cncf-cla: yes, lgtm, size/XS
