Repository kubernetes-sigs/azurefile-csi-driver, pull requests merged in 2020-10, with the labels that each got.

#447 chore: upgrade to csi-provisioner v2.0.2
  charts/latest/azurefile-csi-driver/values.yaml
  deploy/csi-azurefile-controller.yaml
Labels: approved, cncf-cla: yes, kind/feature, size/XS

#448 Revert "fix: create nonroot user in Dockerfile"
  charts/latest/azurefile-csi-driver/templates/csi-azurefile-controller.yaml
  charts/latest/azurefile-csi-driver/templates/csi-azurefile-node.yaml
  deploy/csi-azurefile-controller.yaml
  deploy/csi-azurefile-node.yaml
  pkg/azurefileplugin/Dockerfile
  pkg/azurefileplugin/dev.Dockerfile
Labels: approved, cncf-cla: yes, size/S

#450 fix: use dnsPolicy ClusterFirstWithHostNet for hostNetwork
  charts/latest/azurefile-csi-driver/templates/csi-azurefile-node.yaml
  deploy/csi-azurefile-node.yaml
Labels: approved, cncf-cla: yes, kind/bug, size/XS

#451 CI: enable unit tests for macos in github actions
  .github/workflows/darwin.yaml
  Makefile
  pkg/azurefile/nodeserver_test.go
Labels: approved, cncf-cla: yes, kind/test, lgtm, ok-to-test, size/M

#455 Updating region list
  deploy/example/nfs/README.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#461 fix: not schedule driver pod on virtual node
  charts/latest/azurefile-csi-driver/templates/csi-azurefile-node-windows.yaml
  charts/latest/azurefile-csi-driver/templates/csi-azurefile-node.yaml
  deploy/csi-azurefile-node-windows.yaml
  deploy/csi-azurefile-node.yaml
Labels: approved, cncf-cla: yes, kind/bug, size/M

#464 chore: upgrade csi-provisioner to v2.0.4
  charts/latest/azurefile-csi-driver/values.yaml
  deploy/csi-azurefile-controller.yaml
Labels: approved, cncf-cla: yes, kind/feature, size/XS
