Repository kubernetes-sigs/azurefile-csi-driver, pull requests merged in 2020-11, with the labels that each got.

#462 image: support multi OS versions for Windows images
  Makefile
  docs/csi-dev.md
  hack/release-image.sh
  pkg/azurefileplugin/Windows.Dockerfile
Labels: approved, cncf-cla: yes, lgtm, size/L

#463 Add AZURE prefix to e2e environment variables
  test/utils/credentials/credentials.go
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, size/S

#466 feat: support NFS dynamic scenario
  pkg/azurefile/azure.go
  pkg/azurefile/azure_test.go
  pkg/azurefile/azurefile.go
  pkg/azurefile/controllerserver.go
  test/e2e/dynamic_provisioning_test.go
Labels: approved, cncf-cla: yes, kind/feature, lgtm, size/L

#470 fix: trim new line for azure storage account name
  pkg/azurefile/azurefile.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, ok-to-test, size/XS

#468 fix: update livenessprobe version from v1.1.0 to v2.0.0
  charts/latest/azurefile-csi-driver/templates/csi-azurefile-controller.yaml
  charts/latest/azurefile-csi-driver/templates/csi-azurefile-node.yaml
  charts/latest/azurefile-csi-driver/values.yaml
  deploy/csi-azurefile-controller.yaml
  deploy/csi-azurefile-node.yaml
Labels: cncf-cla: yes, kind/bug, lgtm, ok-to-test, size/S

#469 fix: vnet resource group setting issue
  pkg/azurefile/azure.go
Labels: approved, cncf-cla: yes, kind/bug, size/XS

#472 chore: upgrade node-driver-registrar version to v2.0.1
  charts/README.md
  charts/latest/azurefile-csi-driver/values.yaml
  deploy/csi-azurefile-node-windows.yaml
  deploy/csi-azurefile-node.yaml
Labels: cncf-cla: yes, lgtm, size/S

#473 fix: add actimeo and fix NFS account type issue
  pkg/azurefile/azurefile.go
  pkg/azurefile/azurefile_test.go
  pkg/azurefile/controllerserver.go
  pkg/mounter/safe_mounter_windows.go
Labels: approved, cncf-cla: yes, kind/bug, size/M

#474 doc: fix NFS doc naming issue
  deploy/example/nfs/README.md
  deploy/example/nfs/statefulset.yaml
  deploy/example/storageclass-azurefile-nfs.yaml
Labels: approved, cncf-cla: yes, kind/documentation, size/M

#478 Fix the controllerexpand response to bytes
  pkg/azurefile/controllerserver.go
  pkg/azurefile/controllerserver_test.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, size/XS

#476 fix: copy netapi32.dll from windows-servercore-cache instead of servercore
  pkg/azurefileplugin/Windows.Dockerfile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#479 feat: support run controller on master node
  Makefile
  charts/README.md
  charts/latest/azurefile-csi-driver/templates/csi-azurefile-controller.yaml
  charts/latest/azurefile-csi-driver/values.yaml
  deploy/csi-azurefile-controller.yaml
Labels: approved, cncf-cla: yes, kind/feature, size/S

#481 fix: incorrect operation status
  pkg/azurefile/controllerserver.go
Labels: approved, cncf-cla: yes, kind/bug, size/XS
