Repository kubernetes-sigs/azurefile-csi-driver, pull requests merged in 2020-02, with the labels that each got.

#163 feat: MSI support
  charts/latest/azurefile-csi-driver/templates/csi-azurefile-controller.yaml
  charts/latest/azurefile-csi-driver/templates/csi-azurefile-node.yaml
  deploy/crd-csi-driver-registry.yaml
  deploy/crd-csi-node-info.yaml
  deploy/csi-azurefile-controller.yaml
  deploy/csi-azurefile-node.yaml
  deploy/rbac-csi-azurefile-controller.yaml
  pkg/azurefileplugin/main.go
Labels: approved, cncf-cla: yes, kind/feature, size/M

#166 test: Add negative mountOptions test case
  test/e2e/dynamic_provisioning_test.go
  test/e2e/pre_provisioning_test.go
  test/e2e/testsuites/dynamically_provisioned_invalid_mount_options.go
  test/e2e/testsuites/testsuites.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#168 doc: fix yaml format
  deploy/example/nginx-pod-azurefile.yaml
  deploy/example/pv-azurefile-csi.yaml
  deploy/example/pvc-azurefile-csi-static.yaml
  deploy/example/pvc-azurefile-csi.yaml
  deploy/example/snapshot/volumesnapshot-azurefile.yaml
  deploy/example/snapshot/volumesnapshotclass-azurefile.yaml
  deploy/example/storageclass-azurefile-csi-mountoptions.yaml
  deploy/example/storageclass-azurefile-csi.yaml
  hack/verify-yamllint.sh
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, size/M

#170 test: increase wait duration while performing helm install
  Makefile
  test/utils/check_driver_pods_restart.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#169 fix: mount timeout issue
  pkg/azurefile/nodeserver.go
  test/utils/azurefile_log.sh
Labels: approved, cncf-cla: yes, kind/bug, lgtm, size/S

#171 Complete resize feature
  charts/latest/azurefile-csi-driver/templates/csi-azurefile-controller.yaml
  charts/latest/azurefile-csi-driver/templates/rbac-csi-azurefile-controller.yaml
  charts/latest/azurefile-csi-driver/values.yaml
  deploy/csi-azurefile-controller.yaml
  deploy/example/resize/README.md
  deploy/example/storageclass-azurefile-csi.yaml
  deploy/rbac-csi-azurefile-controller.yaml
  deploy/v0.2.0/rbac-csi-azurefile-controller.yaml
  deploy/v0.3.0/crd-csi-driver-registry.yaml
  deploy/v0.3.0/crd-csi-node-info.yaml
  deploy/v0.4.0/crd-csi-driver-registry.yaml
  deploy/v0.4.0/crd-csi-node-info.yaml
  deploy/v0.4.0/csi-azurefile-node.yaml
  deploy/v0.4.0/rbac-csi-azurefile-controller.yaml
  hack/verify-helm-chart.sh
  pkg/azurefile/azurefile.go
  pkg/azurefile/nodeserver.go
Labels: approved, cncf-cla: yes, kind/documentation, kind/flake, lgtm, size/L
