Repository kubernetes-sigs/azurefile-csi-driver, pull requests merged in 2021-03, with the labels that each got.

#574 fix: account throttling issue
  pkg/azurefile/azurefile.go
  pkg/azurefile/controllerserver.go
Labels: approved, cncf-cla: yes, do-not-merge/hold, kind/bug, size/S

#575 fix: create volume not idempotent when accountName is not provided
  pkg/azurefile/azurefile.go
  pkg/azurefile/controllerserver.go
Labels: approved, cncf-cla: yes, do-not-merge/hold, kind/bug, size/M

#577 fix: skip write secret if account name is in cache
  pkg/azurefile/controllerserver.go
Labels: approved, cncf-cla: yes, do-not-merge/hold, kind/bug, size/XS

#580 fix: no get file share when create file
  go.mod
  go.sum
  vendor/modules.txt
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azureclients/fileclient/azure_fileclient.go
Labels: approved, cncf-cla: yes, kind/bug, size/L

#581 feat: increase csi-provisioner timeout as 300s
  .github/workflows/darwin.yaml
  .github/workflows/linux.yaml
  charts/latest/azurefile-csi-driver-v1.1.0.tgz
  charts/latest/azurefile-csi-driver/templates/csi-azurefile-controller.yaml
  deploy/csi-azurefile-controller.yaml
  go.mod
Labels: approved, cncf-cla: yes, kind/feature, size/S

#578 feat: optimize file share creation in parallel
  docs/driver-parameters.md
  pkg/azurefile/azurefile.go
  pkg/azurefile/azurefile_client.go
  pkg/azurefile/azurefile_client_test.go
  pkg/azurefile/azurefile_test.go
  pkg/azurefile/controllerserver.go
  pkg/azurefile/utils.go
  pkg/azurefile/utils_test.go
  test/e2e/dynamic_provisioning_test.go
Labels: approved, cncf-cla: yes, do-not-merge/hold, kind/feature, size/XL

#584 feat: refine ShareDeleteRetentionPolicy
  docs/driver-parameters.md
  go.mod
  go.sum
  pkg/azurefile/azurefile.go
  pkg/azurefile/controllerserver.go
  vendor/modules.txt
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azureclients/deploymentclient/azure_deploymentclient.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azureclients/fileclient/azure_fileclient.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azureclients/fileclient/interface.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azureclients/fileclient/mockfileclient/interface.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_controller_common.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_managedDiskController.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_storageaccount.go
Labels: approved, cncf-cla: yes, kind/feature, size/L

#585 feat: refine Disable file service delete retention policy
  docs/driver-parameters.md
  go.mod
  go.sum
  pkg/azurefile/azurefile.go
  pkg/azurefile/azurefile_client.go
  pkg/azurefile/controllerserver.go
  vendor/modules.txt
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_storageaccount.go
Labels: approved, cncf-cla: yes, kind/feature, size/M

#587 Bugfix for volume being forced to one account
  pkg/azurefile/controllerserver.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, ok-to-test, size/XS

#588 feat: increase driver memory limit
  charts/latest/azurefile-csi-driver-v1.1.0.tgz
  charts/latest/azurefile-csi-driver/templates/csi-azurefile-controller.yaml
  deploy/csi-azurefile-controller.yaml
Labels: approved, cncf-cla: yes, kind/feature, size/XS

#586 feat: increate remove tag cache as 1 Min
  pkg/azurefile/azurefile.go
Labels: approved, cncf-cla: yes, size/XS

#589 fix: delete should return success when hit not found
  pkg/azurefile/azurefile.go
Labels: approved, cncf-cla: yes, kind/bug, size/XS

#590 fix: increase node memory limit
  charts/latest/azurefile-csi-driver-v1.1.0.tgz
  charts/latest/azurefile-csi-driver/templates/csi-azurefile-node.yaml
  deploy/csi-azurefile-node.yaml
Labels: approved, cncf-cla: yes, kind/bug, size/XS

#592 test: disable 'should create a volume on demand with useDataPlaneAPI' test case for in-tree driver
  test/e2e/dynamic_provisioning_test.go
Labels: approved, cncf-cla: yes, kind/failing-test, lgtm, size/XS

#593 fix: increase csi-resizer memory limit to 300Mi
  charts/latest/azurefile-csi-driver-v1.1.0.tgz
  charts/latest/azurefile-csi-driver/templates/csi-azurefile-controller.yaml
  deploy/csi-azurefile-controller.yaml
Labels: approved, cncf-cla: yes, kind/bug, size/XS

#594 fix: generate key pair for ssh configuration used for vm creation
  test/utils/azure/azure_helpers.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#595 doc: cut v1.1.0 release
  .github/workflows/windows.yaml
  README.md
  charts/README.md
  charts/index.yaml
  charts/v1.1.0/azurefile-csi-driver-v1.1.0.tgz
  charts/v1.1.0/azurefile-csi-driver/Chart.yaml
  charts/v1.1.0/azurefile-csi-driver/templates/NOTES.txt
  charts/v1.1.0/azurefile-csi-driver/templates/_helpers.tpl
  charts/v1.1.0/azurefile-csi-driver/templates/crd-csi-snapshot.yaml
  charts/v1.1.0/azurefile-csi-driver/templates/csi-azurefile-controller.yaml
  charts/v1.1.0/azurefile-csi-driver/templates/csi-azurefile-driver.yaml
  charts/v1.1.0/azurefile-csi-driver/templates/csi-azurefile-node-windows.yaml
  charts/v1.1.0/azurefile-csi-driver/templates/csi-azurefile-node.yaml
  charts/v1.1.0/azurefile-csi-driver/templates/csi-snapshot-controller.yaml
  charts/v1.1.0/azurefile-csi-driver/templates/rbac-csi-azurefile-controller.yaml
  charts/v1.1.0/azurefile-csi-driver/templates/rbac-csi-azurefile-node.yaml
  charts/v1.1.0/azurefile-csi-driver/templates/rbac-csi-snapshot-controller.yaml
  charts/v1.1.0/azurefile-csi-driver/templates/serviceaccount-csi-azurefile-controller.yaml
  charts/v1.1.0/azurefile-csi-driver/templates/serviceaccount-csi-azurefile-node.yaml
  charts/v1.1.0/azurefile-csi-driver/templates/serviceaccount-csi-snapshot-controller.yaml
  charts/v1.1.0/azurefile-csi-driver/values.yaml
  deploy/v1.1.0/crd-csi-snapshot.yaml
  deploy/v1.1.0/csi-azurefile-controller.yaml
  deploy/v1.1.0/csi-azurefile-driver.yaml
  deploy/v1.1.0/csi-azurefile-node-windows.yaml
  deploy/v1.1.0/csi-azurefile-node.yaml
  deploy/v1.1.0/csi-snapshot-controller.yaml
  deploy/v1.1.0/rbac-csi-azurefile-controller.yaml
  deploy/v1.1.0/rbac-csi-azurefile-node.yaml
  deploy/v1.1.0/rbac-csi-snapshot-controller.yaml
  docs/install-azurefile-csi-driver.md
  docs/install-csi-driver-v1.1.0.md
Labels: approved, cncf-cla: yes, kind/documentation, size/XXL

#596 chore: switch master branch to use v1.2.0
  Makefile
  charts/index.yaml
  charts/latest/azurefile-csi-driver-v1.1.0.tgz
  charts/latest/azurefile-csi-driver-v1.2.0.tgz
  charts/latest/azurefile-csi-driver/Chart.yaml
Labels: approved, cncf-cla: yes, kind/documentation, size/M

#597 fix: CSI migration issue by upgrade csi-provisioner
  charts/latest/azurefile-csi-driver-v1.2.0.tgz
  charts/latest/azurefile-csi-driver/values.yaml
  deploy/csi-azurefile-controller.yaml
Labels: approved, cncf-cla: yes, kind/feature, size/XS

#598 feat: upgrade csi-attacher to v3.1.0
  README.md
  charts/latest/azurefile-csi-driver-v1.2.0.tgz
  charts/latest/azurefile-csi-driver/templates/rbac-csi-azurefile-controller.yaml
  charts/latest/azurefile-csi-driver/values.yaml
  deploy/csi-azurefile-controller.yaml
  deploy/rbac-csi-azurefile-controller.yaml
Labels: approved, cncf-cla: yes, kind/feature, size/S

#599 fix: reset labels to follow Helm Best Practices, prevent pod recreation
  charts/latest/azurefile-csi-driver-v1.2.0.tgz
  charts/latest/azurefile-csi-driver/templates/_helpers.tpl
Labels: approved, cncf-cla: yes, kind/bug, size/S

#604 Fixing a minor bug in the example and adding the MSI pre-requisite
  deploy/example/nfs/README.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#605 test: Normalize share name to not include capital letters
  test/e2e/driver/azurefile_driver.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, ok-to-test, size/XS
