Repository kubernetes-sigs/azurefile-csi-driver, pull requests merged in 2021-06, with the labels that each got.

#686 test: add on-prem support e2e test
  Makefile
  deploy/example/smb-provisioner/smb-server-lb.yaml
  deploy/example/smb-provisioner/smb-server.yaml
  test/e2e/dynamic_provisioning_test.go
  test/e2e/suite_test.go
  test/e2e/testsuites/dynamically_provisioned_inline_volume.go
  test/e2e/testsuites/specs.go
  test/e2e/testsuites/testsuites.go
Labels: approved, cncf-cla: yes, kind/test, size/L

#688 doc: add on-prem server support doc
  README.md
  deploy/example/smb-provisioner/README.md
  deploy/example/smb-provisioner/nginx-on-prem-volume.yaml
  hack/verify-yamllint.sh
Labels: approved, cncf-cla: yes, kind/documentation, size/M

#689 test: add e2e test for on-prem server support on Windows
  test/e2e/dynamic_provisioning_test.go
  test/utils/get_smb_svc_public_ip.sh
Labels: approved, cncf-cla: yes, kind/test, size/M

#690 doc: cut v1.3.0 release
  README.md
  charts/README.md
  charts/index.yaml
  charts/v1.3.0/azurefile-csi-driver-v1.3.0.tgz
  charts/v1.3.0/azurefile-csi-driver/Chart.yaml
  charts/v1.3.0/azurefile-csi-driver/templates/NOTES.txt
  charts/v1.3.0/azurefile-csi-driver/templates/_helpers.tpl
  charts/v1.3.0/azurefile-csi-driver/templates/crd-csi-snapshot.yaml
  charts/v1.3.0/azurefile-csi-driver/templates/csi-azurefile-controller.yaml
  charts/v1.3.0/azurefile-csi-driver/templates/csi-azurefile-driver.yaml
  charts/v1.3.0/azurefile-csi-driver/templates/csi-azurefile-node-windows.yaml
  charts/v1.3.0/azurefile-csi-driver/templates/csi-azurefile-node.yaml
  charts/v1.3.0/azurefile-csi-driver/templates/csi-snapshot-controller.yaml
  charts/v1.3.0/azurefile-csi-driver/templates/rbac-csi-azurefile-controller.yaml
  charts/v1.3.0/azurefile-csi-driver/templates/rbac-csi-azurefile-node.yaml
  charts/v1.3.0/azurefile-csi-driver/templates/rbac-csi-snapshot-controller.yaml
  charts/v1.3.0/azurefile-csi-driver/templates/serviceaccount-csi-azurefile-controller.yaml
  charts/v1.3.0/azurefile-csi-driver/templates/serviceaccount-csi-azurefile-node.yaml
  charts/v1.3.0/azurefile-csi-driver/templates/serviceaccount-csi-snapshot-controller.yaml
  charts/v1.3.0/azurefile-csi-driver/values.yaml
  deploy/v1.3.0/crd-csi-snapshot.yaml
  deploy/v1.3.0/csi-azurefile-controller.yaml
  deploy/v1.3.0/csi-azurefile-driver.yaml
  deploy/v1.3.0/csi-azurefile-node-windows.yaml
  deploy/v1.3.0/csi-azurefile-node.yaml
  deploy/v1.3.0/csi-snapshot-controller.yaml
  deploy/v1.3.0/rbac-csi-azurefile-controller.yaml
  deploy/v1.3.0/rbac-csi-azurefile-node.yaml
  deploy/v1.3.0/rbac-csi-snapshot-controller.yaml
  docs/install-azurefile-csi-driver.md
  docs/install-csi-driver-v1.3.0.md
Labels: approved, cncf-cla: yes, kind/documentation, size/XXL

#691 chore: switch master branch to use v1.4.0
  Makefile
  charts/index.yaml
  charts/latest/azurefile-csi-driver-v1.3.0.tgz
  charts/latest/azurefile-csi-driver-v1.4.0.tgz
  charts/latest/azurefile-csi-driver/Chart.yaml
Labels: approved, cncf-cla: yes, kind/documentation, size/M

#693 add imagepullsecrets
  charts/latest/azurefile-csi-driver-v1.4.0.tgz
  charts/latest/azurefile-csi-driver/templates/csi-azurefile-controller.yaml
  charts/latest/azurefile-csi-driver/templates/csi-azurefile-node-windows.yaml
  charts/latest/azurefile-csi-driver/templates/csi-azurefile-node.yaml
  charts/latest/azurefile-csi-driver/templates/csi-snapshot-controller.yaml
  charts/latest/azurefile-csi-driver/values.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#699 fix: read cloud config from secret regression
  pkg/azurefile/azure.go
Labels: approved, cncf-cla: yes, kind/bug, size/XS

#702 feat: add mountOptions for inline volume
  deploy/example/nginx-pod-azurefile-inline-volume.yaml
  deploy/example/pv-azurefile-csi.yaml
  deploy/example/pv-azurefile-nfs.yaml
  pkg/azurefile/azurefile.go
  pkg/azurefile/controllerserver.go
  pkg/azurefile/nodeserver.go
  test/e2e/testsuites/testsuites.go
Labels: approved, cncf-cla: yes, do-not-merge/hold, kind/feature, size/M

#703 feat: support customization tolerations in chart
  charts/latest/azurefile-csi-driver-v1.4.0.tgz
  charts/latest/azurefile-csi-driver/templates/csi-azurefile-controller.yaml
  charts/latest/azurefile-csi-driver/templates/csi-azurefile-node-windows.yaml
  charts/latest/azurefile-csi-driver/templates/csi-azurefile-node.yaml
  charts/latest/azurefile-csi-driver/values.yaml
Labels: approved, cncf-cla: yes, kind/feature, size/M

#704 fix: add snapshot controller tolerations
  charts/latest/azurefile-csi-driver-v1.4.0.tgz
  charts/latest/azurefile-csi-driver/templates/csi-snapshot-controller.yaml
Labels: approved, cncf-cla: yes, kind/bug, size/XS

#705 fix: deploy/csi-snapshot-controller.yaml tolerations
  deploy/csi-snapshot-controller.yaml
Labels: approved, cncf-cla: yes, kind/bug, size/XS

#706 doc: cut v1.4.0 release
  README.md
  charts/README.md
  charts/index.yaml
  charts/v1.4.0/azurefile-csi-driver-v1.4.0.tgz
  charts/v1.4.0/azurefile-csi-driver/Chart.yaml
  charts/v1.4.0/azurefile-csi-driver/templates/NOTES.txt
  charts/v1.4.0/azurefile-csi-driver/templates/_helpers.tpl
  charts/v1.4.0/azurefile-csi-driver/templates/crd-csi-snapshot-ga.yaml
  charts/v1.4.0/azurefile-csi-driver/templates/crd-csi-snapshot.yaml
  charts/v1.4.0/azurefile-csi-driver/templates/csi-azurefile-controller.yaml
  charts/v1.4.0/azurefile-csi-driver/templates/csi-azurefile-driver.yaml
  charts/v1.4.0/azurefile-csi-driver/templates/csi-azurefile-node-windows.yaml
  charts/v1.4.0/azurefile-csi-driver/templates/csi-azurefile-node.yaml
  charts/v1.4.0/azurefile-csi-driver/templates/csi-snapshot-controller.yaml
  charts/v1.4.0/azurefile-csi-driver/templates/rbac-csi-azurefile-controller.yaml
  charts/v1.4.0/azurefile-csi-driver/templates/rbac-csi-azurefile-node.yaml
  charts/v1.4.0/azurefile-csi-driver/templates/rbac-csi-snapshot-controller.yaml
  charts/v1.4.0/azurefile-csi-driver/templates/serviceaccount-csi-azurefile-controller.yaml
  charts/v1.4.0/azurefile-csi-driver/templates/serviceaccount-csi-azurefile-node.yaml
  charts/v1.4.0/azurefile-csi-driver/templates/serviceaccount-csi-snapshot-controller.yaml
  charts/v1.4.0/azurefile-csi-driver/values.yaml
  deploy/v1.4.0/crd-csi-snapshot.yaml
  deploy/v1.4.0/csi-azurefile-controller.yaml
  deploy/v1.4.0/csi-azurefile-driver.yaml
  deploy/v1.4.0/csi-azurefile-node-windows.yaml
  deploy/v1.4.0/csi-azurefile-node.yaml
  deploy/v1.4.0/csi-snapshot-controller.yaml
  deploy/v1.4.0/rbac-csi-azurefile-controller.yaml
  deploy/v1.4.0/rbac-csi-azurefile-node.yaml
  deploy/v1.4.0/rbac-csi-snapshot-controller.yaml
  docs/install-azurefile-csi-driver.md
  docs/install-csi-driver-v1.4.0.md
Labels: approved, cncf-cla: yes, kind/documentation, size/XXL

#707 chore: switch master branch to use v1.5.0
  Makefile
  charts/index.yaml
  charts/latest/azurefile-csi-driver-v1.4.0.tgz
  charts/latest/azurefile-csi-driver-v1.5.0.tgz
  charts/latest/azurefile-csi-driver/Chart.yaml
Labels: approved, cncf-cla: yes, kind/documentation, size/M

#709 test: add storeAccountKey test
  test/e2e/dynamic_provisioning_test.go
Labels: approved, cncf-cla: yes, kind/test, size/S

#711 feat: remove cloud config dependency
  docs/driver-parameters.md
  pkg/azurefile/azurefile.go
  pkg/azurefile/azurefile_client.go
  pkg/azurefile/controllerserver.go
  pkg/azurefile/nodeserver.go
Labels: approved, cncf-cla: yes, do-not-merge/hold, kind/feature, size/M

#713 feat: upgrade TLS1.0 to TLS1.2 in account creation
  go.mod
  go.sum
  vendor/modules.txt
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/auth/azure_auth.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/consts/consts.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_routes.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_storageaccount.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_utils.go
Labels: approved, cncf-cla: yes, kind/feature, size/L

#715 fix: disable subnet set if account is provided
  pkg/azurefile/controllerserver.go
Labels: approved, cncf-cla: yes, kind/bug, size/XS

#721 fix: duplicate tolerations on Windows node
  charts/latest/azurefile-csi-driver-v1.5.0.tgz
  charts/latest/azurefile-csi-driver/templates/csi-azurefile-node-windows.yaml
Labels: approved, cncf-cla: yes, kind/bug, size/XS

#722 feat: support alternative driver name
  charts/README.md
  charts/latest/azurefile-csi-driver-v1.5.0.tgz
  charts/latest/azurefile-csi-driver/templates/csi-azurefile-controller.yaml
  charts/latest/azurefile-csi-driver/templates/csi-azurefile-driver.yaml
  charts/latest/azurefile-csi-driver/templates/csi-azurefile-node-windows.yaml
  charts/latest/azurefile-csi-driver/templates/csi-azurefile-node.yaml
  charts/latest/azurefile-csi-driver/values.yaml
  pkg/azurefile/azurefile.go
  pkg/azurefile/azurefile_test.go
  pkg/azurefile/version.go
  pkg/azurefile/version_test.go
  pkg/azurefileplugin/main.go
  test/e2e/driver/azurefile_driver.go
  test/e2e/suite_test.go
  test/e2e/testsuites/testsuites.go
Labels: approved, cncf-cla: yes, kind/feature, size/M

#697 feat: Add networkEndpointType parameter to allow customers to create Private Endpoints
  docs/driver-parameters.md
  go.mod
  go.sum
  pkg/azurefile/azurefile.go
  pkg/azurefile/controllerserver.go
  test/e2e/dynamic_provisioning_test.go
  vendor/github.com/Azure/azure-sdk-for-go/services/privatedns/mgmt/2018-09-01/privatedns/CHANGELOG.md
  vendor/github.com/Azure/azure-sdk-for-go/services/privatedns/mgmt/2018-09-01/privatedns/_meta.json
  vendor/github.com/Azure/azure-sdk-for-go/services/privatedns/mgmt/2018-09-01/privatedns/client.go
  vendor/github.com/Azure/azure-sdk-for-go/services/privatedns/mgmt/2018-09-01/privatedns/enums.go
  vendor/github.com/Azure/azure-sdk-for-go/services/privatedns/mgmt/2018-09-01/privatedns/models.go
  vendor/github.com/Azure/azure-sdk-for-go/services/privatedns/mgmt/2018-09-01/privatedns/privatezones.go
  vendor/github.com/Azure/azure-sdk-for-go/services/privatedns/mgmt/2018-09-01/privatedns/recordsets.go
  vendor/github.com/Azure/azure-sdk-for-go/services/privatedns/mgmt/2018-09-01/privatedns/version.go
  vendor/github.com/Azure/azure-sdk-for-go/services/privatedns/mgmt/2018-09-01/privatedns/virtualnetworklinks.go
  vendor/modules.txt
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azureclients/privatednsclient/azure_privatednsclient.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azureclients/privatednsclient/interface.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azureclients/privatednszonegroupclient/azure_privatednszonegroupclient.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azureclients/privatednszonegroupclient/interface.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azureclients/privateendpointclient/azure_privateendpointclient.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azureclients/privateendpointclient/interface.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azureclients/storageaccountclient/interface.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azureclients/virtualnetworklinksclient/azure_virtualnetworklinksclient.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azureclients/virtualnetworklinksclient/interface.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_controller_common.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_loadbalancer.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_standard.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_storageaccount.go
Labels: approved, cncf-cla: yes, kind/feature, lgtm, size/XXL

#723 fix: incorrect display driverName when using alternative driver name
  go.mod
  go.sum
  pkg/azurefile/azurefile.go
  pkg/azurefile/version.go
  pkg/azurefile/version_test.go
  pkg/azurefileplugin/main.go
  vendor/modules.txt
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_loadbalancer.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_storageaccount.go
Labels: approved, cncf-cla: yes, kind/bug, size/L
