Repository kubernetes-sigs/azurefile-csi-driver, pull requests merged in 2021-08, with the labels that each got.

#757 fix(doc): link in kubectl apply is not working
  deploy/example/e2e_usage.md
Labels: kind/bug, ok-to-test, kind/documentation, size/XS, lgtm, approved, cncf-cla: yes

#758 feat: support maxUnavailable config in helm chart
  charts/README.md
  charts/latest/azurefile-csi-driver-v1.6.0.tgz
  charts/latest/azurefile-csi-driver/templates/csi-azurefile-node-windows.yaml
  charts/latest/azurefile-csi-driver/templates/csi-azurefile-node.yaml
  deploy/csi-azurefile-node-windows.yaml
  deploy/csi-azurefile-node.yaml
Labels: kind/feature, size/S, approved, cncf-cla: yes

#760 fix: driver register issue on Windows node
  charts/latest/azurefile-csi-driver-v1.6.0.tgz
  charts/latest/azurefile-csi-driver/templates/csi-azurefile-node-windows.yaml
  charts/latest/azurefile-csi-driver/templates/csi-azurefile-node.yaml
  charts/latest/azurefile-csi-driver/values.yaml
  deploy/csi-azurefile-node-windows.yaml
  deploy/csi-azurefile-node.yaml
Labels: kind/bug, size/M, approved, cncf-cla: yes

#761 chore: add preStop in node registrar
  charts/README.md
  charts/latest/azurefile-csi-driver-v1.6.0.tgz
  charts/latest/azurefile-csi-driver/templates/csi-azurefile-node.yaml
  deploy/csi-azurefile-node.yaml
Labels: kind/cleanup, size/S, approved, cncf-cla: yes

#762 credentials typo on Readme
  README.md
Labels: ok-to-test, kind/documentation, size/XS, lgtm, approved, cncf-cla: yes

#764 feat: support custom userAgent in driver setting
  charts/README.md
  charts/latest/azurefile-csi-driver-v1.6.0.tgz
  charts/latest/azurefile-csi-driver/templates/csi-azurefile-controller.yaml
  charts/latest/azurefile-csi-driver/templates/csi-azurefile-node-windows.yaml
  charts/latest/azurefile-csi-driver/templates/csi-azurefile-node.yaml
  charts/latest/azurefile-csi-driver/values.yaml
  pkg/azurefile/azurefile.go
  pkg/azurefile/version.go
  pkg/azurefile/version_test.go
  pkg/azurefileplugin/main.go
Labels: kind/feature, size/M, approved, cncf-cla: yes

#765 fix: remove kubelet-registration-probe on Linux
  charts/latest/azurefile-csi-driver-v1.6.0.tgz
  charts/latest/azurefile-csi-driver/templates/NOTES.txt
  charts/latest/azurefile-csi-driver/templates/_helpers.tpl
  charts/latest/azurefile-csi-driver/templates/crd-csi-snapshot.yaml
  charts/latest/azurefile-csi-driver/templates/csi-azurefile-controller.yaml
  charts/latest/azurefile-csi-driver/templates/csi-azurefile-driver.yaml
  charts/latest/azurefile-csi-driver/templates/csi-azurefile-node-windows.yaml
  charts/latest/azurefile-csi-driver/templates/csi-azurefile-node.yaml
  charts/latest/azurefile-csi-driver/templates/csi-snapshot-controller.yaml
  charts/latest/azurefile-csi-driver/templates/rbac-csi-azurefile-controller.yaml
  charts/latest/azurefile-csi-driver/templates/rbac-csi-azurefile-node.yaml
  charts/latest/azurefile-csi-driver/templates/rbac-csi-snapshot-controller.yaml
  charts/latest/azurefile-csi-driver/templates/serviceaccount-csi-azurefile-controller.yaml
  charts/latest/azurefile-csi-driver/templates/serviceaccount-csi-azurefile-node.yaml
  charts/latest/azurefile-csi-driver/templates/serviceaccount-csi-snapshot-controller.yaml
  deploy/csi-azurefile-node.yaml
Labels: kind/bug, size/S, approved, cncf-cla: yes

#766 fix: set default userAgent issue
  go.mod
  go.sum
  pkg/azurefile/azure.go
  vendor/github.com/Azure/azure-sdk-for-go/NOTICE
  vendor/github.com/Azure/azure-sdk-for-go/NOTICE.txt
  vendor/github.com/Azure/azure-sdk-for-go/storage/README.md
  vendor/github.com/Azure/azure-sdk-for-go/version/version.go
  vendor/github.com/onsi/gomega/CHANGELOG.md
  vendor/github.com/onsi/gomega/env.go
  vendor/github.com/onsi/gomega/gomega_dsl.go
  vendor/github.com/onsi/gomega/internal/assertion.go
  vendor/github.com/onsi/gomega/internal/async_assertion.go
  vendor/github.com/onsi/gomega/internal/defaults/env.go
  vendor/github.com/onsi/gomega/internal/duration_bundle.go
  vendor/github.com/onsi/gomega/internal/gomega.go
  vendor/github.com/onsi/gomega/internal/oraclematcher/oracle_matcher.go
  vendor/github.com/onsi/gomega/internal/testingtsupport/testing_t_support.go
  vendor/github.com/onsi/gomega/matchers/and.go
  vendor/github.com/onsi/gomega/matchers/not.go
  vendor/github.com/onsi/gomega/matchers/or.go
  vendor/github.com/onsi/gomega/matchers/with_transform.go
  vendor/github.com/onsi/gomega/types/types.go
  vendor/modules.txt
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_config.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_instances.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_standard.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_vmsets.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_vmss.go
Labels: kind/bug, approved, cncf-cla: yes, size/XXL

#767 test: refine getCloudProvider unit test
  pkg/azurefile/azure.go
  pkg/azurefile/azure_test.go
Labels: size/M, approved, cncf-cla: yes, kind/test

#768 feat: set default userAgentSuffix in driver installation
  charts/README.md
  charts/latest/azurefile-csi-driver-v1.6.0.tgz
  charts/latest/azurefile-csi-driver/values.yaml
  deploy/csi-azurefile-controller.yaml
  deploy/csi-azurefile-node-windows.yaml
  deploy/csi-azurefile-node.yaml
Labels: kind/feature, size/XS, lgtm, approved, cncf-cla: yes

#769 chore: remove commit id & build date in userAgent
  pkg/azurefile/version.go
  pkg/azurefile/version_test.go
Labels: kind/cleanup, size/XS, approved, cncf-cla: yes

#770 feat: upgrade snapshotter GA version to v4.2.0
  charts/latest/azurefile-csi-driver-v1.6.0.tgz
  charts/latest/azurefile-csi-driver/templates/csi-azurefile-controller.yaml
  charts/latest/azurefile-csi-driver/templates/csi-snapshot-controller.yaml
  charts/latest/azurefile-csi-driver/values.yaml
Labels: kind/feature, size/S, approved, cncf-cla: yes

#755 feat: Implement Volume_mount_group capability
  go.mod
  go.sum
  pkg/azurefile/azurefile.go
  pkg/azurefile/nodeserver.go
  pkg/azurefile/nodeserver_test.go
  test/sanity/run-test.sh
  vendor/github.com/container-storage-interface/spec/lib/go/csi/csi.pb.go
  vendor/modules.txt
Labels: kind/feature, size/XL, lgtm, approved, cncf-cla: yes

#763 update base image to bullseye
  Makefile
  pkg/azurefileplugin/Dockerfile
Labels: kind/cleanup, ok-to-test, size/S, lgtm, approved, cncf-cla: yes

#773 feat: Add AzureFile API metrics
  go.mod
  go.sum
  vendor/modules.txt
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azureclients/armclient/interface.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azureclients/containerserviceclient/interface.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azureclients/deploymentclient/interface.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azureclients/diskclient/interface.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azureclients/diskclient/mockdiskclient/interface.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azureclients/fileclient/azure_fileclient.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azureclients/fileclient/interface.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azureclients/fileclient/mockfileclient/interface.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azureclients/interfaceclient/interface.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azureclients/interfaceclient/mockinterfaceclient/interface.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azureclients/loadbalancerclient/interface.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azureclients/loadbalancerclient/mockloadbalancerclient/interface.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azureclients/privatednsclient/interface.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azureclients/privatednszonegroupclient/interface.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azureclients/privateendpointclient/interface.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azureclients/publicipclient/interface.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azureclients/publicipclient/mockpublicipclient/interface.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azureclients/routeclient/interface.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azureclients/routeclient/mockrouteclient/interface.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azureclients/routetableclient/interface.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azureclients/routetableclient/mockroutetableclient/interface.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azureclients/securitygroupclient/interface.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azureclients/securitygroupclient/mocksecuritygroupclient/interface.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azureclients/snapshotclient/interface.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azureclients/snapshotclient/mocksnapshotclient/interface.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azureclients/storageaccountclient/interface.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azureclients/storageaccountclient/mockstorageaccountclient/interface.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azureclients/subnetclient/interface.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azureclients/subnetclient/mocksubnetclient/interface.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azureclients/virtualnetworklinksclient/interface.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azureclients/vmasclient/interface.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azureclients/vmclient/interface.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azureclients/vmclient/mockvmclient/interface.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azureclients/vmsizeclient/interface.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azureclients/vmssclient/interface.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azureclients/vmssclient/mockvmssclient/interface.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azureclients/vmssvmclient/interface.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azureclients/vmssvmclient/mockvmssvmclient/interface.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azureclients/zoneclient/interface.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/consts/consts.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_managedDiskController.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/retry/azure_error.go
Labels: kind/feature, lgtm, approved, cncf-cla: yes, size/XXL

#772 chore: upgrade dev base image to bullseye
  pkg/azurefileplugin/dev.Dockerfile
Labels: kind/cleanup, size/XS, approved, cncf-cla: yes

#776 feat: add CSIDriver annotation
  charts/latest/azurefile-csi-driver-v1.6.0.tgz
  charts/latest/azurefile-csi-driver/templates/csi-azurefile-driver.yaml
  deploy/csi-azurefile-driver.yaml
Labels: kind/feature, size/S, approved, cncf-cla: yes

#780 chore: upgrade to snapshot v4.2.1
  charts/latest/azurefile-csi-driver-v1.6.0.tgz
  charts/latest/azurefile-csi-driver/values.yaml
Labels: kind/feature, size/XS, approved, cncf-cla: yes

#781 feat: support file share accessTier setting
  docs/driver-parameters.md
  go.mod
  go.sum
  pkg/azurefile/azurefile.go
  pkg/azurefile/azurefile_test.go
  pkg/azurefile/controllerserver.go
  test/e2e/dynamic_provisioning_test.go
  vendor/modules.txt
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azureclients/armclient/azure_armclient.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azureclients/fileclient/azure_fileclient.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azureclients/loadbalancerclient/interface.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_controller_common.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_loadbalancer.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/version/base.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/version/doc.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/version/version.go
Labels: kind/feature, size/L, approved, cncf-cla: yes
