Repository kubernetes-sigs/azurefile-csi-driver, pull requests merged in 2021-11, with the labels that each got.

#827 chore: increase sidecar contianer cpu limit in controller
  charts/latest/azurefile-csi-driver-v1.8.0.tgz
  charts/latest/azurefile-csi-driver/templates/csi-azurefile-controller.yaml
  deploy/csi-azurefile-controller.yaml
  pkg/azurefile/utils.go
Labels: kind/bug, size/S, approved, cncf-cla: yes

#828 fix: increase registrar container cpu limit
  charts/latest/azurefile-csi-driver-v1.8.0.tgz
  charts/latest/azurefile-csi-driver/templates/csi-azurefile-node.yaml
  deploy/csi-azurefile-node.yaml
Labels: kind/bug, size/XS, approved, cncf-cla: yes

#830 fix: create private endpoint failure on Government cloud
  go.mod
  go.sum
  vendor/modules.txt
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azureclients/privatednsclient/azure_privatednsclient.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azureclients/privatednszonegroupclient/azure_privatednszonegroupclient.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azureclients/privateendpointclient/azure_privateendpointclient.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_controller_common.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_managedDiskController.go
Labels: kind/bug, size/M, approved, cncf-cla: yes

#832 fix: increase registrar probe timeout value on Windows
  charts/latest/azurefile-csi-driver-v1.8.0.tgz
  charts/latest/azurefile-csi-driver/templates/csi-azurefile-node-windows.yaml
  deploy/csi-azurefile-node-windows.yaml
Labels: kind/bug, size/XS, approved, cncf-cla: yes

#833 chore: increase sidecar container memory limit
  charts/latest/azurefile-csi-driver-v1.8.0.tgz
  charts/latest/azurefile-csi-driver/templates/csi-azurefile-controller.yaml
  deploy/csi-azurefile-controller.yaml
Labels: kind/feature, size/S, approved, cncf-cla: yes

#834 Refactoring Kubernetes labels and add custom labels
  charts/README.md
  charts/latest/azurefile-csi-driver-v1.8.0.tgz
  charts/latest/azurefile-csi-driver/templates/_helpers.tpl
  charts/latest/azurefile-csi-driver/templates/csi-azurefile-controller.yaml
  charts/latest/azurefile-csi-driver/templates/csi-azurefile-driver.yaml
  charts/latest/azurefile-csi-driver/templates/csi-azurefile-node-windows.yaml
  charts/latest/azurefile-csi-driver/templates/csi-azurefile-node.yaml
  charts/latest/azurefile-csi-driver/templates/csi-snapshot-controller.yaml
  charts/latest/azurefile-csi-driver/templates/rbac-csi-azurefile-controller.yaml
  charts/latest/azurefile-csi-driver/templates/rbac-csi-azurefile-node.yaml
  charts/latest/azurefile-csi-driver/templates/rbac-csi-snapshot-controller.yaml
  charts/latest/azurefile-csi-driver/templates/serviceaccount-csi-azurefile-controller.yaml
  charts/latest/azurefile-csi-driver/templates/serviceaccount-csi-azurefile-node.yaml
  charts/latest/azurefile-csi-driver/templates/serviceaccount-csi-snapshot-controller.yaml
  charts/latest/azurefile-csi-driver/values.yaml
Labels: kind/feature, size/L, ok-to-test, lgtm, approved, cncf-cla: yes

#839 chore: set default replica num of snapshot controller as 2
  charts/latest/azurefile-csi-driver-v1.8.0.tgz
  charts/latest/azurefile-csi-driver/templates/csi-snapshot-controller.yaml
  charts/latest/azurefile-csi-driver/values.yaml
  deploy/csi-snapshot-controller.yaml
Labels: kind/feature, size/S, approved, cncf-cla: yes

#840 feat: add allowEmptyCloudConfig config in chart
  charts/README.md
  charts/latest/azurefile-csi-driver-v1.8.0.tgz
  charts/latest/azurefile-csi-driver/templates/csi-azurefile-controller.yaml
  charts/latest/azurefile-csi-driver/templates/csi-azurefile-node-windows.yaml
  charts/latest/azurefile-csi-driver/templates/csi-azurefile-node.yaml
  charts/latest/azurefile-csi-driver/values.yaml
  pkg/azurefile/azure.go
  pkg/azurefile/azure_test.go
  pkg/azurefile/azurefile.go
  pkg/azurefileplugin/main.go
Labels: kind/feature, size/M, approved, cncf-cla: yes

#841 feat: upgrade sidecar container version to support WS2022
  charts/README.md
  charts/latest/azurefile-csi-driver-v1.8.0.tgz
  charts/latest/azurefile-csi-driver/templates/csi-azurefile-node.yaml
  charts/latest/azurefile-csi-driver/values.yaml
  deploy/csi-azurefile-controller.yaml
  deploy/csi-azurefile-node-windows.yaml
  deploy/csi-azurefile-node.yaml
Labels: kind/feature, size/S, approved, cncf-cla: yes

#842 feat: support resources config in chart
  charts/README.md
  charts/latest/azurefile-csi-driver-v1.8.0.tgz
  charts/latest/azurefile-csi-driver/templates/csi-azurefile-controller.yaml
  charts/latest/azurefile-csi-driver/templates/csi-azurefile-node-windows.yaml
  charts/latest/azurefile-csi-driver/templates/csi-azurefile-node.yaml
  charts/latest/azurefile-csi-driver/templates/csi-snapshot-controller.yaml
  charts/latest/azurefile-csi-driver/values.yaml
  pkg/azurefile/azure_test.go
Labels: kind/feature, size/L, do-not-merge/hold, approved, cncf-cla: yes

#843 feat: support nfs Premium_ZRS account
  pkg/azurefile/azurefile.go
  pkg/azurefile/controllerserver.go
  test/e2e/dynamic_provisioning_test.go
  test/e2e/suite_test.go
Labels: kind/feature, size/S, do-not-merge/hold, approved, cncf-cla: yes

#846 feat: disable GET_VOLUME_STATS by default
  README.md
  charts/README.md
  charts/latest/azurefile-csi-driver-v1.8.0.tgz
  charts/latest/azurefile-csi-driver/templates/csi-azurefile-node-windows.yaml
  charts/latest/azurefile-csi-driver/templates/csi-azurefile-node.yaml
  charts/latest/azurefile-csi-driver/values.yaml
  pkg/azurefile/azurefile.go
  pkg/azurefileplugin/main.go
Labels: kind/feature, size/S, approved, cncf-cla: yes

#847 feat: increase sidecar container cpu limits
  charts/README.md
  charts/latest/azurefile-csi-driver-v1.8.0.tgz
  charts/latest/azurefile-csi-driver/values.yaml
  deploy/csi-azurefile-controller.yaml
  deploy/csi-azurefile-node-windows.yaml
  deploy/csi-azurefile-node.yaml
Labels: kind/feature, size/M, approved, cncf-cla: yes

#844 doc: cut v1.8.0 release
  README.md
  charts/README.md
  charts/index.yaml
  charts/latest/azurefile-csi-driver-v1.8.0.tgz
  charts/v1.8.0/azurefile-csi-driver-v1.8.0.tgz
  charts/v1.8.0/azurefile-csi-driver/Chart.yaml
  charts/v1.8.0/azurefile-csi-driver/templates/NOTES.txt
  charts/v1.8.0/azurefile-csi-driver/templates/_helpers.tpl
  charts/v1.8.0/azurefile-csi-driver/templates/crd-csi-snapshot-ga.yaml
  charts/v1.8.0/azurefile-csi-driver/templates/crd-csi-snapshot.yaml
  charts/v1.8.0/azurefile-csi-driver/templates/csi-azurefile-controller.yaml
  charts/v1.8.0/azurefile-csi-driver/templates/csi-azurefile-driver.yaml
  charts/v1.8.0/azurefile-csi-driver/templates/csi-azurefile-node-windows.yaml
  charts/v1.8.0/azurefile-csi-driver/templates/csi-azurefile-node.yaml
  charts/v1.8.0/azurefile-csi-driver/templates/csi-snapshot-controller.yaml
  charts/v1.8.0/azurefile-csi-driver/templates/rbac-csi-azurefile-controller.yaml
  charts/v1.8.0/azurefile-csi-driver/templates/rbac-csi-azurefile-node.yaml
  charts/v1.8.0/azurefile-csi-driver/templates/rbac-csi-snapshot-controller.yaml
  charts/v1.8.0/azurefile-csi-driver/templates/serviceaccount-csi-azurefile-controller.yaml
  charts/v1.8.0/azurefile-csi-driver/templates/serviceaccount-csi-azurefile-node.yaml
  charts/v1.8.0/azurefile-csi-driver/templates/serviceaccount-csi-snapshot-controller.yaml
  charts/v1.8.0/azurefile-csi-driver/values.yaml
  deploy/v1.8.0/crd-csi-snapshot.yaml
  deploy/v1.8.0/csi-azurefile-controller.yaml
  deploy/v1.8.0/csi-azurefile-driver.yaml
  deploy/v1.8.0/csi-azurefile-node-windows.yaml
  deploy/v1.8.0/csi-azurefile-node.yaml
  deploy/v1.8.0/csi-snapshot-controller.yaml
  deploy/v1.8.0/rbac-csi-azurefile-controller.yaml
  deploy/v1.8.0/rbac-csi-azurefile-node.yaml
  deploy/v1.8.0/rbac-csi-snapshot-controller.yaml
  docs/install-azurefile-csi-driver.md
  docs/install-csi-driver-v1.8.0.md
Labels: kind/documentation, do-not-merge/hold, approved, cncf-cla: yes, size/XXL

#848 chore: switch master branch to use v1.9.0
  Makefile
  charts/index.yaml
  charts/latest/azurefile-csi-driver-v1.8.0.tgz
  charts/latest/azurefile-csi-driver-v1.9.0.tgz
  charts/latest/azurefile-csi-driver/Chart.yaml
Labels: kind/documentation, size/M, approved, cncf-cla: yes
