Repository kubernetes-sigs/azurefile-csi-driver, pull requests merged in 2021-09, with the labels that each got.

#782 feat: support allowBlobPublicAccess in storage class
  docs/driver-parameters.md
  go.mod
  go.sum
  pkg/azurefile/azurefile.go
  pkg/azurefile/controllerserver.go
  test/e2e/dynamic_provisioning_test.go
  vendor/modules.txt
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_blobDiskController.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_storage.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_storageaccount.go
Labels: kind/feature, size/M, approved, cncf-cla: yes

#785 test: fix intree test failures
  test/e2e/dynamic_provisioning_test.go
Labels: size/M, lgtm, approved, cncf-cla: yes, kind/test

#783 chore: upgrade azure lib
  go.mod
  go.sum
  pkg/azurefile/azurefile.go
  pkg/azurefile/azurefile_test.go
  pkg/azurefile/controllerserver.go
  pkg/azurefile/controllerserver_test.go
  pkg/azurefile/nodeserver.go
  test/e2e/testsuites/pre_provisioned_existing_credentials_tester.go
  test/e2e/testsuites/pre_provisioned_provided_credentials_tester.go
  vendor/modules.txt
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_blobDiskController.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_storageaccount.go
Labels: kind/feature, size/L, approved, cncf-cla: yes

#784 fix: remove ClusterFirstWithHostNet dnsPolicy
  Makefile
  charts/README.md
  charts/latest/azurefile-csi-driver-v1.6.0.tgz
  charts/latest/azurefile-csi-driver/templates/csi-azurefile-node.yaml
  charts/latest/azurefile-csi-driver/values.yaml
  deploy/csi-azurefile-node.yaml
Labels: kind/bug, size/XS, approved, cncf-cla: yes

#787 test: specify userAgentSuffix in e2e test
  Makefile
Labels: size/XS, approved, cncf-cla: yes, kind/test

#788 chore: upgrade sidcar container versions
  charts/latest/azurefile-csi-driver-v1.6.0.tgz
  charts/latest/azurefile-csi-driver/values.yaml
  deploy/csi-azurefile-controller.yaml
  deploy/csi-azurefile-node-windows.yaml
  deploy/csi-azurefile-node.yaml
Labels: kind/feature, size/S, approved, cncf-cla: yes

#790 doc: cut v1.6.0 release
  README.md
  charts/index.yaml
  charts/v1.6.0/azurefile-csi-driver-v1.6.0.tgz
  charts/v1.6.0/azurefile-csi-driver/Chart.yaml
  charts/v1.6.0/azurefile-csi-driver/templates/NOTES.txt
  charts/v1.6.0/azurefile-csi-driver/templates/_helpers.tpl
  charts/v1.6.0/azurefile-csi-driver/templates/crd-csi-snapshot-ga.yaml
  charts/v1.6.0/azurefile-csi-driver/templates/crd-csi-snapshot.yaml
  charts/v1.6.0/azurefile-csi-driver/templates/csi-azurefile-controller.yaml
  charts/v1.6.0/azurefile-csi-driver/templates/csi-azurefile-driver.yaml
  charts/v1.6.0/azurefile-csi-driver/templates/csi-azurefile-node-windows.yaml
  charts/v1.6.0/azurefile-csi-driver/templates/csi-azurefile-node.yaml
  charts/v1.6.0/azurefile-csi-driver/templates/csi-snapshot-controller.yaml
  charts/v1.6.0/azurefile-csi-driver/templates/rbac-csi-azurefile-controller.yaml
  charts/v1.6.0/azurefile-csi-driver/templates/rbac-csi-azurefile-node.yaml
  charts/v1.6.0/azurefile-csi-driver/templates/rbac-csi-snapshot-controller.yaml
  charts/v1.6.0/azurefile-csi-driver/templates/serviceaccount-csi-azurefile-controller.yaml
  charts/v1.6.0/azurefile-csi-driver/templates/serviceaccount-csi-azurefile-node.yaml
  charts/v1.6.0/azurefile-csi-driver/templates/serviceaccount-csi-snapshot-controller.yaml
  charts/v1.6.0/azurefile-csi-driver/values.yaml
  deploy/v1.6.0/crd-csi-snapshot.yaml
  deploy/v1.6.0/csi-azurefile-controller.yaml
  deploy/v1.6.0/csi-azurefile-driver.yaml
  deploy/v1.6.0/csi-azurefile-node-windows.yaml
  deploy/v1.6.0/csi-azurefile-node.yaml
  deploy/v1.6.0/csi-snapshot-controller.yaml
  deploy/v1.6.0/rbac-csi-azurefile-controller.yaml
  deploy/v1.6.0/rbac-csi-azurefile-node.yaml
  deploy/v1.6.0/rbac-csi-snapshot-controller.yaml
  docs/install-azurefile-csi-driver.md
  docs/install-csi-driver-v1.6.0.md
Labels: kind/documentation, approved, cncf-cla: yes, size/XXL

#791 chore: switch master branch to use v1.7.0
  Makefile
  charts/index.yaml
  charts/latest/azurefile-csi-driver-v1.6.0.tgz
  charts/latest/azurefile-csi-driver-v1.7.0.tgz
  charts/latest/azurefile-csi-driver/Chart.yaml
Labels: kind/documentation, size/M, approved, cncf-cla: yes

#792 test: upgrade csi-provisioner to v3.0.0 in external e2e test
  test/external-e2e/run.sh
Labels: kind/feature, size/XS, approved, cncf-cla: yes

#789 test: Add unit tests
  pkg/azurefile/azurefile_client_test.go
  pkg/azurefile/controllerserver_test.go
  pkg/azurefile/nodeserver_test.go
  pkg/azurefile/utils_test.go
Labels: size/L, lgtm, approved, cncf-cla: yes

#794 test: remove deprecated test configs
  test/e2e/manifest/in-tree-vmss.json
  test/e2e/manifest/in-tree.json
  test/e2e/manifest/linux-vmss.json
  test/e2e/manifest/migration-windows.json
  test/e2e/manifest/migration.json
Labels: size/S, approved, cncf-cla: yes, kind/test

#795 test: enable smb fsGroup external test
  deploy/example/storageclass-azurefile-csi.yaml
  pkg/azurefile/nodeserver.go
  test/external-e2e/run.sh
  test/external-e2e/testdriver-smb.yaml
Labels: size/XS, approved, cncf-cla: yes, kind/test

#796 test: run v1.22 external test
  test/external-e2e/run.sh
Labels: size/XS, approved, cncf-cla: yes, kind/test

#797 feat: ReadWriteOncePod support
  pkg/azurefile/azurefile.go
  pkg/azurefile/controllerserver.go
  pkg/csi-common/utils_test.go
  test/sanity/run-test.sh
  test/sanity/run-tests-all-clouds.sh
Labels: kind/feature, size/S, approved, cncf-cla: yes

#798 feat: upgrade snapshot CRD to v4.2.1
  charts/latest/azurefile-csi-driver-v1.7.0.tgz
  charts/latest/azurefile-csi-driver/templates/crd-csi-snapshot-ga.yaml
  deploy/csi-azurefile-node-windows.yaml
  deploy/csi-azurefile-node.yaml
Labels: kind/feature, size/M, lgtm, approved, cncf-cla: yes

#759 feat: enable fsGroup for nfs
  pkg/azurefile/nodeserver.go
  pkg/azurefile/utils.go
  pkg/azurefile/utils_test.go
  vendor/k8s.io/client-go/util/testing/fake_handler.go
  vendor/k8s.io/client-go/util/testing/tmpdir.go
  vendor/modules.txt
Labels: size/L, approved, cncf-cla: yes, kind/test

#799 chore: refine ProxyMounter interface
  pkg/azurefile/azure_common_windows.go
  pkg/mounter/safe_mounter_v1beta_windows.go
  pkg/mounter/safe_mounter_windows.go
Labels: size/L, kind/cleanup, approved, cncf-cla: yes

#800 feat: add ReadWriteOncePod cap
  pkg/azurefile/azurefile.go
  test/sanity/run-test.sh
Labels: kind/feature, size/XS, approved, cncf-cla: yes

#801 fix: libssl1.1 vulnerability
  Makefile
  pkg/azurefileplugin/Dockerfile
  pkg/azurefileplugin/dev.Dockerfile
Labels: kind/bug, size/XS, approved, cncf-cla: yes

#803 test: add trivy vulnerability scanning test
  .github/workflows/trivy.yaml
  Makefile
  pkg/azurefileplugin/Dockerfile
  pkg/azurefileplugin/dev.Dockerfile
Labels: size/M, approved, cncf-cla: yes, kind/test

#807 feat: adds 'Windows Server 2022' to build process
  Makefile
  docs/csi-dev.md
Labels: kind/feature, ok-to-test, kind/documentation, size/XS, lgtm, approved, cncf-cla: yes

#804 feat: add affinity and node affinity as values
  charts/latest/azurefile-csi-driver-v1.7.0.tgz
  charts/latest/azurefile-csi-driver/templates/csi-azurefile-controller.yaml
  charts/latest/azurefile-csi-driver/templates/csi-azurefile-node-windows.yaml
  charts/latest/azurefile-csi-driver/templates/csi-azurefile-node.yaml
  charts/latest/azurefile-csi-driver/templates/csi-snapshot-controller.yaml
  charts/latest/azurefile-csi-driver/values.yaml
Labels: ok-to-test, size/M, lgtm, approved, cncf-cla: yes

#806 feat: set allowBlobPublicAccess as false by default
  docs/driver-parameters.md
  pkg/azurefile/controllerserver.go
Labels: kind/feature, size/XS, approved, cncf-cla: yes

#808 feat: add 20H2 Windows image support
  Makefile
  docs/csi-dev.md
Labels: kind/feature, size/XS, approved, cncf-cla: yes

#809 fix: driver pod crash issue on Windows
  charts/latest/azurefile-csi-driver-v1.7.0.tgz
  charts/latest/azurefile-csi-driver/templates/csi-azurefile-controller.yaml
  charts/latest/azurefile-csi-driver/templates/csi-azurefile-node-windows.yaml
  charts/latest/azurefile-csi-driver/templates/csi-azurefile-node.yaml
  deploy/csi-azurefile-controller.yaml
  deploy/csi-azurefile-node-windows.yaml
  deploy/csi-azurefile-node.yaml
Labels: kind/bug, size/S, approved, cncf-cla: yes
