Repository kubernetes-sigs/azurefile-csi-driver, pull requests merged in 2021-05, with the labels that each got.

#638 fix: random arm64 build failure
  Makefile
Labels: approved, cncf-cla: yes, kind/bug, size/XS

#639 fix: remove namespace in ClusterRole
  charts/latest/azurefile-csi-driver-v1.2.0.tgz
  charts/latest/azurefile-csi-driver/templates/rbac-csi-azurefile-controller.yaml
  charts/latest/azurefile-csi-driver/templates/rbac-csi-azurefile-node.yaml
  charts/latest/azurefile-csi-driver/templates/rbac-csi-snapshot-controller.yaml
  deploy/rbac-csi-azurefile-controller.yaml
  deploy/rbac-csi-azurefile-node.yaml
  deploy/rbac-csi-snapshot-controller.yaml
Labels: approved, cncf-cla: yes, kind/bug, size/S

#640 add sanity test step in github actions
  .github/workflows/linux.yaml
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, ok-to-test, size/XS

#641 doc: cut v1.2.0 release
  .github/workflows/linux.yaml
  README.md
  charts/README.md
  charts/index.yaml
  charts/v1.2.0/azurefile-csi-driver-v1.2.0.tgz
  charts/v1.2.0/azurefile-csi-driver/Chart.yaml
  charts/v1.2.0/azurefile-csi-driver/templates/NOTES.txt
  charts/v1.2.0/azurefile-csi-driver/templates/_helpers.tpl
  charts/v1.2.0/azurefile-csi-driver/templates/crd-csi-snapshot.yaml
  charts/v1.2.0/azurefile-csi-driver/templates/csi-azurefile-controller.yaml
  charts/v1.2.0/azurefile-csi-driver/templates/csi-azurefile-driver.yaml
  charts/v1.2.0/azurefile-csi-driver/templates/csi-azurefile-node-windows.yaml
  charts/v1.2.0/azurefile-csi-driver/templates/csi-azurefile-node.yaml
  charts/v1.2.0/azurefile-csi-driver/templates/csi-snapshot-controller.yaml
  charts/v1.2.0/azurefile-csi-driver/templates/rbac-csi-azurefile-controller.yaml
  charts/v1.2.0/azurefile-csi-driver/templates/rbac-csi-azurefile-node.yaml
  charts/v1.2.0/azurefile-csi-driver/templates/rbac-csi-snapshot-controller.yaml
  charts/v1.2.0/azurefile-csi-driver/templates/serviceaccount-csi-azurefile-controller.yaml
  charts/v1.2.0/azurefile-csi-driver/templates/serviceaccount-csi-azurefile-node.yaml
  charts/v1.2.0/azurefile-csi-driver/templates/serviceaccount-csi-snapshot-controller.yaml
  charts/v1.2.0/azurefile-csi-driver/values.yaml
  deploy/v1.2.0/crd-csi-snapshot.yaml
  deploy/v1.2.0/csi-azurefile-controller.yaml
  deploy/v1.2.0/csi-azurefile-driver.yaml
  deploy/v1.2.0/csi-azurefile-node-windows.yaml
  deploy/v1.2.0/csi-azurefile-node.yaml
  deploy/v1.2.0/csi-snapshot-controller.yaml
  deploy/v1.2.0/rbac-csi-azurefile-controller.yaml
  deploy/v1.2.0/rbac-csi-azurefile-node.yaml
  deploy/v1.2.0/rbac-csi-snapshot-controller.yaml
  docs/install-azurefile-csi-driver.md
  docs/install-csi-driver-v1.2.0.md
Labels: approved, cncf-cla: yes, kind/feature, size/XXL

#642 chore: switch master branch to use v1.3.0
  Makefile
  charts/index.yaml
  charts/latest/azurefile-csi-driver-v1.2.0.tgz
  charts/latest/azurefile-csi-driver-v1.3.0.tgz
  charts/latest/azurefile-csi-driver/Chart.yaml
Labels: approved, cncf-cla: yes, kind/cleanup, size/M

#643 feat: Enable creation of storage accounts that support large file shares
  go.mod
  go.sum
  pkg/azurefile/azurefile.go
  pkg/azurefile/controllerserver.go
  test/e2e/dynamic_provisioning_test.go
  vendor/modules.txt
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azureclients/containerserviceclient/azure_containerserviceclient.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azureclients/deploymentclient/azure_deploymentclient.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azureclients/diskclient/azure_diskclient.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azureclients/interfaceclient/azure_interfaceclient.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azureclients/loadbalancerclient/azure_loadbalancerclient.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azureclients/publicipclient/azure_publicipclient.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azureclients/routeclient/azure_routeclient.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azureclients/routetableclient/azure_routetableclient.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azureclients/securitygroupclient/azure_securitygroupclient.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azureclients/snapshotclient/azure_snapshotclient.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azureclients/storageaccountclient/azure_storageaccountclient.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azureclients/subnetclient/azure_subnetclient.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azureclients/vmasclient/azure_vmasclient.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azureclients/vmclient/azure_vmclient.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azureclients/vmsizeclient/azure_vmsizeclient.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azureclients/vmssclient/azure_vmssclient.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azureclients/vmssvmclient/azure_vmssvmclient.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/consts/consts.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_routes.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_storageaccount.go
  vendor/sigs.k8s.io/structured-merge-diff/v4/typed/reconcile_schema.go
  vendor/sigs.k8s.io/structured-merge-diff/v4/typed/remove.go
Labels: approved, cncf-cla: yes, kind/feature, lgtm, size/L

#644 add a new helm parameter for livenessProbe health port
  charts/README.md
  charts/latest/azurefile-csi-driver-v1.3.0.tgz
  charts/latest/azurefile-csi-driver/templates/csi-azurefile-node.yaml
  charts/latest/azurefile-csi-driver/values.yaml
Labels: approved, cncf-cla: yes, kind/feature, lgtm, ok-to-test, size/XS

#645 test: disable enableLargeFileshares in-tree test
  test/e2e/dynamic_provisioning_test.go
Labels: approved, cncf-cla: yes, kind/failing-test, size/XS

#648 fix: second pod mount error for static provisioning(sharename specified)
  pkg/azurefile/azurefile.go
  pkg/azurefile/azurefile_test.go
  pkg/azurefile/controllerserver.go
Labels: approved, cncf-cla: yes, kind/bug, size/S

#649 test: add test for volumeID collision fix
  test/e2e/pre_provisioning_test.go
Labels: approved, cncf-cla: yes, kind/test, size/XS

#650 test: fix containerd Windows e2e test failure
  hack/verify-examples.sh
  test/e2e/testsuites/dynamically_provisioned_delete_pod_tester.go
  test/e2e/testsuites/dynamically_provisioned_statefulset_tester.go
Labels: approved, cncf-cla: yes, kind/failing-test, size/S

#652 chore: upgrade `apiextensions.k8s.io/v1beta1` and `storage.k8s.io/v1beta1 `
  charts/latest/azurefile-csi-driver-v1.3.0.tgz
  charts/latest/azurefile-csi-driver/templates/crd-csi-snapshot.yaml
  charts/latest/azurefile-csi-driver/templates/csi-azurefile-driver.yaml
  deploy/crd-csi-snapshot.yaml
  deploy/csi-azurefile-driver.yaml
  test/e2e/testsuites/dynamically_provisioned_statefulset_tester.go
Labels: approved, cncf-cla: yes, kind/cleanup, size/XXL

#653 chore: upgrade base image to fix CVE issue
  pkg/azurefileplugin/Dockerfile
Labels: approved, cncf-cla: yes, kind/cleanup, size/XS

#656 chore: refine updateSubnetServiceEndpoints
  pkg/azurefile/azure.go
  pkg/azurefile/azure_test.go
  pkg/azurefile/controllerserver.go
  pkg/azurefile/controllerserver_test.go
Labels: approved, cncf-cla: yes, kind/cleanup, size/L

#657 feat: add inline volume support
  charts/latest/azurefile-csi-driver-v1.3.0.tgz
  charts/latest/azurefile-csi-driver/templates/csi-azurefile-driver.yaml
  charts/latest/azurefile-csi-driver/templates/csi-azurefile-node-windows.yaml
  deploy/csi-azurefile-driver.yaml
  deploy/csi-azurefile-node-windows.yaml
  pkg/azurefile/azurefile.go
  pkg/azurefile/nodeserver.go
  test/e2e/dynamic_provisioning_test.go
  test/e2e/pre_provisioning_test.go
  test/e2e/testsuites/dynamically_provisioned_inline_volume.go
  test/e2e/testsuites/specs.go
  test/e2e/testsuites/testsuites.go
Labels: approved, cncf-cla: yes, do-not-merge/hold, kind/feature, size/L

#658 doc: inline volume, kubeconfig, kubelet chart config
  charts/README.md
  charts/latest/azurefile-csi-driver-v1.3.0.tgz
  charts/latest/azurefile-csi-driver/templates/csi-azurefile-controller.yaml
  charts/latest/azurefile-csi-driver/templates/csi-azurefile-node-windows.yaml
  charts/latest/azurefile-csi-driver/templates/csi-azurefile-node.yaml
  charts/latest/azurefile-csi-driver/values.yaml
  deploy/example/e2e_usage.md
  deploy/example/nginx-pod-azurefile-inline-volume.yaml
Labels: approved, cncf-cla: yes, kind/documentation, size/M

#661 fix: CentOS/RedHat cert issue in chart installation
  README.md
  charts/README.md
  charts/latest/azurefile-csi-driver-v1.3.0.tgz
  charts/latest/azurefile-csi-driver/templates/csi-azurefile-controller.yaml
  charts/latest/azurefile-csi-driver/templates/csi-azurefile-node.yaml
  charts/latest/azurefile-csi-driver/values.yaml
  test/e2e/pre_provisioning_test.go
Labels: approved, cncf-cla: yes, kind/bug, size/M

#662 fix: set "host is down" as corrupted mount
  go.mod
  go.sum
  vendor/k8s.io/mount-utils/mount_helper_common.go
  vendor/k8s.io/mount-utils/mount_helper_unix.go
  vendor/k8s.io/mount-utils/mount_helper_windows.go
  vendor/k8s.io/mount-utils/resizefs_linux.go
  vendor/modules.txt
Labels: approved, cncf-cla: yes, kind/bug, size/L

#654 doc: Update docs for EnableLargeFileShares
  docs/csi-debug.md
  docs/driver-parameters.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#663 fix: remove unnecessary lock in NodePublish
  pkg/azurefile/nodeserver.go
  pkg/azurefile/nodeserver_test.go
Labels: approved, cncf-cla: yes, kind/bug, size/M

#664 chore: upgrade sidecar container versions
  charts/README.md
  charts/latest/azurefile-csi-driver-v1.3.0.tgz
  charts/latest/azurefile-csi-driver/values.yaml
  deploy/csi-azurefile-controller.yaml
  deploy/csi-azurefile-node-windows.yaml
  deploy/csi-azurefile-node.yaml
  test/e2e/testsuites/dynamically_provisioned_statefulset_tester.go
Labels: approved, cncf-cla: yes, kind/feature, size/M

#666 feat: store secret in pod.Namespace if not specified
  charts/latest/azurefile-csi-driver-v1.3.0.tgz
  charts/latest/azurefile-csi-driver/templates/csi-azurefile-controller.yaml
  deploy/csi-azurefile-controller.yaml
  pkg/azurefile/azurefile.go
  pkg/azurefile/controllerserver.go
  test/e2e/dynamic_provisioning_test.go
  test/e2e/pre_provisioning_test.go
Labels: approved, cncf-cla: yes, do-not-merge/hold, kind/feature, size/M

#613 test: add inline volume test
  test/e2e/dynamic_provisioning_test.go
Labels: approved, cncf-cla: yes, kind/test, size/L

#667 test: run more external storage tests
  test/external-e2e/run.sh
  test/external-e2e/testdriver.yaml
Labels: approved, cncf-cla: yes, kind/test, size/S

#669 test: run external storage test with 1.21 suites
  test/external-e2e/run.sh
Labels: approved, cncf-cla: yes, kind/bug, size/XS

#670 test: run external tests on NFS
  test/external-e2e/run.sh
Labels: approved, cncf-cla: yes, kind/test, size/S

#671 fix: unmount stuck issue when azure file is not found
  pkg/azurefile/azure_common_linux.go
  pkg/azurefile/nodeserver.go
Labels: approved, cncf-cla: yes, do-not-merge/hold, kind/bug, size/XS

#672 fix: sercretNamesapce empty issue in old driver PV
  pkg/azurefile/azurefile.go
Labels: approved, cncf-cla: yes, kind/bug, size/XS

#674 doc: Add example enable large file shares
  deploy/example/largeFileShares/README.md
  deploy/example/largeFileShares/pvc-azurefile-largefileshares.yaml
  deploy/example/largeFileShares/storageclass-azurefile-largefileshares.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#675 fix: only use pod.Namespace in inline volume support
  pkg/azurefile/nodeserver.go
Labels: approved, cncf-cla: yes, kind/bug, size/XS

#676 doc: update yaml configs
  deploy/example/largeFileShares/pvc-azurefile-largefileshares.yaml
  deploy/example/largeFileShares/storageclass-azurefile-largefileshares.yaml
  deploy/example/nginx-pod-azurefile-inline-volume.yaml
  hack/verify-yamllint.sh
Labels: approved, cncf-cla: yes, kind/documentation, size/XS

#678 fix: only read secret for inline volume
  pkg/azurefile/azurefile.go
  pkg/azurefile/controllerserver.go
  pkg/azurefile/nodeserver.go
Labels: approved, cncf-cla: yes, kind/bug, size/S

#679 test: split external storage tests to smb & nfs tests
  Makefile
  charts/latest/azurefile-csi-driver-v1.3.0.tgz
  charts/latest/azurefile-csi-driver/templates/csi-azurefile-driver.yaml
  charts/latest/azurefile-csi-driver/values.yaml
  deploy/example/resize/README.md
  test/external-e2e/run.sh
  test/external-e2e/testdriver-nfs.yaml
  test/external-e2e/testdriver-smb.yaml
Labels: approved, cncf-cla: yes, kind/feature, size/L

#683 feat: support customized smb server
  pkg/azurefile/nodeserver.go
  pkg/azurefile/nodeserver_test.go
Labels: approved, cncf-cla: yes, kind/feature, size/XS

#685 fix: controller could run well without cloud provider
  pkg/azurefile/azure.go
  pkg/azurefile/azure_test.go
  pkg/azurefile/azurefile.go
Labels: approved, cncf-cla: yes, kind/feature, size/L

#684 fix: convert source path on Windows
  pkg/mounter/safe_mounter_windows.go
Labels: approved, cncf-cla: yes, kind/bug, size/XS
