Repository kubernetes-sigs/azurefile-csi-driver, pull requests merged in 2021-01, with the labels that each got.

#511 feat: switch to use csi-proxy beta API
  charts/latest/azurefile-csi-driver/templates/csi-azurefile-node-windows.yaml
  deploy/csi-azurefile-node-windows.yaml
  go.mod
  go.sum
  pkg/mounter/safe_mounter_windows.go
  vendor/github.com/kubernetes-csi/csi-proxy/client/api/filesystem/v1beta1/api.pb.go
  vendor/github.com/kubernetes-csi/csi-proxy/client/api/filesystem/v1beta1/api.proto
  vendor/github.com/kubernetes-csi/csi-proxy/client/api/smb/v1beta1/api.pb.go
  vendor/github.com/kubernetes-csi/csi-proxy/client/api/smb/v1beta1/api.proto
  vendor/github.com/kubernetes-csi/csi-proxy/client/groups/filesystem/v1beta1/client_generated.go
  vendor/github.com/kubernetes-csi/csi-proxy/client/groups/smb/v1beta1/client_generated.go
  vendor/modules.txt
Labels: approved, cncf-cla: yes, kind/feature, size/L

#512 doc: cut v0.10.0 release
  README.md
  charts/README.md
  charts/v0.10.0/azurefile-csi-driver-v0.10.0.tgz
  charts/v0.10.0/azurefile-csi-driver/Chart.yaml
  charts/v0.10.0/azurefile-csi-driver/templates/NOTES.txt
  charts/v0.10.0/azurefile-csi-driver/templates/_helpers.tpl
  charts/v0.10.0/azurefile-csi-driver/templates/crd-csi-snapshot.yaml
  charts/v0.10.0/azurefile-csi-driver/templates/csi-azurefile-controller.yaml
  charts/v0.10.0/azurefile-csi-driver/templates/csi-azurefile-driver.yaml
  charts/v0.10.0/azurefile-csi-driver/templates/csi-azurefile-node-windows.yaml
  charts/v0.10.0/azurefile-csi-driver/templates/csi-azurefile-node.yaml
  charts/v0.10.0/azurefile-csi-driver/templates/csi-snapshot-controller.yaml
  charts/v0.10.0/azurefile-csi-driver/templates/rbac-csi-azurefile-controller.yaml
  charts/v0.10.0/azurefile-csi-driver/templates/rbac-csi-azurefile-node.yaml
  charts/v0.10.0/azurefile-csi-driver/templates/rbac-csi-snapshot-controller.yaml
  charts/v0.10.0/azurefile-csi-driver/templates/serviceaccount-csi-azurefile-controller.yaml
  charts/v0.10.0/azurefile-csi-driver/templates/serviceaccount-csi-azurefile-node.yaml
  charts/v0.10.0/azurefile-csi-driver/templates/serviceaccount-csi-snapshot-controller.yaml
  charts/v0.10.0/azurefile-csi-driver/values.yaml
  deploy/example/daemonset.yaml
  deploy/example/deployment.yaml
  deploy/example/nfs/README.md
  deploy/example/nfs/statefulset.yaml
  deploy/example/nginx-pod-azurefile.yaml
  deploy/example/statefulset.yaml
  deploy/example/storageclass-azurefile-nfs.yaml
  deploy/example/windows/README.md
  deploy/v0.10.0/crd-csi-snapshot.yaml
  deploy/v0.10.0/csi-azurefile-controller.yaml
  deploy/v0.10.0/csi-azurefile-driver.yaml
  deploy/v0.10.0/csi-azurefile-node-windows.yaml
  deploy/v0.10.0/csi-azurefile-node.yaml
  deploy/v0.10.0/csi-snapshot-controller.yaml
  deploy/v0.10.0/rbac-csi-azurefile-controller.yaml
  deploy/v0.10.0/rbac-csi-azurefile-node.yaml
  deploy/v0.10.0/rbac-csi-snapshot-controller.yaml
  docs/install-azurefile-csi-driver.md
  docs/install-csi-driver-v0.10.0.md
Labels: approved, cncf-cla: yes, kind/documentation, size/XXL

#514 test: enable GH actions on all branches
  .github/workflows/darwin.yaml
  .github/workflows/ubuntu.yml
  .github/workflows/windows.yml
Labels: approved, cncf-cla: yes, kind/cleanup, size/M

#515 test: refine windows ut
  pkg/azurefile/fake_mounter.go
  pkg/azurefile/nodeserver_test.go
Labels: approved, cncf-cla: yes, kind/test, size/L

#516 test: fix NodePublishVolume Windows unit test
  .github/workflows/linux.yaml
  .github/workflows/windows.yaml
  pkg/azurefile/nodeserver_test.go
  test/utils/testutil/testutil.go
Labels: approved, cncf-cla: yes, size/M

#519 feat: add secretName parameter
  docs/driver-parameters.md
  pkg/azurefile/azurefile.go
  pkg/azurefile/controllerserver.go
  pkg/azurefile/controllerserver_test.go
  pkg/azurefile/utils.go
  pkg/azurefile/utils_test.go
  test/e2e/dynamic_provisioning_test.go
Labels: approved, cncf-cla: yes, kind/feature, size/M

#520 test: fix secretName e2e test
  test/e2e/dynamic_provisioning_test.go
Labels: approved, cncf-cla: yes, kind/test, lgtm, size/XS

#521 chore: upgrade resizer to v1.1.0
  charts/latest/azurefile-csi-driver/templates/csi-azurefile-controller.yaml
  charts/latest/azurefile-csi-driver/values.yaml
  deploy/csi-azurefile-controller.yaml
Labels: approved, cncf-cla: yes, do-not-merge/hold, kind/feature, size/XS

#522 test: fix in-tree e2e test failure
  test/e2e/dynamic_provisioning_test.go
Labels: approved, cncf-cla: yes, kind/failing-test, size/S

#524 fix: account creation lock issue
  pkg/azurefile/controllerserver.go
Labels: approved, cncf-cla: yes, kind/bug, size/XS

#523 fix: ExceedsAccountLimit issue
  go.mod
  go.sum
  pkg/azurefile/azurefile.go
  pkg/azurefile/controllerserver.go
  vendor/modules.txt
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azureclients/diskclient/interface.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_controller_common.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_controller_standard.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_controller_vmss.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_loadbalancer.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_managedDiskController.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_mock_vmsets.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_standard.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_storageaccount.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_vmsets.go
Labels: approved, cncf-cla: yes, kind/bug, size/XL

#527 feat: add kubeletPath support in Helm chart
  charts/README.md
  charts/latest/azurefile-csi-driver/templates/csi-azurefile-node-windows.yaml
  charts/latest/azurefile-csi-driver/templates/csi-azurefile-node.yaml
  charts/latest/azurefile-csi-driver/values.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#513 fix: Handle concurrent operation of NodeUnstage with NodeStage and NodeUnpublish with NodePublish
  pkg/azurefile/azurefile.go
  pkg/azurefile/nodeserver.go
  pkg/azurefile/nodeserver_test.go
  pkg/azurefile/volume_lock.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, ok-to-test, size/L

#518 test: add restart driver e2e test
  test/e2e/dynamic_provisioning_test.go
  test/e2e/testsuites/dynamically_provisioned_restart_driver_tester.go
  test/utils/restart_driver_daemonset.sh
Labels: approved, cncf-cla: yes, kind/test, lgtm, ok-to-test, size/L

#529 feat: upgrade to snapshotter v3.0.3
  charts/latest/azurefile-csi-driver/values.yaml
  deploy/csi-azurefile-controller.yaml
  deploy/csi-snapshot-controller.yaml
Labels: approved, cncf-cla: yes, kind/feature, size/XS

#530 chore: remove klog v1
  go.mod
  test/e2e/driver/azurefile_driver.go
  test/e2e/testsuites/testsuites.go
  vendor/k8s.io/klog/.travis.yml
  vendor/k8s.io/klog/CONTRIBUTING.md
  vendor/k8s.io/klog/LICENSE
  vendor/k8s.io/klog/OWNERS
  vendor/k8s.io/klog/README.md
  vendor/k8s.io/klog/RELEASE.md
  vendor/k8s.io/klog/SECURITY_CONTACTS
  vendor/k8s.io/klog/code-of-conduct.md
  vendor/k8s.io/klog/go.mod
  vendor/k8s.io/klog/go.sum
  vendor/k8s.io/klog/klog.go
  vendor/k8s.io/klog/klog_file.go
  vendor/modules.txt
Labels: approved, cncf-cla: yes, kind/cleanup, size/XXL

#531 test: add verify example test
  Makefile
  deploy/example/daemonset.yaml
  deploy/example/statefulset-nonroot.yaml
  deploy/example/windows/deployment.yaml
  deploy/example/windows/statefulset.yaml
  hack/verify-examples.sh
  test/e2e/suite_test.go
Labels: approved, cncf-cla: yes, kind/test, size/M

#532 fix: reduce driver logs
  .github/workflows/darwin.yaml
  .github/workflows/linux.yaml
  charts/latest/azurefile-csi-driver/templates/csi-azurefile-controller.yaml
  charts/latest/azurefile-csi-driver/templates/csi-azurefile-node-windows.yaml
  charts/latest/azurefile-csi-driver/templates/csi-azurefile-node.yaml
  charts/latest/azurefile-csi-driver/templates/csi-snapshot-controller.yaml
  deploy/csi-azurefile-controller.yaml
  deploy/csi-azurefile-node-windows.yaml
  deploy/csi-azurefile-node.yaml
  deploy/csi-snapshot-controller.yaml
  hack/verify-examples.sh
  pkg/csi-common/controllerserver-default.go
  pkg/csi-common/identityserver-default.go
  pkg/csi-common/nodeserver-default.go
  pkg/csi-common/utils.go
  pkg/csi-common/utils_test.go
Labels: approved, cncf-cla: yes, kind/bug, size/L

#534 chore: upgrade livenessprobe to v2.2.0
  charts/latest/azurefile-csi-driver/values.yaml
  deploy/csi-azurefile-controller.yaml
  deploy/csi-azurefile-node-windows.yaml
  deploy/csi-azurefile-node.yaml
Labels: approved, cncf-cla: yes, kind/feature, size/S

#537 feat: add more controller metrics
  pkg/azurefile/controllerserver.go
Labels: approved, cncf-cla: yes, kind/feature, size/M

#535 feat: add lock in controller
  deploy/example/windows/README.md
  pkg/azurefile/controllerserver.go
Labels: approved, cncf-cla: yes, do-not-merge/hold, kind/feature, size/M

#538 fix: missing cloud_provider_azure metrics
  go.mod
  pkg/azurefileplugin/main.go
  vendor/modules.txt
Labels: approved, cncf-cla: yes, do-not-merge/hold, kind/bug, size/S

#539 feat: skip account matching with special tags
  go.mod
  go.sum
  vendor/k8s.io/cloud-provider/cloud.go
  vendor/k8s.io/cloud-provider/go.mod
  vendor/k8s.io/cloud-provider/go.sum
  vendor/modules.txt
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azureclients/armclient/azure_armclient.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azureclients/diskclient/azure_diskclient.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azureclients/interfaceclient/azure_interfaceclient.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azureclients/interfaceclient/interface.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azureclients/loadbalancerclient/azure_loadbalancerclient.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azureclients/loadbalancerclient/interface.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azureclients/publicipclient/azure_publicipclient.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azureclients/publicipclient/interface.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azureclients/routeclient/azure_routeclient.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azureclients/routeclient/interface.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azureclients/routetableclient/azure_routetableclient.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azureclients/routetableclient/interface.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azureclients/securitygroupclient/azure_securitygroupclient.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azureclients/securitygroupclient/interface.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azureclients/snapshotclient/azure_snapshotclient.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azureclients/snapshotclient/interface.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azureclients/storageaccountclient/azure_storageaccountclient.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azureclients/storageaccountclient/interface.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azureclients/storageaccountclient/mockstorageaccountclient/interface.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azureclients/subnetclient/azure_subnetclient.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azureclients/subnetclient/interface.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azureclients/vmclient/azure_vmclient.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azureclients/vmclient/interface.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azureclients/vmsizeclient/azure_vmsizeclient.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azureclients/vmsizeclient/interface.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azureclients/vmssclient/azure_vmssclient.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azureclients/vmssclient/interface.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azureclients/vmssvmclient/azure_vmssvmclient.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azureclients/vmssvmclient/interface.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_backoff.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_instances.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_loadbalancer.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_storageaccount.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_vmss.go
Labels: approved, cncf-cla: yes, kind/feature, size/XL

#540 feat: skip matching account if exceeding limit
  pkg/azurefile/controllerserver.go
Labels: approved, cncf-cla: yes, do-not-merge/hold, kind/feature, size/S

#541 feat: remove skip-matching tag in DeleteVolume
  go.mod
  go.sum
  pkg/azurefile/controllerserver.go
  vendor/modules.txt
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azureclients/armclient/azure_armclient.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_storageaccount.go
Labels: approved, cncf-cla: yes, kind/feature, size/M

#542 chore: upgrade csi-provisioner to v2.1.0
  charts/latest/azurefile-csi-driver/values.yaml
  deploy/csi-azurefile-controller.yaml
  pkg/azurefile/identityserver.go
Labels: approved, cncf-cla: yes, kind/feature, size/XS

#543 fix: remove securityContext on Windows
  charts/latest/azurefile-csi-driver/templates/csi-azurefile-node-windows.yaml
  deploy/csi-azurefile-node-windows.yaml
Labels: approved, cncf-cla: yes, kind/bug, size/XS

#544 doc: refine examples
  deploy/example/statefulset-nonroot.yaml
  deploy/example/statefulset.yaml
Labels: approved, cncf-cla: yes, kind/documentation, size/XS

#547 fix: update latest helm chart
  .gitignore
  charts/index.yaml
  charts/latest/azurefile-csi-driver-v1.0.0.tgz
  charts/latest/azurefile-csi-driver/Chart.yaml
Labels: approved, cncf-cla: yes, kind/bug, size/XS

#549 test: add helm chart tgz file verification
  hack/verify-helm-chart.sh
Labels: approved, cncf-cla: yes, kind/test, size/S

#550 test: add chart tgz files verification
  charts/v0.2.0/azurefile-csi-driver-0.2.0.tgz
  charts/v0.2.0/azurefile-csi-driver/templates/csi-azurefile-controller.yaml
  charts/v0.2.0/azurefile-csi-driver/templates/csi-azurefile-node.yaml
  charts/v0.2.0/azurefile-csi-driver/templates/rbac-csi-azurefile-controller.yaml
  charts/v0.3.0/azurefile-csi-driver-0.3.0.tgz
  charts/v0.3.0/azurefile-csi-driver/templates/csi-azurefile-controller.yaml
  charts/v0.3.0/azurefile-csi-driver/templates/csi-azurefile-node.yaml
  charts/v0.3.0/azurefile-csi-driver/templates/rbac-csi-azurefile-controller.yaml
  charts/v0.4.0/azurefile-csi-driver-v0.4.0.tgz
  charts/v0.5.0/azurefile-csi-driver-v0.5.0.tgz
  hack/verify-helm-chart.sh
Labels: approved, cncf-cla: yes, kind/test, size/S
