Repository kubernetes-sigs/azurefile-csi-driver, pull requests merged in 2021-02, with the labels that each got.

#551 test: add expand volume integration test
  test/integration/run-test.sh
Labels: approved, cncf-cla: yes, kind/test, size/XS

#552 doc: update charts index
  charts/index.yaml
Labels: approved, cncf-cla: yes, kind/documentation, size/M

#553 doc: cut v1.0.0 GA release
  README.md
  charts/README.md
  charts/index.yaml
  charts/v1.0.0/azurefile-csi-driver-v1.0.0.tgz
  charts/v1.0.0/azurefile-csi-driver/Chart.yaml
  charts/v1.0.0/azurefile-csi-driver/templates/NOTES.txt
  charts/v1.0.0/azurefile-csi-driver/templates/_helpers.tpl
  charts/v1.0.0/azurefile-csi-driver/templates/crd-csi-snapshot.yaml
  charts/v1.0.0/azurefile-csi-driver/templates/csi-azurefile-controller.yaml
  charts/v1.0.0/azurefile-csi-driver/templates/csi-azurefile-driver.yaml
  charts/v1.0.0/azurefile-csi-driver/templates/csi-azurefile-node-windows.yaml
  charts/v1.0.0/azurefile-csi-driver/templates/csi-azurefile-node.yaml
  charts/v1.0.0/azurefile-csi-driver/templates/csi-snapshot-controller.yaml
  charts/v1.0.0/azurefile-csi-driver/templates/rbac-csi-azurefile-controller.yaml
  charts/v1.0.0/azurefile-csi-driver/templates/rbac-csi-azurefile-node.yaml
  charts/v1.0.0/azurefile-csi-driver/templates/rbac-csi-snapshot-controller.yaml
  charts/v1.0.0/azurefile-csi-driver/templates/serviceaccount-csi-azurefile-controller.yaml
  charts/v1.0.0/azurefile-csi-driver/templates/serviceaccount-csi-azurefile-node.yaml
  charts/v1.0.0/azurefile-csi-driver/templates/serviceaccount-csi-snapshot-controller.yaml
  charts/v1.0.0/azurefile-csi-driver/values.yaml
  deploy/v1.0.0/crd-csi-snapshot.yaml
  deploy/v1.0.0/csi-azurefile-controller.yaml
  deploy/v1.0.0/csi-azurefile-driver.yaml
  deploy/v1.0.0/csi-azurefile-node-windows.yaml
  deploy/v1.0.0/csi-azurefile-node.yaml
  deploy/v1.0.0/csi-snapshot-controller.yaml
  deploy/v1.0.0/rbac-csi-azurefile-controller.yaml
  deploy/v1.0.0/rbac-csi-azurefile-node.yaml
  deploy/v1.0.0/rbac-csi-snapshot-controller.yaml
  docs/install-azurefile-csi-driver.md
  docs/install-csi-driver-v1.0.0.md
Labels: approved, cncf-cla: yes, do-not-merge/hold, kind/documentation, size/XXL

#555 test: verify helm chart files
  hack/verify-all.sh
  hack/verify-helm-chart-files.sh
  hack/verify-helm-chart.sh
Labels: approved, cncf-cla: yes, kind/test, size/M

#554 chore: switch master branch to use v1.1.0
  Makefile
  charts/index.yaml
  charts/latest/azurefile-csi-driver-v1.0.0.tgz
  charts/latest/azurefile-csi-driver-v1.1.0.tgz
  charts/latest/azurefile-csi-driver/Chart.yaml
  charts/latest/azurefile-csi-driver/templates/NOTES.txt
  charts/latest/azurefile-csi-driver/templates/_helpers.tpl
  charts/latest/azurefile-csi-driver/templates/crd-csi-snapshot.yaml
  charts/latest/azurefile-csi-driver/templates/csi-azurefile-controller.yaml
  charts/latest/azurefile-csi-driver/templates/csi-azurefile-driver.yaml
  charts/latest/azurefile-csi-driver/templates/csi-azurefile-node-windows.yaml
  charts/latest/azurefile-csi-driver/templates/csi-azurefile-node.yaml
  charts/latest/azurefile-csi-driver/templates/csi-snapshot-controller.yaml
  charts/latest/azurefile-csi-driver/templates/rbac-csi-azurefile-controller.yaml
  charts/latest/azurefile-csi-driver/templates/rbac-csi-azurefile-node.yaml
  charts/latest/azurefile-csi-driver/templates/rbac-csi-snapshot-controller.yaml
  charts/latest/azurefile-csi-driver/templates/serviceaccount-csi-azurefile-controller.yaml
  charts/latest/azurefile-csi-driver/templates/serviceaccount-csi-azurefile-node.yaml
  charts/latest/azurefile-csi-driver/templates/serviceaccount-csi-snapshot-controller.yaml
  charts/latest/azurefile-csi-driver/values.yaml
Labels: approved, cncf-cla: yes, kind/documentation, size/M

#558 test: set lower logLevel in e2e testing
  Makefile
  charts/README.md
  charts/latest/azurefile-csi-driver-v1.1.0.tgz
  charts/latest/azurefile-csi-driver/templates/csi-azurefile-controller.yaml
  charts/latest/azurefile-csi-driver/templates/csi-azurefile-node-windows.yaml
  charts/latest/azurefile-csi-driver/templates/csi-azurefile-node.yaml
  charts/latest/azurefile-csi-driver/values.yaml
  pkg/csi-common/utils.go
  pkg/csi-common/utils_test.go
Labels: approved, cncf-cla: yes, kind/test, size/S

#559 fix: add taints for windows daemonset
  charts/latest/azurefile-csi-driver-v1.1.0.tgz
  charts/latest/azurefile-csi-driver/templates/csi-azurefile-controller.yaml
  charts/latest/azurefile-csi-driver/templates/csi-azurefile-node-windows.yaml
  deploy/csi-azurefile-controller.yaml
  deploy/csi-azurefile-node-windows.yaml
Labels: approved, cncf-cla: yes, kind/bug, size/S

#561 test: only set low level logs in windows tests
  Makefile
  pkg/csi-common/utils.go
  pkg/csi-common/utils_test.go
Labels: approved, cncf-cla: yes, kind/test, size/S

#563 improve the unit test coverage for controllerserver
  pkg/azurefile/controllerserver_test.go
Labels: approved, cncf-cla: yes, kind/test, lgtm, ok-to-test, size/L

#564 fix: incorrect protocol and fsType combination
  hack/verify-helm-chart-files.sh
  pkg/azurefile/controllerserver.go
  pkg/azurefile/controllerserver_test.go
Labels: approved, cncf-cla: yes, kind/bug, size/M

#572 fix: increate csi-resizer memory limit
  charts/latest/azurefile-csi-driver-v1.1.0.tgz
  charts/latest/azurefile-csi-driver/templates/csi-azurefile-controller.yaml
  deploy/csi-azurefile-controller.yaml
Labels: approved, cncf-cla: yes, kind/bug, lgtm, size/XS
