Repository kubernetes-sigs/azurefile-csi-driver, pull requests merged in 2021-07, with the labels that each got.

#725 chore: Wait for examples to complete and return error on failed rollout
  hack/verify-examples.sh
Labels: approved, cncf-cla: yes, lgtm, size/M

#724 chore: show current driver name
  pkg/azurefile/version.go
  pkg/azurefile/version_test.go
Labels: approved, cncf-cla: yes, kind/cleanup, size/XS

#727 test: switch to csi-proxy v1.0.0-rc.1 in unit test
  .github/workflows/windows.yaml
Labels: approved, cncf-cla: yes, kind/test, size/XS

#729 feat: support customization of deployment and daemonset
  charts/README.md
  charts/latest/azurefile-csi-driver-v1.5.0.tgz
  charts/latest/azurefile-csi-driver/templates/csi-azurefile-controller.yaml
  charts/latest/azurefile-csi-driver/templates/csi-azurefile-node-windows.yaml
  charts/latest/azurefile-csi-driver/templates/csi-azurefile-node.yaml
  charts/latest/azurefile-csi-driver/templates/csi-snapshot-controller.yaml
  charts/latest/azurefile-csi-driver/templates/rbac-csi-azurefile-controller.yaml
  charts/latest/azurefile-csi-driver/templates/rbac-csi-azurefile-node.yaml
  charts/latest/azurefile-csi-driver/templates/rbac-csi-snapshot-controller.yaml
  charts/latest/azurefile-csi-driver/templates/serviceaccount-csi-azurefile-controller.yaml
  charts/latest/azurefile-csi-driver/templates/serviceaccount-csi-azurefile-node.yaml
  charts/latest/azurefile-csi-driver/templates/serviceaccount-csi-snapshot-controller.yaml
  charts/latest/azurefile-csi-driver/values.yaml
  test/utils/azurefile_log.sh
Labels: approved, cncf-cla: yes, kind/feature, size/M

#730 fix: remove node metricsPort
  charts/latest/azurefile-csi-driver-v1.5.0.tgz
  charts/latest/azurefile-csi-driver/templates/csi-azurefile-node-windows.yaml
  charts/latest/azurefile-csi-driver/templates/csi-azurefile-node.yaml
  deploy/csi-azurefile-node-windows.yaml
  deploy/csi-azurefile-node.yaml
Labels: approved, cncf-cla: yes, kind/cleanup, size/S

#734 fix: conflict inline volume mount options with default
  pkg/azurefile/nodeserver.go
Labels: approved, cncf-cla: yes, kind/bug, size/XS

#735 fix: customized role naming
  charts/latest/azurefile-csi-driver-v1.5.0.tgz
  charts/latest/azurefile-csi-driver/templates/rbac-csi-azurefile-controller.yaml
  charts/latest/azurefile-csi-driver/templates/rbac-csi-azurefile-node.yaml
  charts/latest/azurefile-csi-driver/values.yaml
  test/external-e2e/run.sh
  test/external-e2e/testdriver-nfs.yaml
  test/external-e2e/testdriver-smb.yaml
  test/utils/azurefile_log.sh
Labels: approved, cncf-cla: yes, kind/feature, size/M

#736 feat: customize healthPort in helm install
  charts/README.md
  charts/latest/azurefile-csi-driver-v1.5.0.tgz
  charts/latest/azurefile-csi-driver/templates/csi-azurefile-controller.yaml
  charts/latest/azurefile-csi-driver/templates/csi-azurefile-node-windows.yaml
  charts/latest/azurefile-csi-driver/templates/csi-azurefile-node.yaml
  charts/latest/azurefile-csi-driver/values.yaml
Labels: approved, cncf-cla: yes, kind/feature, size/S

#737 fix: always enable csi-snapshotter in helm install
  charts/latest/azurefile-csi-driver-v1.5.0.tgz
  charts/latest/azurefile-csi-driver/templates/csi-azurefile-controller.yaml
  charts/latest/azurefile-csi-driver/values.yaml
  deploy/csi-azurefile-controller.yaml
Labels: approved, cncf-cla: yes, kind/bug, size/S

#739 fix: unmount failure due to incorrect mount path check
  pkg/azurefile/nodeserver.go
Labels: approved, cncf-cla: yes, kind/bug, size/XS

#740 chore: refine driver parameter setting
  pkg/azurefile/azurefile.go
  pkg/azurefile/azurefile_test.go
  pkg/azurefileplugin/main.go
  test/e2e/suite_test.go
Labels: approved, cncf-cla: yes, kind/cleanup, size/M

#741 feat: add cloudConfigSecret in helm install
  charts/README.md
  charts/latest/azurefile-csi-driver-v1.5.0.tgz
  charts/latest/azurefile-csi-driver/templates/csi-azurefile-controller.yaml
  charts/latest/azurefile-csi-driver/templates/csi-azurefile-node-windows.yaml
  charts/latest/azurefile-csi-driver/templates/csi-azurefile-node.yaml
  charts/latest/azurefile-csi-driver/values.yaml
  pkg/azurefile/azure.go
  pkg/azurefile/azure_test.go
  pkg/azurefile/azurefile.go
  pkg/azurefileplugin/main.go
Labels: approved, cncf-cla: yes, kind/feature, size/M

#743 feat: customize controller hostNetwork setting in helm install
  charts/README.md
  charts/latest/azurefile-csi-driver-v1.5.0.tgz
  charts/latest/azurefile-csi-driver/templates/csi-azurefile-controller.yaml
  charts/latest/azurefile-csi-driver/values.yaml
Labels: approved, cncf-cla: yes, kind/feature, size/XS

#738 feat: support private endpoint for smb protocol
  docs/driver-parameters.md
  go.mod
  go.sum
  pkg/azurefile/controllerserver.go
  test/e2e/dynamic_provisioning_test.go
  vendor/modules.txt
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azureclients/publicipclient/azure_publicipclient.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azureclients/publicipclient/interface.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azureclients/publicipclient/mockpublicipclient/interface.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/consts/consts.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_controller_standard.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_controller_vmss.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_fakes.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_loadbalancer.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_managedDiskController.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_storageaccount.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_utils.go
Labels: approved, cncf-cla: yes, do-not-merge/hold, kind/feature, size/L

#744 fix: respect VnetResourceGroup in private link creation
  go.mod
  go.sum
  vendor/modules.txt
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azureclients/armclient/azure_armclient.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_loadbalancer.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_mock_vmsets.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_standard.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_storageaccount.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_vmsets.go
Labels: approved, cncf-cla: yes, kind/bug, size/XL

#745 test: switch to csi-proxy-v1.0.0 config
  .github/workflows/windows.yaml
  test/e2e/manifest/containerd-windows.json
  test/e2e/manifest/migration-windows.json
  test/e2e/manifest/windows.json
Labels: approved, cncf-cla: yes, kind/test, size/XS

#746 doc: cut v1.5.0 release
  README.md
  charts/index.yaml
  charts/v1.5.0/azurefile-csi-driver-v1.5.0.tgz
  charts/v1.5.0/azurefile-csi-driver/Chart.yaml
  charts/v1.5.0/azurefile-csi-driver/templates/NOTES.txt
  charts/v1.5.0/azurefile-csi-driver/templates/_helpers.tpl
  charts/v1.5.0/azurefile-csi-driver/templates/crd-csi-snapshot-ga.yaml
  charts/v1.5.0/azurefile-csi-driver/templates/crd-csi-snapshot.yaml
  charts/v1.5.0/azurefile-csi-driver/templates/csi-azurefile-controller.yaml
  charts/v1.5.0/azurefile-csi-driver/templates/csi-azurefile-driver.yaml
  charts/v1.5.0/azurefile-csi-driver/templates/csi-azurefile-node-windows.yaml
  charts/v1.5.0/azurefile-csi-driver/templates/csi-azurefile-node.yaml
  charts/v1.5.0/azurefile-csi-driver/templates/csi-snapshot-controller.yaml
  charts/v1.5.0/azurefile-csi-driver/templates/rbac-csi-azurefile-controller.yaml
  charts/v1.5.0/azurefile-csi-driver/templates/rbac-csi-azurefile-node.yaml
  charts/v1.5.0/azurefile-csi-driver/templates/rbac-csi-snapshot-controller.yaml
  charts/v1.5.0/azurefile-csi-driver/templates/serviceaccount-csi-azurefile-controller.yaml
  charts/v1.5.0/azurefile-csi-driver/templates/serviceaccount-csi-azurefile-node.yaml
  charts/v1.5.0/azurefile-csi-driver/templates/serviceaccount-csi-snapshot-controller.yaml
  charts/v1.5.0/azurefile-csi-driver/values.yaml
  deploy/v1.5.0/crd-csi-snapshot.yaml
  deploy/v1.5.0/csi-azurefile-controller.yaml
  deploy/v1.5.0/csi-azurefile-driver.yaml
  deploy/v1.5.0/csi-azurefile-node-windows.yaml
  deploy/v1.5.0/csi-azurefile-node.yaml
  deploy/v1.5.0/csi-snapshot-controller.yaml
  deploy/v1.5.0/rbac-csi-azurefile-controller.yaml
  deploy/v1.5.0/rbac-csi-azurefile-node.yaml
  deploy/v1.5.0/rbac-csi-snapshot-controller.yaml
  docs/install-azurefile-csi-driver.md
  docs/install-csi-driver-v1.5.0.md
Labels: approved, cncf-cla: yes, kind/documentation, size/XXL

#747 chore: switch master branch to use v1.6.0
  Makefile
  charts/index.yaml
  charts/latest/azurefile-csi-driver-v1.5.0.tgz
  charts/latest/azurefile-csi-driver-v1.6.0.tgz
  charts/latest/azurefile-csi-driver/Chart.yaml
Labels: approved, cncf-cla: yes, kind/documentation, size/M

#748 chore: refine windows image build
  Makefile
Labels: approved, cncf-cla: yes, kind/cleanup, size/XS

#749 feat: support latest image tag on Windows containerd
  Makefile
Labels: approved, cncf-cla: yes, kind/feature, size/XS

#750 cleanup: refine csi-proxy v1beta interface
  pkg/mounter/safe_mounter_v1beta_windows.go
Labels: approved, cncf-cla: yes, kind/cleanup, size/S

#751 fix: increase memory limit on node driver
  charts/latest/azurefile-csi-driver-v1.6.0.tgz
  charts/latest/azurefile-csi-driver/templates/csi-azurefile-node.yaml
  deploy/csi-azurefile-node.yaml
Labels: approved, cncf-cla: yes, kind/bug, size/XS

#752 chore: upgrade to csi-proxy-v1.0.1
  go.mod
  go.sum
  vendor/github.com/kubernetes-csi/csi-proxy/client/LICENSE
  vendor/github.com/kubernetes-csi/csi-proxy/client/apiversion/version.go
  vendor/github.com/kubernetes-csi/csi-proxy/client/utils.go
  vendor/modules.txt
Labels: approved, cncf-cla: yes, kind/cleanup, size/M
