Repository kubernetes-sigs/azurefile-csi-driver, pull requests merged in 2022-05, with the labels that each got.

#820 test: enable fsGroup external test for nfs
  test/external-e2e/testdriver-nfs.yaml
Labels: size/XS, approved, cncf-cla: yes, kind/test

#1014 test: run k8s 1.24 external e2e test
  test/external-e2e/run.sh
Labels: size/XS, approved, cncf-cla: yes, kind/test

#1016 chore: add cloud config logging in driver init
  pkg/azurefile/azurefile.go
Labels: kind/cleanup, size/XS, approved, cncf-cla: yes

#1017 fix: set fsGroupPolicy as ReadWriteOnceWithFSType by default
  charts/README.md
  charts/latest/azurefile-csi-driver-v1.18.0.tgz
  charts/latest/azurefile-csi-driver/templates/csi-azurefile-driver.yaml
  charts/latest/azurefile-csi-driver/values.yaml
  deploy/csi-azurefile-driver.yaml
  pkg/azurefile/nodeserver.go
  pkg/azurefile/utils.go
  pkg/azurefile/utils_test.go
  vendor/k8s.io/client-go/util/testing/fake_handler.go
  vendor/k8s.io/client-go/util/testing/tmpdir.go
  vendor/modules.txt
Labels: kind/bug, size/L, approved, cncf-cla: yes

#1019 fix: bypass chmod if mounting point permissions are correct
  pkg/azurefile/nodeserver.go
  pkg/azurefile/utils.go
  pkg/azurefile/utils_test.go
  test/e2e/dynamic_provisioning_test.go
Labels: kind/bug, size/M, approved, cncf-cla: yes

#1013 feat: add fsGroupChangePolicy for nfs protocol
  docs/driver-parameters.md
  pkg/azurefile/azurefile.go
  pkg/azurefile/controllerserver.go
  pkg/azurefile/nodeserver.go
  pkg/azurefile/nodeserver_test.go
  pkg/azurefile/utils.go
  pkg/azurefile/utils_test.go
  test/e2e/dynamic_provisioning_test.go
  test/external-e2e/run.sh
  test/external-e2e/testdriver-nfs.yaml
  vendor/k8s.io/client-go/util/testing/fake_handler.go
  vendor/k8s.io/client-go/util/testing/tmpdir.go
  vendor/modules.txt
Labels: kind/bug, size/L, approved, cncf-cla: yes

#1022 test: fix unstable e2e tests which check file content
  test/e2e/testsuites/dynamically_provisioned_delete_pod_tester.go
  test/e2e/testsuites/dynamically_provisioned_restart_driver_tester.go
  test/e2e/testsuites/dynamically_provisioned_statefulset_tester.go
  test/e2e/testsuites/testsuites.go
Labels: size/M, approved, cncf-cla: yes, kind/test

#1024 feat: set fsGroupChangePolicy as OnRootMismatch for nfs by default
  docs/driver-parameters.md
  pkg/azurefile/utils.go
  test/e2e/dynamic_provisioning_test.go
  test/external-e2e/run.sh
Labels: kind/feature, size/S, approved, cncf-cla: yes

#1025 feat: add fsGroupChangePolicy None parameter
  deploy/example/storageclass-azurefile-nfs.yaml
  docs/driver-parameters.md
  pkg/azurefile/azurefile.go
  pkg/azurefile/nodeserver.go
  pkg/azurefile/utils_test.go
  pkg/azurefileplugin/main.go
Labels: kind/feature, size/S, approved, cncf-cla: yes

#1026 fix: inline volume mount options passing issue
  pkg/azurefile/nodeserver.go
  test/e2e/dynamic_provisioning_test.go
  test/e2e/testsuites/testsuites.go
Labels: kind/bug, size/XS, approved, cncf-cla: yes

#1027 doc: cut v1.18.0 release
  README.md
  charts/README.md
  charts/index.yaml
  charts/latest/azurefile-csi-driver-v1.18.0.tgz
  charts/v1.18.0/azurefile-csi-driver-v1.18.0.tgz
  charts/v1.18.0/azurefile-csi-driver/Chart.yaml
  charts/v1.18.0/azurefile-csi-driver/templates/NOTES.txt
  charts/v1.18.0/azurefile-csi-driver/templates/_helpers.tpl
  charts/v1.18.0/azurefile-csi-driver/templates/crd-csi-snapshot.yaml
  charts/v1.18.0/azurefile-csi-driver/templates/csi-azurefile-controller.yaml
  charts/v1.18.0/azurefile-csi-driver/templates/csi-azurefile-driver.yaml
  charts/v1.18.0/azurefile-csi-driver/templates/csi-azurefile-node-windows.yaml
  charts/v1.18.0/azurefile-csi-driver/templates/csi-azurefile-node.yaml
  charts/v1.18.0/azurefile-csi-driver/templates/csi-snapshot-controller.yaml
  charts/v1.18.0/azurefile-csi-driver/templates/rbac-csi-azurefile-controller.yaml
  charts/v1.18.0/azurefile-csi-driver/templates/rbac-csi-azurefile-node.yaml
  charts/v1.18.0/azurefile-csi-driver/templates/rbac-csi-snapshot-controller.yaml
  charts/v1.18.0/azurefile-csi-driver/templates/serviceaccount-csi-azurefile-controller.yaml
  charts/v1.18.0/azurefile-csi-driver/templates/serviceaccount-csi-azurefile-node.yaml
  charts/v1.18.0/azurefile-csi-driver/templates/serviceaccount-csi-snapshot-controller.yaml
  charts/v1.18.0/azurefile-csi-driver/values.yaml
  deploy/v1.18.0/crd-csi-snapshot.yaml
  deploy/v1.18.0/csi-azurefile-controller.yaml
  deploy/v1.18.0/csi-azurefile-driver.yaml
  deploy/v1.18.0/csi-azurefile-node-windows.yaml
  deploy/v1.18.0/csi-azurefile-node.yaml
  deploy/v1.18.0/csi-snapshot-controller.yaml
  deploy/v1.18.0/rbac-csi-azurefile-controller.yaml
  deploy/v1.18.0/rbac-csi-azurefile-node.yaml
  deploy/v1.18.0/rbac-csi-snapshot-controller.yaml
  docs/install-azurefile-csi-driver.md
  docs/install-csi-driver-v1.18.0.md
Labels: kind/documentation, approved, cncf-cla: yes, size/XXL

#1029 chore: switch master branch to use v1.19.0
  Makefile
  charts/index.yaml
  charts/latest/azurefile-csi-driver-v1.18.0.tgz
  charts/latest/azurefile-csi-driver-v1.19.0.tgz
  charts/latest/azurefile-csi-driver/Chart.yaml
Labels: kind/documentation, size/M, approved, cncf-cla: yes

#1031 Add myself as reviewer for azurefile CSI driver
  OWNERS
Labels: size/XS, lgtm, approved, cncf-cla: yes

#1032 fix: incorrect runOnMaster label config
  Makefile
  charts/latest/azurefile-csi-driver-v1.19.0.tgz
  charts/latest/azurefile-csi-driver/templates/csi-azurefile-controller.yaml
Labels: kind/bug, size/XS, lgtm, approved, cncf-cla: yes
