Repository kubernetes-sigs/azurefile-csi-driver, pull requests merged in 2022-04, with the labels that each got.

#959 doc: update ZRS, nconnect parameter doc
  .github/workflows/codeql-analysis.yml
  deploy/example/disk/storageclass-azurefile-csi.yaml
  deploy/example/largeFileShares/storageclass-azurefile-largefileshares.yaml
  deploy/example/nfs/README.md
  deploy/example/pv-azurefile-csi.yaml
  deploy/example/pv-azurefile-nfs.yaml
  deploy/example/pvc-azurefile-csi-static.yaml
  deploy/example/storageclass-azurefile-csi.yaml
  deploy/example/storageclass-azurefile-nfs.yaml
  docs/driver-parameters.md
Labels: kind/documentation, size/M, approved, cncf-cla: yes

#960 fix: CVE-2018-25032 in image build
  pkg/azurefileplugin/Dockerfile
Labels: kind/bug, size/XS, approved, cncf-cla: yes

#963 test: fix golinter error
  .github/workflows/static.yaml
Labels: kind/failing-test, size/XS, approved, cncf-cla: yes

#962 Bump prometheus/client_golang to v1.11.1
  go.mod
  go.sum
  vendor/github.com/prometheus/client_golang/prometheus/build_info_pre_1.12.go
  vendor/github.com/prometheus/client_golang/prometheus/counter.go
  vendor/github.com/prometheus/client_golang/prometheus/desc.go
  vendor/github.com/prometheus/client_golang/prometheus/expvar_collector.go
  vendor/github.com/prometheus/client_golang/prometheus/gauge.go
  vendor/github.com/prometheus/client_golang/prometheus/go_collector.go
  vendor/github.com/prometheus/client_golang/prometheus/histogram.go
  vendor/github.com/prometheus/client_golang/prometheus/metric.go
  vendor/github.com/prometheus/client_golang/prometheus/process_collector.go
  vendor/github.com/prometheus/client_golang/prometheus/promhttp/delegator.go
  vendor/github.com/prometheus/client_golang/prometheus/promhttp/http.go
  vendor/github.com/prometheus/client_golang/prometheus/promhttp/instrument_client.go
  vendor/github.com/prometheus/client_golang/prometheus/promhttp/instrument_server.go
  vendor/github.com/prometheus/client_golang/prometheus/promhttp/option.go
  vendor/github.com/prometheus/client_golang/prometheus/registry.go
  vendor/github.com/prometheus/client_golang/prometheus/summary.go
  vendor/github.com/prometheus/client_golang/prometheus/value.go
  vendor/github.com/prometheus/client_golang/prometheus/vec.go
  vendor/github.com/prometheus/client_golang/prometheus/wrap.go
  vendor/modules.txt
Labels: size/XL, lgtm, approved, cncf-cla: yes

#965 fix: default namespace issue
  pkg/azurefile/azurefile.go
  pkg/azurefile/controllerserver.go
Labels: kind/bug, size/S, approved, cncf-cla: yes

#961 feat: provide a flag to allow accessing storage account key using cluster identity for inline volume
  charts/README.md
  charts/latest/azurefile-csi-driver-v1.14.0.tgz
  charts/latest/azurefile-csi-driver/templates/csi-azurefile-node-windows.yaml
  charts/latest/azurefile-csi-driver/templates/csi-azurefile-node.yaml
  charts/latest/azurefile-csi-driver/values.yaml
  pkg/azurefile/azurefile.go
  pkg/azurefile/nodeserver.go
  pkg/azurefileplugin/main.go
Labels: kind/feature, size/M, approved, cncf-cla: yes

#964 feat: support mount smb file share in another subscription
  docs/driver-parameters.md
  go.mod
  go.sum
  pkg/azurefile/azurefile.go
  pkg/azurefile/azurefile_test.go
  pkg/azurefile/controllerserver.go
  pkg/azurefile/controllerserver_test.go
  vendor/github.com/Azure/azure-sdk-for-go/version/version.go
  vendor/github.com/Azure/go-autorest/autorest/azure/environments.go
  vendor/github.com/Azure/go-autorest/autorest/azure/rp.go
  vendor/github.com/Azure/go-autorest/autorest/mocks/go_mod_tidy_hack.go
  vendor/github.com/Azure/go-autorest/autorest/mocks/mocks.go
  vendor/github.com/onsi/gomega/CHANGELOG.md
  vendor/github.com/onsi/gomega/RELEASING.md
  vendor/github.com/onsi/gomega/gomega_dsl.go
  vendor/github.com/onsi/gomega/matchers.go
  vendor/github.com/onsi/gomega/matchers/contain_element_matcher.go
  vendor/github.com/onsi/gomega/matchers/have_each_matcher.go
  vendor/golang.org/x/net/http2/go118.go
  vendor/golang.org/x/net/http2/not_go118.go
  vendor/golang.org/x/net/http2/transport.go
  vendor/modules.txt
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/auth/azure_auth.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azureclients/storageaccountclient/azure_storageaccountclient.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azureclients/storageaccountclient/interface.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azureclients/storageaccountclient/mockstorageaccountclient/interface.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azureclients/vmclient/azure_vmclient.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azureclients/vmssvmclient/azure_vmssvmclient.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/consts/consts.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_loadbalancer.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_loadbalancer_backendpool.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_managedDiskController.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_standard.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_storageaccount.go
Labels: kind/feature, approved, cncf-cla: yes, size/XXL

#966 feat: add shareNamePrefix parameter in storage class
  docs/driver-parameters.md
  pkg/azurefile/azurefile.go
  pkg/azurefile/controllerserver.go
  pkg/azurefile/utils.go
  pkg/azurefile/utils_test.go
  test/e2e/dynamic_provisioning_test.go
Labels: kind/feature, size/M, approved, cncf-cla: yes

#967 chore: refine mount on Windows logs
  pkg/mounter/safe_mounter_v1beta_windows.go
  pkg/mounter/safe_mounter_windows.go
Labels: kind/cleanup, size/S, approved, cncf-cla: yes

#969 chore: fix typos in driver parameters
  charts/latest/azurefile-csi-driver-v1.14.0.tgz
  charts/latest/azurefile-csi-driver/templates/csi-azurefile-node-windows.yaml
  charts/latest/azurefile-csi-driver/templates/csi-azurefile-node.yaml
  pkg/azurefileplugin/main.go
Labels: kind/documentation, size/XS, approved, cncf-cla: yes

#970 doc: cut v1.14.0 release
  README.md
  charts/README.md
  charts/index.yaml
  charts/latest/azurefile-csi-driver-v1.14.0.tgz
  charts/v1.14.0/azurefile-csi-driver-v1.14.0.tgz
  charts/v1.14.0/azurefile-csi-driver/Chart.yaml
  charts/v1.14.0/azurefile-csi-driver/templates/NOTES.txt
  charts/v1.14.0/azurefile-csi-driver/templates/_helpers.tpl
  charts/v1.14.0/azurefile-csi-driver/templates/crd-csi-snapshot.yaml
  charts/v1.14.0/azurefile-csi-driver/templates/csi-azurefile-controller.yaml
  charts/v1.14.0/azurefile-csi-driver/templates/csi-azurefile-driver.yaml
  charts/v1.14.0/azurefile-csi-driver/templates/csi-azurefile-node-windows.yaml
  charts/v1.14.0/azurefile-csi-driver/templates/csi-azurefile-node.yaml
  charts/v1.14.0/azurefile-csi-driver/templates/csi-snapshot-controller.yaml
  charts/v1.14.0/azurefile-csi-driver/templates/rbac-csi-azurefile-controller.yaml
  charts/v1.14.0/azurefile-csi-driver/templates/rbac-csi-azurefile-node.yaml
  charts/v1.14.0/azurefile-csi-driver/templates/rbac-csi-snapshot-controller.yaml
  charts/v1.14.0/azurefile-csi-driver/templates/serviceaccount-csi-azurefile-controller.yaml
  charts/v1.14.0/azurefile-csi-driver/templates/serviceaccount-csi-azurefile-node.yaml
  charts/v1.14.0/azurefile-csi-driver/templates/serviceaccount-csi-snapshot-controller.yaml
  charts/v1.14.0/azurefile-csi-driver/values.yaml
  deploy/v1.14.0/crd-csi-snapshot.yaml
  deploy/v1.14.0/csi-azurefile-controller.yaml
  deploy/v1.14.0/csi-azurefile-driver.yaml
  deploy/v1.14.0/csi-azurefile-node-windows.yaml
  deploy/v1.14.0/csi-azurefile-node.yaml
  deploy/v1.14.0/csi-snapshot-controller.yaml
  deploy/v1.14.0/rbac-csi-azurefile-controller.yaml
  deploy/v1.14.0/rbac-csi-azurefile-node.yaml
  deploy/v1.14.0/rbac-csi-snapshot-controller.yaml
  docs/install-azurefile-csi-driver.md
  docs/install-csi-driver-v1.14.0.md
Labels: kind/documentation, approved, cncf-cla: yes, size/XXL

#972 chore: switch master branch to use v1.15.0
  Makefile
  charts/index.yaml
  charts/latest/azurefile-csi-driver-v1.14.0.tgz
  charts/latest/azurefile-csi-driver-v1.15.0.tgz
  charts/latest/azurefile-csi-driver/Chart.yaml
Labels: kind/documentation, size/M, approved, cncf-cla: yes

#973 test: adjust csi-proxy loglevel in test
  .github/workflows/windows.yaml
Labels: size/XS, approved, cncf-cla: yes, kind/test

#974 test: enable external slow tests
  test/external-e2e/run.sh
Labels: kind/failing-test, size/XS, approved, cncf-cla: yes

#975 test: enable volumeMountGroup external tests
  test/external-e2e/testdriver-nfs.yaml
  test/external-e2e/testdriver-smb.yaml
Labels: size/XS, approved, cncf-cla: yes, kind/test

#978 chore: Update golang.org/x/crypto for CVE-2022-27191
  go.mod
  go.sum
  vendor/golang.org/x/crypto/chacha20/chacha_s390x.go
  vendor/golang.org/x/crypto/curve25519/internal/field/fe_amd64.go
  vendor/golang.org/x/crypto/internal/poly1305/sum_generic.go
  vendor/golang.org/x/crypto/internal/poly1305/sum_s390x.go
  vendor/golang.org/x/crypto/ssh/certs.go
  vendor/golang.org/x/crypto/ssh/cipher.go
  vendor/golang.org/x/crypto/ssh/client.go
  vendor/golang.org/x/crypto/ssh/client_auth.go
  vendor/golang.org/x/crypto/ssh/common.go
  vendor/golang.org/x/crypto/ssh/doc.go
  vendor/golang.org/x/crypto/ssh/handshake.go
  vendor/golang.org/x/crypto/ssh/kex.go
  vendor/golang.org/x/crypto/ssh/keys.go
  vendor/golang.org/x/crypto/ssh/messages.go
  vendor/golang.org/x/crypto/ssh/server.go
  vendor/golang.org/x/crypto/ssh/session.go
  vendor/golang.org/x/crypto/ssh/transport.go
  vendor/modules.txt
Labels: kind/cleanup, size/XL, lgtm, approved, cncf-cla: yes

#980 fix: disable match tags by default in account search when creating file share
  docs/driver-parameters.md
  go.mod
  go.sum
  pkg/azurefile/azurefile.go
  pkg/azurefile/controllerserver.go
  pkg/azurefile/controllerserver_test.go
  test/e2e/dynamic_provisioning_test.go
  vendor/github.com/Azure/azure-sdk-for-go/version/version.go
  vendor/modules.txt
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/consts/consts.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_standard.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_storageaccount.go
Labels: kind/bug, size/L, approved, cncf-cla: yes

#982 doc: cut v1.15.0 release
  README.md
  charts/README.md
  charts/index.yaml
  charts/latest/azurefile-csi-driver-v1.15.0.tgz
  charts/v1.15.0/azurefile-csi-driver-v1.15.0.tgz
  charts/v1.15.0/azurefile-csi-driver/Chart.yaml
  charts/v1.15.0/azurefile-csi-driver/templates/NOTES.txt
  charts/v1.15.0/azurefile-csi-driver/templates/_helpers.tpl
  charts/v1.15.0/azurefile-csi-driver/templates/crd-csi-snapshot.yaml
  charts/v1.15.0/azurefile-csi-driver/templates/csi-azurefile-controller.yaml
  charts/v1.15.0/azurefile-csi-driver/templates/csi-azurefile-driver.yaml
  charts/v1.15.0/azurefile-csi-driver/templates/csi-azurefile-node-windows.yaml
  charts/v1.15.0/azurefile-csi-driver/templates/csi-azurefile-node.yaml
  charts/v1.15.0/azurefile-csi-driver/templates/csi-snapshot-controller.yaml
  charts/v1.15.0/azurefile-csi-driver/templates/rbac-csi-azurefile-controller.yaml
  charts/v1.15.0/azurefile-csi-driver/templates/rbac-csi-azurefile-node.yaml
  charts/v1.15.0/azurefile-csi-driver/templates/rbac-csi-snapshot-controller.yaml
  charts/v1.15.0/azurefile-csi-driver/templates/serviceaccount-csi-azurefile-controller.yaml
  charts/v1.15.0/azurefile-csi-driver/templates/serviceaccount-csi-azurefile-node.yaml
  charts/v1.15.0/azurefile-csi-driver/templates/serviceaccount-csi-snapshot-controller.yaml
  charts/v1.15.0/azurefile-csi-driver/values.yaml
  deploy/v1.15.0/crd-csi-snapshot.yaml
  deploy/v1.15.0/csi-azurefile-controller.yaml
  deploy/v1.15.0/csi-azurefile-driver.yaml
  deploy/v1.15.0/csi-azurefile-node-windows.yaml
  deploy/v1.15.0/csi-azurefile-node.yaml
  deploy/v1.15.0/csi-snapshot-controller.yaml
  deploy/v1.15.0/rbac-csi-azurefile-controller.yaml
  deploy/v1.15.0/rbac-csi-azurefile-node.yaml
  deploy/v1.15.0/rbac-csi-snapshot-controller.yaml
  docs/install-azurefile-csi-driver.md
  docs/install-csi-driver-v1.15.0.md
Labels: kind/documentation, approved, cncf-cla: yes, size/XXL

#984 chore: switch master branch to use v1.16.0
  Makefile
  charts/index.yaml
  charts/latest/azurefile-csi-driver-v1.15.0.tgz
  charts/latest/azurefile-csi-driver-v1.16.0.tgz
  charts/latest/azurefile-csi-driver/Chart.yaml
Labels: kind/documentation, size/M, approved, cncf-cla: yes

#985 test: add account creation leak test
  docs/driver-parameters.md
  test/e2e/suite_test.go
  test/e2e/testsuites/dynamically_provisioned_tags_tester.go
  test/utils/azure/azure_helpers.go
Labels: size/S, approved, cncf-cla: yes, kind/test

#986 fix: expand volume failure in csi migration scenario
  pkg/azurefile/controllerserver.go
Labels: kind/bug, size/XS, approved, cncf-cla: yes

#981 test: enable disableDeleteRetentionPolicy test
  test/e2e/dynamic_provisioning_test.go
Labels: kind/failing-test, size/XS, approved, cncf-cla: yes

#989 chore: fail earlier if creating virutal link failed before account creation
  go.mod
  go.sum
  vendor/k8s.io/klog/v2/OWNERS
  vendor/k8s.io/klog/v2/README.md
  vendor/k8s.io/klog/v2/contextual.go
  vendor/k8s.io/klog/v2/exit.go
  vendor/k8s.io/klog/v2/imports.go
  vendor/k8s.io/klog/v2/internal/buffer/buffer.go
  vendor/k8s.io/klog/v2/internal/clock/README.md
  vendor/k8s.io/klog/v2/internal/clock/clock.go
  vendor/k8s.io/klog/v2/internal/serialize/keyvalues.go
  vendor/k8s.io/klog/v2/internal/severity/severity.go
  vendor/k8s.io/klog/v2/k8s_references.go
  vendor/k8s.io/klog/v2/klog.go
  vendor/k8s.io/klog/v2/klogr.go
  vendor/modules.txt
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_instances.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_loadbalancer.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_standard.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_storageaccount.go
Labels: kind/cleanup, approved, cncf-cla: yes, size/XXL

#992 chore: refine package patching in image build
  pkg/azurefileplugin/Dockerfile
Labels: kind/cleanup, size/XS, approved, cncf-cla: yes

#993 test: fix in-tree test failure due to matchTags parameter issue
  test/e2e/dynamic_provisioning_test.go
Labels: kind/failing-test, size/XS, approved, cncf-cla: yes

#990 chore: add secretNamespace to volumeid
  pkg/azurefile/azurefile.go
  pkg/azurefile/azurefile_test.go
  pkg/azurefile/controllerserver.go
  test/e2e/testsuites/dynamically_provisioned_resize_volume_tester.go
  test/e2e/testsuites/dynamically_provisioned_tags_tester.go
Labels: kind/feature, size/M, approved, cncf-cla: yes

#994 chore: switch base image registry
  pkg/azurefileplugin/Dockerfile
Labels: kind/cleanup, size/XS, approved, cncf-cla: yes

#995 cleanup: refine secretNamespace assignment in Expand, DeleteVolume
  pkg/azurefile/controllerserver.go
Labels: kind/cleanup, size/S, approved, cncf-cla: yes

#996 fix: disallow disableDeleteRetentionPolicy on Standard account type
  pkg/azurefile/controllerserver.go
  pkg/azurefile/controllerserver_test.go
Labels: size/L, approved, cncf-cla: yes, kind/test

#997 doc: cut v1.16.0 release
  README.md
  charts/README.md
  charts/index.yaml
  charts/latest/azurefile-csi-driver-v1.16.0.tgz
  charts/v1.16.0/azurefile-csi-driver-v1.16.0.tgz
  charts/v1.16.0/azurefile-csi-driver/Chart.yaml
  charts/v1.16.0/azurefile-csi-driver/templates/NOTES.txt
  charts/v1.16.0/azurefile-csi-driver/templates/_helpers.tpl
  charts/v1.16.0/azurefile-csi-driver/templates/crd-csi-snapshot.yaml
  charts/v1.16.0/azurefile-csi-driver/templates/csi-azurefile-controller.yaml
  charts/v1.16.0/azurefile-csi-driver/templates/csi-azurefile-driver.yaml
  charts/v1.16.0/azurefile-csi-driver/templates/csi-azurefile-node-windows.yaml
  charts/v1.16.0/azurefile-csi-driver/templates/csi-azurefile-node.yaml
  charts/v1.16.0/azurefile-csi-driver/templates/csi-snapshot-controller.yaml
  charts/v1.16.0/azurefile-csi-driver/templates/rbac-csi-azurefile-controller.yaml
  charts/v1.16.0/azurefile-csi-driver/templates/rbac-csi-azurefile-node.yaml
  charts/v1.16.0/azurefile-csi-driver/templates/rbac-csi-snapshot-controller.yaml
  charts/v1.16.0/azurefile-csi-driver/templates/serviceaccount-csi-azurefile-controller.yaml
  charts/v1.16.0/azurefile-csi-driver/templates/serviceaccount-csi-azurefile-node.yaml
  charts/v1.16.0/azurefile-csi-driver/templates/serviceaccount-csi-snapshot-controller.yaml
  charts/v1.16.0/azurefile-csi-driver/values.yaml
  deploy/v1.16.0/crd-csi-snapshot.yaml
  deploy/v1.16.0/csi-azurefile-controller.yaml
  deploy/v1.16.0/csi-azurefile-driver.yaml
  deploy/v1.16.0/csi-azurefile-node-windows.yaml
  deploy/v1.16.0/csi-azurefile-node.yaml
  deploy/v1.16.0/csi-snapshot-controller.yaml
  deploy/v1.16.0/rbac-csi-azurefile-controller.yaml
  deploy/v1.16.0/rbac-csi-azurefile-node.yaml
  deploy/v1.16.0/rbac-csi-snapshot-controller.yaml
  docs/install-azurefile-csi-driver.md
  docs/install-csi-driver-v1.16.0.md
Labels: kind/documentation, approved, cncf-cla: yes, size/XXL

#999 chore: switch master branch to use v1.17.0
  Makefile
  charts/index.yaml
  charts/latest/azurefile-csi-driver-v1.16.0.tgz
  charts/latest/azurefile-csi-driver-v1.17.0.tgz
  charts/latest/azurefile-csi-driver/Chart.yaml
Labels: kind/documentation, size/M, approved, cncf-cla: yes

#1000 test: skip on-prem test on capz windows
  test/e2e/dynamic_provisioning_test.go
  test/e2e/suite_test.go
Labels: kind/failing-test, size/XS, approved, cncf-cla: yes

#1002 chore: refine metrics naming
  pkg/azurefile/azurefile.go
  pkg/azurefile/controllerserver.go
Labels: kind/cleanup, size/S, approved, cncf-cla: yes

#1003 chore: rename metrics columns
  pkg/azurefile/azurefile.go
  pkg/azurefile/controllerserver.go
Labels: kind/cleanup, size/XS, approved, cncf-cla: yes

#988 test: support Win2022 test on capz
  hack/verify-examples.sh
  test/e2e/dynamic_provisioning_test.go
  test/e2e/pre_provisioning_test.go
  test/e2e/suite_test.go
  test/e2e/testsuites/dynamically_provisioned_cmd_volume_tester.go
  test/e2e/testsuites/dynamically_provisioned_volume_snapshot_tester.go
  test/e2e/testsuites/pre_provisioned_existing_credentials_tester.go
  test/e2e/testsuites/specs.go
  test/e2e/testsuites/testsuites.go
Labels: size/L, approved, cncf-cla: yes, kind/test

#1005 chore: upgrade sidecar image versions
  charts/README.md
  charts/latest/azurefile-csi-driver-v1.17.0.tgz
  charts/latest/azurefile-csi-driver/values.yaml
  deploy/csi-azurefile-controller.yaml
  deploy/csi-azurefile-driver.yaml
  deploy/csi-azurefile-node-windows.yaml
  deploy/csi-azurefile-node.yaml
Labels: kind/feature, size/S, approved, cncf-cla: yes

#1007 doc: cut v1.17.0 release
  README.md
  charts/README.md
  charts/index.yaml
  charts/latest/azurefile-csi-driver-v1.17.0.tgz
  charts/v1.17.0/azurefile-csi-driver-v1.17.0.tgz
  charts/v1.17.0/azurefile-csi-driver/Chart.yaml
  charts/v1.17.0/azurefile-csi-driver/templates/NOTES.txt
  charts/v1.17.0/azurefile-csi-driver/templates/_helpers.tpl
  charts/v1.17.0/azurefile-csi-driver/templates/crd-csi-snapshot.yaml
  charts/v1.17.0/azurefile-csi-driver/templates/csi-azurefile-controller.yaml
  charts/v1.17.0/azurefile-csi-driver/templates/csi-azurefile-driver.yaml
  charts/v1.17.0/azurefile-csi-driver/templates/csi-azurefile-node-windows.yaml
  charts/v1.17.0/azurefile-csi-driver/templates/csi-azurefile-node.yaml
  charts/v1.17.0/azurefile-csi-driver/templates/csi-snapshot-controller.yaml
  charts/v1.17.0/azurefile-csi-driver/templates/rbac-csi-azurefile-controller.yaml
  charts/v1.17.0/azurefile-csi-driver/templates/rbac-csi-azurefile-node.yaml
  charts/v1.17.0/azurefile-csi-driver/templates/rbac-csi-snapshot-controller.yaml
  charts/v1.17.0/azurefile-csi-driver/templates/serviceaccount-csi-azurefile-controller.yaml
  charts/v1.17.0/azurefile-csi-driver/templates/serviceaccount-csi-azurefile-node.yaml
  charts/v1.17.0/azurefile-csi-driver/templates/serviceaccount-csi-snapshot-controller.yaml
  charts/v1.17.0/azurefile-csi-driver/values.yaml
  deploy/v1.17.0/crd-csi-snapshot.yaml
  deploy/v1.17.0/csi-azurefile-controller.yaml
  deploy/v1.17.0/csi-azurefile-driver.yaml
  deploy/v1.17.0/csi-azurefile-node-windows.yaml
  deploy/v1.17.0/csi-azurefile-node.yaml
  deploy/v1.17.0/csi-snapshot-controller.yaml
  deploy/v1.17.0/rbac-csi-azurefile-controller.yaml
  deploy/v1.17.0/rbac-csi-azurefile-node.yaml
  deploy/v1.17.0/rbac-csi-snapshot-controller.yaml
  docs/install-azurefile-csi-driver.md
  docs/install-csi-driver-v1.17.0.md
Labels: kind/documentation, approved, cncf-cla: yes, size/XXL

#1009 chore: switch master branch to use v1.18.0
  Makefile
  charts/index.yaml
  charts/latest/azurefile-csi-driver-v1.17.0.tgz
  charts/latest/azurefile-csi-driver-v1.18.0.tgz
  charts/latest/azurefile-csi-driver/Chart.yaml
Labels: kind/documentation, size/M, approved, cncf-cla: yes
