Repository kubernetes-sigs/azurefile-csi-driver, pull requests merged in 2022-12, with the labels that each got.

#1132 chore: upgrade to csi-node-driver-registrar v2.6.2
  charts/README.md
  charts/latest/azurefile-csi-driver-v0.0.0.tgz
  charts/latest/azurefile-csi-driver/values.yaml
  deploy/csi-azurefile-node-windows.yaml
  deploy/csi-azurefile-node.yaml
Labels: kind/feature, size/XS, approved, cncf-cla: yes

#1136 Add requirements.txt with fixed versions to use in pip install
  hack/requirements.txt
  hack/verify-helm-chart.sh
Labels: kind/cleanup, size/M, lgtm, approved, cncf-cla: yes

#1135 fix: CVE-2022-41717
  go.mod
  go.sum
  vendor/golang.org/x/net/http2/hpack/encode.go
  vendor/golang.org/x/net/http2/server.go
  vendor/golang.org/x/net/http2/transport.go
  vendor/golang.org/x/sys/windows/syscall_windows.go
  vendor/golang.org/x/sys/windows/zsyscall_windows.go
  vendor/modules.txt
Labels: kind/bug, size/L, approved, cncf-cla: yes

#1141 cleanup: Use k8s utils pointer instead of Azure autorest/to
  go.mod
  pkg/azurefile/controllerserver.go
  pkg/azurefile/controllerserver_test.go
  test/e2e/testsuites/testsuites.go
  test/utils/azure/azure_helpers.go
Labels: kind/cleanup, ok-to-test, size/M, lgtm, approved, cncf-cla: yes

#1144 chore: refine logging
  pkg/azurefile/azure_common_linux.go
  pkg/azurefile/controllerserver.go
Labels: kind/cleanup, size/XS, approved, cncf-cla: yes

#1145 docs: recommend the use of the nosharesock mount option, and clearify how volumeHandle should be used.
  deploy/example/nginx-pod-azurefile-inline-volume.yaml
  deploy/example/pv-azurefile-csi.yaml
  deploy/example/pv-azurefile-nfs.yaml
  docs/intree-static-example.md
Labels: ok-to-test, kind/documentation, size/XS, lgtm, approved, cncf-cla: yes

#1148 docs: add a section on volumeHandle to the PV Static Provision documentation
  docs/driver-parameters.md
Labels: ok-to-test, kind/documentation, size/XS, lgtm, approved, cncf-cla: yes

#1150 cleanup: remove redundant unmount volume code since it's already handled by mount-utils
  pkg/azurefile/azure_common_linux.go
  test/e2e/dynamic_provisioning_test.go
  test/e2e/testsuites/dynamically_provisioned_delete_pod_tester.go
  test/e2e/testsuites/dynamically_provisioned_restart_driver_tester.go
  test/e2e/testsuites/dynamically_provisioned_volume_unmount_tester.go
  test/e2e/testsuites/specs.go
  test/e2e/testsuites/testsuites.go
Labels: size/L, approved, cncf-cla: yes

#1151 cleanup: remove useless functions
  pkg/azurefile/azure_common_darwin.go
  pkg/azurefile/azure_common_linux.go
  pkg/azurefile/azure_common_windows.go
  pkg/azurefile/nodeserver.go
  pkg/mounter/safe_mounter_windows.go
Labels: kind/cleanup, size/M, approved, cncf-cla: yes

#1153 test: add helm lint test
  hack/verify-helm-chart.sh
Labels: kind/bug, ok-to-test, size/XS, lgtm, approved, cncf-cla: yes

#1143 fix: support privateendpoint with latest cloud-provider-azure
  go.mod
  go.sum
  pkg/azurefile/controllerserver.go
  vendor/modules.txt
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_controller_common.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_controller_standard.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_controller_vmssflex.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_loadbalancer.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_storageaccount.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_utils.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_vmss.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_vmss_cache.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_vmssflex_cache.go
Labels: size/L, ok-to-test, lgtm, approved, cncf-cla: yes
