Repository kubernetes-sigs/azurefile-csi-driver, pull requests merged in 2022-06, with the labels that each got.

#1035 test: fix windows e2e test failure on 1.25 cluster
  Makefile
  charts/latest/azurefile-csi-driver-v1.19.0.tgz
  charts/latest/azurefile-csi-driver/templates/csi-azurefile-node-windows.yaml
Labels: size/XS, approved, cncf-cla: yes, kind/test

#1036 feat: add controller.runOnControlPlane in chart config
  charts/README.md
  charts/latest/azurefile-csi-driver-v1.19.0.tgz
  charts/latest/azurefile-csi-driver/templates/csi-azurefile-controller.yaml
  charts/latest/azurefile-csi-driver/values.yaml
Labels: kind/feature, size/XS, approved, cncf-cla: yes

#1023 add new option to allow VHD feature opt-out
  pkg/azurefile/azurefile.go
  pkg/azurefile/azurefile_test.go
  pkg/azurefile/controllerserver.go
  pkg/azurefile/controllerserver_test.go
  pkg/azurefileplugin/main.go
Labels: kind/bug, ok-to-test, size/M, lgtm, approved, cncf-cla: yes, kind/regression

#1030 doc: mark VHD disk feature as experimental feature
  docs/driver-parameters.md
Labels: kind/documentation, size/XS, approved, cncf-cla: yes

#1039 doc: cut v1.19.0 release
  README.md
  charts/README.md
  charts/index.yaml
  charts/latest/azurefile-csi-driver-v1.19.0.tgz
  charts/v1.19.0/azurefile-csi-driver-v1.19.0.tgz
  charts/v1.19.0/azurefile-csi-driver/Chart.yaml
  charts/v1.19.0/azurefile-csi-driver/templates/NOTES.txt
  charts/v1.19.0/azurefile-csi-driver/templates/_helpers.tpl
  charts/v1.19.0/azurefile-csi-driver/templates/crd-csi-snapshot.yaml
  charts/v1.19.0/azurefile-csi-driver/templates/csi-azurefile-controller.yaml
  charts/v1.19.0/azurefile-csi-driver/templates/csi-azurefile-driver.yaml
  charts/v1.19.0/azurefile-csi-driver/templates/csi-azurefile-node-windows.yaml
  charts/v1.19.0/azurefile-csi-driver/templates/csi-azurefile-node.yaml
  charts/v1.19.0/azurefile-csi-driver/templates/csi-snapshot-controller.yaml
  charts/v1.19.0/azurefile-csi-driver/templates/rbac-csi-azurefile-controller.yaml
  charts/v1.19.0/azurefile-csi-driver/templates/rbac-csi-azurefile-node.yaml
  charts/v1.19.0/azurefile-csi-driver/templates/rbac-csi-snapshot-controller.yaml
  charts/v1.19.0/azurefile-csi-driver/templates/serviceaccount-csi-azurefile-controller.yaml
  charts/v1.19.0/azurefile-csi-driver/templates/serviceaccount-csi-azurefile-node.yaml
  charts/v1.19.0/azurefile-csi-driver/templates/serviceaccount-csi-snapshot-controller.yaml
  charts/v1.19.0/azurefile-csi-driver/values.yaml
  deploy/v1.19.0/crd-csi-snapshot.yaml
  deploy/v1.19.0/csi-azurefile-controller.yaml
  deploy/v1.19.0/csi-azurefile-driver.yaml
  deploy/v1.19.0/csi-azurefile-node-windows.yaml
  deploy/v1.19.0/csi-azurefile-node.yaml
  deploy/v1.19.0/csi-snapshot-controller.yaml
  deploy/v1.19.0/rbac-csi-azurefile-controller.yaml
  deploy/v1.19.0/rbac-csi-azurefile-node.yaml
  deploy/v1.19.0/rbac-csi-snapshot-controller.yaml
  docs/install-azurefile-csi-driver.md
  docs/install-csi-driver-v1.19.0.md
Labels: kind/documentation, approved, cncf-cla: yes, size/XXL

#1041 chore: switch master branch to use v1.20.0
  Makefile
  charts/index.yaml
  charts/latest/azurefile-csi-driver-v1.19.0.tgz
  charts/latest/azurefile-csi-driver-v1.20.0.tgz
  charts/latest/azurefile-csi-driver/Chart.yaml
Labels: kind/documentation, size/M, approved, cncf-cla: yes

#1044 feat: upgrade sidecar image versions
  charts/README.md
  charts/latest/azurefile-csi-driver-v1.20.0.tgz
  charts/latest/azurefile-csi-driver/values.yaml
  deploy/csi-azurefile-controller.yaml
  deploy/csi-azurefile-node-windows.yaml
  deploy/csi-azurefile-node.yaml
  pkg/azurefile/controllerserver.go
  pkg/azurefile/controllerserver_test.go
  pkg/azurefile/nodeserver.go
  pkg/azurefile/nodeserver_test.go
Labels: kind/feature, size/L, approved, cncf-cla: yes

#1045 chore: add more logging in ExpandVolume
  pkg/azurefile/controllerserver.go
  pkg/azurefile/controllerserver_test.go
Labels: kind/cleanup, size/S, approved, cncf-cla: yes

#1046 feat: support pv/pvc metadata for shareName parameter
  charts/latest/azurefile-csi-driver-v1.20.0.tgz
  docs/driver-parameters.md
  pkg/azurefile/azurefile.go
  pkg/azurefile/controllerserver.go
  pkg/azurefile/nodeserver.go
  pkg/azurefile/utils.go
  pkg/azurefile/utils_test.go
  test/e2e/dynamic_provisioning_test.go
Labels: kind/feature, size/L, approved, cncf-cla: yes

#1048 chore: shorten userAgent
  pkg/azurefile/version.go
  pkg/azurefile/version_test.go
Labels: kind/cleanup, size/XS, approved, cncf-cla: yes
