Repository kubernetes-sigs/azurefile-csi-driver, pull requests merged in 2022-09, with the labels that each got.

#1079 chore: refine the log printing in getAccountKeyFromSecret process
  pkg/azurefile/azurefile.go
Labels: size/S, approved, cncf-cla: yes

#1081 fix: chart index file
  charts/index.yaml
Labels: kind/bug, size/M, approved, cncf-cla: yes

#1084 fix: CVE-2022-27664
  go.mod
  go.sum
  vendor/golang.org/x/net/html/render.go
  vendor/golang.org/x/net/html/token.go
  vendor/golang.org/x/net/http2/frame.go
  vendor/golang.org/x/net/http2/hpack/encode.go
  vendor/golang.org/x/net/http2/hpack/hpack.go
  vendor/golang.org/x/net/http2/http2.go
  vendor/golang.org/x/net/http2/server.go
  vendor/golang.org/x/net/http2/transport.go
  vendor/golang.org/x/sys/unix/syscall_aix.go
  vendor/modules.txt
Labels: kind/bug, size/L, lgtm, approved, cncf-cla: yes

#1085 fix: cancel the context when timeout of deleting file share
  pkg/azurefile/azurefile.go
  pkg/azurefile/azurefile_client.go
  pkg/azurefile/azurefile_client_test.go
  pkg/azurefile/controllerserver.go
Labels: kind/bug, size/S, lgtm, approved, cncf-cla: yes

#1086 test: run sanity test on csi-test v5.0.0
  test/sanity/run-test.sh
  test/sanity/run-tests-all-clouds.sh
Labels: size/XS, approved, cncf-cla: yes, kind/test

#1089 Updated CONTRIBUTION.md file
  CONTRIBUTING.md
Labels: ok-to-test, size/XS, lgtm, approved, cncf-cla: yes

#1092 chore: upgrade cloud provider azure lib
  go.mod
  go.sum
  pkg/azurefile/azurefile.go
  pkg/azurefile/azurefile_client.go
  pkg/azurefile/azurefile_client_test.go
  pkg/azurefile/azurefile_test.go
  pkg/azurefile/controllerserver.go
  pkg/azurefile/controllerserver_test.go
  vendor/github.com/onsi/gomega/CHANGELOG.md
  vendor/github.com/onsi/gomega/gomega_dsl.go
  vendor/k8s.io/klog/v2/OWNERS
  vendor/k8s.io/klog/v2/contextual.go
  vendor/k8s.io/klog/v2/internal/serialize/keyvalues.go
  vendor/k8s.io/klog/v2/klog.go
  vendor/modules.txt
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/auth/azure_auth.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azureclients/armclient/util.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azureclients/fileclient/azure_fileclient.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azureclients/fileclient/interface.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azureclients/fileclient/mockfileclient/interface.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/consts/consts.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_file.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_loadbalancer.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_managedDiskController.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_routes.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_standard.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_storage.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_storageaccount.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_vmss.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_vmssflex.go
Labels: kind/feature, size/XL, lgtm, approved, cncf-cla: yes

#1091 feat: support https proxy and http proxy in chart config
  charts/latest/azurefile-csi-driver-v0.0.0.tgz
  charts/latest/azurefile-csi-driver/templates/csi-azurefile-controller.yaml
  charts/latest/azurefile-csi-driver/templates/csi-azurefile-node-windows.yaml
  charts/latest/azurefile-csi-driver/templates/csi-azurefile-node.yaml
  charts/latest/azurefile-csi-driver/values.yaml
Labels: kind/feature, ok-to-test, size/S, lgtm, approved, cncf-cla: yes

#1096 feat(helm): add support for labels, annotations, podLabels and podAnnotations
  charts/README.md
  charts/latest/azurefile-csi-driver-v0.0.0.tgz
  charts/latest/azurefile-csi-driver/templates/csi-azurefile-controller.yaml
  charts/latest/azurefile-csi-driver/templates/csi-azurefile-node-windows.yaml
  charts/latest/azurefile-csi-driver/templates/csi-azurefile-node.yaml
  charts/latest/azurefile-csi-driver/templates/csi-snapshot-controller.yaml
  charts/latest/azurefile-csi-driver/values.yaml
Labels: kind/feature, ok-to-test, size/M, lgtm, approved, cncf-cla: yes

#1100 doc: cut v1.22.0 release
  README.md
  charts/README.md
  charts/index.yaml
  charts/latest/azurefile-csi-driver-v0.0.0.tgz
  charts/v1.22.0/azurefile-csi-driver-v1.22.0.tgz
  charts/v1.22.0/azurefile-csi-driver/Chart.yaml
  charts/v1.22.0/azurefile-csi-driver/templates/NOTES.txt
  charts/v1.22.0/azurefile-csi-driver/templates/_helpers.tpl
  charts/v1.22.0/azurefile-csi-driver/templates/crd-csi-snapshot.yaml
  charts/v1.22.0/azurefile-csi-driver/templates/csi-azurefile-controller.yaml
  charts/v1.22.0/azurefile-csi-driver/templates/csi-azurefile-driver.yaml
  charts/v1.22.0/azurefile-csi-driver/templates/csi-azurefile-node-windows.yaml
  charts/v1.22.0/azurefile-csi-driver/templates/csi-azurefile-node.yaml
  charts/v1.22.0/azurefile-csi-driver/templates/csi-snapshot-controller.yaml
  charts/v1.22.0/azurefile-csi-driver/templates/rbac-csi-azurefile-controller.yaml
  charts/v1.22.0/azurefile-csi-driver/templates/rbac-csi-azurefile-node.yaml
  charts/v1.22.0/azurefile-csi-driver/templates/rbac-csi-snapshot-controller.yaml
  charts/v1.22.0/azurefile-csi-driver/templates/serviceaccount-csi-azurefile-controller.yaml
  charts/v1.22.0/azurefile-csi-driver/templates/serviceaccount-csi-azurefile-node.yaml
  charts/v1.22.0/azurefile-csi-driver/templates/serviceaccount-csi-snapshot-controller.yaml
  charts/v1.22.0/azurefile-csi-driver/values.yaml
  deploy/v1.22.0/crd-csi-snapshot.yaml
  deploy/v1.22.0/csi-azurefile-controller.yaml
  deploy/v1.22.0/csi-azurefile-driver.yaml
  deploy/v1.22.0/csi-azurefile-node-windows.yaml
  deploy/v1.22.0/csi-azurefile-node.yaml
  deploy/v1.22.0/csi-snapshot-controller.yaml
  deploy/v1.22.0/rbac-csi-azurefile-controller.yaml
  deploy/v1.22.0/rbac-csi-azurefile-node.yaml
  deploy/v1.22.0/rbac-csi-snapshot-controller.yaml
  docs/install-azurefile-csi-driver.md
  docs/install-csi-driver-v1.22.0.md
  hack/verify-helm-chart-index.sh
Labels: kind/documentation, approved, cncf-cla: yes, size/XXL
