Repository kubernetes-sigs/azurefile-csi-driver, pull requests merged in 2022-03, with the labels that each got.

#927 feat: add mountPermissions parameter in storage class
  docs/driver-parameters.md
  pkg/azurefile/azurefile.go
  pkg/azurefile/controllerserver.go
  pkg/azurefile/controllerserver_test.go
  pkg/azurefile/nodeserver.go
  pkg/azurefile/nodeserver_test.go
  test/e2e/dynamic_provisioning_test.go
Labels: kind/feature, size/L, approved, cncf-cla: yes

#926 doc: cut v1.12.0 release
  README.md
  charts/README.md
  charts/index.yaml
  charts/latest/azurefile-csi-driver-v1.12.0.tgz
  charts/v1.12.0/azurefile-csi-driver-v1.12.0.tgz
  charts/v1.12.0/azurefile-csi-driver/Chart.yaml
  charts/v1.12.0/azurefile-csi-driver/templates/NOTES.txt
  charts/v1.12.0/azurefile-csi-driver/templates/_helpers.tpl
  charts/v1.12.0/azurefile-csi-driver/templates/crd-csi-snapshot.yaml
  charts/v1.12.0/azurefile-csi-driver/templates/csi-azurefile-controller.yaml
  charts/v1.12.0/azurefile-csi-driver/templates/csi-azurefile-driver.yaml
  charts/v1.12.0/azurefile-csi-driver/templates/csi-azurefile-node-windows.yaml
  charts/v1.12.0/azurefile-csi-driver/templates/csi-azurefile-node.yaml
  charts/v1.12.0/azurefile-csi-driver/templates/csi-snapshot-controller.yaml
  charts/v1.12.0/azurefile-csi-driver/templates/rbac-csi-azurefile-controller.yaml
  charts/v1.12.0/azurefile-csi-driver/templates/rbac-csi-azurefile-node.yaml
  charts/v1.12.0/azurefile-csi-driver/templates/rbac-csi-snapshot-controller.yaml
  charts/v1.12.0/azurefile-csi-driver/templates/serviceaccount-csi-azurefile-controller.yaml
  charts/v1.12.0/azurefile-csi-driver/templates/serviceaccount-csi-azurefile-node.yaml
  charts/v1.12.0/azurefile-csi-driver/templates/serviceaccount-csi-snapshot-controller.yaml
  charts/v1.12.0/azurefile-csi-driver/values.yaml
  deploy/v1.12.0/crd-csi-snapshot.yaml
  deploy/v1.12.0/csi-azurefile-controller.yaml
  deploy/v1.12.0/csi-azurefile-driver.yaml
  deploy/v1.12.0/csi-azurefile-node-windows.yaml
  deploy/v1.12.0/csi-azurefile-node.yaml
  deploy/v1.12.0/csi-snapshot-controller.yaml
  deploy/v1.12.0/rbac-csi-azurefile-controller.yaml
  deploy/v1.12.0/rbac-csi-azurefile-node.yaml
  deploy/v1.12.0/rbac-csi-snapshot-controller.yaml
  docs/install-azurefile-csi-driver.md
  docs/install-csi-driver-v1.12.0.md
Labels: kind/documentation, approved, cncf-cla: yes, size/XXL

#929 chore: switch master branch to use v1.13.0
  Makefile
  charts/index.yaml
  charts/latest/azurefile-csi-driver-v1.12.0.tgz
  charts/latest/azurefile-csi-driver-v1.13.0.tgz
  charts/latest/azurefile-csi-driver/Chart.yaml
Labels: kind/documentation, size/M, approved, cncf-cla: yes

#930 test: fix driver pod restarts script
  test/utils/check_driver_pods_restart.sh
Labels: size/M, approved, cncf-cla: yes, kind/test

#933 fix: add tags matching in storage account search
  go.mod
  go.sum
  test/e2e/dynamic_provisioning_test.go
  vendor/github.com/Azure/azure-sdk-for-go/version/version.go
  vendor/k8s.io/cloud-provider/api/well_known_annotations.go
  vendor/k8s.io/cloud-provider/api/well_known_taints.go
  vendor/k8s.io/cloud-provider/node/helpers/address.go
  vendor/k8s.io/cloud-provider/node/helpers/labels.go
  vendor/k8s.io/cloud-provider/node/helpers/taints.go
  vendor/k8s.io/component-helpers/node/util/cidr.go
  vendor/k8s.io/component-helpers/node/util/conditions.go
  vendor/k8s.io/component-helpers/node/util/status.go
  vendor/modules.txt
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/nodemanager/nodemanager.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_controller_vmss.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_loadbalancer_backendpool.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_storageaccount.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_vmss.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/virtualmachine/virtualmachine.go
Labels: kind/bug, approved, cncf-cla: yes, size/XXL

#932 test: remove runOnMaster config in e2e test
  Makefile
  charts/latest/azurefile-csi-driver-v1.13.0.tgz
  charts/latest/azurefile-csi-driver/values.yaml
Labels: size/XS, approved, cncf-cla: yes, kind/test

#937 fix: armclient panic when response is nil
  go.mod
  go.sum
  vendor/github.com/Azure/azure-sdk-for-go/version/version.go
  vendor/modules.txt
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azureclients/armclient/azure_armclient.go
Labels: kind/bug, size/S, approved, cncf-cla: yes

#938 fix: reduce account api throttling in removing tags
  pkg/azurefile/azurefile.go
Labels: kind/bug, size/S, approved, cncf-cla: yes

#940 Rephrase block volume error
  pkg/azurefile/controllerserver.go
  pkg/azurefile/controllerserver_test.go
Labels: kind/cleanup, size/XS, lgtm, approved, cncf-cla: yes

#942 test: fix in-tree driver test failure in k/k
  test/e2e/suite_test.go
Labels: kind/failing-test, size/XS, approved, cncf-cla: yes

#943 fix: CVE-2022-0778 in image build
  pkg/azurefileplugin/Dockerfile
Labels: kind/bug, size/XS, approved, cncf-cla: yes

#944 doc: add nconnect mount option in nfs example
  deploy/example/pv-azurefile-nfs.yaml
  deploy/example/storageclass-azurefile-nfs.yaml
  test/e2e/dynamic_provisioning_test.go
Labels: kind/documentation, size/XS, approved, cncf-cla: yes

#945 feat: provide latency data in logs
  go.mod
  go.sum
  pkg/azurefile/controllerserver.go
  vendor/github.com/Azure/azure-sdk-for-go/version/version.go
  vendor/github.com/spf13/cobra/MAINTAINERS
  vendor/github.com/spf13/cobra/Makefile
  vendor/github.com/spf13/cobra/README.md
  vendor/github.com/spf13/cobra/projects_using_cobra.md
  vendor/github.com/spf13/cobra/shell_completions.md
  vendor/github.com/spf13/cobra/user_guide.md
  vendor/github.com/stretchr/testify/assert/assertion_compare.go
  vendor/github.com/stretchr/testify/assert/assertion_compare_can_convert.go
  vendor/github.com/stretchr/testify/assert/assertion_compare_legacy.go
  vendor/github.com/stretchr/testify/assert/assertion_format.go
  vendor/github.com/stretchr/testify/assert/assertion_forward.go
  vendor/github.com/stretchr/testify/assert/assertion_order.go
  vendor/github.com/stretchr/testify/assert/assertions.go
  vendor/modules.txt
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/metrics/azure_metrics.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_backoff.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_controller_common.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_controller_standard.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_controller_vmss.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_loadbalancer.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_managedDiskController.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_routes.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_standard.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_vmss.go
Labels: kind/feature, size/XL, approved, cncf-cla: yes

#946 feat: add azureGoSDKLogLevel config in chart
  Makefile
  charts/README.md
  charts/latest/azurefile-csi-driver-v1.13.0.tgz
  charts/latest/azurefile-csi-driver/templates/csi-azurefile-controller.yaml
  charts/latest/azurefile-csi-driver/templates/csi-azurefile-node-windows.yaml
  charts/latest/azurefile-csi-driver/templates/csi-azurefile-node.yaml
  charts/latest/azurefile-csi-driver/values.yaml
Labels: kind/feature, size/XS, approved, cncf-cla: yes

#947 test: add ENV setting info in e2e tests
  test/e2e/suite_test.go
Labels: size/XS, approved, cncf-cla: yes, kind/test

#948 test: add more debugging info in e2e test
  test/e2e/suite_test.go
Labels: size/XS, approved, cncf-cla: yes, kind/test

#950 fix: leader-election namespace issue
  charts/latest/azurefile-csi-driver-v1.13.0.tgz
  charts/latest/azurefile-csi-driver/templates/csi-azurefile-controller.yaml
  charts/latest/azurefile-csi-driver/templates/csi-snapshot-controller.yaml
  deploy/csi-azurefile-controller.yaml
  deploy/csi-snapshot-controller.yaml
  go.mod
  hack/verify-all.sh
  vendor/modules.txt
Labels: kind/bug, size/S, approved, cncf-cla: yes

#951 doc: cut v1.13.0 release
  README.md
  charts/README.md
  charts/index.yaml
  charts/latest/azurefile-csi-driver-v1.13.0.tgz
  charts/v1.13.0/azurefile-csi-driver-v1.13.0.tgz
  charts/v1.13.0/azurefile-csi-driver/Chart.yaml
  charts/v1.13.0/azurefile-csi-driver/templates/NOTES.txt
  charts/v1.13.0/azurefile-csi-driver/templates/_helpers.tpl
  charts/v1.13.0/azurefile-csi-driver/templates/crd-csi-snapshot.yaml
  charts/v1.13.0/azurefile-csi-driver/templates/csi-azurefile-controller.yaml
  charts/v1.13.0/azurefile-csi-driver/templates/csi-azurefile-driver.yaml
  charts/v1.13.0/azurefile-csi-driver/templates/csi-azurefile-node-windows.yaml
  charts/v1.13.0/azurefile-csi-driver/templates/csi-azurefile-node.yaml
  charts/v1.13.0/azurefile-csi-driver/templates/csi-snapshot-controller.yaml
  charts/v1.13.0/azurefile-csi-driver/templates/rbac-csi-azurefile-controller.yaml
  charts/v1.13.0/azurefile-csi-driver/templates/rbac-csi-azurefile-node.yaml
  charts/v1.13.0/azurefile-csi-driver/templates/rbac-csi-snapshot-controller.yaml
  charts/v1.13.0/azurefile-csi-driver/templates/serviceaccount-csi-azurefile-controller.yaml
  charts/v1.13.0/azurefile-csi-driver/templates/serviceaccount-csi-azurefile-node.yaml
  charts/v1.13.0/azurefile-csi-driver/templates/serviceaccount-csi-snapshot-controller.yaml
  charts/v1.13.0/azurefile-csi-driver/values.yaml
  deploy/v1.13.0/crd-csi-snapshot.yaml
  deploy/v1.13.0/csi-azurefile-controller.yaml
  deploy/v1.13.0/csi-azurefile-driver.yaml
  deploy/v1.13.0/csi-azurefile-node-windows.yaml
  deploy/v1.13.0/csi-azurefile-node.yaml
  deploy/v1.13.0/csi-snapshot-controller.yaml
  deploy/v1.13.0/rbac-csi-azurefile-controller.yaml
  deploy/v1.13.0/rbac-csi-azurefile-node.yaml
  deploy/v1.13.0/rbac-csi-snapshot-controller.yaml
  docs/install-azurefile-csi-driver.md
  docs/install-csi-driver-v1.13.0.md
Labels: kind/documentation, approved, cncf-cla: yes, size/XXL

#953 chore: switch master branch to use v1.14.0
  Makefile
  charts/index.yaml
  charts/latest/azurefile-csi-driver-v1.13.0.tgz
  charts/latest/azurefile-csi-driver-v1.14.0.tgz
  charts/latest/azurefile-csi-driver/Chart.yaml
Labels: kind/documentation, size/M, approved, cncf-cla: yes

#954 fix: CVE issues in image build
  pkg/azurefileplugin/Dockerfile
  pkg/azurefileplugin/Windows.Dockerfile
Labels: kind/bug, size/XS, approved, cncf-cla: yes

#955 fix: default secretNamespace should be pvc namespace
  docs/driver-parameters.md
  pkg/azurefile/azurefile.go
  pkg/azurefile/controllerserver.go
Labels: kind/bug, size/S, approved, cncf-cla: yes
