Repository kubernetes-sigs/azurefile-csi-driver, pull requests merged in 2022-11, with the labels that each got.

#1125 cleanup: remove unused install docs
  docs/install-csi-driver-v0.10.0.md
  docs/install-csi-driver-v0.2.0.md
  docs/install-csi-driver-v0.3.0.md
  docs/install-csi-driver-v0.4.0.md
  docs/install-csi-driver-v0.5.0.md
  docs/install-csi-driver-v0.6.0.md
  docs/install-csi-driver-v0.7.0.md
  docs/install-csi-driver-v0.8.0.md
  docs/install-csi-driver-v0.9.0.md
Labels: size/L, kind/cleanup, approved, cncf-cla: yes

#1127 feat: add useDataPlaneAPI in snapshot storage class
  pkg/azurefile/controllerserver.go
  pkg/azurefile/controllerserver_test.go
Labels: kind/feature, size/S, approved, cncf-cla: yes

#1128 doc: cut v1.24.0 release
  README.md
  charts/README.md
  charts/index.yaml
  charts/latest/azurefile-csi-driver-v0.0.0.tgz
  charts/v1.24.0/azurefile-csi-driver-v1.24.0.tgz
  charts/v1.24.0/azurefile-csi-driver/Chart.yaml
  charts/v1.24.0/azurefile-csi-driver/templates/NOTES.txt
  charts/v1.24.0/azurefile-csi-driver/templates/_helpers.tpl
  charts/v1.24.0/azurefile-csi-driver/templates/crd-csi-snapshot.yaml
  charts/v1.24.0/azurefile-csi-driver/templates/csi-azurefile-controller.yaml
  charts/v1.24.0/azurefile-csi-driver/templates/csi-azurefile-driver.yaml
  charts/v1.24.0/azurefile-csi-driver/templates/csi-azurefile-node-windows.yaml
  charts/v1.24.0/azurefile-csi-driver/templates/csi-azurefile-node.yaml
  charts/v1.24.0/azurefile-csi-driver/templates/csi-snapshot-controller.yaml
  charts/v1.24.0/azurefile-csi-driver/templates/rbac-csi-azurefile-controller.yaml
  charts/v1.24.0/azurefile-csi-driver/templates/rbac-csi-azurefile-node.yaml
  charts/v1.24.0/azurefile-csi-driver/templates/rbac-csi-snapshot-controller.yaml
  charts/v1.24.0/azurefile-csi-driver/templates/serviceaccount-csi-azurefile-controller.yaml
  charts/v1.24.0/azurefile-csi-driver/templates/serviceaccount-csi-azurefile-node.yaml
  charts/v1.24.0/azurefile-csi-driver/templates/serviceaccount-csi-snapshot-controller.yaml
  charts/v1.24.0/azurefile-csi-driver/values.yaml
  deploy/v1.24.0/crd-csi-snapshot.yaml
  deploy/v1.24.0/csi-azurefile-controller.yaml
  deploy/v1.24.0/csi-azurefile-driver.yaml
  deploy/v1.24.0/csi-azurefile-node-windows.yaml
  deploy/v1.24.0/csi-azurefile-node.yaml
  deploy/v1.24.0/csi-snapshot-controller.yaml
  deploy/v1.24.0/rbac-csi-azurefile-controller.yaml
  deploy/v1.24.0/rbac-csi-azurefile-node.yaml
  deploy/v1.24.0/rbac-csi-snapshot-controller.yaml
  docs/install-azurefile-csi-driver.md
  docs/install-csi-driver-v1.24.0.md
Labels: kind/documentation, approved, cncf-cla: yes, size/XXL

#1130 Clean up .travis.yml
  .travis.yml
Labels: kind/cleanup, ok-to-test, size/S, lgtm, approved, cncf-cla: yes
