Repository kubernetes-sigs/azurefile-csi-driver, pull requests merged in 2022-07, with the labels that each got.

#1051 chore: set master branch chart version to v0.0.0
  charts/index.yaml
  charts/latest/azurefile-csi-driver-v0.0.0.tgz
  charts/latest/azurefile-csi-driver-v1.20.0.tgz
  charts/latest/azurefile-csi-driver/Chart.yaml
Labels: kind/documentation, size/M, approved, cncf-cla: yes

#1052 chore: upgrade base image to debian-base:bullseye-v1.4.0
  pkg/azurefileplugin/Dockerfile
  test/sanity/run-tests-all-clouds.sh
Labels: size/XS, approved, cncf-cla: yes, kind/test

#1053 fix: CSI function should return internal error
  charts/README.md
  charts/latest/azurefile-csi-driver-v0.0.0.tgz
  charts/latest/azurefile-csi-driver/values.yaml
  deploy/csi-azurefile-node-windows.yaml
  pkg/azurefile/controllerserver.go
  pkg/azurefile/nodeserver.go
Labels: kind/bug, size/S, approved, cncf-cla: yes

#1056 chore: switch master branch to use v1.21.0
  Makefile
Labels: kind/documentation, size/XS, approved, cncf-cla: yes

#1058 fix: don't return error if request size is smaller than existing quota
  pkg/azurefile/controllerserver.go
  pkg/azurefile/controllerserver_test.go
Labels: kind/bug, size/M, approved, cncf-cla: yes

#1061 chore: add node-role.kubernetes.io/control-plane toleration
  charts/latest/azurefile-csi-driver-v0.0.0.tgz
  charts/latest/azurefile-csi-driver/values.yaml
  deploy/csi-azurefile-controller.yaml
  deploy/csi-snapshot-controller.yaml
Labels: size/S, kind/documentation, lgtm, approved, cncf-cla: yes
