Repository kubernetes-sigs/azurefile-csi-driver, pull requests merged in 2023-05, with the labels that each got.

#1235 chore: upgrade csi sidecar container images
  charts/README.md
  charts/latest/azurefile-csi-driver-v0.0.0.tgz
  charts/latest/azurefile-csi-driver/values.yaml
  deploy/csi-azurefile-controller.yaml
  deploy/csi-azurefile-node-windows.yaml
  deploy/csi-azurefile-node.yaml
Labels: kind/feature, size/M, approved, cncf-cla: yes

#1182 feat: add host-process containers in helm charts
  Makefile
  charts/README.md
  charts/latest/azurefile-csi-driver-v0.0.0.tgz
  charts/latest/azurefile-csi-driver/templates/csi-azurefile-node-windows-hostprocess.yaml
  charts/latest/azurefile-csi-driver/templates/csi-azurefile-node-windows.yaml
  charts/latest/azurefile-csi-driver/values.yaml
  deploy/csi-azurefile-node-windows-hostprocess.yaml
  deploy/install-driver.sh
  deploy/uninstall-driver.sh
  pkg/azurefile/azure.go
  pkg/azurefile/azure_test.go
  pkg/azurefile/azurefile.go
  pkg/azurefileplugin/WindowsHostProcess.Dockerfile
  pkg/os/smb/smb.go
Labels: size/L, lgtm, approved, cncf-cla: yes

#1237 test: add dependabot
  .github/dependabot.yaml
Labels: size/S, approved, cncf-cla: yes, kind/test

#1243 fix: windows host process container deployment
  Makefile
  charts/latest/azurefile-csi-driver-v0.0.0.tgz
  charts/latest/azurefile-csi-driver/templates/csi-azurefile-node-windows-hostprocess.yaml
  deploy/csi-azurefile-node-windows-hostprocess.yaml
  hack/release-image.sh
Labels: kind/bug, size/S, approved

#1248 chore: refine workload identity docs.
  docs/workload-identity.md
Labels: size/S, lgtm, approved, cncf-cla: yes

#1245 fix: add closetimeo=0 option to fix data sync issue on Ubuntu 22.04
  pkg/azurefile/azurefile.go
  pkg/azurefile/azurefile_test.go
  pkg/azurefile/nodeserver.go
  pkg/azurefileplugin/main.go
Labels: kind/bug, size/M, approved, cncf-cla: yes

#1244 fix: default actimeo option should respect acregmax and acdirmax
  pkg/azurefile/azurefile.go
  pkg/azurefile/azurefile_test.go
Labels: kind/bug, size/S, approved, cncf-cla: yes

#1250 Changing kubernetes-release bucket path to dl.k8s.io
  test/external-e2e/run.sh
Labels: ok-to-test, size/XS, lgtm, approved, cncf-cla: yes

#1255 chore: refine windows host process container image build
  Makefile
  hack/release-image.sh
Labels: kind/cleanup, size/XS, approved, cncf-cla: yes

#1256 cleanup: update new chart versions and remove deprecated versions
  README.md
  charts/v1.26.2/azurefile-csi-driver-v1.26.2.tgz
  charts/v1.26.2/azurefile-csi-driver/Chart.yaml
  charts/v1.26.2/azurefile-csi-driver/templates/NOTES.txt
  charts/v1.26.2/azurefile-csi-driver/templates/_helpers.tpl
  charts/v1.26.2/azurefile-csi-driver/templates/crd-csi-snapshot.yaml
  charts/v1.26.2/azurefile-csi-driver/templates/csi-azurefile-controller.yaml
  charts/v1.26.2/azurefile-csi-driver/templates/csi-azurefile-driver.yaml
  charts/v1.26.2/azurefile-csi-driver/templates/csi-azurefile-node-windows.yaml
  charts/v1.26.2/azurefile-csi-driver/templates/csi-azurefile-node.yaml
  charts/v1.26.2/azurefile-csi-driver/templates/csi-snapshot-controller.yaml
  charts/v1.26.2/azurefile-csi-driver/templates/rbac-csi-azurefile-controller.yaml
  charts/v1.26.2/azurefile-csi-driver/templates/rbac-csi-azurefile-node.yaml
  charts/v1.26.2/azurefile-csi-driver/templates/rbac-csi-snapshot-controller.yaml
  charts/v1.26.2/azurefile-csi-driver/templates/serviceaccount-csi-azurefile-controller.yaml
  charts/v1.26.2/azurefile-csi-driver/templates/serviceaccount-csi-azurefile-node.yaml
  charts/v1.26.2/azurefile-csi-driver/templates/serviceaccount-csi-snapshot-controller.yaml
  charts/v1.26.2/azurefile-csi-driver/values.yaml
  deploy/v1.26.2/crd-csi-snapshot.yaml
  deploy/v1.26.2/csi-azurefile-controller.yaml
  deploy/v1.26.2/csi-azurefile-driver.yaml
  deploy/v1.26.2/csi-azurefile-node-windows.yaml
  deploy/v1.26.2/csi-azurefile-node.yaml
  deploy/v1.26.2/csi-snapshot-controller.yaml
  deploy/v1.26.2/rbac-csi-azurefile-controller.yaml
  deploy/v1.26.2/rbac-csi-azurefile-node.yaml
  deploy/v1.26.2/rbac-csi-snapshot-controller.yaml
  docs/install-azurefile-csi-driver.md
  docs/install-csi-driver-v1.25.0.md
  docs/install-csi-driver-v1.26.0.md
  docs/install-csi-driver-v1.26.2.md
Labels: kind/documentation, approved, cncf-cla: yes, size/XXL

#1258 fix: make sure the VolumeSnapshots v1 CRDs exist before starting
  charts/latest/azurefile-csi-driver-v0.0.0.tgz
  charts/latest/azurefile-csi-driver/templates/csi-snapshot-controller.yaml
  deploy/csi-snapshot-controller.yaml
Labels: kind/bug, size/S, approved, cncf-cla: yes

#1261 Build: add dependabot job for dockerfile updates.
  .github/dependabot.yaml
Labels: size/S, lgtm, approved, cncf-cla: yes, kind/test

#1263 doc: refine workload identity doc
  README.md
  docs/workload-identity.md
Labels: kind/documentation, size/M, lgtm, approved, cncf-cla: yes

#1259 [release-1.27] fix: make sure the VolumeSnapshots v1 CRDs exist before starting
  charts/latest/azurefile-csi-driver-v1.27.0.tgz
  charts/latest/azurefile-csi-driver/templates/csi-snapshot-controller.yaml
  deploy/csi-snapshot-controller.yaml
Labels: kind/bug, size/S, approved, cncf-cla: yes

#1267 fix: append nosharesock mount option on Linux node by default
  pkg/azurefile/azurefile.go
  pkg/azurefile/azurefile_test.go
  pkg/azurefile/nodeserver.go
  pkg/azurefileplugin/main.go
Labels: kind/bug, size/M, approved, cncf-cla: yes

#1265 chore: update windows host process lib
  pkg/os/filesystem/filesystem.go
  pkg/os/smb/smb.go
  pkg/util/util.go
Labels: kind/feature, size/M, approved, cncf-cla: yes

#1269 [release-1.24] fix: append nosharesock mount option on Linux node by default
  pkg/azurefile/azurefile.go
  pkg/azurefile/azurefile_test.go
  pkg/azurefile/nodeserver.go
  pkg/azurefileplugin/main.go
Labels: kind/bug, size/M, approved, cncf-cla: yes

#1270 [release-1.26] fix: append nosharesock mount option on Linux node by default
  pkg/azurefile/azurefile.go
  pkg/azurefile/azurefile_test.go
  pkg/azurefile/nodeserver.go
  pkg/azurefileplugin/main.go
Labels: kind/bug, size/M, approved, cncf-cla: yes

#1277 chore: refactor host process code
  Makefile
  charts/README.md
  charts/latest/azurefile-csi-driver-v0.0.0.tgz
  charts/latest/azurefile-csi-driver/templates/csi-azurefile-node-windows-hostprocess.yaml
  charts/latest/azurefile-csi-driver/templates/csi-azurefile-node-windows.yaml
  charts/latest/azurefile-csi-driver/values.yaml
  deploy/csi-azurefile-node-windows-hostprocess.yaml
  hack/release-image.sh
  pkg/mounter/safe_mounter_host_process_windows.go
  pkg/os/filesystem/filesystem.go
  pkg/os/filesystem/types.go
Labels: size/L, kind/cleanup, approved, cncf-cla: yes

#1279 cleanup: remove unnecessary path validation on hpc deployment
  pkg/os/filesystem/filesystem.go
Labels: kind/cleanup, size/XS, approved, cncf-cla: yes

#1281 doc: remove unused resourceGroup field when secret is specified
  deploy/example/pv-azurefile-csi.yaml
Labels: kind/documentation, size/XS, approved, cncf-cla: yes

#1282 doc: cut v1.28.0 release
  README.md
  charts/README.md
  charts/index.yaml
  charts/latest/azurefile-csi-driver-v0.0.0.tgz
  charts/v1.28.0/azurefile-csi-driver-v1.28.0.tgz
  charts/v1.28.0/azurefile-csi-driver/Chart.yaml
  charts/v1.28.0/azurefile-csi-driver/templates/NOTES.txt
  charts/v1.28.0/azurefile-csi-driver/templates/_helpers.tpl
  charts/v1.28.0/azurefile-csi-driver/templates/crd-csi-snapshot.yaml
  charts/v1.28.0/azurefile-csi-driver/templates/csi-azurefile-controller.yaml
  charts/v1.28.0/azurefile-csi-driver/templates/csi-azurefile-driver.yaml
  charts/v1.28.0/azurefile-csi-driver/templates/csi-azurefile-node-windows-hostprocess.yaml
  charts/v1.28.0/azurefile-csi-driver/templates/csi-azurefile-node-windows.yaml
  charts/v1.28.0/azurefile-csi-driver/templates/csi-azurefile-node.yaml
  charts/v1.28.0/azurefile-csi-driver/templates/csi-snapshot-controller.yaml
  charts/v1.28.0/azurefile-csi-driver/templates/rbac-csi-azurefile-controller.yaml
  charts/v1.28.0/azurefile-csi-driver/templates/rbac-csi-azurefile-node.yaml
  charts/v1.28.0/azurefile-csi-driver/templates/rbac-csi-snapshot-controller.yaml
  charts/v1.28.0/azurefile-csi-driver/templates/serviceaccount-csi-azurefile-controller.yaml
  charts/v1.28.0/azurefile-csi-driver/templates/serviceaccount-csi-azurefile-node.yaml
  charts/v1.28.0/azurefile-csi-driver/templates/serviceaccount-csi-snapshot-controller.yaml
  charts/v1.28.0/azurefile-csi-driver/values.yaml
  deploy/v1.28.0/crd-csi-snapshot.yaml
  deploy/v1.28.0/csi-azurefile-controller.yaml
  deploy/v1.28.0/csi-azurefile-driver.yaml
  deploy/v1.28.0/csi-azurefile-node-windows-hostprocess.yaml
  deploy/v1.28.0/csi-azurefile-node-windows.yaml
  deploy/v1.28.0/csi-azurefile-node.yaml
  deploy/v1.28.0/csi-snapshot-controller.yaml
  deploy/v1.28.0/rbac-csi-azurefile-controller.yaml
  deploy/v1.28.0/rbac-csi-azurefile-node.yaml
  deploy/v1.28.0/rbac-csi-snapshot-controller.yaml
  docs/install-azurefile-csi-driver.md
  docs/install-csi-driver-v1.28.0.md
Labels: kind/documentation, approved, cncf-cla: yes, size/XXL

#1284 fix: hpc image build on AKS
  Makefile
  hack/release-image.sh
Labels: kind/bug, size/S, approved, cncf-cla: yes

#1285 fix: hpc image build on AKS
  Makefile
  hack/release-image.sh
Labels: kind/bug, size/S, approved, cncf-cla: yes

#1287 chore: enable host process deployment test
  Makefile
  pkg/os/smb/smb.go
  pkg/util/util.go
Labels: kind/cleanup, size/S, approved, cncf-cla: yes
