Repository kubernetes-sigs/azurefile-csi-driver, pull requests merged in 2023-07, with the labels that each got.

#1316 Doc: fix typo for storeAccountKey
  docs/driver-parameters.md
Labels: ok-to-test, kind/documentation, size/XS, lgtm, approved, cncf-cla: yes

#1324 fix: CVE-2023-2431
  go.mod
  go.sum
  pkg/azurefile/utils.go
  vendor/k8s.io/api/batch/v1/generated.proto
  vendor/k8s.io/api/batch/v1/types.go
  vendor/k8s.io/api/batch/v1/types_swagger_doc_generated.go
  vendor/k8s.io/api/core/v1/generated.proto
  vendor/k8s.io/api/core/v1/types.go
  vendor/k8s.io/api/core/v1/types_swagger_doc_generated.go
  vendor/k8s.io/apimachinery/pkg/types/namespacedname.go
  vendor/k8s.io/apiserver/pkg/cel/common/values.go
  vendor/k8s.io/client-go/discovery/discovery_client.go
  vendor/k8s.io/client-go/openapi/client.go
  vendor/k8s.io/client-go/openapi/groupversion.go
  vendor/k8s.io/kube-openapi/pkg/handler/handler.go
  vendor/k8s.io/kubernetes/pkg/apis/core/types.go
  vendor/k8s.io/kubernetes/pkg/features/kube_features.go
  vendor/k8s.io/kubernetes/pkg/volume/volume_linux.go
  vendor/k8s.io/kubernetes/pkg/volume/volume_unsupported.go
  vendor/k8s.io/kubernetes/test/e2e/framework/get.go
  vendor/k8s.io/kubernetes/test/e2e/framework/kubectl/builder.go
  vendor/modules.txt
  vendor/sigs.k8s.io/apiserver-network-proxy/konnectivity-client/pkg/client/client.go
  vendor/sigs.k8s.io/apiserver-network-proxy/konnectivity-client/pkg/client/metrics/metrics.go
Labels: kind/bug, size/L, approved, cncf-cla: yes

#1325 fix: use InClusterConfig by default on Windows node
  charts/README.md
  deploy/csi-azurefile-node-windows-hostprocess.yaml
  deploy/csi-azurefile-node-windows.yaml
Labels: kind/bug, size/XS, approved, cncf-cla: yes

#1327 [release-1.26] fix: CVE-2023-2727
  go.mod
  go.sum
  vendor/modules.txt
Labels: kind/bug, size/L, approved, cncf-cla: yes
