Repository kubernetes-sigs/azurefile-csi-driver, pull requests merged in 2023-10, with the labels that each got.

#1472 [release-1.29] fix: refine create volume metrics
  pkg/azurefile/controllerserver.go
Labels: kind/bug, size/M, approved, cncf-cla: yes

#1475 fix: upgrade mount-utils lib
  go.mod
  go.sum
  vendor/k8s.io/mount-utils/mount.go
  vendor/k8s.io/mount-utils/mount_helper_unix.go
  vendor/k8s.io/mount-utils/mount_linux.go
  vendor/k8s.io/mount-utils/mount_windows.go
  vendor/k8s.io/mount-utils/resizefs_linux.go
  vendor/modules.txt
Labels: kind/bug, size/L, approved, cncf-cla: yes

#1391 fix: check storage account type if parameter is missing
  deploy/example/azure.json
  docs/csi-debug.md
  pkg/azurefile/controllerserver.go
  pkg/azurefile/controllerserver_test.go
  test/e2e/driver/azurefile_driver.go
Labels: kind/bug, size/L, lgtm, approved, cncf-cla: yes

#1477 doc: refine inline volume example
  deploy/example/e2e_usage.md
Labels: kind/documentation, size/XS, approved, cncf-cla: yes

#1481 test: fix verify-helm-chart failure
  hack/verify-helm-chart.sh
Labels: kind/failing-test, size/XS, approved, cncf-cla: yes

#1486 [release-1.28] doc: fix typos
  deploy/example/azure.json
  docs/csi-debug.md
  pkg/azurefile/controllerserver.go
  test/e2e/driver/azurefile_driver.go
Labels: size/S, kind/documentation, approved, cncf-cla: yes

#1478 test: add nfs snapshot e2e test
  test/e2e/dynamic_provisioning_test.go
  test/e2e/suite_test.go
  test/e2e/testsuites/dynamically_provisioned_volume_snapshot_tester.go
Labels: size/M, approved, cncf-cla: yes, kind/test

#1492 fix: CVE-2023-39325
  .trivyignore
  go.mod
  go.sum
  vendor/golang.org/x/net/http2/server.go
  vendor/modules.txt
Labels: size/M, approved, cncf-cla: yes

#1500 cleanup: fix k8s.io/endpointslice dependency
  go.mod
  hack/verify-gomod.sh
  vendor/modules.txt
Labels: kind/failing-test, size/XS, approved, cncf-cla: yes

#1491 test: enable cloudprovider_azure metrics print
  .trivyignore
  hack/verify-examples.sh
  test/e2e/dynamic_provisioning_test.go
  test/e2e/suite_test.go
  test/utils/azurefile_log.sh
Labels: size/M, approved, cncf-cla: yes, kind/test

#1504 [release-1.26] test: enable cloudprovider_azure metrics print
  hack/verify-examples.sh
  test/e2e/dynamic_provisioning_test.go
  test/e2e/suite_test.go
  test/utils/azurefile_log.sh
Labels: size/M, kind/failing-test, approved, cncf-cla: yes

#1505 fix: nfs volume creation failure due to Microsoft.Storage.Global Service endpoint enabled
  pkg/azurefile/azure.go
Labels: kind/bug, size/XS, approved, cncf-cla: yes

#1501 feat: add node metrics
  charts/latest/azurefile-csi-driver-v0.0.0.tgz
  charts/latest/azurefile-csi-driver/templates/csi-azurefile-node-windows-hostprocess.yaml
  charts/latest/azurefile-csi-driver/templates/csi-azurefile-node-windows.yaml
  charts/latest/azurefile-csi-driver/templates/csi-azurefile-node.yaml
  charts/latest/azurefile-csi-driver/values.yaml
  deploy/csi-azurefile-node-windows-hostprocess.yaml
  deploy/csi-azurefile-node-windows.yaml
  deploy/csi-azurefile-node.yaml
  pkg/azurefile/nodeserver.go
Labels: kind/feature, size/M, approved, cncf-cla: yes

#1512 [release-1.28] feat: add node metrics
  charts/latest/azurefile-csi-driver-v1.28.5.tgz
  charts/latest/azurefile-csi-driver/templates/csi-azurefile-node-windows-hostprocess.yaml
  charts/latest/azurefile-csi-driver/templates/csi-azurefile-node-windows.yaml
  charts/latest/azurefile-csi-driver/templates/csi-azurefile-node.yaml
  charts/latest/azurefile-csi-driver/values.yaml
  deploy/csi-azurefile-node-windows-hostprocess.yaml
  deploy/csi-azurefile-node-windows.yaml
  deploy/csi-azurefile-node.yaml
  pkg/azurefile/nodeserver.go
Labels: kind/feature, size/M, approved, cncf-cla: yes

#1511 [release-1.29] feat: add node metrics
  charts/latest/azurefile-csi-driver-v1.29.0.tgz
  charts/latest/azurefile-csi-driver/templates/csi-azurefile-node-windows-hostprocess.yaml
  charts/latest/azurefile-csi-driver/templates/csi-azurefile-node-windows.yaml
  charts/latest/azurefile-csi-driver/templates/csi-azurefile-node.yaml
  charts/latest/azurefile-csi-driver/values.yaml
  deploy/csi-azurefile-node-windows-hostprocess.yaml
  deploy/csi-azurefile-node-windows.yaml
  deploy/csi-azurefile-node.yaml
  pkg/azurefile/nodeserver.go
Labels: kind/feature, size/M, approved, cncf-cla: yes

#1510 fix: incorrect volumesnapshot size
  pkg/azurefile/controllerserver.go
Labels: kind/bug, ok-to-test, size/XS, lgtm, approved, cncf-cla: yes

#1518 doc: correct check azurefile csi pod status doc
  charts/latest/azurefile-csi-driver-v0.0.0.tgz
  charts/latest/azurefile-csi-driver/templates/NOTES.txt
Labels: ok-to-test, kind/documentation, size/XS, lgtm, approved, cncf-cla: yes

#1520 [release-1.29] fix: increase provisioner timeout as 20min
  charts/latest/azurefile-csi-driver-v1.29.0.tgz
  charts/latest/azurefile-csi-driver/templates/csi-azurefile-controller.yaml
  deploy/csi-azurefile-controller.yaml
Labels: kind/bug, size/XS, approved, cncf-cla: yes

#1519 fix: increase provisioner timeout as 20min
  charts/latest/azurefile-csi-driver-v0.0.0.tgz
  charts/latest/azurefile-csi-driver/templates/csi-azurefile-controller.yaml
  deploy/csi-azurefile-controller.yaml
Labels: kind/bug, size/XS, approved, cncf-cla: yes

#1529 chore: upgrade sidecar image versions
  charts/README.md
  charts/latest/azurefile-csi-driver-v0.0.0.tgz
  charts/latest/azurefile-csi-driver/values.yaml
  deploy/csi-azurefile-controller.yaml
Labels: kind/feature, size/S, approved, cncf-cla: yes

#1531 chore: upgrade sidecar image versions
  charts/README.md
  charts/latest/azurefile-csi-driver-v0.0.0.tgz
  charts/latest/azurefile-csi-driver/values.yaml
  deploy/csi-azurefile-controller.yaml
  deploy/csi-azurefile-node-windows-hostprocess.yaml
  deploy/csi-azurefile-node-windows.yaml
  deploy/csi-azurefile-node.yaml
Labels: kind/feature, size/S, approved, cncf-cla: yes
