Repository kubernetes-sigs/azurefile-csi-driver, pull requests merged in 2023-02, with the labels that each got.

#1174 feat: add support for SMB Multi-channels in premium account creation
  docs/driver-parameters.md
  pkg/azurefile/azurefile.go
  pkg/azurefile/controllerserver.go
  test/e2e/dynamic_provisioning_test.go
Labels: kind/feature, size/M, approved, cncf-cla: yes

#1176 fix: buildx issue with provenance disabled
  Makefile
  hack/boilerplate/boilerplate.py
  test/external-e2e/run.sh
Labels: kind/failing-test, size/XS, approved, cncf-cla: yes

#1175 fix: switch base image to fix CVEs
  pkg/azurefileplugin/Dockerfile
Labels: ok-to-test, size/XS, lgtm, approved, cncf-cla: yes

#1178 chore: remove dependency on golang.org/x/text specific version
  go.mod
  go.sum
  vendor/golang.org/x/text/internal/language/compact/language.go
  vendor/golang.org/x/text/internal/language/language.go
  vendor/golang.org/x/text/internal/language/lookup.go
  vendor/golang.org/x/text/language/go1_1.go
  vendor/golang.org/x/text/language/go1_2.go
  vendor/golang.org/x/text/language/language.go
  vendor/golang.org/x/text/language/parse.go
  vendor/golang.org/x/text/runes/runes.go
  vendor/golang.org/x/text/unicode/bidi/trieval.go
  vendor/modules.txt
Labels: kind/cleanup, size/M, approved, cncf-cla: yes

#1179 feat: append help link when there is mount error
  pkg/azurefile/azurefile.go
  pkg/azurefile/nodeserver.go
  pkg/azurefileplugin/main.go
Labels: kind/feature, size/S, approved, cncf-cla: yes

#1180 doc: cut v1.26.0 release
  README.md
  charts/README.md
  charts/index.yaml
  charts/latest/azurefile-csi-driver-v0.0.0.tgz
  charts/v1.26.0/azurefile-csi-driver-v1.26.0.tgz
  charts/v1.26.0/azurefile-csi-driver/Chart.yaml
  charts/v1.26.0/azurefile-csi-driver/templates/NOTES.txt
  charts/v1.26.0/azurefile-csi-driver/templates/_helpers.tpl
  charts/v1.26.0/azurefile-csi-driver/templates/crd-csi-snapshot.yaml
  charts/v1.26.0/azurefile-csi-driver/templates/csi-azurefile-controller.yaml
  charts/v1.26.0/azurefile-csi-driver/templates/csi-azurefile-driver.yaml
  charts/v1.26.0/azurefile-csi-driver/templates/csi-azurefile-node-windows.yaml
  charts/v1.26.0/azurefile-csi-driver/templates/csi-azurefile-node.yaml
  charts/v1.26.0/azurefile-csi-driver/templates/csi-snapshot-controller.yaml
  charts/v1.26.0/azurefile-csi-driver/templates/rbac-csi-azurefile-controller.yaml
  charts/v1.26.0/azurefile-csi-driver/templates/rbac-csi-azurefile-node.yaml
  charts/v1.26.0/azurefile-csi-driver/templates/rbac-csi-snapshot-controller.yaml
  charts/v1.26.0/azurefile-csi-driver/templates/serviceaccount-csi-azurefile-controller.yaml
  charts/v1.26.0/azurefile-csi-driver/templates/serviceaccount-csi-azurefile-node.yaml
  charts/v1.26.0/azurefile-csi-driver/templates/serviceaccount-csi-snapshot-controller.yaml
  charts/v1.26.0/azurefile-csi-driver/values.yaml
  deploy/v1.26.0/crd-csi-snapshot.yaml
  deploy/v1.26.0/csi-azurefile-controller.yaml
  deploy/v1.26.0/csi-azurefile-driver.yaml
  deploy/v1.26.0/csi-azurefile-node-windows.yaml
  deploy/v1.26.0/csi-azurefile-node.yaml
  deploy/v1.26.0/csi-snapshot-controller.yaml
  deploy/v1.26.0/rbac-csi-azurefile-controller.yaml
  deploy/v1.26.0/rbac-csi-azurefile-node.yaml
  deploy/v1.26.0/rbac-csi-snapshot-controller.yaml
  docs/install-azurefile-csi-driver.md
  docs/install-csi-driver-v1.26.0.md
Labels: kind/documentation, approved, cncf-cla: yes, size/XXL

#1188 fix: remove forceUmount and lazyUmount
  pkg/azurefile/azure_common_linux.go
  pkg/mounter/safe_mounter_unix.go
Labels: kind/bug, size/M, approved, cncf-cla: yes

#1192 doc: cut v1.26.1 release
  README.md
  charts/README.md
  charts/index.yaml
  charts/latest/azurefile-csi-driver-v0.0.0.tgz
  charts/v1.26.1/azurefile-csi-driver-v1.26.1.tgz
  charts/v1.26.1/azurefile-csi-driver/Chart.yaml
  charts/v1.26.1/azurefile-csi-driver/templates/NOTES.txt
  charts/v1.26.1/azurefile-csi-driver/templates/_helpers.tpl
  charts/v1.26.1/azurefile-csi-driver/templates/crd-csi-snapshot.yaml
  charts/v1.26.1/azurefile-csi-driver/templates/csi-azurefile-controller.yaml
  charts/v1.26.1/azurefile-csi-driver/templates/csi-azurefile-driver.yaml
  charts/v1.26.1/azurefile-csi-driver/templates/csi-azurefile-node-windows.yaml
  charts/v1.26.1/azurefile-csi-driver/templates/csi-azurefile-node.yaml
  charts/v1.26.1/azurefile-csi-driver/templates/csi-snapshot-controller.yaml
  charts/v1.26.1/azurefile-csi-driver/templates/rbac-csi-azurefile-controller.yaml
  charts/v1.26.1/azurefile-csi-driver/templates/rbac-csi-azurefile-node.yaml
  charts/v1.26.1/azurefile-csi-driver/templates/rbac-csi-snapshot-controller.yaml
  charts/v1.26.1/azurefile-csi-driver/templates/serviceaccount-csi-azurefile-controller.yaml
  charts/v1.26.1/azurefile-csi-driver/templates/serviceaccount-csi-azurefile-node.yaml
  charts/v1.26.1/azurefile-csi-driver/templates/serviceaccount-csi-snapshot-controller.yaml
  charts/v1.26.1/azurefile-csi-driver/values.yaml
  deploy/v1.26.1/crd-csi-snapshot.yaml
  deploy/v1.26.1/csi-azurefile-controller.yaml
  deploy/v1.26.1/csi-azurefile-driver.yaml
  deploy/v1.26.1/csi-azurefile-node-windows.yaml
  deploy/v1.26.1/csi-azurefile-node.yaml
  deploy/v1.26.1/csi-snapshot-controller.yaml
  deploy/v1.26.1/rbac-csi-azurefile-controller.yaml
  deploy/v1.26.1/rbac-csi-azurefile-node.yaml
  deploy/v1.26.1/rbac-csi-snapshot-controller.yaml
  docs/install-azurefile-csi-driver.md
  docs/install-csi-driver-v1.26.1.md
Labels: kind/documentation, approved, cncf-cla: yes, size/XXL

#1196 fix: CVE-2022-41723
  go.mod
  go.sum
  vendor/golang.org/x/net/html/parse.go
  vendor/golang.org/x/net/html/token.go
  vendor/golang.org/x/net/http2/flow.go
  vendor/golang.org/x/net/http2/frame.go
  vendor/golang.org/x/net/http2/hpack/hpack.go
  vendor/golang.org/x/net/http2/server.go
  vendor/golang.org/x/net/http2/transport.go
  vendor/golang.org/x/net/trace/histogram.go
  vendor/golang.org/x/sys/cpu/cpu_gccgo_x86.c
  vendor/golang.org/x/sys/cpu/endian_big.go
  vendor/golang.org/x/sys/cpu/endian_little.go
  vendor/golang.org/x/sys/unix/gccgo_c.c
  vendor/golang.org/x/sys/unix/syscall_darwin.go
  vendor/golang.org/x/sys/unix/syscall_freebsd_386.go
  vendor/golang.org/x/sys/unix/syscall_freebsd_amd64.go
  vendor/golang.org/x/sys/unix/syscall_freebsd_arm.go
  vendor/golang.org/x/sys/unix/syscall_freebsd_arm64.go
  vendor/golang.org/x/sys/unix/syscall_freebsd_riscv64.go
  vendor/golang.org/x/sys/unix/syscall_linux.go
  vendor/golang.org/x/sys/unix/syscall_unix.go
  vendor/golang.org/x/sys/unix/timestruct.go
  vendor/golang.org/x/sys/unix/xattr_bsd.go
  vendor/golang.org/x/sys/unix/zerrors_linux.go
  vendor/golang.org/x/sys/unix/zerrors_linux_386.go
  vendor/golang.org/x/sys/unix/zerrors_linux_amd64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_arm.go
  vendor/golang.org/x/sys/unix/zerrors_linux_arm64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_loong64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mips.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mips64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mips64le.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mipsle.go
  vendor/golang.org/x/sys/unix/zerrors_linux_ppc.go
  vendor/golang.org/x/sys/unix/zerrors_linux_ppc64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_ppc64le.go
  vendor/golang.org/x/sys/unix/zerrors_linux_riscv64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_s390x.go
  vendor/golang.org/x/sys/unix/zerrors_linux_sparc64.go
  vendor/golang.org/x/sys/unix/zsyscall_linux.go
  vendor/golang.org/x/sys/unix/ztypes_linux.go
  vendor/golang.org/x/sys/windows/syscall_windows.go
  vendor/modules.txt
Labels: kind/bug, size/XL, approved, cncf-cla: yes

#1195 doc: remove accountAccessTier in doc since it's only for blob
  docs/driver-parameters.md
Labels: kind/documentation, size/XS, approved, cncf-cla: yes

#1197 cleanup: remove metrics-address on driver daemonset on the node
  charts/README.md
  charts/latest/azurefile-csi-driver-v0.0.0.tgz
  charts/latest/azurefile-csi-driver/templates/csi-azurefile-node-windows.yaml
  charts/latest/azurefile-csi-driver/templates/csi-azurefile-node.yaml
  charts/latest/azurefile-csi-driver/values.yaml
  deploy/csi-azurefile-node-windows.yaml
  deploy/csi-azurefile-node.yaml
  pkg/azurefileplugin/main.go
Labels: kind/cleanup, size/S, approved, cncf-cla: yes

#1198 Pin k8s.io/dynamic-resource-allocation to v0.26.0
  go.mod
  vendor/modules.txt
Labels: kind/cleanup, size/XS, lgtm, approved, cncf-cla: yes

#1199 test: add "go list" check
  hack/verify-gomod.sh
Labels: size/XS, approved, cncf-cla: yes, kind/test
