Repository kubernetes-sigs/azurefile-csi-driver, pull requests merged in 2023-04, with the labels that each got.

#1209 doc: refine subcriptionID parameter doc
  docs/driver-parameters.md
Labels: kind/documentation, size/XS, approved, cncf-cla: yes

#1212 tes: fix golint action failure
  .github/workflows/static.yaml
  pkg/azurefile/nodeserver.go
Labels: size/S, kind/failing-test, approved, cncf-cla: yes

#1210 feat: enable securityContext.seccompProfile
  charts/latest/azurefile-csi-driver-v0.0.0.tgz
  charts/latest/azurefile-csi-driver/templates/csi-azurefile-node-windows.yaml
  charts/latest/azurefile-csi-driver/templates/csi-azurefile-node.yaml
  deploy/csi-azurefile-node-windows.yaml
  deploy/csi-azurefile-node.yaml
Labels: kind/feature, size/S, approved, cncf-cla: yes

#1216 test: fix restart_driver_daemonset script
  test/utils/restart_driver_daemonset.sh
Labels: size/S, kind/failing-test, approved, cncf-cla: yes

#1217 feat: add chart config value enableRegistrationProbe
  Makefile
  charts/README.md
  charts/latest/azurefile-csi-driver-v0.0.0.tgz
  charts/latest/azurefile-csi-driver/templates/csi-azurefile-node-windows.yaml
  charts/latest/azurefile-csi-driver/templates/csi-azurefile-node.yaml
  charts/latest/azurefile-csi-driver/values.yaml
Labels: kind/bug, size/S, approved, cncf-cla: yes

#1220 doc: add nconnect mount options in NFSv4.1 example
  deploy/example/nfs/README.md
  deploy/example/pv-azurefile-nfs.yaml
  deploy/example/storageclass-azurefile-nfs.yaml
  test/e2e/dynamic_provisioning_test.go
Labels: size/S, kind/documentation, approved, cncf-cla: yes

#1223 cleanup: replace deprecated ioutil method
  pkg/azurefile/azure_test.go
  pkg/azurefile/azurefile_test.go
  pkg/azurefile/nodeserver.go
  test/utils/credentials/credentials.go
  test/utils/credentials/credentials_test.go
Labels: kind/cleanup, ok-to-test, size/S, lgtm, approved, cncf-cla: yes

#1225 feat: add selectRandomMatchingAccount parameter in storage class
  docs/driver-parameters.md
  go.mod
  go.sum
  pkg/azurefile/azurefile.go
  pkg/azurefile/controllerserver.go
  pkg/azurefile/controllerserver_test.go
  test/e2e/dynamic_provisioning_test.go
  vendor/modules.txt
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_managedDiskController.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_storageaccount.go
Labels: kind/feature, size/M, lgtm, approved, cncf-cla: yes

#1230 [release-1.24] fix: debian image CVEs
  pkg/azurefileplugin/Dockerfile
Labels: kind/bug, size/XS, approved, cncf-cla: yes

#1229 chore: upgrade CSI driver sidecar image versions
  charts/README.md
  charts/latest/azurefile-csi-driver-v0.0.0.tgz
  charts/latest/azurefile-csi-driver/values.yaml
  deploy/csi-azurefile-controller.yaml
  deploy/csi-azurefile-node-windows.yaml
  deploy/csi-azurefile-node.yaml
Labels: kind/feature, size/M, approved, cncf-cla: yes
