Repository kubernetes-sigs/azurefile-csi-driver, pull requests merged in 2023-01, with the labels that each got.

#1146 fix: use force unmount to fix unmount NFS volume stuck issue
  go.mod
  go.sum
  pkg/azurefile/azure_common_linux.go
  pkg/mounter/safe_mounter_unix.go
  vendor/k8s.io/mount-utils/mount_linux.go
  vendor/modules.txt
Labels: kind/bug, size/M, approved, cncf-cla: yes

#1155 fix: set ForceAttemptHTTP2 as false to increase ARM throttling limit
  go.mod
  go.sum
  vendor/modules.txt
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azureclients/armclient/azure_armclient.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/config/azure_ratelimit.go
Labels: kind/bug, size/M, approved, cncf-cla: yes

#1159 doc: update install doc
  README.md
  docs/install-azurefile-csi-driver.md
Labels: size/S, kind/documentation, approved, cncf-cla: yes

#1158 fix: target is busy unmount failure
  pkg/azurefile/azure_common_linux.go
Labels: kind/bug, size/S, approved, cncf-cla: yes

#1160 cleanup: fix umount failure logging
  pkg/azurefile/azure_common_linux.go
Labels: kind/cleanup, size/XS, approved, cncf-cla: yes

#1162 doc: cut v1.25.0 release
  README.md
  charts/README.md
  charts/index.yaml
  charts/latest/azurefile-csi-driver-v0.0.0.tgz
  charts/v1.25.0/azurefile-csi-driver-v1.25.0.tgz
  charts/v1.25.0/azurefile-csi-driver/Chart.yaml
  charts/v1.25.0/azurefile-csi-driver/templates/NOTES.txt
  charts/v1.25.0/azurefile-csi-driver/templates/_helpers.tpl
  charts/v1.25.0/azurefile-csi-driver/templates/crd-csi-snapshot.yaml
  charts/v1.25.0/azurefile-csi-driver/templates/csi-azurefile-controller.yaml
  charts/v1.25.0/azurefile-csi-driver/templates/csi-azurefile-driver.yaml
  charts/v1.25.0/azurefile-csi-driver/templates/csi-azurefile-node-windows.yaml
  charts/v1.25.0/azurefile-csi-driver/templates/csi-azurefile-node.yaml
  charts/v1.25.0/azurefile-csi-driver/templates/csi-snapshot-controller.yaml
  charts/v1.25.0/azurefile-csi-driver/templates/rbac-csi-azurefile-controller.yaml
  charts/v1.25.0/azurefile-csi-driver/templates/rbac-csi-azurefile-node.yaml
  charts/v1.25.0/azurefile-csi-driver/templates/rbac-csi-snapshot-controller.yaml
  charts/v1.25.0/azurefile-csi-driver/templates/serviceaccount-csi-azurefile-controller.yaml
  charts/v1.25.0/azurefile-csi-driver/templates/serviceaccount-csi-azurefile-node.yaml
  charts/v1.25.0/azurefile-csi-driver/templates/serviceaccount-csi-snapshot-controller.yaml
  charts/v1.25.0/azurefile-csi-driver/values.yaml
  deploy/v1.25.0/crd-csi-snapshot.yaml
  deploy/v1.25.0/csi-azurefile-controller.yaml
  deploy/v1.25.0/csi-azurefile-driver.yaml
  deploy/v1.25.0/csi-azurefile-node-windows.yaml
  deploy/v1.25.0/csi-azurefile-node.yaml
  deploy/v1.25.0/csi-snapshot-controller.yaml
  deploy/v1.25.0/rbac-csi-azurefile-controller.yaml
  deploy/v1.25.0/rbac-csi-azurefile-node.yaml
  deploy/v1.25.0/rbac-csi-snapshot-controller.yaml
  docs/install-azurefile-csi-driver.md
  docs/install-csi-driver-v1.25.0.md
  test/e2e/suite_test.go
Labels: kind/documentation, approved, cncf-cla: yes, size/XXL

#1165 docs: update storage class definition for optional cross-subscription config
  deploy/example/storageclass-azurefile-existing-share.yaml
Labels: ok-to-test, kind/documentation, size/XS, lgtm, approved, cncf-cla: yes

#1164 doc: refine doc
  deploy/example/pv-azurefile-csi.yaml
  deploy/example/pv-azurefile-nfs.yaml
  docs/driver-parameters.md
Labels: size/S, kind/documentation, approved, cncf-cla: yes

#1166 fix: make account search backward compatible
  go.mod
  go.sum
  vendor/modules.txt
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/consts/consts.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_backoff.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_loadbalancer.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_loadbalancer_backendpool.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_storageaccount.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_wrap.go
Labels: kind/bug, size/L, approved, cncf-cla: yes

#1167 doc: cut v1.25.1 release
  README.md
  charts/README.md
  charts/index.yaml
  charts/latest/azurefile-csi-driver-v0.0.0.tgz
  charts/v1.25.1/azurefile-csi-driver-v1.25.1.tgz
  charts/v1.25.1/azurefile-csi-driver/Chart.yaml
  charts/v1.25.1/azurefile-csi-driver/templates/NOTES.txt
  charts/v1.25.1/azurefile-csi-driver/templates/_helpers.tpl
  charts/v1.25.1/azurefile-csi-driver/templates/crd-csi-snapshot.yaml
  charts/v1.25.1/azurefile-csi-driver/templates/csi-azurefile-controller.yaml
  charts/v1.25.1/azurefile-csi-driver/templates/csi-azurefile-driver.yaml
  charts/v1.25.1/azurefile-csi-driver/templates/csi-azurefile-node-windows.yaml
  charts/v1.25.1/azurefile-csi-driver/templates/csi-azurefile-node.yaml
  charts/v1.25.1/azurefile-csi-driver/templates/csi-snapshot-controller.yaml
  charts/v1.25.1/azurefile-csi-driver/templates/rbac-csi-azurefile-controller.yaml
  charts/v1.25.1/azurefile-csi-driver/templates/rbac-csi-azurefile-node.yaml
  charts/v1.25.1/azurefile-csi-driver/templates/rbac-csi-snapshot-controller.yaml
  charts/v1.25.1/azurefile-csi-driver/templates/serviceaccount-csi-azurefile-controller.yaml
  charts/v1.25.1/azurefile-csi-driver/templates/serviceaccount-csi-azurefile-node.yaml
  charts/v1.25.1/azurefile-csi-driver/templates/serviceaccount-csi-snapshot-controller.yaml
  charts/v1.25.1/azurefile-csi-driver/values.yaml
  deploy/v1.25.1/crd-csi-snapshot.yaml
  deploy/v1.25.1/csi-azurefile-controller.yaml
  deploy/v1.25.1/csi-azurefile-driver.yaml
  deploy/v1.25.1/csi-azurefile-node-windows.yaml
  deploy/v1.25.1/csi-azurefile-node.yaml
  deploy/v1.25.1/csi-snapshot-controller.yaml
  deploy/v1.25.1/rbac-csi-azurefile-controller.yaml
  deploy/v1.25.1/rbac-csi-azurefile-node.yaml
  deploy/v1.25.1/rbac-csi-snapshot-controller.yaml
  docs/install-azurefile-csi-driver.md
  docs/install-csi-driver-v1.25.1.md
Labels: kind/documentation, approved, cncf-cla: yes, size/XXL

#1170 doc: Fix URL to azure-files-csi driver doc in README.md
  README.md
Labels: ok-to-test, kind/documentation, size/XS, lgtm, approved, cncf-cla: yes

#1172 fix: incorrect driver version in CSIDriver
  deploy/csi-azurefile-driver.yaml
  deploy/v1.21.0/csi-azurefile-driver.yaml
  deploy/v1.22.0/csi-azurefile-driver.yaml
  deploy/v1.23.0/csi-azurefile-driver.yaml
  deploy/v1.24.0/csi-azurefile-driver.yaml
  deploy/v1.25.0/csi-azurefile-driver.yaml
  deploy/v1.25.1/csi-azurefile-driver.yaml
Labels: kind/bug, size/S, approved, cncf-cla: yes
