Repository kubernetes-sigs/azurefile-csi-driver, pull requests merged in 2023-12, with the labels that each got.

#1621 test: upgrade to ginko/v2 in external e2e tests
  test/external-e2e/run.sh
Labels: size/XS, approved, cncf-cla: yes, kind/test

#1622 cleanup: go.mod
  go.mod
  go.sum
  vendor/modules.txt
Labels: kind/cleanup, approved, cncf-cla: yes, size/XXL

#1626 fix: CVE-2023-48795
  .trivyignore
  go.mod
  go.sum
  vendor/golang.org/x/crypto/ssh/channel.go
  vendor/golang.org/x/crypto/ssh/client.go
  vendor/golang.org/x/crypto/ssh/handshake.go
  vendor/golang.org/x/crypto/ssh/server.go
  vendor/golang.org/x/crypto/ssh/transport.go
  vendor/modules.txt
Labels: kind/bug, size/L, approved, cncf-cla: yes

#1631 doc: fix volume cloning doc
  deploy/example/cloning/README.md
Labels: kind/documentation, size/XS, approved, cncf-cla: yes

#1630 [release-1.26] fix: CVE-2023-48795
  go.mod
  go.sum
  vendor/golang.org/x/crypto/ssh/channel.go
  vendor/golang.org/x/crypto/ssh/client.go
  vendor/golang.org/x/crypto/ssh/client_auth.go
  vendor/golang.org/x/crypto/ssh/common.go
  vendor/golang.org/x/crypto/ssh/handshake.go
  vendor/golang.org/x/crypto/ssh/server.go
  vendor/golang.org/x/crypto/ssh/tcpip.go
  vendor/golang.org/x/crypto/ssh/transport.go
  vendor/golang.org/x/sys/unix/fcntl.go
  vendor/golang.org/x/sys/unix/ioctl_linux.go
  vendor/golang.org/x/sys/unix/mkerrors.sh
  vendor/golang.org/x/sys/unix/syscall_bsd.go
  vendor/golang.org/x/sys/unix/syscall_linux.go
  vendor/golang.org/x/sys/unix/syscall_openbsd.go
  vendor/golang.org/x/sys/unix/syscall_solaris.go
  vendor/golang.org/x/sys/unix/syscall_zos_s390x.go
  vendor/golang.org/x/sys/unix/zerrors_linux.go
  vendor/golang.org/x/sys/unix/zsyscall_linux.go
  vendor/golang.org/x/sys/unix/zsyscall_openbsd_386.go
  vendor/golang.org/x/sys/unix/zsyscall_openbsd_386.s
  vendor/golang.org/x/sys/unix/zsyscall_openbsd_amd64.go
  vendor/golang.org/x/sys/unix/zsyscall_openbsd_amd64.s
  vendor/golang.org/x/sys/unix/zsyscall_openbsd_arm.go
  vendor/golang.org/x/sys/unix/zsyscall_openbsd_arm.s
  vendor/golang.org/x/sys/unix/zsyscall_openbsd_arm64.go
  vendor/golang.org/x/sys/unix/zsyscall_openbsd_arm64.s
  vendor/golang.org/x/sys/unix/zsyscall_openbsd_mips64.go
  vendor/golang.org/x/sys/unix/zsyscall_openbsd_mips64.s
  vendor/golang.org/x/sys/unix/zsyscall_openbsd_ppc64.go
  vendor/golang.org/x/sys/unix/zsyscall_openbsd_ppc64.s
  vendor/golang.org/x/sys/unix/zsyscall_openbsd_riscv64.go
  vendor/golang.org/x/sys/unix/zsyscall_openbsd_riscv64.s
  vendor/golang.org/x/sys/unix/ztypes_linux.go
  vendor/golang.org/x/sys/windows/syscall_windows.go
  vendor/golang.org/x/sys/windows/zsyscall_windows.go
  vendor/modules.txt
Labels: kind/bug, size/XL, approved, cncf-cla: yes

#1634 Refactor: remove grpc wrapper
  pkg/azurefile/azurefile.go
  pkg/azurefile/azurefile_test.go
  pkg/azurefileplugin/main.go
  pkg/csi-common/server.go
  pkg/csi-common/server_test.go
  pkg/csi-common/utils.go
  pkg/csi-common/utils_test.go
  test/e2e/suite_test.go
Labels: size/L, kind/cleanup, lgtm, cncf-cla: yes

#1638 Refactor: move flag option to azurefile package
  pkg/azurefile/azurefile.go
  pkg/azurefile/azurefile_options.go
  pkg/azurefile/azurefile_options_test.go
  pkg/azurefile/azurefile_test.go
  pkg/azurefileplugin/main.go
  test/e2e/suite_test.go
Labels: size/L, kind/cleanup, lgtm, approved, cncf-cla: yes

#1639 feat: upgrade azcopy to v10.22.1 for volume clone feature
  .trivyignore
  pkg/azurefileplugin/Dockerfile
Labels: kind/feature, size/XS, approved, cncf-cla: yes

#1642 fix: reduce mount lock to avoid volumeID collision issue
  pkg/azurefile/nodeserver.go
  pkg/azurefile/nodeserver_test.go
Labels: kind/bug, size/S, approved, cncf-cla: yes

#1645 test: always use latest azcopy version in sanity test
  test/sanity/run-test.sh
Labels: size/S, approved, cncf-cla: yes, kind/test

#1566 feat: support workload identity setting in static PV mount
  charts/latest/azurefile-csi-driver-v0.0.0.tgz
  charts/latest/azurefile-csi-driver/templates/csi-azurefile-driver.yaml
  docs/workload-identity-deploy-csi-driver.md
  docs/workload-identity-static-pv-mount.md
  go.mod
  go.sum
  pkg/azurefile/azurefile.go
  pkg/azurefile/nodeserver.go
  pkg/azurefile/nodeserver_test.go
  vendor/modules.txt
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azureclients/diskclient/mockdiskclient/interface.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azureclients/fileclient/mockfileclient/interface.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azureclients/interfaceclient/mockinterfaceclient/interface.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azureclients/loadbalancerclient/mockloadbalancerclient/interface.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azureclients/privatelinkserviceclient/mockprivatelinkserviceclient/interface.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azureclients/publicipclient/mockpublicipclient/interface.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azureclients/routeclient/mockrouteclient/interface.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azureclients/routetableclient/mockroutetableclient/interface.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azureclients/securitygroupclient/mocksecuritygroupclient/interface.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azureclients/snapshotclient/mocksnapshotclient/interface.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azureclients/storageaccountclient/mockstorageaccountclient/interface.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azureclients/subnetclient/mocksubnetclient/interface.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azureclients/vmclient/mockvmclient/interface.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azureclients/vmssclient/mockvmssclient/interface.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azureclients/vmssvmclient/mockvmssvmclient/interface.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_controller_common.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_loadbalancer.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_loadbalancer_healthprobe.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_storageaccount.go
Labels: kind/feature, size/L, lgtm, approved, cncf-cla: yes

#1648 fix: mountPermission settting issue due to case insensitive parameter
  pkg/azurefile/nodeserver.go
  pkg/azurefile/nodeserver_test.go
  pkg/azurefile/utils.go
  pkg/azurefile/utils_test.go
Labels: kind/bug, size/L, approved, cncf-cla: yes

#1649 [release-1.29] fix: mountPermission settting issue due to case insensitive parameter
  pkg/azurefile/nodeserver.go
  pkg/azurefile/utils.go
  pkg/azurefile/utils_test.go
Labels: kind/bug, size/M, approved, cncf-cla: yes

#1650 [release-1.28] fix: mountPermission settting issue due to case insensitive parameter
  pkg/azurefile/nodeserver.go
  pkg/azurefile/utils.go
  pkg/azurefile/utils_test.go
Labels: kind/bug, size/M, approved, cncf-cla: yes
