Repository kubernetes-sigs/azurefile-csi-driver, pull requests merged in 2023-08, with the labels that each got.

#1345 fix: stop resize file share when account limit is exceeded
  pkg/azurefile/azurefile.go
  pkg/azurefile/controllerserver.go
Labels: kind/bug, size/S, approved, cncf-cla: yes

#1347 [release-1.24] fix: stop resize file share when account limit is exceeded
  pkg/azurefile/azurefile.go
  pkg/azurefile/controllerserver.go
Labels: kind/bug, size/S, approved, cncf-cla: yes

#1349 [release-1.26] fix: stop resize file share when account limit is exceeded
  pkg/azurefile/azurefile.go
  pkg/azurefile/controllerserver.go
Labels: kind/bug, size/S, approved, cncf-cla: yes

#1348 [release-1.27] fix: stop resize file share when account limit is exceeded
  pkg/azurefile/azurefile.go
  pkg/azurefile/controllerserver.go
Labels: kind/bug, size/S, approved, cncf-cla: yes

#1361 test: run one e2e test using smb protocol
  test/e2e/dynamic_provisioning_test.go
Labels: kind/failing-test, size/XS, approved, cncf-cla: yes

#1362 feat: add accountQuota parameter
  docs/driver-parameters.md
  go.mod
  pkg/azurefile/azurefile.go
  pkg/azurefile/azurefile_test.go
  pkg/azurefile/controllerserver.go
  pkg/azurefile/controllerserver_test.go
  test/e2e/dynamic_provisioning_test.go
Labels: kind/feature, size/L, approved, cncf-cla: yes

#1364 [release-1.28] feat: add accountQuota parameter
  docs/driver-parameters.md
  go.mod
  pkg/azurefile/azurefile.go
  pkg/azurefile/azurefile_test.go
  pkg/azurefile/controllerserver.go
  pkg/azurefile/controllerserver_test.go
  test/e2e/dynamic_provisioning_test.go
Labels: kind/feature, size/L, approved, cncf-cla: yes

#1363 feat(helm) Allow setting an alternate name of the configmap for the azure credential path
  charts/README.md
  charts/latest/azurefile-csi-driver-v0.0.0.tgz
  charts/latest/azurefile-csi-driver/templates/csi-azurefile-controller.yaml
  charts/latest/azurefile-csi-driver/templates/csi-azurefile-node-windows-hostprocess.yaml
  charts/latest/azurefile-csi-driver/templates/csi-azurefile-node-windows.yaml
  charts/latest/azurefile-csi-driver/templates/csi-azurefile-node.yaml
  charts/latest/azurefile-csi-driver/values.yaml
Labels: kind/feature, size/S, lgtm, approved, cncf-cla: yes

#1365 [release-1.27] feat: add accountQuota parameter
  docs/driver-parameters.md
  go.mod
  pkg/azurefile/azurefile.go
  pkg/azurefile/azurefile_test.go
  pkg/azurefile/controllerserver.go
  pkg/azurefile/controllerserver_test.go
  test/e2e/dynamic_provisioning_test.go
Labels: kind/feature, size/L, approved, cncf-cla: yes

#1366 [release-1.26] feat: add accountQuota parameter
  docs/driver-parameters.md
  go.mod
  pkg/azurefile/azurefile.go
  pkg/azurefile/azurefile_test.go
  pkg/azurefile/controllerserver.go
  pkg/azurefile/controllerserver_test.go
Labels: kind/feature, size/L, approved, cncf-cla: yes

#1337 fix: incorrect volume usage on Windows node with host process deployment
  go.mod
  pkg/azurefile/azure_common_darwin.go
  pkg/azurefile/azure_common_linux.go
  pkg/azurefile/azure_common_windows.go
  pkg/azurefile/nodeserver.go
  pkg/azurefile/nodeserver_test.go
Labels: kind/bug, size/L, approved, cncf-cla: yes

#1371 [release-1.28] fix: incorrect volume usage on Windows node with host process deployment
  go.mod
  pkg/azurefile/azure_common_darwin.go
  pkg/azurefile/azure_common_linux.go
  pkg/azurefile/azure_common_windows.go
  pkg/azurefile/nodeserver.go
  pkg/azurefile/nodeserver_test.go
Labels: kind/bug, size/L, approved, cncf-cla: yes

#1376 test: fix test failure on MacOS
  pkg/azurefile/azurefile_test.go
  pkg/azurefile/controllerserver_test.go
Labels: size/S, kind/failing-test, approved, cncf-cla: yes

#1392 fix: upgrade base image to alpine 3.18 to fix DNS issue
  pkg/azurefileplugin/Dockerfile
Labels: kind/bug, size/XS, approved, cncf-cla: yes

#1409 fix: delay removing skipMatchingTag when account is full
  pkg/azurefile/azurefile.go
  pkg/azurefile/controllerserver.go
  pkg/azurefileplugin/main.go
Labels: kind/bug, size/S, approved, cncf-cla: yes

#1414 [release-1.24] fix: delay removing skipMatchingTag when account is full
  pkg/azurefile/azurefile.go
  pkg/azurefile/controllerserver.go
  pkg/azurefileplugin/main.go
Labels: kind/bug, size/S, approved, cncf-cla: yes

#1412 [release-1.27] fix: delay removing skipMatchingTag when account is full
  pkg/azurefile/azurefile.go
  pkg/azurefile/controllerserver.go
  pkg/azurefileplugin/main.go
Labels: kind/bug, size/S, approved, cncf-cla: yes

#1413 [release-1.26] fix: delay removing skipMatchingTag when account is full
  pkg/azurefile/azurefile.go
  pkg/azurefile/controllerserver.go
  pkg/azurefileplugin/main.go
Labels: kind/bug, size/S, approved, cncf-cla: yes
