Repository kubernetes-sigs/azurefile-csi-driver, pull requests merged in 2024-04, with the labels that each got.

#1795 fix: panic when cloud config is not set
  pkg/azurefile/azurefile.go
Labels: kind/bug, size/XS, approved, cncf-cla: yes

#1805 [release-1.30] feat: use new restricted liveness probe endpoint
  charts/latest/azurefile-csi-driver-v1.30.0.tgz
  charts/latest/azurefile-csi-driver/templates/csi-azurefile-controller.yaml
  charts/latest/azurefile-csi-driver/templates/csi-azurefile-node-windows.yaml
  charts/latest/azurefile-csi-driver/templates/csi-azurefile-node.yaml
  deploy/csi-azurefile-controller.yaml
  deploy/csi-azurefile-node-windows.yaml
  deploy/csi-azurefile-node.yaml
Labels: kind/feature, size/M, approved, cncf-cla: yes

#1804 feat: use new restricted liveness probe endpoint
  charts/latest/azurefile-csi-driver-v0.0.0.tgz
  charts/latest/azurefile-csi-driver/templates/csi-azurefile-controller.yaml
  charts/latest/azurefile-csi-driver/templates/csi-azurefile-node-windows.yaml
  charts/latest/azurefile-csi-driver/templates/csi-azurefile-node.yaml
  charts/v1.29.2/azurefile-csi-driver-v1.29.2.tgz
  charts/v1.29.2/azurefile-csi-driver/templates/csi-azurefile-controller.yaml
  charts/v1.29.2/azurefile-csi-driver/templates/csi-azurefile-node-windows.yaml
  charts/v1.29.2/azurefile-csi-driver/templates/csi-azurefile-node.yaml
  charts/v1.30.0/azurefile-csi-driver-v1.30.0.tgz
  charts/v1.30.0/azurefile-csi-driver/templates/csi-azurefile-controller.yaml
  charts/v1.30.0/azurefile-csi-driver/templates/csi-azurefile-node-windows.yaml
  charts/v1.30.0/azurefile-csi-driver/templates/csi-azurefile-node.yaml
  deploy/csi-azurefile-controller.yaml
  deploy/csi-azurefile-node-windows.yaml
  deploy/csi-azurefile-node.yaml
  deploy/v1.29.2/csi-azurefile-controller.yaml
  deploy/v1.29.2/csi-azurefile-node-windows.yaml
  deploy/v1.29.2/csi-azurefile-node.yaml
  deploy/v1.30.0/csi-azurefile-controller.yaml
  deploy/v1.30.0/csi-azurefile-node-windows.yaml
  deploy/v1.30.0/csi-azurefile-node.yaml
Labels: kind/feature, size/L, approved, cncf-cla: yes

#1807 [release-1.29] feat: use new restricted liveness probe endpoint
  charts/latest/azurefile-csi-driver-v1.29.4.tgz
  charts/latest/azurefile-csi-driver/templates/csi-azurefile-controller.yaml
  charts/latest/azurefile-csi-driver/templates/csi-azurefile-node-windows.yaml
  charts/latest/azurefile-csi-driver/templates/csi-azurefile-node.yaml
  deploy/csi-azurefile-controller.yaml
  deploy/csi-azurefile-node-windows.yaml
  deploy/csi-azurefile-node.yaml
Labels: kind/feature, size/M, approved, cncf-cla: yes

#1809 [release-1.28] feat: use new restricted liveness probe endpoint
  charts/latest/azurefile-csi-driver-v1.28.9.tgz
  charts/latest/azurefile-csi-driver/templates/csi-azurefile-controller.yaml
  charts/latest/azurefile-csi-driver/templates/csi-azurefile-node-windows.yaml
  charts/latest/azurefile-csi-driver/templates/csi-azurefile-node.yaml
  deploy/csi-azurefile-controller.yaml
  deploy/csi-azurefile-node-windows.yaml
  deploy/csi-azurefile-node.yaml
Labels: kind/feature, size/M, approved, cncf-cla: yes

#1812 feat: upgrade to azcopy v10.24.0 for volume clone feature
  .trivyignore
  pkg/azurefileplugin/Dockerfile
  test/sanity/run-test.sh
Labels: kind/feature, size/XS, approved, cncf-cla: yes

#1818 [release-1.28] fix: revert http-endpoint change on windows daemonset
  charts/latest/azurefile-csi-driver-v1.28.9.tgz
  charts/latest/azurefile-csi-driver/templates/csi-azurefile-node-windows.yaml
  deploy/csi-azurefile-node-windows.yaml
Labels: kind/bug, size/S, approved, cncf-cla: yes

#1815 [release-1.30] fix: revert http-endpoint change on windows daemonset
  charts/latest/azurefile-csi-driver-v1.30.1.tgz
  charts/latest/azurefile-csi-driver/templates/csi-azurefile-node-windows.yaml
  deploy/csi-azurefile-node-windows.yaml
Labels: kind/bug, size/S, approved, cncf-cla: yes

#1814 fix: revert http-endpoint change on windows daemonset
  charts/latest/azurefile-csi-driver-v0.0.0.tgz
  charts/latest/azurefile-csi-driver/templates/csi-azurefile-node-windows.yaml
  charts/v1.29.2/azurefile-csi-driver-v1.29.2.tgz
  charts/v1.29.2/azurefile-csi-driver/templates/csi-azurefile-node-windows.yaml
  charts/v1.30.0/azurefile-csi-driver-v1.30.0.tgz
  charts/v1.30.0/azurefile-csi-driver/templates/csi-azurefile-node-windows.yaml
  deploy/csi-azurefile-node-windows.yaml
  deploy/v1.29.2/csi-azurefile-node-windows.yaml
  deploy/v1.30.0/csi-azurefile-node-windows.yaml
Labels: kind/bug, size/M, approved, cncf-cla: yes

#1817 [release-1.29] fix: revert http-endpoint change on windows daemonset
  charts/latest/azurefile-csi-driver-v1.29.4.tgz
  charts/latest/azurefile-csi-driver/templates/csi-azurefile-node-windows.yaml
  deploy/csi-azurefile-node-windows.yaml
Labels: kind/bug, size/S, approved, cncf-cla: yes

#1823 fix: allow http auth in volume clone
  go.mod
  go.sum
  pkg/azurefile/controllerserver.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/storage/azfile/directory/client.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/storage/azfile/file/client.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/storage/azfile/internal/exported/version.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/storage/azfile/sas/query_params.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/storage/azfile/service/client.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/storage/azfile/share/client.go
  vendor/modules.txt
Labels: kind/bug, size/M, approved, cncf-cla: yes

#1825 [release-1.30] fix: allow http auth in volume clone
  go.mod
  go.sum
  pkg/azurefile/controllerserver.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/azcore/CHANGELOG.md
  vendor/github.com/Azure/azure-sdk-for-go/sdk/azcore/internal/pollers/loc/loc.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/azcore/internal/pollers/util.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/azcore/internal/shared/constants.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/azcore/runtime/poller.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/storage/azfile/directory/client.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/storage/azfile/file/client.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/storage/azfile/internal/exported/shared_key_credential.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/storage/azfile/internal/exported/version.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/storage/azfile/internal/shared/batch_transfer.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/storage/azfile/sas/query_params.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/storage/azfile/service/client.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/storage/azfile/share/client.go
  vendor/github.com/AzureAD/microsoft-authentication-library-for-go/apps/confidential/confidential.go
  vendor/github.com/AzureAD/microsoft-authentication-library-for-go/apps/public/public.go
  vendor/github.com/golang-jwt/jwt/v5/ecdsa.go
  vendor/github.com/golang-jwt/jwt/v5/hmac.go
  vendor/golang.org/x/crypto/chacha20/chacha_ppc64le.s
  vendor/golang.org/x/crypto/ssh/server.go
  vendor/golang.org/x/net/http/httpproxy/proxy.go
  vendor/golang.org/x/net/http2/frame.go
  vendor/golang.org/x/net/http2/pipe.go
  vendor/golang.org/x/net/http2/server.go
  vendor/golang.org/x/net/http2/testsync.go
  vendor/golang.org/x/net/http2/transport.go
  vendor/golang.org/x/sys/unix/mmap_nomremap.go
  vendor/golang.org/x/sys/unix/syscall_zos_s390x.go
  vendor/golang.org/x/sys/windows/syscall_windows.go
  vendor/golang.org/x/sys/windows/types_windows.go
  vendor/golang.org/x/sys/windows/zsyscall_windows.go
  vendor/modules.txt
Labels: kind/bug, approved, cncf-cla: yes, size/XXL

#1821 [release-1.29] feat: upgrade to azcopy v10.24.0 for volume clone feature
  .trivyignore
  pkg/azurefileplugin/Dockerfile
  test/sanity/run-test.sh
Labels: kind/feature, size/XS, approved, cncf-cla: yes

#1822 [release-1.28] feat: upgrade to azcopy v10.24.0 for volume clone feature
  .trivyignore
  pkg/azurefileplugin/Dockerfile
  test/sanity/run-test.sh
Labels: kind/feature, size/XS, approved, cncf-cla: yes

#1466 feat: add smb file restore from snapshot
  charts/latest/azurefile-csi-driver-v0.0.0.tgz
  charts/latest/azurefile-csi-driver/templates/csi-azurefile-controller.yaml
  deploy/csi-azurefile-controller.yaml
  deploy/example/snapshot/pvc-azurefile-snapshot-restored.yaml
  pkg/azurefile/azurefile.go
  pkg/azurefile/azurefile_options.go
  pkg/azurefile/controllerserver.go
  pkg/azurefile/controllerserver_test.go
  test/e2e/driver/driver.go
  test/e2e/dynamic_provisioning_test.go
  test/e2e/testsuites/dynamically_provisioned_volume_snapshot_tester.go
  test/e2e/testsuites/specs.go
  test/e2e/testsuites/testsuites.go
  test/sanity/run-test.sh
Labels: kind/feature, ok-to-test, size/XL, lgtm, approved, cncf-cla: yes

#1832 [release-1.29] feat: use cluster identity for using azcopy in volume cloning
  go.mod
  hack/update-mock.sh
  pkg/azurefile/azurefile.go
  pkg/azurefile/controllerserver.go
  pkg/azurefile/controllerserver_test.go
  pkg/util/util.go
  pkg/util/util_mock.go
  pkg/util/util_test.go
Labels: kind/feature, size/L, ok-to-test, cncf-cla: yes

#1833 [release-1.30] feat: add smb file restore from snapshot
  charts/latest/azurefile-csi-driver-v1.30.1.tgz
  charts/latest/azurefile-csi-driver/templates/csi-azurefile-controller.yaml
  deploy/csi-azurefile-controller.yaml
  deploy/example/snapshot/pvc-azurefile-snapshot-restored.yaml
  pkg/azurefile/azurefile.go
  pkg/azurefile/azurefile_options.go
  pkg/azurefile/controllerserver.go
  pkg/azurefile/controllerserver_test.go
  test/e2e/driver/driver.go
  test/e2e/dynamic_provisioning_test.go
  test/e2e/testsuites/dynamically_provisioned_volume_snapshot_tester.go
  test/e2e/testsuites/specs.go
  test/e2e/testsuites/testsuites.go
  test/sanity/run-test.sh
Labels: kind/feature, ok-to-test, size/XL, lgtm, approved, cncf-cla: yes

#1834 [release-1.29] chore: refine sastoken cache
  pkg/azurefile/azurefile.go
  pkg/azurefile/controllerserver.go
  pkg/azurefile/controllerserver_test.go
Labels: size/M, approved, cncf-cla: yes

#1836 test: ignore azcopy CVE-2023-45288
  .trivyignore
Labels: kind/failing-test, size/XS, approved, cncf-cla: yes

#1835 chore: set node_get_volume_stats log level to 6
  go.mod
  go.sum
  pkg/azurefile/nodeserver.go
  vendor/k8s.io/apiserver/pkg/features/kube_features.go
  vendor/k8s.io/apiserver/pkg/storage/cacher/cacher.go
  vendor/k8s.io/apiserver/pkg/storage/cacher/lister_watcher.go
  vendor/k8s.io/apiserver/pkg/storage/cacher/watch_progress.go
  vendor/modules.txt
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azureclients/armclient/azure_armclient.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azureclients/armclient/util.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azureclients/vmssvmclient/azure_vmssvmclient.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/consts/consts.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/metrics/azure_metrics.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_loadbalancer.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_zones.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/loadbalancer/accesscontrol.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/loadbalancer/configuration.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/loadbalancer/iputil/prefix.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/loadbalancer/securitygroup/securitygroup.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/retry/azure_error.go
Labels: size/L, kind/cleanup, approved, cncf-cla: yes

#1838 fix: CVE-2023-45288
  go.mod
  go.sum
  vendor/golang.org/x/crypto/chacha20/chacha_ppc64le.s
  vendor/golang.org/x/crypto/internal/poly1305/sum_ppc64le.s
  vendor/golang.org/x/crypto/ssh/server.go
  vendor/golang.org/x/net/html/token.go
  vendor/golang.org/x/net/http/httpproxy/proxy.go
  vendor/golang.org/x/net/http2/frame.go
  vendor/golang.org/x/net/http2/pipe.go
  vendor/golang.org/x/net/http2/server.go
  vendor/golang.org/x/net/http2/testsync.go
  vendor/golang.org/x/net/http2/transport.go
  vendor/golang.org/x/net/websocket/client.go
  vendor/golang.org/x/net/websocket/dial.go
  vendor/golang.org/x/sys/unix/aliases.go
  vendor/golang.org/x/sys/unix/mmap_nomremap.go
  vendor/golang.org/x/sys/unix/syscall_darwin_libSystem.go
  vendor/golang.org/x/sys/unix/syscall_freebsd.go
  vendor/golang.org/x/sys/unix/syscall_linux.go
  vendor/golang.org/x/sys/unix/syscall_zos_s390x.go
  vendor/golang.org/x/sys/unix/zsyscall_linux.go
  vendor/golang.org/x/sys/unix/ztypes_linux.go
  vendor/golang.org/x/sys/windows/syscall_windows.go
  vendor/golang.org/x/sys/windows/types_windows.go
  vendor/golang.org/x/sys/windows/zsyscall_windows.go
  vendor/modules.txt
Labels: kind/bug, approved, cncf-cla: yes, size/XXL

#1837 [release-1.29] fix: CVE-2023-45288
  go.mod
  go.sum
  vendor/golang.org/x/crypto/chacha20/chacha_ppc64le.s
  vendor/golang.org/x/crypto/internal/poly1305/sum_ppc64le.s
  vendor/golang.org/x/crypto/ssh/server.go
  vendor/golang.org/x/net/html/token.go
  vendor/golang.org/x/net/http/httpproxy/proxy.go
  vendor/golang.org/x/net/http2/frame.go
  vendor/golang.org/x/net/http2/pipe.go
  vendor/golang.org/x/net/http2/server.go
  vendor/golang.org/x/net/http2/testsync.go
  vendor/golang.org/x/net/http2/transport.go
  vendor/golang.org/x/net/websocket/client.go
  vendor/golang.org/x/net/websocket/dial.go
  vendor/golang.org/x/sys/unix/aliases.go
  vendor/golang.org/x/sys/unix/mmap_nomremap.go
  vendor/golang.org/x/sys/unix/syscall_darwin_libSystem.go
  vendor/golang.org/x/sys/unix/syscall_freebsd.go
  vendor/golang.org/x/sys/unix/syscall_linux.go
  vendor/golang.org/x/sys/unix/syscall_zos_s390x.go
  vendor/golang.org/x/sys/unix/zsyscall_linux.go
  vendor/golang.org/x/sys/unix/ztypes_linux.go
  vendor/golang.org/x/sys/windows/syscall_windows.go
  vendor/golang.org/x/sys/windows/types_windows.go
  vendor/golang.org/x/sys/windows/zsyscall_windows.go
  vendor/modules.txt
Labels: kind/bug, approved, cncf-cla: yes, size/XXL

#1846 fix: remove SMBGlobalMapping on Windows node
  pkg/azurefile/azure_common_darwin.go
  pkg/azurefile/azure_common_linux.go
  pkg/azurefile/azure_common_windows.go
  pkg/azurefile/azurefile.go
  pkg/azurefile/azurefile_options.go
  pkg/azurefile/nodeserver.go
  pkg/mounter/safe_mounter_host_process_windows.go
  pkg/mounter/safe_mounter_v1beta_windows.go
  pkg/os/smb/smb.go
  pkg/os/smb/smb_test.go
Labels: kind/bug, size/L, approved, cncf-cla: yes

#1855 cleanup: refine extensiveMountCheck usage in unmount
  pkg/azurefile/azure_common_linux.go
  pkg/mounter/safe_mounter_host_process_windows.go
Labels: kind/cleanup, size/S, approved, cncf-cla: yes

#1854 fix: trim slash in RemoveSmbGlobalMapping
  pkg/os/smb/smb.go
Labels: kind/bug, size/XS, approved, cncf-cla: yes

#1849 [release-1.28] fix: remove SMBGlobalMapping on Windows node
  pkg/azurefile/azure_common_darwin.go
  pkg/azurefile/azure_common_linux.go
  pkg/azurefile/azure_common_windows.go
  pkg/azurefile/azurefile.go
  pkg/azurefile/nodeserver.go
  pkg/azurefileplugin/main.go
  pkg/mounter/safe_mounter_host_process_windows.go
  pkg/mounter/safe_mounter_v1beta_windows.go
  pkg/os/smb/smb.go
  pkg/os/smb/smb_test.go
Labels: kind/bug, size/L, approved, cncf-cla: yes

#1853 [release-1.30] fix: trim slash in RemoveSmbGlobalMapping
  pkg/os/smb/smb.go
Labels: kind/bug, size/XS, approved, cncf-cla: yes

#1848 [release-1.29] fix: remove SMBGlobalMapping on Windows node
  pkg/azurefile/azure_common_darwin.go
  pkg/azurefile/azure_common_linux.go
  pkg/azurefile/azure_common_windows.go
  pkg/azurefile/azurefile.go
  pkg/azurefile/nodeserver.go
  pkg/azurefileplugin/main.go
  pkg/mounter/safe_mounter_host_process_windows.go
  pkg/mounter/safe_mounter_v1beta_windows.go
  pkg/os/smb/smb.go
  pkg/os/smb/smb_test.go
Labels: kind/bug, size/L, approved, cncf-cla: yes

#1869 [release-1.28] fix: CVE-2024-3177
  .trivyignore
  go.mod
  go.sum
  vendor/k8s.io/apiserver/pkg/admission/plugin/cel/composition.go
  vendor/k8s.io/apiserver/pkg/endpoints/discovery/aggregated/handler.go
  vendor/k8s.io/apiserver/pkg/features/kube_features.go
  vendor/k8s.io/apiserver/pkg/server/config.go
  vendor/k8s.io/apiserver/pkg/server/filters/priority-and-fairness.go
  vendor/k8s.io/apiserver/pkg/server/options/recommended.go
  vendor/k8s.io/apiserver/pkg/storage/cacher/cacher.go
  vendor/k8s.io/apiserver/pkg/storage/cacher/lister_watcher.go
  vendor/k8s.io/apiserver/pkg/storage/cacher/watch_progress.go
  vendor/k8s.io/apiserver/pkg/util/flowcontrol/apf_controller.go
  vendor/k8s.io/apiserver/pkg/util/flowcontrol/apf_filter.go
  vendor/k8s.io/apiserver/pkg/util/flowcontrol/fairqueuing/interface.go
  vendor/k8s.io/apiserver/pkg/util/flowcontrol/fairqueuing/queueset/queueset.go
  vendor/k8s.io/apiserver/pkg/util/flowcontrol/metrics/metrics.go
  vendor/k8s.io/component-base/metrics/prometheus/slis/metrics.go
  vendor/k8s.io/component-helpers/storage/volume/helpers.go
  vendor/k8s.io/kubernetes/pkg/apis/core/validation/validation.go
  vendor/k8s.io/kubernetes/pkg/features/kube_features.go
  vendor/k8s.io/kubernetes/pkg/volume/util/types/types.go
  vendor/k8s.io/kubernetes/test/utils/image/manifest.go
  vendor/modules.txt
Labels: kind/bug, size/XL, approved, cncf-cla: yes

#1868 [release-1.29] fix: CVE-2024-3177
  .trivyignore
  go.mod
  go.sum
  vendor/k8s.io/apimachinery/pkg/util/httpstream/wsstream/conn.go
  vendor/k8s.io/apiserver/pkg/features/kube_features.go
  vendor/k8s.io/apiserver/pkg/storage/cacher/cacher.go
  vendor/k8s.io/apiserver/pkg/storage/cacher/watch_cache_interval.go
  vendor/k8s.io/client-go/tools/remotecommand/websocket.go
  vendor/k8s.io/kubernetes/pkg/apis/core/types.go
  vendor/k8s.io/kubernetes/pkg/apis/core/validation/validation.go
  vendor/k8s.io/kubernetes/pkg/features/kube_features.go
  vendor/k8s.io/kubernetes/pkg/volume/plugins.go
  vendor/k8s.io/kubernetes/pkg/volume/util/types/types.go
  vendor/k8s.io/kubernetes/test/utils/image/manifest.go
  vendor/modules.txt
Labels: kind/bug, size/L, approved, cncf-cla: yes

#1866 fix: CVE-2024-3177
  .trivyignore
  go.mod
  go.sum
  vendor/k8s.io/apiserver/pkg/features/kube_features.go
  vendor/k8s.io/apiserver/pkg/storage/cacher/cacher.go
  vendor/k8s.io/apiserver/pkg/storage/cacher/watch_cache_interval.go
  vendor/k8s.io/kubernetes/pkg/apis/core/types.go
  vendor/k8s.io/kubernetes/pkg/apis/core/validation/validation.go
  vendor/k8s.io/kubernetes/pkg/features/kube_features.go
  vendor/k8s.io/kubernetes/pkg/volume/plugins.go
  vendor/k8s.io/kubernetes/pkg/volume/util/types/types.go
  vendor/k8s.io/kubernetes/test/utils/image/manifest.go
  vendor/modules.txt
Labels: kind/bug, size/L, approved, cncf-cla: yes
