Repository kubernetes-sigs/azurefile-csi-driver, pull requests merged in 2024-03, with the labels that each got.

#1744 fix: nfs file share created in storage account that has smb file share
  go.mod
  go.sum
  vendor/github.com/Azure/azure-sdk-for-go/sdk/azcore/CHANGELOG.md
  vendor/github.com/Azure/azure-sdk-for-go/sdk/azcore/core.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/azcore/etag.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/azcore/internal/exported/response_error.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/azcore/internal/log/log.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/azcore/internal/shared/constants.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/azcore/log/log.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/azcore/runtime/errors.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/azcore/runtime/request.go
  vendor/github.com/onsi/ginkgo/v2/CHANGELOG.md
  vendor/github.com/onsi/ginkgo/v2/core_dsl.go
  vendor/github.com/onsi/ginkgo/v2/ginkgo/internal/gocovmerge.go
  vendor/github.com/onsi/ginkgo/v2/ginkgo/internal/profiles_and_reports.go
  vendor/github.com/onsi/ginkgo/v2/internal/node.go
  vendor/github.com/onsi/ginkgo/v2/internal/suite.go
  vendor/github.com/onsi/ginkgo/v2/reporting_dsl.go
  vendor/github.com/onsi/ginkgo/v2/types/version.go
  vendor/golang.org/x/tools/cover/profile.go
  vendor/golang.org/x/tools/internal/versions/versions.go
  vendor/golang.org/x/tools/internal/versions/versions_go121.go
  vendor/modules.txt
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azclient/auth.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_controller_standard.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_controller_vmss.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_controller_vmssflex.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_mock_vmsets.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_storageaccount.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_vmsets.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/config/azure_auth.go
Labels: kind/bug, size/XL, approved, cncf-cla: yes

#1745 fix: nfs protocol does not support standard account
  pkg/azurefile/azurefile.go
  pkg/azurefile/controllerserver.go
  pkg/azurefile/controllerserver_test.go
Labels: kind/bug, size/M, approved, cncf-cla: yes

#1750 test: ignore azcopy CVE-2024-24786
  .trivyignore
Labels: kind/failing-test, size/XS, approved, cncf-cla: yes

#1751 fix: fix azcopy exec timeout func
  pkg/azurefile/azurefile.go
  pkg/azurefile/controllerserver.go
  pkg/azurefile/controllerserver_test.go
  pkg/azurefile/volume_lock.go
  pkg/util/util.go
  pkg/util/util_test.go
Labels: kind/bug, size/L, ok-to-test, lgtm, cncf-cla: yes

#1756 feat: upgrade azcopy version to 10.23.0 for volume clone feature
  pkg/azurefileplugin/Dockerfile
  test/sanity/run-test.sh
Labels: kind/feature, size/XS, approved, cncf-cla: yes

#1761 [release-1.28] feat: upgrade azcopy version to 10.23.0 for volume clone feature
  pkg/azurefileplugin/Dockerfile
  test/sanity/run-test.sh
Labels: kind/feature, size/XS, approved, cncf-cla: yes

#1760 [release-1.29] feat: upgrade azcopy version to 10.23.0 for volume clone feature
  pkg/azurefileplugin/Dockerfile
  test/sanity/run-test.sh
Labels: kind/feature, size/XS, approved, cncf-cla: yes

#1762 Add group update policy for k8s.io dependencies
  .github/dependabot.yaml
Labels: kind/cleanup, size/XS, lgtm, approved, cncf-cla: yes

#1766 chore: refine refine private endpoint to reduce error messages
  go.mod
  go.sum
  vendor/github.com/onsi/ginkgo/v2/CHANGELOG.md
  vendor/github.com/onsi/ginkgo/v2/core_dsl.go
  vendor/github.com/onsi/ginkgo/v2/reporters/default_reporter.go
  vendor/github.com/onsi/ginkgo/v2/types/config.go
  vendor/github.com/onsi/ginkgo/v2/types/version.go
  vendor/github.com/stretchr/testify/assert/assertion_compare.go
  vendor/github.com/stretchr/testify/assert/assertion_compare_can_convert.go
  vendor/github.com/stretchr/testify/assert/assertion_compare_legacy.go
  vendor/github.com/stretchr/testify/assert/assertion_format.go
  vendor/github.com/stretchr/testify/assert/assertion_forward.go
  vendor/github.com/stretchr/testify/assert/assertions.go
  vendor/github.com/stretchr/testify/assert/http_assertions.go
  vendor/modules.txt
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azclient/cloud.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/consts/consts.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_storageaccount.go
Labels: kind/cleanup, size/XL, approved, cncf-cla: yes

#1765 fix: mount stuck issue
  pkg/azurefile/azurefile.go
  pkg/azurefile/nodeserver.go
  pkg/util/util.go
  pkg/util/util_test.go
Labels: kind/bug, size/S, approved, cncf-cla: yes

#1770 chore: refine sastoken cache
  pkg/azurefile/azurefile.go
  pkg/azurefile/controllerserver.go
  pkg/azurefile/controllerserver_test.go
Labels: kind/cleanup, size/M, approved, cncf-cla: yes

#1777 fix: strip service account token
  pkg/csi-common/utils.go
  pkg/csi-common/utils_test.go
Labels: kind/cleanup, size/M, lgtm, approved, cncf-cla: yes

#1783 fix: workload identity did not work
  pkg/azurefile/azure.go
  pkg/azurefile/azure_test.go
Labels: kind/bug, size/M, lgtm, approved, cncf-cla: yes
