Repository kubernetes-sigs/azurefile-csi-driver, pull requests merged in 2024-10, with the labels that each got.

#2132 test: run windows ut with host process enabled
  pkg/azurefile/fake_mounter.go
Labels: size/XS, approved, cncf-cla: yes, kind/test

#1971 feat: add support for confidential pods
  Makefile
  charts/latest/azurefile-csi-driver-v0.0.0.tgz
  charts/latest/azurefile-csi-driver/templates/csi-azurefile-node.yaml
  charts/latest/azurefile-csi-driver/templates/rbac-csi-azurefile-node.yaml
  charts/latest/azurefile-csi-driver/values.yaml
  deploy/csi-azurefile-node.yaml
  deploy/example/kata-cc/statefulset.yaml
  deploy/example/kata-cc/storageclass-azurefile-kata-cc.yaml
  deploy/rbac-csi-azurefile-controller.yaml
  deploy/rbac-csi-azurefile-node.yaml
  go.mod
  go.sum
  hack/verify-yamllint.sh
  pkg/azurefile/azure.go
  pkg/azurefile/azure_test.go
  pkg/azurefile/azurefile.go
  pkg/azurefile/azurefile_options.go
  pkg/azurefile/azurefile_test.go
  pkg/azurefile/controllerserver.go
  pkg/azurefile/directvolume_interface.go
  pkg/azurefile/directvolume_mock.go
  pkg/azurefile/nodeserver.go
  pkg/azurefile/nodeserver_test.go
  pkg/azurefile/resolver_interface.go
  pkg/azurefile/resolver_mock.go
  pkg/azurefile/utils.go
  pkg/azurefile/utils_test.go
  vendor/github.com/Microsoft/go-winio/.golangci.yml
  vendor/github.com/Microsoft/go-winio/hvsock.go
  vendor/github.com/Microsoft/go-winio/internal/fs/doc.go
  vendor/github.com/Microsoft/go-winio/internal/fs/fs.go
  vendor/github.com/Microsoft/go-winio/internal/fs/security.go
  vendor/github.com/Microsoft/go-winio/internal/fs/zsyscall_windows.go
  vendor/github.com/Microsoft/go-winio/internal/socket/socket.go
  vendor/github.com/Microsoft/go-winio/internal/stringbuffer/wstring.go
  vendor/github.com/Microsoft/go-winio/pipe.go
  vendor/github.com/Microsoft/go-winio/zsyscall_windows.go
  vendor/github.com/golang/mock/AUTHORS
  vendor/github.com/golang/mock/CONTRIBUTORS
  vendor/github.com/golang/mock/LICENSE
  vendor/github.com/golang/mock/gomock/call.go
  vendor/github.com/golang/mock/gomock/callset.go
  vendor/github.com/golang/mock/gomock/controller.go
  vendor/github.com/golang/mock/gomock/matchers.go
  vendor/github.com/kata-containers/kata-containers/src/runtime/LICENSE
  vendor/github.com/kata-containers/kata-containers/src/runtime/pkg/direct-volume/utils.go
  vendor/github.com/moby/sys/mountinfo/mountinfo_linux.go
  vendor/modules.txt
Labels: ok-to-test, lgtm, approved, cncf-cla: yes, size/XXL

#2137 doc: cut v1.31.0 release
  README.md
  charts/index.yaml
  charts/latest/azurefile-csi-driver-v0.0.0.tgz
  charts/v1.31.0/azurefile-csi-driver-1.31.0.tgz
  charts/v1.31.0/azurefile-csi-driver/Chart.yaml
  charts/v1.31.0/azurefile-csi-driver/templates/NOTES.txt
  charts/v1.31.0/azurefile-csi-driver/templates/_helpers.tpl
  charts/v1.31.0/azurefile-csi-driver/templates/crd-csi-snapshot.yaml
  charts/v1.31.0/azurefile-csi-driver/templates/csi-azurefile-controller.yaml
  charts/v1.31.0/azurefile-csi-driver/templates/csi-azurefile-driver.yaml
  charts/v1.31.0/azurefile-csi-driver/templates/csi-azurefile-node-windows-hostprocess.yaml
  charts/v1.31.0/azurefile-csi-driver/templates/csi-azurefile-node-windows.yaml
  charts/v1.31.0/azurefile-csi-driver/templates/csi-azurefile-node.yaml
  charts/v1.31.0/azurefile-csi-driver/templates/csi-snapshot-controller.yaml
  charts/v1.31.0/azurefile-csi-driver/templates/rbac-csi-azurefile-controller.yaml
  charts/v1.31.0/azurefile-csi-driver/templates/rbac-csi-azurefile-node.yaml
  charts/v1.31.0/azurefile-csi-driver/templates/rbac-csi-snapshot-controller.yaml
  charts/v1.31.0/azurefile-csi-driver/templates/serviceaccount-csi-azurefile-controller.yaml
  charts/v1.31.0/azurefile-csi-driver/templates/serviceaccount-csi-azurefile-node.yaml
  charts/v1.31.0/azurefile-csi-driver/templates/serviceaccount-csi-snapshot-controller.yaml
  charts/v1.31.0/azurefile-csi-driver/values.yaml
  deploy/v1.31.0/crd-csi-snapshot.yaml
  deploy/v1.31.0/csi-azurefile-controller.yaml
  deploy/v1.31.0/csi-azurefile-driver.yaml
  deploy/v1.31.0/csi-azurefile-node-windows-hostprocess.yaml
  deploy/v1.31.0/csi-azurefile-node-windows.yaml
  deploy/v1.31.0/csi-azurefile-node.yaml
  deploy/v1.31.0/csi-snapshot-controller.yaml
  deploy/v1.31.0/rbac-csi-azurefile-controller.yaml
  deploy/v1.31.0/rbac-csi-azurefile-node.yaml
  deploy/v1.31.0/rbac-csi-snapshot-controller.yaml
  docs/install-azurefile-csi-driver.md
  docs/install-csi-driver-v1.31.0.md
Labels: kind/documentation, approved, cncf-cla: yes, size/XXL

#2139 doc: remove obsolete doc about volumeID format
  docs/driver-parameters.md
  docs/workload-identity-static-pv-mount.md
Labels: kind/documentation, size/XS, approved, cncf-cla: yes

#2144 fix: add CriticalAddonsOnly toleration into controller pod
  charts/latest/azurefile-csi-driver-v0.0.0.tgz
  charts/latest/azurefile-csi-driver/values.yaml
  charts/v1.29.9/azurefile-csi-driver-v1.29.9.tgz
  charts/v1.29.9/azurefile-csi-driver/values.yaml
  charts/v1.30.6/azurefile-csi-driver-v1.30.6.tgz
  charts/v1.30.6/azurefile-csi-driver/values.yaml
  charts/v1.31.0/azurefile-csi-driver-1.31.0.tgz
  charts/v1.31.0/azurefile-csi-driver/values.yaml
  deploy/csi-azurefile-controller.yaml
  deploy/v1.29.9/csi-azurefile-controller.yaml
  deploy/v1.30.6/csi-azurefile-controller.yaml
  deploy/v1.31.0/csi-azurefile-controller.yaml
Labels: kind/bug, size/S, approved, cncf-cla: yes

#2147 [release-1.29] fix: add CriticalAddonsOnly toleration into controller pod
  charts/latest/azurefile-csi-driver-v1.29.9.tgz
  charts/latest/azurefile-csi-driver/values.yaml
  charts/v1.29.9/azurefile-csi-driver-v1.29.9.tgz
  charts/v1.29.9/azurefile-csi-driver/values.yaml
  deploy/csi-azurefile-controller.yaml
  deploy/v1.29.9/csi-azurefile-controller.yaml
Labels: kind/bug, size/S, approved, cncf-cla: yes

#2146 [release-1.30] fix: add CriticalAddonsOnly toleration into controller pod
  charts/latest/azurefile-csi-driver-v1.30.6.tgz
  charts/latest/azurefile-csi-driver/values.yaml
  charts/v1.30.6/azurefile-csi-driver-v1.30.6.tgz
  charts/v1.30.6/azurefile-csi-driver/values.yaml
  deploy/csi-azurefile-controller.yaml
  deploy/v1.30.6/csi-azurefile-controller.yaml
Labels: kind/bug, size/S, approved, cncf-cla: yes

#2145 [release-1.31] fix: add CriticalAddonsOnly toleration into controller pod
  charts/latest/azurefile-csi-driver-1.31.0.tgz
  charts/latest/azurefile-csi-driver/values.yaml
  charts/v1.31.0/azurefile-csi-driver-1.31.0.tgz
  charts/v1.31.0/azurefile-csi-driver/values.yaml
  deploy/csi-azurefile-controller.yaml
  deploy/v1.31.0/csi-azurefile-controller.yaml
Labels: kind/bug, size/S, approved, cncf-cla: yes

#2149 doc: support example pod running on arm64 node
  deploy/example/cloning/nginx-pod-restored-cloning.yaml
  deploy/example/daemonset.yaml
  deploy/example/deployment.yaml
  deploy/example/disk/statefulset-stress.yaml
  deploy/example/kata-cc/statefulset.yaml
  deploy/example/nfs/statefulset.yaml
  deploy/example/nginx-pod-azurefile-inline-volume.yaml
  deploy/example/nginx-pod-azurefile.yaml
  deploy/example/smb-provisioner/nginx-on-prem-volume.yaml
  deploy/example/snapshot/nginx-pod-restored-snapshot.yaml
  deploy/example/statefulset.yaml
  docs/workload-identity-static-pv-mount.md
Labels: size/S, kind/documentation, approved, cncf-cla: yes

#2151 test: add UserAgent for e2e client
  test/utils/azure/azure_helpers.go
Labels: size/XS, lgtm, approved, cncf-cla: yes, kind/test
