Repository kubernetes-sigs/azurefile-csi-driver, pull requests merged in 2024-02, with the labels that each got.

#1688 test: fix sanity test failure
  pkg/azurefile/nodeserver_test.go
  test/sanity/run-test.sh
Labels: size/S, approved, cncf-cla: yes, kind/test

#1686 [release-1.29] fix: increase volume cloning timeout
  pkg/azurefile/azurefile.go
  pkg/azurefile/azurefile_test.go
  pkg/azurefile/nodeserver_test.go
  pkg/azurefileplugin/main.go
Labels: kind/bug, size/M, approved, cncf-cla: yes

#1696 cleanup: remove integration test
  Makefile
  test/integration/README.md
  test/integration/integration_test.go
  test/integration/run-test.sh
  test/integration/run-tests-all-clouds.sh
Labels: size/L, kind/cleanup, approved, cncf-cla: yes

#1698 test: fix goveralls
  .github/workflows/linux.yaml
Labels: kind/failing-test, size/XS, approved, cncf-cla: yes

#1703 [release-1.28] test: fix windows ut failure
  pkg/azurefile/nodeserver_test.go
Labels: size/S, kind/failing-test, approved, cncf-cla: yes

#1706 chore: respect RetryAfter in throttling condition
  pkg/azurefile/azurefile.go
  pkg/azurefile/controllerserver.go
  pkg/azurefile/utils.go
  pkg/azurefile/utils_test.go
Labels: kind/feature, size/M, approved, cncf-cla: yes

#1709 [release-1.28] chore: respect RetryAfter in throttling condition
  pkg/azurefile/azurefile.go
  pkg/azurefile/controllerserver.go
  pkg/azurefile/utils.go
  pkg/azurefile/utils_test.go
Labels: size/M, approved, cncf-cla: yes

#1710 fix: panic when controller does not have cloud config
  pkg/azurefile/azurefile.go
  pkg/azurefile/azurefile_dataplane_client.go
  pkg/azurefile/azurefile_dataplane_client_test.go
  pkg/azurefile/azurefile_test.go
  pkg/azurefile/controllerserver.go
  pkg/azurefile/nodeserver.go
Labels: kind/bug, size/L, approved, cncf-cla: yes

#1711 [release-1.26] chore: respect RetryAfter in throttling condition
  pkg/azurefile/azurefile.go
  pkg/azurefile/controllerserver.go
  pkg/azurefile/utils.go
  pkg/azurefile/utils_test.go
Labels: size/M, approved, cncf-cla: yes

#1712 [release-1.29] fix: panic when controller does not have cloud config
  pkg/azurefile/azurefile.go
  pkg/azurefile/azurefile_test.go
  pkg/azurefile/controllerserver.go
  pkg/azurefile/nodeserver.go
Labels: size/L, lgtm, approved, cncf-cla: yes

#1719 doc: cut v1.30.0 release
  README.md
  charts/index.yaml
  charts/latest/azurefile-csi-driver-v0.0.0.tgz
  charts/v1.30.0/azurefile-csi-driver-v1.30.0.tgz
  charts/v1.30.0/azurefile-csi-driver/Chart.yaml
  charts/v1.30.0/azurefile-csi-driver/templates/NOTES.txt
  charts/v1.30.0/azurefile-csi-driver/templates/_helpers.tpl
  charts/v1.30.0/azurefile-csi-driver/templates/crd-csi-snapshot.yaml
  charts/v1.30.0/azurefile-csi-driver/templates/csi-azurefile-controller.yaml
  charts/v1.30.0/azurefile-csi-driver/templates/csi-azurefile-driver.yaml
  charts/v1.30.0/azurefile-csi-driver/templates/csi-azurefile-node-windows-hostprocess.yaml
  charts/v1.30.0/azurefile-csi-driver/templates/csi-azurefile-node-windows.yaml
  charts/v1.30.0/azurefile-csi-driver/templates/csi-azurefile-node.yaml
  charts/v1.30.0/azurefile-csi-driver/templates/csi-snapshot-controller.yaml
  charts/v1.30.0/azurefile-csi-driver/templates/rbac-csi-azurefile-controller.yaml
  charts/v1.30.0/azurefile-csi-driver/templates/rbac-csi-azurefile-node.yaml
  charts/v1.30.0/azurefile-csi-driver/templates/rbac-csi-snapshot-controller.yaml
  charts/v1.30.0/azurefile-csi-driver/templates/serviceaccount-csi-azurefile-controller.yaml
  charts/v1.30.0/azurefile-csi-driver/templates/serviceaccount-csi-azurefile-node.yaml
  charts/v1.30.0/azurefile-csi-driver/templates/serviceaccount-csi-snapshot-controller.yaml
  charts/v1.30.0/azurefile-csi-driver/values.yaml
  deploy/v1.30.0/crd-csi-snapshot.yaml
  deploy/v1.30.0/csi-azurefile-controller.yaml
  deploy/v1.30.0/csi-azurefile-driver.yaml
  deploy/v1.30.0/csi-azurefile-node-windows-hostprocess.yaml
  deploy/v1.30.0/csi-azurefile-node-windows.yaml
  deploy/v1.30.0/csi-azurefile-node.yaml
  deploy/v1.30.0/csi-snapshot-controller.yaml
  deploy/v1.30.0/rbac-csi-azurefile-controller.yaml
  deploy/v1.30.0/rbac-csi-azurefile-node.yaml
  deploy/v1.30.0/rbac-csi-snapshot-controller.yaml
  docs/install-azurefile-csi-driver.md
  docs/install-csi-driver-v1.30.0.md
Labels: kind/documentation, approved, cncf-cla: yes, size/XXL

#1721 chore: Update csi-azurefile-driver.yaml
  deploy/csi-azurefile-driver.yaml
Labels: size/XS, lgtm, cncf-cla: yes

#1723 feat: allow multiple subnets in updating service endpoints
  docs/driver-parameters.md
  pkg/azurefile/controllerserver.go
  pkg/azurefile/controllerserver_test.go
Labels: kind/feature, size/M, approved, cncf-cla: yes

#1728 [release-1.29] test: remove vhd disk test
  test/e2e/dynamic_provisioning_test.go
Labels: size/S, kind/failing-test, approved, cncf-cla: yes

#1727 [release-1.30] test: remove vhd disk test
  test/e2e/dynamic_provisioning_test.go
Labels: size/S, kind/failing-test, approved, cncf-cla: yes

#1729 fix: ensure azure cloud config could be loaded from secret
  pkg/azurefile/azure.go
Labels: kind/bug, ok-to-test, size/XS, lgtm, approved, cncf-cla: yes

#1733 test: remove one vhd e2e test
  test/e2e/dynamic_provisioning_test.go
Labels: size/S, kind/failing-test, approved, cncf-cla: yes

#1730 chore: upgrade azure cloud provider lib
  go.mod
  go.sum
  vendor/github.com/go-logr/logr/slogr/slogr.go
  vendor/golang.org/x/crypto/internal/poly1305/sum_ppc64le.s
  vendor/k8s.io/apiserver/pkg/admission/plugin/cel/composition.go
  vendor/k8s.io/apiserver/pkg/admission/plugin/validatingadmissionpolicy/controller_reconcile.go
  vendor/k8s.io/apiserver/pkg/cel/environment/base.go
  vendor/k8s.io/component-base/metrics/prometheus/slis/metrics.go
  vendor/k8s.io/component-helpers/storage/volume/helpers.go
  vendor/k8s.io/klog/v2/OWNERS
  vendor/k8s.io/klog/v2/contextual_slog.go
  vendor/k8s.io/klog/v2/klog.go
  vendor/k8s.io/klog/v2/klogr_slog.go
  vendor/k8s.io/klog/v2/safeptr.go
  vendor/modules.txt
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azclient/virtualmachineclient/interface.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_storageaccount.go
Labels: kind/feature, size/L, approved, cncf-cla: yes
