Repository kubernetes-sigs/azurefile-csi-driver, pull requests merged in 2024-08, with the labels that each got.

#2022 [release-1.28] feat: upgrade to azcopy v10.26.0 for volume clone and snapshot restore
  .trivyignore
  pkg/azurefileplugin/Dockerfile
  test/sanity/run-test.sh
Labels: kind/feature, size/XS, approved, cncf-cla: yes

#2018 feat: upgrade to azcopy v10.26.0 for volume clone and snapshot restore
  .trivyignore
  pkg/azurefileplugin/Dockerfile
  test/sanity/run-test.sh
Labels: kind/feature, size/XS, approved, cncf-cla: yes

#2020 [release-1.29] feat: upgrade to azcopy v10.26.0 for volume clone and snapshot restore
  .trivyignore
  pkg/azurefileplugin/Dockerfile
  test/sanity/run-test.sh
Labels: kind/feature, size/XS, approved, cncf-cla: yes

#2019 [release-1.30] feat: upgrade to azcopy v10.26.0 for volume clone and snapshot restore
  .trivyignore
  pkg/azurefileplugin/Dockerfile
  test/sanity/run-test.sh
Labels: kind/feature, size/XS, approved, cncf-cla: yes

#2003 fix: set the correct destination account name for copy volume if storageAccount is specified in storage class
  pkg/azurefile/azurefile.go
  pkg/azurefile/controllerserver.go
  pkg/azurefile/controllerserver_test.go
  test/e2e/dynamic_provisioning_test.go
  test/e2e/testsuites/dynamically_provisioned_volume_cloning_tester.go
Labels: kind/bug, size/L, ok-to-test, lgtm, cncf-cla: yes

#2027 fix: only last subnet is set in account ACL created by driver
  pkg/azurefile/controllerserver.go
Labels: kind/bug, size/XS, approved, cncf-cla: yes

#2031 fix: respect ReadOnly AccessMode in volume mount
  pkg/azurefile/nodeserver.go
  pkg/azurefile/utils.go
  pkg/azurefile/utils_test.go
  test/e2e/dynamic_provisioning_test.go
  test/e2e/testsuites/specs.go
  test/e2e/testsuites/testsuites.go
Labels: kind/bug, size/L, approved, cncf-cla: yes

#2030 [release-1.28] fix: only last subnet is set in account ACL created by driver
  pkg/azurefile/controllerserver.go
Labels: kind/bug, size/XS, approved, cncf-cla: yes

#2026 fix: nfs mount failure when there are multiple subnets in the cluster
  pkg/azurefile/azure.go
  pkg/azurefile/azure_test.go
  pkg/azurefile/azurefile.go
  pkg/azurefile/controllerserver.go
  pkg/azurefile/controllerserver_test.go
Labels: kind/bug, size/L, approved, cncf-cla: yes

#2033 [release-1.29] fix: set the correct destination account name for copy volume if storageAccount is specified in storage class
  pkg/azurefile/azurefile.go
  pkg/azurefile/controllerserver.go
  pkg/azurefile/controllerserver_test.go
  pkg/util/util.go
  pkg/util/util_test.go
  test/e2e/dynamic_provisioning_test.go
  test/e2e/testsuites/dynamically_provisioned_volume_cloning_tester.go
Labels: kind/bug, size/L, ok-to-test, cncf-cla: yes

#2036 fix: VirtualNetworkRule match issue during account search
  go.mod
  go.sum
  vendor/modules.txt
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_storageaccount.go
Labels: kind/bug, size/S, approved, cncf-cla: yes

#2037 [release-1.30] fix: VirtualNetworkRule match issue during account search
  go.mod
  go.sum
  vendor/modules.txt
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_storageaccount.go
Labels: kind/bug, size/S, approved, cncf-cla: yes

#2043 chore: set HostProcess container deployment on Windows as default
  charts/README.md
  charts/latest/azurefile-csi-driver-v0.0.0.tgz
  charts/latest/azurefile-csi-driver/values.yaml
  deploy/install-driver.sh
Labels: kind/feature, size/S, approved, cncf-cla: yes

#2044 [release-1.28] fix: incorrect snapshot size with default 100Gi
  pkg/azurefile/controllerserver.go
Labels: kind/bug, ok-to-test, size/XS, cncf-cla: yes

#2045 [release-1.30] chore: set HostProcess container deployment on Windows as default
  charts/README.md
  charts/latest/azurefile-csi-driver-v1.30.4.tgz
  charts/latest/azurefile-csi-driver/values.yaml
  deploy/install-driver.sh
Labels: kind/feature, size/S, approved, cncf-cla: yes

#2048 chore: fix missing securityContext on controller pods
  charts/latest/azurefile-csi-driver-v0.0.0.tgz
  charts/latest/azurefile-csi-driver/templates/csi-azurefile-controller.yaml
  charts/latest/azurefile-csi-driver/templates/csi-snapshot-controller.yaml
  deploy/csi-azurefile-controller.yaml
  deploy/csi-snapshot-controller.yaml
Labels: kind/cleanup, size/S, cncf-cla: yes

#2054 test: use workload identity for e2e test
  Makefile
  deploy/example/smb-provisioner/smb-server-lb.yaml
  deploy/example/smb-provisioner/smb-server.yaml
  go.mod
  go.sum
  hack/verify-examples.sh
  pkg/azurefile/azure.go
  test/e2e/suite_test.go
  test/e2e/testsuites/dynamically_provisioned_resize_volume_tester.go
  test/e2e/testsuites/dynamically_provisioned_tags_tester.go
  test/sanity/run-test.sh
  test/sanity/sanity_test.go
  test/utils/azure/azure_helpers.go
  test/utils/credentials/credentials.go
  test/utils/credentials/credentials_test.go
  test/utils/get_smb_svc_public_ip.sh
  test/utils/get_storage_account_secret_name.sh
  test/utils/testutil/testutil.go
  vendor/github.com/pelletier/go-toml/.dockerignore
  vendor/github.com/pelletier/go-toml/.gitignore
  vendor/github.com/pelletier/go-toml/CONTRIBUTING.md
  vendor/github.com/pelletier/go-toml/Dockerfile
  vendor/github.com/pelletier/go-toml/LICENSE
  vendor/github.com/pelletier/go-toml/Makefile
  vendor/github.com/pelletier/go-toml/PULL_REQUEST_TEMPLATE.md
  vendor/github.com/pelletier/go-toml/README.md
  vendor/github.com/pelletier/go-toml/azure-pipelines.yml
  vendor/github.com/pelletier/go-toml/benchmark.sh
  vendor/github.com/pelletier/go-toml/doc.go
  vendor/github.com/pelletier/go-toml/example-crlf.toml
  vendor/github.com/pelletier/go-toml/example.toml
  vendor/github.com/pelletier/go-toml/fuzz.go
  vendor/github.com/pelletier/go-toml/fuzz.sh
  vendor/github.com/pelletier/go-toml/keysparsing.go
  vendor/github.com/pelletier/go-toml/lexer.go
  vendor/github.com/pelletier/go-toml/localtime.go
  vendor/github.com/pelletier/go-toml/marshal.go
  vendor/github.com/pelletier/go-toml/marshal_OrderPreserve_test.toml
  vendor/github.com/pelletier/go-toml/marshal_test.toml
  vendor/github.com/pelletier/go-toml/parser.go
  vendor/github.com/pelletier/go-toml/position.go
  vendor/github.com/pelletier/go-toml/token.go
  vendor/github.com/pelletier/go-toml/toml.go
  vendor/github.com/pelletier/go-toml/tomlpub.go
  vendor/github.com/pelletier/go-toml/tomltree_create.go
  vendor/github.com/pelletier/go-toml/tomltree_write.go
  vendor/github.com/pelletier/go-toml/tomltree_writepub.go
  vendor/modules.txt
Labels: ok-to-test, cncf-cla: yes, size/XXL

#2056 [release-1.30] test: use workload identity for e2e test
  Makefile
  deploy/example/smb-provisioner/smb-server-lb.yaml
  deploy/example/smb-provisioner/smb-server.yaml
  go.mod
  go.sum
  hack/verify-examples.sh
  pkg/azurefile/azure.go
  test/e2e/suite_test.go
  test/e2e/testsuites/dynamically_provisioned_resize_volume_tester.go
  test/e2e/testsuites/dynamically_provisioned_tags_tester.go
  test/sanity/run-test.sh
  test/sanity/sanity_test.go
  test/utils/azure/azure_helpers.go
  test/utils/credentials/credentials.go
  test/utils/credentials/credentials_test.go
  test/utils/get_smb_svc_public_ip.sh
  test/utils/get_storage_account_secret_name.sh
  test/utils/testutil/testutil.go
  vendor/github.com/pelletier/go-toml/.dockerignore
  vendor/github.com/pelletier/go-toml/.gitignore
  vendor/github.com/pelletier/go-toml/CONTRIBUTING.md
  vendor/github.com/pelletier/go-toml/Dockerfile
  vendor/github.com/pelletier/go-toml/LICENSE
  vendor/github.com/pelletier/go-toml/Makefile
  vendor/github.com/pelletier/go-toml/PULL_REQUEST_TEMPLATE.md
  vendor/github.com/pelletier/go-toml/README.md
  vendor/github.com/pelletier/go-toml/azure-pipelines.yml
  vendor/github.com/pelletier/go-toml/benchmark.sh
  vendor/github.com/pelletier/go-toml/doc.go
  vendor/github.com/pelletier/go-toml/example-crlf.toml
  vendor/github.com/pelletier/go-toml/example.toml
  vendor/github.com/pelletier/go-toml/fuzz.go
  vendor/github.com/pelletier/go-toml/fuzz.sh
  vendor/github.com/pelletier/go-toml/keysparsing.go
  vendor/github.com/pelletier/go-toml/lexer.go
  vendor/github.com/pelletier/go-toml/localtime.go
  vendor/github.com/pelletier/go-toml/marshal.go
  vendor/github.com/pelletier/go-toml/marshal_OrderPreserve_test.toml
  vendor/github.com/pelletier/go-toml/marshal_test.toml
  vendor/github.com/pelletier/go-toml/parser.go
  vendor/github.com/pelletier/go-toml/position.go
  vendor/github.com/pelletier/go-toml/token.go
  vendor/github.com/pelletier/go-toml/toml.go
  vendor/github.com/pelletier/go-toml/tomlpub.go
  vendor/github.com/pelletier/go-toml/tomltree_create.go
  vendor/github.com/pelletier/go-toml/tomltree_write.go
  vendor/github.com/pelletier/go-toml/tomltree_writepub.go
  vendor/modules.txt
Labels: kind/failing-test, approved, cncf-cla: yes, size/XXL

#2057 fix: upgrade csi-provisioner to v5.0.2 to fix pv deletion stuck issue
  charts/README.md
  charts/latest/azurefile-csi-driver-v0.0.0.tgz
  charts/latest/azurefile-csi-driver/values.yaml
  charts/v1.30.5/azurefile-csi-driver-v1.30.5.tgz
  charts/v1.30.5/azurefile-csi-driver/values.yaml
  deploy/csi-azurefile-controller.yaml
  deploy/v1.30.5/csi-azurefile-controller.yaml
Labels: kind/bug, size/M, approved, cncf-cla: yes

#2058 [release-1.30] fix: upgrade csi-provisioner to v5.0.2 to fix pv deletion stuck issue
  charts/README.md
  charts/latest/azurefile-csi-driver-v1.30.5.tgz
  charts/latest/azurefile-csi-driver/values.yaml
  deploy/csi-azurefile-controller.yaml
Labels: kind/bug, size/M, approved, cncf-cla: yes

#2059 fix: bump mount-utils to treat ENODEV error as corrupted mount
  go.mod
  go.sum
  vendor/k8s.io/mount-utils/mount_helper_unix.go
  vendor/modules.txt
Labels: kind/bug, size/S, approved, cncf-cla: yes

#2062 [release-1.28] test: use workload identity for e2e test
  Makefile
  deploy/example/smb-provisioner/smb-server-lb.yaml
  deploy/example/smb-provisioner/smb-server.yaml
  go.mod
  go.sum
  hack/verify-examples.sh
  pkg/azurefile/azure.go
  test/e2e/suite_test.go
  test/e2e/testsuites/dynamically_provisioned_resize_volume_tester.go
  test/e2e/testsuites/dynamically_provisioned_tags_tester.go
  test/integration/README.md
  test/integration/integration_test.go
  test/integration/run-test.sh
  test/integration/run-tests-all-clouds.sh
  test/sanity/run-test.sh
  test/sanity/sanity_test.go
  test/utils/azure/azure_helpers.go
  test/utils/credentials/credentials.go
  test/utils/credentials/credentials_test.go
  test/utils/get_smb_svc_public_ip.sh
  test/utils/get_storage_account_secret_name.sh
  test/utils/testutil/testutil.go
  vendor/github.com/pelletier/go-toml/.dockerignore
  vendor/github.com/pelletier/go-toml/.gitignore
  vendor/github.com/pelletier/go-toml/CONTRIBUTING.md
  vendor/github.com/pelletier/go-toml/Dockerfile
  vendor/github.com/pelletier/go-toml/LICENSE
  vendor/github.com/pelletier/go-toml/Makefile
  vendor/github.com/pelletier/go-toml/PULL_REQUEST_TEMPLATE.md
  vendor/github.com/pelletier/go-toml/README.md
  vendor/github.com/pelletier/go-toml/azure-pipelines.yml
  vendor/github.com/pelletier/go-toml/benchmark.sh
  vendor/github.com/pelletier/go-toml/doc.go
  vendor/github.com/pelletier/go-toml/example-crlf.toml
  vendor/github.com/pelletier/go-toml/example.toml
  vendor/github.com/pelletier/go-toml/fuzz.go
  vendor/github.com/pelletier/go-toml/fuzz.sh
  vendor/github.com/pelletier/go-toml/keysparsing.go
  vendor/github.com/pelletier/go-toml/lexer.go
  vendor/github.com/pelletier/go-toml/localtime.go
  vendor/github.com/pelletier/go-toml/marshal.go
  vendor/github.com/pelletier/go-toml/marshal_OrderPreserve_test.toml
  vendor/github.com/pelletier/go-toml/marshal_test.toml
  vendor/github.com/pelletier/go-toml/parser.go
  vendor/github.com/pelletier/go-toml/position.go
  vendor/github.com/pelletier/go-toml/token.go
  vendor/github.com/pelletier/go-toml/toml.go
  vendor/github.com/pelletier/go-toml/tomlpub.go
  vendor/github.com/pelletier/go-toml/tomltree_create.go
  vendor/github.com/pelletier/go-toml/tomltree_write.go
  vendor/github.com/pelletier/go-toml/tomltree_writepub.go
  vendor/modules.txt
Labels: kind/failing-test, approved, cncf-cla: yes, size/XXL

#2064 [release-1.28] fix: bump mount-utils to treat ENODEV error as corrupted mount
  go.mod
  go.sum
  vendor/k8s.io/mount-utils/mount_helper_unix.go
  vendor/modules.txt
Labels: kind/bug, size/S, approved, cncf-cla: yes

#2063 [release-1.29] fix: bump mount-utils to treat ENODEV error as corrupted mount
  go.mod
  go.sum
  vendor/k8s.io/mount-utils/mount_helper_unix.go
  vendor/modules.txt
Labels: kind/bug, size/S, approved, cncf-cla: yes

#2067 fix: CVE-2024-38428 remove wget to close vuln, reduce image size
  pkg/azurefileplugin/Dockerfile
Labels: kind/bug, ok-to-test, size/M, lgtm, approved, cncf-cla: yes

#2071 test: don't return error when deleting rg failed in sanity test
  pkg/util/util.go
  test/sanity/sanity_test.go
  test/utils/azure/azure_helpers.go
Labels: size/S, kind/failing-test, approved, cncf-cla: yes

#2075 [release-1.28] test: don't return error when deleting rg failed in sanity test
  test/sanity/sanity_test.go
  test/utils/azure/azure_helpers.go
Labels: size/S, kind/failing-test, approved, cncf-cla: yes

#2077 test: increase sanity test timeout as 30min
  Makefile
Labels: kind/failing-test, size/XS, approved, cncf-cla: yes

#2084 fix: azcopy copy command fallback log
  pkg/azurefile/controllerserver.go
Labels: kind/bug, ok-to-test, size/XS, lgtm, approved, cncf-cla: yes

#2081 chore: Replace deprecated k8s.io/utils/pointer with k8s.io/utils/ptr
  pkg/azurefile/azure.go
  pkg/azurefile/azure_test.go
  pkg/azurefile/controllerserver.go
  pkg/azurefile/controllerserver_test.go
  test/e2e/testsuites/testsuites.go
  test/utils/azure/azure_helpers.go
Labels: ok-to-test, size/M, lgtm, approved, cncf-cla: yes
