Repository kubernetes-sigs/azurefile-csi-driver, pull requests merged in 2024-11, with the labels that each got.

#2153 fix: reduce get file share throttling when CreateSnapshot
  pkg/azurefile/controllerserver.go
  test/sanity/run-test.sh
Labels: kind/bug, size/XS, approved, cncf-cla: yes

#2160 test: enable more sanity tests
  test/sanity/run-test.sh
Labels: size/XS, approved, cncf-cla: yes, kind/test

#2164 test: fix trivy action
  .github/workflows/trivy.yaml
Labels: kind/failing-test, size/XS, approved, cncf-cla: yes

#2165 fix: CVE-2024-51744
  go.mod
  go.sum
  vendor/github.com/golang-jwt/jwt/v4/parser.go
  vendor/modules.txt
Labels: kind/bug, size/M, approved, cncf-cla: yes

#2170 feat: upgrade to azcopy v10.27.0 for volume clone and snapshot restore
  .trivyignore
  pkg/azurefileplugin/Dockerfile
  test/sanity/run-test.sh
Labels: kind/feature, size/XS, approved, cncf-cla: yes

#2180 [release-1.28] feat: upgrade to azcopy v10.27.0 for volume clone and snapshot restore
  .trivyignore
  pkg/azurefileplugin/Dockerfile
  test/sanity/run-test.sh
Labels: kind/feature, size/XS, approved, cncf-cla: yes

#2179 [release-1.29] feat: upgrade to azcopy v10.27.0 for volume clone and snapshot restore
  .trivyignore
  pkg/azurefileplugin/Dockerfile
  test/sanity/run-test.sh
Labels: kind/feature, size/XS, approved, cncf-cla: yes

#2172 feat: replace Get-Item powershell cmd with golang api on Windows HostProcess mode
  pkg/mounter/safe_mounter_host_process_windows.go
  pkg/os/smb/smb.go
Labels: kind/feature, ok-to-test, size/S, cncf-cla: yes

#2186 fix: tagValueDelimiter parameter mismatch
  pkg/azurefile/azurefile.go
Labels: kind/bug, size/XS, approved, cncf-cla: yes

#2185 revert: GetRemoteServerFromTarget on Windows cache optimization
  pkg/mounter/safe_mounter_host_process_windows.go
  pkg/mounter/safe_mounter_unix_test.go
  pkg/mounter/safe_mounter_windows.go
  pkg/os/smb/smb.go
  pkg/os/smb/smb_test.go
Labels: kind/cleanup, size/M, approved, cncf-cla: yes

#2182 feat: add a file watcher for Azure client cert auth
  go.mod
  pkg/azurefile/azure.go
  pkg/filewatcher/filewatcher.go
Labels: kind/bug, ok-to-test, size/M, cncf-cla: yes

#2192 feat: upgrade to azcopy v10.27.1 for volme snapshot and clone
  .trivyignore
  pkg/azurefileplugin/Dockerfile
  test/sanity/run-test.sh
Labels: kind/feature, size/XS, approved, cncf-cla: yes

#2198 [release-1.29] feat: upgrade to azcopy v10.27.1 for volme snapshot and clone
  .trivyignore
  pkg/azurefileplugin/Dockerfile
  test/sanity/run-test.sh
Labels: kind/feature, size/XS, approved, cncf-cla: yes

#2201 [release-1.29] fix: reduce get file share throttling when CreateSnapshot
  pkg/azurefile/controllerserver.go
  test/sanity/run-test.sh
Labels: kind/bug, size/XS, approved, cncf-cla: yes

#2204 cleanup: remove unused livenessProbe in registrar
  charts/latest/azurefile-csi-driver-v0.0.0.tgz
  charts/latest/azurefile-csi-driver/templates/csi-azurefile-node-windows.yaml
  charts/latest/azurefile-csi-driver/templates/csi-azurefile-node.yaml
  charts/latest/azurefile-csi-driver/values.yaml
  deploy/csi-azurefile-node-windows.yaml
  deploy/csi-azurefile-node.yaml
Labels: kind/cleanup, size/M, approved, cncf-cla: yes

#2206 [release-1.30] cleanup: remove unused livenessProbe in registrar
  charts/latest/azurefile-csi-driver-v1.30.6.tgz
  charts/latest/azurefile-csi-driver/templates/csi-azurefile-node-windows.yaml
  charts/latest/azurefile-csi-driver/templates/csi-azurefile-node.yaml
  charts/latest/azurefile-csi-driver/values.yaml
  deploy/csi-azurefile-node-windows.yaml
  deploy/csi-azurefile-node.yaml
Labels: kind/cleanup, size/M, approved, cncf-cla: yes

#2205 [release-1.31] cleanup: remove unused livenessProbe in registrar
  charts/latest/azurefile-csi-driver-1.31.0.tgz
  charts/latest/azurefile-csi-driver/templates/csi-azurefile-node-windows.yaml
  charts/latest/azurefile-csi-driver/templates/csi-azurefile-node.yaml
  charts/latest/azurefile-csi-driver/values.yaml
  deploy/csi-azurefile-node-windows.yaml
  deploy/csi-azurefile-node.yaml
Labels: kind/cleanup, size/M, approved, cncf-cla: yes

#2207 [release-1.29] cleanup: remove unused livenessProbe in registrar
  charts/latest/azurefile-csi-driver-v1.29.9.tgz
  charts/latest/azurefile-csi-driver/templates/csi-azurefile-node-windows.yaml
  charts/latest/azurefile-csi-driver/templates/csi-azurefile-node.yaml
  charts/latest/azurefile-csi-driver/values.yaml
  deploy/csi-azurefile-node-windows.yaml
  deploy/csi-azurefile-node.yaml
Labels: kind/cleanup, size/M, approved, cncf-cla: yes

#2208 Group all deps update into one pr.
  .github/dependabot.yaml
Labels: size/XS, lgtm, approved, cncf-cla: yes, kind/test

#2209 chore: update CSI spec to v1.10.0
  go.mod
  go.sum
  pkg/azurefile/azurefile.go
  pkg/azurefile/controllerserver.go
  pkg/azurefile/controllerserver_test.go
  pkg/azurefile/identityserver_test.go
  pkg/azurefile/nodeserver.go
  pkg/azurefile/nodeserver_test.go
  pkg/csi-common/utils_test.go
  vendor/github.com/container-storage-interface/spec/lib/go/csi/csi.pb.go
  vendor/github.com/container-storage-interface/spec/lib/go/csi/csi_grpc.pb.go
  vendor/modules.txt
Labels: kind/feature, approved, cncf-cla: yes, size/XXL

#2213 fix: increase snapshot container memory limit
  charts/README.md
  charts/latest/azurefile-csi-driver-v0.0.0.tgz
  charts/latest/azurefile-csi-driver/values.yaml
  deploy/csi-azurefile-controller.yaml
  deploy/csi-snapshot-controller.yaml
Labels: kind/bug, size/S, approved, cncf-cla: yes

#2214 [release-1.31] fix: increase snapshot container memory limit
  charts/README.md
  charts/latest/azurefile-csi-driver-1.31.0.tgz
  charts/latest/azurefile-csi-driver/values.yaml
  deploy/csi-azurefile-controller.yaml
  deploy/csi-snapshot-controller.yaml
Labels: kind/bug, size/S, approved, cncf-cla: yes

#2215 [release-1.30] fix: increase snapshot container memory limit
  charts/README.md
  charts/latest/azurefile-csi-driver-v1.30.6.tgz
  charts/latest/azurefile-csi-driver/values.yaml
  deploy/csi-azurefile-controller.yaml
  deploy/csi-snapshot-controller.yaml
Labels: kind/bug, size/S, approved, cncf-cla: yes

#2217 chore: increase wait-for-azcopy-timeout-minutes as 19min
  pkg/azurefile/azurefile_options.go
Labels: kind/feature, size/XS, approved, cncf-cla: yes

#2226 fix: ignore ShareAlreadyExists error in snapshot restore and clone
  pkg/azurefile/controllerserver.go
Labels: kind/bug, size/XS, approved, cncf-cla: yes
