Repository kubernetes-sigs/azurefile-csi-driver, pull requests merged in 2024-01, with the labels that each got.

#1651 test: enable volumeMountGroup external tests on nfs protocol
  test/external-e2e/testdriver-nfs.yaml
Labels: size/XS, approved, cncf-cla: yes, kind/test

#1653 chore: fix docs for workload identity
  docs/workload-identity-static-pv-mount.md
Labels: kind/documentation, size/XS, lgtm, approved, cncf-cla: yes

#1652 [release-1.29] cleanup: remove getClientID func
  pkg/azurefile/nodeserver.go
  pkg/azurefile/nodeserver_test.go
Labels: kind/cleanup, size/M, approved, cncf-cla: yes

#1654 feat: use cluster identity for using azcopy in volume cloning
  hack/update-mock.sh
  pkg/azurefile/azurefile.go
  pkg/azurefile/controllerserver.go
  pkg/azurefile/controllerserver_test.go
  pkg/util/util.go
  pkg/util/util_mock.go
  pkg/util/util_test.go
Labels: kind/feature, size/L, ok-to-test, lgtm, approved, cncf-cla: yes

#1661 test: use same azcopy version in sanity test
  test/sanity/run-test.sh
Labels: ok-to-test, size/S, cncf-cla: yes, kind/test

#1663 cleanup: remove csi-attacher config
  charts/latest/azurefile-csi-driver-v0.0.0.tgz
  charts/latest/azurefile-csi-driver/templates/csi-azurefile-controller.yaml
  charts/latest/azurefile-csi-driver/values.yaml
  deploy/csi-azurefile-controller.yaml
  hack/verify-helm-chart.sh
  pkg/azurefile/controllerserver.go
  pkg/azurefile/controllerserver_test.go
Labels: size/L, kind/cleanup, approved, cncf-cla: yes

#1664 [release-1.29] cleanup: remove csi-attacher config
  charts/latest/azurefile-csi-driver-v1.29.2.tgz
  charts/latest/azurefile-csi-driver/templates/csi-azurefile-controller.yaml
  charts/latest/azurefile-csi-driver/values.yaml
  deploy/csi-azurefile-controller.yaml
  hack/verify-helm-chart.sh
  pkg/azurefile/controllerserver.go
  pkg/azurefile/controllerserver_test.go
Labels: size/L, kind/cleanup, approved, cncf-cla: yes

#1668 chore: upgrade sidecar image versions
  charts/README.md
  charts/latest/azurefile-csi-driver-v0.0.0.tgz
  charts/latest/azurefile-csi-driver/values.yaml
  deploy/csi-azurefile-controller.yaml
  deploy/csi-azurefile-node-windows-hostprocess.yaml
  deploy/csi-azurefile-node-windows.yaml
  deploy/csi-azurefile-node.yaml
  deploy/csi-snapshot-controller.yaml
Labels: kind/feature, size/M, approved, cncf-cla: yes

#1669 feat: upgrade azcopy version to 10.22.2 for volume clone feature
  pkg/azurefileplugin/Dockerfile
  test/sanity/run-test.sh
Labels: kind/feature, size/S, approved, cncf-cla: yes

#1673 [release-1.28] feat: upgrade azcopy version to 10.22.2 for volume clone feature
  pkg/azurefileplugin/Dockerfile
  test/sanity/run-test.sh
Labels: kind/feature, size/XS, approved, cncf-cla: yes

#1672 [release-1.29] feat: upgrade azcopy version to 10.22.2 for volume clone feature
  pkg/azurefileplugin/Dockerfile
  test/sanity/run-test.sh
Labels: kind/feature, size/XS, approved, cncf-cla: yes

#1675 chore: add flag for azcopy use sas token by default
  pkg/azurefile/azurefile.go
  pkg/azurefile/azurefile_options.go
  pkg/azurefile/controllerserver.go
Labels: ok-to-test, size/XS, lgtm, approved, cncf-cla: yes, kind/test

#1677 fix: increase volume cloning timeout and reduce time cost
  pkg/azurefile/azurefile.go
  pkg/azurefile/azurefile_options.go
  pkg/azurefile/azurefile_test.go
Labels: kind/bug, size/S, approved, cncf-cla: yes
