Repository kubernetes-sigs/azurefile-csi-driver, pull requests merged in 2024-07, with the labels that each got.

#1961 test: fix trivy action failure
  .github/workflows/trivy.yaml
  .trivyignore
Labels: size/XS, approved, cncf-cla: yes

#1960 fix: incorrect status.creationTime value in snapshot creation with useDataPlaneAPI: “true”
  pkg/azurefile/controllerserver.go
Labels: kind/bug, ok-to-test, size/XS, lgtm, cncf-cla: yes

#1969 feat: add tagValueDelimiter parameter
  pkg/azurefile/azurefile.go
  pkg/azurefile/controllerserver.go
  pkg/azurefile/utils.go
  pkg/azurefile/utils_test.go
  test/e2e/testsuites/dynamically_provisioned_tags_tester.go
Labels: kind/feature, ok-to-test, size/M, lgtm, approved, cncf-cla: yes

#1972 feat: add allowSharedKeyAccess parameter
  docs/driver-parameters.md
  pkg/azurefile/azurefile.go
  pkg/azurefile/controllerserver.go
  pkg/azurefile/controllerserver_test.go
Labels: kind/feature, ok-to-test, size/M, lgtm, approved, cncf-cla: yes

#1977 cleanup: logs refine
  pkg/azurefile/nodeserver.go
Labels: kind/cleanup, size/XS, approved, cncf-cla: yes

#1981 cleanup: refine logs
  pkg/azurefile/nodeserver.go
Labels: kind/cleanup, size/XS, approved, cncf-cla: yes

#1985 test: add allowSharedKeyAccess e2e test
  test/e2e/dynamic_provisioning_test.go
Labels: size/XS, approved, cncf-cla: yes, kind/test

#1987 test: upgrade csi-test to v5.2.0 for more test coverage
  test/sanity/run-tests-all-clouds.sh
Labels: size/XS, approved, cncf-cla: yes, kind/test

#1989 feat: add metadata tag on the storage account created by the driver
  pkg/azurefile/controllerserver.go
  pkg/azurefile/controllerserver_test.go
Labels: kind/feature, ok-to-test, size/S, lgtm, approved, cncf-cla: yes

#1997 [release-1.29] fix: CVE-2024-5321
  go.mod
  go.sum
  vendor/k8s.io/apiserver/pkg/storage/cacher/watch_cache.go
  vendor/k8s.io/apiserver/pkg/storage/etcd3/metrics/metrics.go
  vendor/k8s.io/kubernetes/pkg/securitycontext/util.go
  vendor/k8s.io/kubernetes/pkg/util/filesystem/defaultfs.go
  vendor/k8s.io/kubernetes/pkg/util/filesystem/util_unix.go
  vendor/k8s.io/kubernetes/pkg/util/filesystem/util_windows.go
  vendor/k8s.io/kubernetes/pkg/volume/plugins.go
  vendor/k8s.io/kubernetes/test/e2e/storage/utils/create.go
  vendor/k8s.io/kubernetes/test/e2e/testing-manifests/storage-csi/external-attacher/rbac.yaml
  vendor/k8s.io/kubernetes/test/e2e/testing-manifests/storage-csi/external-health-monitor/external-health-monitor-controller/rbac.yaml
  vendor/k8s.io/kubernetes/test/e2e/testing-manifests/storage-csi/external-provisioner/rbac.yaml
  vendor/k8s.io/kubernetes/test/e2e/testing-manifests/storage-csi/external-resizer/rbac.yaml
  vendor/k8s.io/kubernetes/test/e2e/testing-manifests/storage-csi/external-snapshotter/csi-snapshotter/rbac-csi-snapshotter.yaml
  vendor/k8s.io/kubernetes/test/e2e/testing-manifests/storage-csi/hostpath/README.md
  vendor/k8s.io/kubernetes/test/e2e/testing-manifests/storage-csi/hostpath/hostpath/csi-hostpath-driverinfo.yaml
  vendor/k8s.io/kubernetes/test/e2e/testing-manifests/storage-csi/hostpath/hostpath/csi-hostpath-plugin.yaml
  vendor/k8s.io/kubernetes/test/e2e/testing-manifests/storage-csi/hostpath/hostpath/csi-hostpath-testing.yaml
  vendor/k8s.io/kubernetes/test/e2e/testing-manifests/storage-csi/mock/csi-mock-driver-attacher.yaml
  vendor/k8s.io/kubernetes/test/e2e/testing-manifests/storage-csi/mock/csi-mock-driver-resizer.yaml
  vendor/k8s.io/kubernetes/test/e2e/testing-manifests/storage-csi/mock/csi-mock-driver-snapshotter.yaml
  vendor/k8s.io/kubernetes/test/e2e/testing-manifests/storage-csi/mock/csi-mock-driver.yaml
  vendor/k8s.io/kubernetes/test/e2e/testing-manifests/storage-csi/mock/csi-mock-proxy.yaml
  vendor/k8s.io/kubernetes/test/e2e/testing-manifests/storage-csi/update-hostpath.sh
  vendor/k8s.io/kubernetes/test/utils/image/manifest.go
  vendor/modules.txt
Labels: kind/bug, size/L, approved, cncf-cla: yes

#1996 [release-1.30] fix: CVE-2024-5321
  go.mod
  go.sum
  vendor/k8s.io/kubernetes/pkg/securitycontext/util.go
  vendor/k8s.io/kubernetes/pkg/util/filesystem/defaultfs.go
  vendor/k8s.io/kubernetes/pkg/util/filesystem/util_unix.go
  vendor/k8s.io/kubernetes/pkg/util/filesystem/util_windows.go
  vendor/k8s.io/kubernetes/test/utils/image/manifest.go
  vendor/modules.txt
Labels: kind/bug, size/L, approved, cncf-cla: yes

#1998 [release-1.28] fix: CVE-2024-5321
  go.mod
  go.sum
  vendor/k8s.io/apiserver/pkg/storage/cacher/watch_cache.go
  vendor/k8s.io/apiserver/pkg/storage/etcd3/metrics/metrics.go
  vendor/k8s.io/cloud-provider/cloud.go
  vendor/k8s.io/kubernetes/pkg/securitycontext/util.go
  vendor/k8s.io/kubernetes/test/e2e/storage/utils/create.go
  vendor/k8s.io/kubernetes/test/e2e/testing-manifests/storage-csi/external-attacher/rbac.yaml
  vendor/k8s.io/kubernetes/test/e2e/testing-manifests/storage-csi/external-health-monitor/external-health-monitor-controller/rbac.yaml
  vendor/k8s.io/kubernetes/test/e2e/testing-manifests/storage-csi/external-provisioner/rbac.yaml
  vendor/k8s.io/kubernetes/test/e2e/testing-manifests/storage-csi/external-resizer/rbac.yaml
  vendor/k8s.io/kubernetes/test/e2e/testing-manifests/storage-csi/external-snapshotter/csi-snapshotter/rbac-csi-snapshotter.yaml
  vendor/k8s.io/kubernetes/test/e2e/testing-manifests/storage-csi/hostpath/README.md
  vendor/k8s.io/kubernetes/test/e2e/testing-manifests/storage-csi/hostpath/hostpath/csi-hostpath-driverinfo.yaml
  vendor/k8s.io/kubernetes/test/e2e/testing-manifests/storage-csi/hostpath/hostpath/csi-hostpath-plugin.yaml
  vendor/k8s.io/kubernetes/test/e2e/testing-manifests/storage-csi/hostpath/hostpath/csi-hostpath-testing.yaml
  vendor/k8s.io/kubernetes/test/e2e/testing-manifests/storage-csi/mock/csi-mock-driver-attacher.yaml
  vendor/k8s.io/kubernetes/test/e2e/testing-manifests/storage-csi/mock/csi-mock-driver-resizer.yaml
  vendor/k8s.io/kubernetes/test/e2e/testing-manifests/storage-csi/mock/csi-mock-driver-snapshotter.yaml
  vendor/k8s.io/kubernetes/test/e2e/testing-manifests/storage-csi/mock/csi-mock-driver.yaml
  vendor/k8s.io/kubernetes/test/e2e/testing-manifests/storage-csi/mock/csi-mock-proxy.yaml
  vendor/k8s.io/kubernetes/test/e2e/testing-manifests/storage-csi/update-hostpath.sh
  vendor/k8s.io/kubernetes/test/utils/image/manifest.go
  vendor/modules.txt
Labels: kind/bug, size/L, approved, cncf-cla: yes

#1995 fix: CVE-2024-5321
  go.mod
  go.sum
  vendor/k8s.io/kubernetes/pkg/securitycontext/util.go
  vendor/k8s.io/kubernetes/pkg/util/filesystem/defaultfs.go
  vendor/k8s.io/kubernetes/pkg/util/filesystem/util_unix.go
  vendor/k8s.io/kubernetes/pkg/util/filesystem/util_windows.go
  vendor/k8s.io/kubernetes/test/utils/image/manifest.go
  vendor/modules.txt
Labels: kind/bug, size/L, approved, cncf-cla: yes

#1999 doc: add nobrl mount option
  deploy/example/e2e_usage.md
  deploy/example/largeFileShares/storageclass-azurefile-largefileshares.yaml
  deploy/example/pv-azurefile-csi.yaml
  deploy/example/resize/README.md
  deploy/example/storageclass-azurefile-csi.yaml
  deploy/example/storageclass-azurefile-existing-share.yaml
  deploy/example/storageclass-azurefile-large-scale.yaml
  deploy/example/storageclass-azurefile-secret.yaml
Labels: size/S, kind/documentation, approved, cncf-cla: yes

#2002 doc: update new chart versions
  README.md
  charts/README.md
  charts/index.yaml
  charts/v1.30.4/azurefile-csi-driver-v1.30.4.tgz
  charts/v1.30.4/azurefile-csi-driver/Chart.yaml
  charts/v1.30.4/azurefile-csi-driver/templates/NOTES.txt
  charts/v1.30.4/azurefile-csi-driver/templates/_helpers.tpl
  charts/v1.30.4/azurefile-csi-driver/templates/crd-csi-snapshot.yaml
  charts/v1.30.4/azurefile-csi-driver/templates/csi-azurefile-controller.yaml
  charts/v1.30.4/azurefile-csi-driver/templates/csi-azurefile-driver.yaml
  charts/v1.30.4/azurefile-csi-driver/templates/csi-azurefile-node-windows-hostprocess.yaml
  charts/v1.30.4/azurefile-csi-driver/templates/csi-azurefile-node-windows.yaml
  charts/v1.30.4/azurefile-csi-driver/templates/csi-azurefile-node.yaml
  charts/v1.30.4/azurefile-csi-driver/templates/csi-snapshot-controller.yaml
  charts/v1.30.4/azurefile-csi-driver/templates/rbac-csi-azurefile-controller.yaml
  charts/v1.30.4/azurefile-csi-driver/templates/rbac-csi-azurefile-node.yaml
  charts/v1.30.4/azurefile-csi-driver/templates/rbac-csi-snapshot-controller.yaml
  charts/v1.30.4/azurefile-csi-driver/templates/serviceaccount-csi-azurefile-controller.yaml
  charts/v1.30.4/azurefile-csi-driver/templates/serviceaccount-csi-azurefile-node.yaml
  charts/v1.30.4/azurefile-csi-driver/templates/serviceaccount-csi-snapshot-controller.yaml
  charts/v1.30.4/azurefile-csi-driver/values.yaml
  deploy/v1.30.4/crd-csi-snapshot.yaml
  deploy/v1.30.4/csi-azurefile-controller.yaml
  deploy/v1.30.4/csi-azurefile-driver.yaml
  deploy/v1.30.4/csi-azurefile-node-windows-hostprocess.yaml
  deploy/v1.30.4/csi-azurefile-node-windows.yaml
  deploy/v1.30.4/csi-azurefile-node.yaml
  deploy/v1.30.4/csi-snapshot-controller.yaml
  deploy/v1.30.4/rbac-csi-azurefile-controller.yaml
  deploy/v1.30.4/rbac-csi-azurefile-node.yaml
  deploy/v1.30.4/rbac-csi-snapshot-controller.yaml
  docs/install-azurefile-csi-driver.md
  docs/install-csi-driver-v1.30.4.md
Labels: kind/documentation, approved, cncf-cla: yes, size/XXL

#2004 test: change default windows tests to use ltsc2022 image
  deploy/example/windows/deployment.yaml
  deploy/example/windows/statefulset.yaml
  hack/verify-examples.sh
Labels: size/S, approved, cncf-cla: yes, kind/test

#2007 [release-1.28] feat: add allowSharedKeyAccess parameter
  docs/driver-parameters.md
  pkg/azurefile/azurefile.go
  pkg/azurefile/controllerserver.go
  pkg/azurefile/controllerserver_test.go
Labels: kind/feature, ok-to-test, size/M, lgtm, approved, cncf-cla: yes

#2013 [release-1.30] fix: add pv patch permission with HonorPVReclaimPolicy enabled
  charts/latest/azurefile-csi-driver-v1.30.4.tgz
  charts/latest/azurefile-csi-driver/templates/rbac-csi-azurefile-controller.yaml
  charts/v1.30.2/azurefile-csi-driver-v1.30.2.tgz
  charts/v1.30.2/azurefile-csi-driver/templates/rbac-csi-azurefile-controller.yaml
  charts/v1.30.4/azurefile-csi-driver-v1.30.4.tgz
  charts/v1.30.4/azurefile-csi-driver/templates/rbac-csi-azurefile-controller.yaml
  deploy/rbac-csi-azurefile-controller.yaml
  deploy/v1.30.2/rbac-csi-azurefile-controller.yaml
  deploy/v1.30.4/rbac-csi-azurefile-controller.yaml
Labels: kind/bug, size/S, approved, cncf-cla: yes

#2014 [release-1.29] fix: add pv patch permission with HonorPVReclaimPolicy enabled
  charts/latest/azurefile-csi-driver-v1.29.6.tgz
  charts/latest/azurefile-csi-driver/templates/rbac-csi-azurefile-controller.yaml
  charts/v1.29.5/azurefile-csi-driver-v1.29.5.tgz
  charts/v1.29.5/azurefile-csi-driver/templates/rbac-csi-azurefile-controller.yaml
  deploy/rbac-csi-azurefile-controller.yaml
  deploy/v1.29.5/rbac-csi-azurefile-controller.yaml
Labels: kind/bug, size/XS, approved, cncf-cla: yes

#2012 fix: add pv patch permission with HonorPVReclaimPolicy enabled
  charts/latest/azurefile-csi-driver-v0.0.0.tgz
  charts/latest/azurefile-csi-driver/templates/rbac-csi-azurefile-controller.yaml
  charts/v1.29.5/azurefile-csi-driver-v1.29.5.tgz
  charts/v1.29.5/azurefile-csi-driver/templates/rbac-csi-azurefile-controller.yaml
  charts/v1.30.2/azurefile-csi-driver-v1.30.2.tgz
  charts/v1.30.2/azurefile-csi-driver/templates/rbac-csi-azurefile-controller.yaml
  charts/v1.30.4/azurefile-csi-driver-v1.30.4.tgz
  charts/v1.30.4/azurefile-csi-driver/templates/rbac-csi-azurefile-controller.yaml
  deploy/rbac-csi-azurefile-controller.yaml
  deploy/v1.29.5/rbac-csi-azurefile-controller.yaml
  deploy/v1.30.2/rbac-csi-azurefile-controller.yaml
  deploy/v1.30.4/rbac-csi-azurefile-controller.yaml
Labels: kind/bug, size/S, approved, cncf-cla: yes

#2015 feat: add grpc interceptor to azurefile driver
  go.mod
  go.sum
  pkg/azurefile/azurefile.go
  vendor/github.com/grpc-ecosystem/go-grpc-middleware/providers/prometheus/LICENSE
  vendor/github.com/grpc-ecosystem/go-grpc-middleware/providers/prometheus/client_metrics.go
  vendor/github.com/grpc-ecosystem/go-grpc-middleware/providers/prometheus/client_options.go
  vendor/github.com/grpc-ecosystem/go-grpc-middleware/providers/prometheus/constants.go
  vendor/github.com/grpc-ecosystem/go-grpc-middleware/providers/prometheus/doc.go
  vendor/github.com/grpc-ecosystem/go-grpc-middleware/providers/prometheus/options.go
  vendor/github.com/grpc-ecosystem/go-grpc-middleware/providers/prometheus/reporter.go
  vendor/github.com/grpc-ecosystem/go-grpc-middleware/providers/prometheus/server_metrics.go
  vendor/github.com/grpc-ecosystem/go-grpc-middleware/providers/prometheus/server_options.go
  vendor/github.com/grpc-ecosystem/go-grpc-middleware/v2/COPYRIGHT
  vendor/github.com/grpc-ecosystem/go-grpc-middleware/v2/LICENSE
  vendor/github.com/grpc-ecosystem/go-grpc-middleware/v2/interceptors/callmeta.go
  vendor/github.com/grpc-ecosystem/go-grpc-middleware/v2/interceptors/client.go
  vendor/github.com/grpc-ecosystem/go-grpc-middleware/v2/interceptors/doc.go
  vendor/github.com/grpc-ecosystem/go-grpc-middleware/v2/interceptors/reporter.go
  vendor/github.com/grpc-ecosystem/go-grpc-middleware/v2/interceptors/server.go
  vendor/github.com/stoewer/go-strcase/README.md
  vendor/github.com/stoewer/go-strcase/camel.go
  vendor/google.golang.org/grpc/reflection/README.md
  vendor/google.golang.org/grpc/reflection/adapt.go
  vendor/google.golang.org/grpc/reflection/grpc_reflection_v1/reflection.pb.go
  vendor/google.golang.org/grpc/reflection/grpc_reflection_v1/reflection_grpc.pb.go
  vendor/google.golang.org/grpc/reflection/grpc_reflection_v1alpha/reflection.pb.go
  vendor/google.golang.org/grpc/reflection/grpc_reflection_v1alpha/reflection_grpc.pb.go
  vendor/google.golang.org/grpc/reflection/internal/internal.go
  vendor/google.golang.org/grpc/reflection/serverreflection.go
  vendor/modules.txt
Labels: kind/feature, ok-to-test, lgtm, approved, cncf-cla: yes, size/XXL
