Repository kubernetes-sigs/azurefile-csi-driver, pull requests merged in 2024-06, with the labels that each got.

#1903 feat: upgrade to azcopy v10.25.0 for volume clone and snapshot restore feature
  .github/workflows/codespell.yml
  .github/workflows/trivy.yaml
  .trivyignore
  pkg/azurefileplugin/Dockerfile
  test/sanity/run-test.sh
Labels: kind/feature, size/S, approved, cncf-cla: yes

#1905 [release-1.28] feat: upgrade to azcopy v10.25.0 for volume clone and snapshot restore
  .github/workflows/codespell.yml
  .github/workflows/trivy.yaml
  .trivyignore
  pkg/azurefileplugin/Dockerfile
  test/sanity/run-test.sh
Labels: size/S, approved, cncf-cla: yes

#1909 fix: CVE-2024-35255
  .trivyignore
  go.mod
  go.sum
  vendor/github.com/Azure/azure-sdk-for-go/sdk/azidentity/.gitignore
  vendor/github.com/Azure/azure-sdk-for-go/sdk/azidentity/CHANGELOG.md
  vendor/github.com/Azure/azure-sdk-for-go/sdk/azidentity/MIGRATION.md
  vendor/github.com/Azure/azure-sdk-for-go/sdk/azidentity/README.md
  vendor/github.com/Azure/azure-sdk-for-go/sdk/azidentity/TOKEN_CACHING.MD
  vendor/github.com/Azure/azure-sdk-for-go/sdk/azidentity/TROUBLESHOOTING.md
  vendor/github.com/Azure/azure-sdk-for-go/sdk/azidentity/assets.json
  vendor/github.com/Azure/azure-sdk-for-go/sdk/azidentity/azure_cli_credential.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/azidentity/azure_pipelines_credential.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/azidentity/chained_token_credential.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/azidentity/ci.yml
  vendor/github.com/Azure/azure-sdk-for-go/sdk/azidentity/client_assertion_credential.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/azidentity/client_certificate_credential.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/azidentity/confidential_client.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/azidentity/default_azure_credential.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/azidentity/developer_credential_util.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/azidentity/device_code_credential.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/azidentity/environment_credential.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/azidentity/errors.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/azidentity/go.work.sum
  vendor/github.com/Azure/azure-sdk-for-go/sdk/azidentity/interactive_browser_credential.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/azidentity/managed-identity-matrix.json
  vendor/github.com/Azure/azure-sdk-for-go/sdk/azidentity/managed_identity_client.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/azidentity/managed_identity_credential.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/azidentity/on_behalf_of_credential.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/azidentity/public_client.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/azidentity/test-resources-post.ps1
  vendor/github.com/Azure/azure-sdk-for-go/sdk/azidentity/test-resources-pre.ps1
  vendor/github.com/Azure/azure-sdk-for-go/sdk/azidentity/test-resources.bicep
  vendor/github.com/Azure/azure-sdk-for-go/sdk/azidentity/version.go
  vendor/modules.txt
Labels: kind/bug, size/XL, approved, cncf-cla: yes

#1908 doc: add smb restore snapshot doc
  deploy/example/snapshot/README.md
  deploy/example/snapshot/nginx-pod-restored-snapshot.yaml
Labels: ok-to-test, kind/documentation, size/M, lgtm, cncf-cla: yes

#1914 [release-1.29] feat: upgrade to azcopy v10.25.0 for volume clone and snapshot restore
  .github/workflows/codespell.yml
  .github/workflows/trivy.yaml
  .trivyignore
  pkg/azurefileplugin/Dockerfile
  test/sanity/run-test.sh
Labels: kind/feature, size/S, approved, cncf-cla: yes

#1918 feat: upgrade to azcopy v10.25.1 for volume clone and snapshot restore
  .trivyignore
  pkg/azurefileplugin/Dockerfile
  test/sanity/run-test.sh
Labels: kind/feature, size/XS, approved, cncf-cla: yes

#1921 [release-1.28] feat: upgrade to azcopy v10.25.1 for volume clone and snapshot restore
  .trivyignore
  pkg/azurefileplugin/Dockerfile
  test/sanity/run-test.sh
Labels: kind/feature, size/XS, approved, cncf-cla: yes

#1920 [release-1.29] feat: upgrade to azcopy v10.25.1 for volume clone and snapshot restore
  .trivyignore
  pkg/azurefileplugin/Dockerfile
  test/sanity/run-test.sh
Labels: kind/feature, size/XS, approved, cncf-cla: yes

#1916 fix: shield guard issues
  charts/latest/azurefile-csi-driver-v0.0.0.tgz
  charts/latest/azurefile-csi-driver/templates/csi-azurefile-controller.yaml
  charts/latest/azurefile-csi-driver/templates/csi-snapshot-controller.yaml
  charts/v1.29.5/azurefile-csi-driver-v1.29.5.tgz
  charts/v1.29.5/azurefile-csi-driver/templates/csi-azurefile-controller.yaml
  charts/v1.29.5/azurefile-csi-driver/templates/csi-snapshot-controller.yaml
  charts/v1.30.2/azurefile-csi-driver-v1.30.2.tgz
  charts/v1.30.2/azurefile-csi-driver/templates/csi-azurefile-controller.yaml
  charts/v1.30.2/azurefile-csi-driver/templates/csi-snapshot-controller.yaml
  deploy/csi-azurefile-controller.yaml
  deploy/csi-snapshot-controller.yaml
  deploy/v1.29.5/csi-azurefile-controller.yaml
  deploy/v1.29.5/csi-snapshot-controller.yaml
  deploy/v1.30.2/csi-azurefile-controller.yaml
  deploy/v1.30.2/csi-snapshot-controller.yaml
Labels: kind/bug, size/L, ok-to-test, lgtm, approved, cncf-cla: yes

#1924 fix: shield guard issues on node
  charts/latest/azurefile-csi-driver-v0.0.0.tgz
  charts/latest/azurefile-csi-driver/templates/csi-azurefile-node-windows-hostprocess.yaml
  charts/latest/azurefile-csi-driver/templates/csi-azurefile-node-windows.yaml
  charts/latest/azurefile-csi-driver/templates/csi-azurefile-node.yaml
  charts/v1.29.5/azurefile-csi-driver-v1.29.5.tgz
  charts/v1.29.5/azurefile-csi-driver/templates/csi-azurefile-node-windows-hostprocess.yaml
  charts/v1.29.5/azurefile-csi-driver/templates/csi-azurefile-node-windows.yaml
  charts/v1.29.5/azurefile-csi-driver/templates/csi-azurefile-node.yaml
  charts/v1.30.2/azurefile-csi-driver-v1.30.2.tgz
  charts/v1.30.2/azurefile-csi-driver/templates/csi-azurefile-node-windows-hostprocess.yaml
  charts/v1.30.2/azurefile-csi-driver/templates/csi-azurefile-node-windows.yaml
  charts/v1.30.2/azurefile-csi-driver/templates/csi-azurefile-node.yaml
  deploy/csi-azurefile-node-windows-hostprocess.yaml
  deploy/csi-azurefile-node-windows.yaml
  deploy/csi-azurefile-node.yaml
  deploy/v1.29.5/csi-azurefile-node-windows-hostprocess.yaml
  deploy/v1.29.5/csi-azurefile-node-windows.yaml
  deploy/v1.29.5/csi-azurefile-node.yaml
  deploy/v1.30.2/csi-azurefile-node-windows-hostprocess.yaml
  deploy/v1.30.2/csi-azurefile-node-windows.yaml
  deploy/v1.30.2/csi-azurefile-node.yaml
Labels: kind/bug, size/L, ok-to-test, lgtm, approved, cncf-cla: yes

#1932 chore: fix workload identity doc
  docs/workload-identity-static-pv-mount.md
Labels: size/M, lgtm, approved, cncf-cla: yes

#1929 [release-1.28] fix shield guard on csi controller and node
  charts/latest/azurefile-csi-driver-v1.28.10.tgz
  charts/latest/azurefile-csi-driver/templates/csi-azurefile-controller.yaml
  charts/latest/azurefile-csi-driver/templates/csi-azurefile-node-windows-hostprocess.yaml
  charts/latest/azurefile-csi-driver/templates/csi-azurefile-node-windows.yaml
  charts/latest/azurefile-csi-driver/templates/csi-azurefile-node.yaml
  charts/latest/azurefile-csi-driver/templates/csi-snapshot-controller.yaml
  deploy/csi-azurefile-controller.yaml
  deploy/csi-azurefile-node-windows-hostprocess.yaml
  deploy/csi-azurefile-node-windows.yaml
  deploy/csi-azurefile-node.yaml
  deploy/csi-snapshot-controller.yaml
Labels: kind/bug, size/L, ok-to-test, lgtm, approved, cncf-cla: yes

#1930 [release-1.29] fix shield guard on csi controller and node
  charts/latest/azurefile-csi-driver-v1.29.5.tgz
  charts/latest/azurefile-csi-driver/templates/csi-azurefile-controller.yaml
  charts/latest/azurefile-csi-driver/templates/csi-azurefile-node-windows-hostprocess.yaml
  charts/latest/azurefile-csi-driver/templates/csi-azurefile-node-windows.yaml
  charts/latest/azurefile-csi-driver/templates/csi-azurefile-node.yaml
  charts/latest/azurefile-csi-driver/templates/csi-snapshot-controller.yaml
  deploy/csi-azurefile-controller.yaml
  deploy/csi-azurefile-node-windows-hostprocess.yaml
  deploy/csi-azurefile-node-windows.yaml
  deploy/csi-azurefile-node.yaml
  deploy/csi-snapshot-controller.yaml
Labels: kind/bug, size/L, ok-to-test, lgtm, approved, cncf-cla: yes

#1933 fix: shield guard issue on windows node hostprocess initContainer
  charts/latest/azurefile-csi-driver-v0.0.0.tgz
  charts/latest/azurefile-csi-driver/templates/csi-azurefile-node-windows-hostprocess.yaml
  charts/v1.29.5/azurefile-csi-driver-v1.29.5.tgz
  charts/v1.29.5/azurefile-csi-driver/templates/csi-azurefile-node-windows-hostprocess.yaml
  charts/v1.30.2/azurefile-csi-driver-v1.30.2.tgz
  charts/v1.30.2/azurefile-csi-driver/templates/csi-azurefile-node-windows-hostprocess.yaml
  deploy/csi-azurefile-node-windows-hostprocess.yaml
  deploy/v1.29.5/csi-azurefile-node-windows-hostprocess.yaml
  deploy/v1.30.2/csi-azurefile-node-windows-hostprocess.yaml
Labels: kind/bug, ok-to-test, size/S, cncf-cla: yes

#1935 doc: refine volumeHandle doc
  deploy/example/pv-azurefile-csi.yaml
  deploy/example/pv-azurefile-nfs.yaml
Labels: kind/documentation, size/XS, approved, cncf-cla: yes

#1934 fix: refine GetRemoteServerFromTarget on Windows with cache optimization
  pkg/mounter/safe_mounter_host_process_windows.go
  pkg/mounter/safe_mounter_windows.go
  pkg/os/smb/smb.go
  pkg/os/smb/smb_test.go
Labels: kind/bug, size/M, approved, cncf-cla: yes

#1940 fix: allow more cache hit in GetRemoteServerFromTarget on hpc deployment
  pkg/os/smb/smb.go
  pkg/util/util.go
Labels: kind/feature, size/S, approved, cncf-cla: yes

#1943 [release-1.28] fix: refine GetRemoteServerFromTarget on Windows with cache optimization
  pkg/os/smb/smb.go
  pkg/util/util.go
Labels: kind/bug, size/S, approved, cncf-cla: yes

#1944 chore: upgrade CSI driver sidecar image versions
  charts/README.md
  charts/latest/azurefile-csi-driver-v0.0.0.tgz
  charts/latest/azurefile-csi-driver/values.yaml
  charts/v1.30.2/azurefile-csi-driver-v1.30.2.tgz
  charts/v1.30.2/azurefile-csi-driver/values.yaml
  deploy/csi-azurefile-controller.yaml
  deploy/csi-azurefile-node-windows-hostprocess.yaml
  deploy/csi-azurefile-node-windows.yaml
  deploy/csi-azurefile-node.yaml
  deploy/csi-snapshot-controller.yaml
  deploy/v1.30.2/csi-azurefile-controller.yaml
  deploy/v1.30.2/csi-azurefile-node-windows-hostprocess.yaml
  deploy/v1.30.2/csi-azurefile-node-windows.yaml
  deploy/v1.30.2/csi-azurefile-node.yaml
  deploy/v1.30.2/csi-snapshot-controller.yaml
Labels: kind/feature, size/M, approved, cncf-cla: yes

#1945 [release-1.30] chore: upgrade CSI driver sidecar image versions
  charts/README.md
  charts/latest/azurefile-csi-driver-v1.30.2.tgz
  charts/latest/azurefile-csi-driver/values.yaml
  charts/v1.30.2/azurefile-csi-driver-v1.30.2.tgz
  charts/v1.30.2/azurefile-csi-driver/values.yaml
  deploy/csi-azurefile-controller.yaml
  deploy/csi-azurefile-node-windows-hostprocess.yaml
  deploy/csi-azurefile-node-windows.yaml
  deploy/csi-azurefile-node.yaml
  deploy/csi-snapshot-controller.yaml
  deploy/v1.30.2/csi-azurefile-controller.yaml
  deploy/v1.30.2/csi-azurefile-node-windows-hostprocess.yaml
  deploy/v1.30.2/csi-azurefile-node-windows.yaml
  deploy/v1.30.2/csi-azurefile-node.yaml
  deploy/v1.30.2/csi-snapshot-controller.yaml
Labels: kind/feature, size/M, approved, cncf-cla: yes

#1952 fix: add azcopy-dir since volume cloning supported from v1.28.6 and v1.29.1
  charts/v1.28.10/azurefile-csi-driver-v1.28.10.tgz
  charts/v1.28.10/azurefile-csi-driver/templates/csi-azurefile-controller.yaml
  charts/v1.28.6/azurefile-csi-driver-v1.28.6.tgz
  charts/v1.28.6/azurefile-csi-driver/templates/csi-azurefile-controller.yaml
  charts/v1.28.7/azurefile-csi-driver-v1.28.7.tgz
  charts/v1.28.7/azurefile-csi-driver/templates/csi-azurefile-controller.yaml
  charts/v1.28.9/azurefile-csi-driver-v1.28.9.tgz
  charts/v1.28.9/azurefile-csi-driver/templates/csi-azurefile-controller.yaml
  charts/v1.29.1/azurefile-csi-driver-v1.29.1.tgz
  charts/v1.29.1/azurefile-csi-driver/templates/csi-azurefile-controller.yaml
  charts/v1.29.2/azurefile-csi-driver-v1.29.2.tgz
  charts/v1.29.2/azurefile-csi-driver/templates/csi-azurefile-controller.yaml
  charts/v1.29.4/azurefile-csi-driver-v1.29.4.tgz
  charts/v1.29.4/azurefile-csi-driver/templates/csi-azurefile-controller.yaml
  charts/v1.29.5/azurefile-csi-driver-v1.29.5.tgz
  charts/v1.29.5/azurefile-csi-driver/templates/csi-azurefile-controller.yaml
  charts/v1.30.0/azurefile-csi-driver-v1.30.0.tgz
  charts/v1.30.0/azurefile-csi-driver/templates/csi-azurefile-controller.yaml
  charts/v1.30.1/azurefile-csi-driver-v1.30.1.tgz
  charts/v1.30.1/azurefile-csi-driver/templates/csi-azurefile-controller.yaml
  deploy/v1.28.10/csi-azurefile-controller.yaml
  deploy/v1.28.6/csi-azurefile-controller.yaml
  deploy/v1.28.7/csi-azurefile-controller.yaml
  deploy/v1.28.9/csi-azurefile-controller.yaml
  deploy/v1.29.1/csi-azurefile-controller.yaml
  deploy/v1.29.2/csi-azurefile-controller.yaml
  deploy/v1.29.4/csi-azurefile-controller.yaml
  deploy/v1.29.5/csi-azurefile-controller.yaml
  deploy/v1.30.0/csi-azurefile-controller.yaml
  deploy/v1.30.1/csi-azurefile-controller.yaml
Labels: kind/bug, ok-to-test, size/M, lgtm, approved, cncf-cla: yes
