Repository kubernetes-sigs/azurefile-csi-driver, pull requests merged in 2025-01, with the labels that each got.

#2313 test: exclude some go fake files in ut coverage
  .github/workflows/linux.yaml
Labels: size/XS, approved, cncf-cla: yes, kind/test

#2314 chore: set GoMaxProcs as 2
  pkg/azurefile/azurefile_options.go
  pkg/azurefileplugin/main.go
Labels: kind/feature, size/XS, approved, cncf-cla: yes

#2316 fix: switch to data plane API call when create snapshot is throttled
  pkg/azurefile/azurefile.go
  pkg/azurefile/controllerserver.go
  pkg/azurefile/utils.go
  pkg/azurefile/utils_test.go
Labels: kind/bug, size/M, approved, cncf-cla: yes

#2321 Replace github.com/golang/mock/gomock with go.uber.org/mock/gomock
  go.mod
  go.sum
  pkg/azurefile/directvolume_mock.go
  pkg/azurefile/nodeserver_test.go
  pkg/azurefile/resolver_mock.go
  vendor/github.com/golang/mock/AUTHORS
  vendor/github.com/golang/mock/CONTRIBUTORS
  vendor/github.com/golang/mock/LICENSE
  vendor/github.com/golang/mock/gomock/call.go
  vendor/github.com/golang/mock/gomock/callset.go
  vendor/github.com/golang/mock/gomock/controller.go
  vendor/github.com/golang/mock/gomock/matchers.go
  vendor/modules.txt
Labels: kind/cleanup, lgtm, approved, cncf-cla: yes, size/XXL

#2326 test: exclude some go fake files in ut coverage
  .github/workflows/linux.yaml
Labels: size/XS, approved, cncf-cla: yes, kind/test

#2327 test: add UT for filewatcher
  pkg/filewatcher/filewatcher.go
  pkg/filewatcher/filewatcher_test.go
Labels: ok-to-test, size/M, lgtm, approved, cncf-cla: yes

#2335 chore: fix azcopy download error
  pkg/azurefileplugin/Dockerfile
  test/sanity/run-test.sh
Labels: kind/cleanup, size/XS, approved, cncf-cla: yes

#2310 doc: Update examples for mount permissions setting
  deploy/example/pv-azurefile-csi.yaml
  deploy/example/storageclass-azurefile-csi.yaml
  docs/install-csi-driver-master.md
Labels: kind/feature, ok-to-test, size/XS, approved, cncf-cla: yes

#2338 [release-1.29] chore: fix azcopy download error
  pkg/azurefileplugin/Dockerfile
  test/sanity/run-test.sh
Labels: kind/cleanup, size/XS, approved, cncf-cla: yes

#2337 [release-1.30] chore: fix azcopy download error
  pkg/azurefileplugin/Dockerfile
  test/sanity/run-test.sh
Labels: kind/cleanup, size/XS, approved, cncf-cla: yes

#2339 test: add UT for ListenEndpoint in utils.go
  pkg/csi-common/utils.go
  pkg/csi-common/utils_test.go
Labels: ok-to-test, size/M, lgtm, approved, cncf-cla: yes

#2340 test: refine UT for ListenEndpoint in utils.go
  pkg/csi-common/utils.go
  pkg/csi-common/utils_test.go
Labels: ok-to-test, size/S, lgtm, approved, cncf-cla: yes

#2341 chore: use original Cloud backoff for Delete and Resize file share
  pkg/azurefile/azurefile.go
  pkg/azurefile/utils.go
  pkg/azurefile/utils_test.go
Labels: kind/cleanup, size/M, lgtm, approved, cncf-cla: yes

#2343 test: add unit test
  .github/workflows/linux.yaml
  pkg/azurefile/utils_test.go
  pkg/util/util.go
  pkg/util/util_test.go
  pkg/util/util_windows.go
Labels: size/L, approved, cncf-cla: yes, kind/test

#2345 test: add UT for azurefile_dataplane_client.go
  pkg/azurefile/azurefile_dataplane_client_test.go
Labels: ok-to-test, size/M, lgtm, approved, cncf-cla: yes

#2142 feat: support Provisioned v2 Azure File share sku
  pkg/azurefile/controllerserver.go
Labels: kind/feature, size/XS, approved, cncf-cla: yes

#2351 Fix: add DisableAzureStackCloud to customize arm endpoint
  go.mod
  go.sum
  vendor/github.com/Azure/azure-sdk-for-go/sdk/azidentity/BREAKING_CHANGES.md
  vendor/github.com/Azure/azure-sdk-for-go/sdk/azidentity/CHANGELOG.md
  vendor/github.com/Azure/azure-sdk-for-go/sdk/azidentity/README.md
  vendor/github.com/Azure/azure-sdk-for-go/sdk/azidentity/TOKEN_CACHING.MD
  vendor/github.com/Azure/azure-sdk-for-go/sdk/azidentity/TROUBLESHOOTING.md
  vendor/github.com/Azure/azure-sdk-for-go/sdk/azidentity/azidentity.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/azidentity/azure_cli_credential.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/azidentity/azure_developer_cli_credential.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/azidentity/chained_token_credential.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/azidentity/ci.yml
  vendor/github.com/Azure/azure-sdk-for-go/sdk/azidentity/confidential_client.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/azidentity/default_azure_credential.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/azidentity/device_code_credential.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/azidentity/interactive_browser_credential.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/azidentity/managed_identity_client.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/azidentity/public_client.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/azidentity/test-resources-post.ps1
  vendor/github.com/Azure/azure-sdk-for-go/sdk/azidentity/version.go
  vendor/go.opentelemetry.io/otel/CHANGELOG.md
  vendor/go.opentelemetry.io/otel/README.md
  vendor/go.opentelemetry.io/otel/RELEASING.md
  vendor/go.opentelemetry.io/otel/renovate.json
  vendor/go.opentelemetry.io/otel/version.go
  vendor/go.opentelemetry.io/otel/versions.yaml
  vendor/k8s.io/api/resource/v1alpha3/generated.proto
  vendor/k8s.io/api/resource/v1alpha3/types.go
  vendor/k8s.io/api/resource/v1alpha3/types_swagger_doc_generated.go
  vendor/k8s.io/api/resource/v1beta1/generated.proto
  vendor/k8s.io/api/resource/v1beta1/types.go
  vendor/k8s.io/api/resource/v1beta1/types_swagger_doc_generated.go
  vendor/modules.txt
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azclient/virtualmachineclient/interface.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azclient/virtualmachineclient/zz_generated_client.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azclient/virtualmachinescalesetclient/interface.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azclient/virtualmachinescalesetclient/zz_generated_client.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azclient/virtualmachinescalesetvmclient/interface.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azclient/virtualmachinescalesetvmclient/zz_generated_client.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_vmss.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/config/azure.go
Labels: kind/bug, size/XL, lgtm, approved, cncf-cla: yes

#2354 fix: only reset cloud config when cloud name is AzureStackCloud
  go.mod
  go.sum
  vendor/modules.txt
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azclient/cloud.go
Labels: kind/bug, size/S, approved, cncf-cla: yes

#2359 chore: upgrade azcopy to v10.28.0
  .github/workflows/trivy.yaml
  .trivyignore
  pkg/azurefileplugin/Dockerfile
  test/sanity/run-test.sh
Labels: kind/feature, size/S, approved, cncf-cla: yes

#2360 chore: upgrade CSI driver sidecar image versions
  charts/README.md
  charts/latest/azurefile-csi-driver-v0.0.0.tgz
  charts/latest/azurefile-csi-driver/values.yaml
  deploy/csi-azurefile-controller.yaml
  deploy/csi-azurefile-node-windows-hostprocess.yaml
  deploy/csi-azurefile-node-windows.yaml
  deploy/csi-azurefile-node.yaml
Labels: kind/feature, size/M, approved, cncf-cla: yes

#2363 [release-1.29] chore: upgrade azcopy to v10.28.0
  .github/workflows/trivy.yaml
  .trivyignore
  pkg/azurefileplugin/Dockerfile
  test/sanity/run-test.sh
Labels: kind/feature, size/S, approved, cncf-cla: yes

#2364 [release-1.31] chore: upgrade CSI driver sidecar image versions
  charts/README.md
  charts/latest/azurefile-csi-driver-1.31.3.tgz
  charts/latest/azurefile-csi-driver/values.yaml
  deploy/csi-azurefile-controller.yaml
  deploy/csi-azurefile-node-windows-hostprocess.yaml
  deploy/csi-azurefile-node-windows.yaml
  deploy/csi-azurefile-node.yaml
Labels: kind/feature, size/M, approved, cncf-cla: yes

#2365 [release-1.30] chore: upgrade CSI driver sidecar image versions
  charts/README.md
  charts/latest/azurefile-csi-driver-v1.30.7.tgz
  charts/latest/azurefile-csi-driver/values.yaml
  deploy/csi-azurefile-controller.yaml
  deploy/csi-azurefile-node-windows-hostprocess.yaml
  deploy/csi-azurefile-node-windows.yaml
  deploy/csi-azurefile-node.yaml
Labels: kind/feature, size/M, approved, cncf-cla: yes
