Repository kubernetes-sigs/azurefile-csi-driver, pull requests merged in 2025-06, with the labels that each got.

#2596 chore: migrate csi driver sidecar images to dalec images
  charts/latest/azurefile-csi-driver-v0.0.0.tgz
  charts/latest/azurefile-csi-driver/values.yaml
  deploy/csi-azurefile-controller.yaml
  deploy/csi-azurefile-node-windows-hostprocess.yaml
  deploy/csi-azurefile-node-windows.yaml
  deploy/csi-azurefile-node.yaml
Labels: kind/cleanup, size/S, approved, cncf-cla: yes

#2598 chore: migrate csi-resizer sidecar image to dalec image
  charts/latest/azurefile-csi-driver-v0.0.0.tgz
  charts/latest/azurefile-csi-driver/values.yaml
  deploy/csi-azurefile-controller.yaml
Labels: kind/cleanup, size/XS, approved, cncf-cla: yes

#2599 fix: disable WMI call method on Windows node
  pkg/azurefile/azurefile_options.go
Labels: kind/bug, size/XS, approved, cncf-cla: yes

#2605 [release-1.32] chore: migrate csi driver sidecar images to dalec images
  charts/latest/azurefile-csi-driver-1.32.4.tgz
  charts/latest/azurefile-csi-driver/values.yaml
  deploy/csi-azurefile-controller.yaml
  deploy/csi-azurefile-node-windows-hostprocess.yaml
  deploy/csi-azurefile-node-windows.yaml
  deploy/csi-azurefile-node.yaml
Labels: kind/cleanup, size/S, approved, cncf-cla: yes

#2608 doc: add StandardV2_LRS in doc examples
  deploy/example/largeFileShares/storageclass-azurefile-largefileshares.yaml
  deploy/example/storageclass-azurefile-csi.yaml
Labels: kind/documentation, size/XS, approved, cncf-cla: yes

#2611 test: fix CVE-2025-4673 in trivy action
  .github/workflows/trivy.yaml
  .trivyignore
Labels: kind/failing-test, size/XS, approved, cncf-cla: yes

#2617 [release-1.31] test: fix golint errors
  .github/workflows/static.yaml
  pkg/azurefile/controllerserver.go
  pkg/csi-common/driver.go
  pkg/csi-common/utils.go
  pkg/csi-common/utils_test.go
Labels: size/M, kind/failing-test, approved, cncf-cla: yes

#2616 feat: support encryptInTransit mountOption in nfs volume
  pkg/azurefile/nodeserver.go
  pkg/azurefile/utils.go
  pkg/azurefile/utils_test.go
  test/e2e/dynamic_provisioning_test.go
Labels: kind/feature, size/L, approved, cncf-cla: yes

#2619 [release-1.30] test: fix golint errors
  .github/workflows/static.yaml
  .github/workflows/trivy.yaml
  .trivyignore
  pkg/azurefile/controllerserver.go
  pkg/csi-common/driver.go
  pkg/csi-common/utils.go
  pkg/csi-common/utils_test.go
Labels: size/M, kind/failing-test, approved, cncf-cla: yes

#2620 fix: aznfs package install failure on arm64 node
  pkg/azurefile-proxy/init.sh
Labels: kind/bug, size/XS, approved, cncf-cla: yes

#2623 chore: migrate csi driver sidecar images to dalec images
  charts/latest/azurefile-csi-driver-v0.0.0.tgz
  charts/latest/azurefile-csi-driver/values.yaml
  deploy/csi-azurefile-controller.yaml
Labels: kind/cleanup, size/XS, approved, cncf-cla: yes

#2624 [release-1.33] chore: migrate csi driver sidecar images to dalec images
  charts/latest/azurefile-csi-driver-1.33.2.tgz
  charts/latest/azurefile-csi-driver/values.yaml
  deploy/csi-azurefile-controller.yaml
Labels: kind/cleanup, size/XS, approved, cncf-cla: yes

#2600 fix: only use the permission bits for chmod
  pkg/azurefile/utils.go
  pkg/azurefile/utils_test.go
Labels: kind/bug, size/M, lgtm, approved, cncf-cla: yes

#2636 [release-1.32] fix: CVE-2025-4563
  go.mod
  go.sum
  vendor/k8s.io/kubernetes/pkg/apis/core/validation/validation.go
  vendor/k8s.io/kubernetes/pkg/features/kube_features.go
  vendor/k8s.io/kubernetes/pkg/features/versioned_kube_features.go
  vendor/k8s.io/kubernetes/pkg/kubelet/config/common.go
  vendor/k8s.io/kubernetes/pkg/util/kernel/constants.go
  vendor/k8s.io/kubernetes/pkg/volume/util/resize_util.go
  vendor/k8s.io/kubernetes/test/utils/image/manifest.go
  vendor/modules.txt
Labels: kind/bug, size/M, approved, cncf-cla: yes
