Repository kubernetes-sigs/azurefile-csi-driver, pull requests merged in 2025-07, with the labels that each got.

#2609 feat: Migrate PathValid and SMB API to use WMI and Win32 API
  go.mod
  pkg/azurefile/azurefile_options.go
  pkg/mounter/safe_mounter_host_process_windows.go
  pkg/os/cim/smb.go
  pkg/os/cim/wmi.go
  pkg/os/filesystem/filesystem.go
  pkg/os/smb/smb_cim.go
Labels: size/L, lgtm, approved, cncf-cla: yes

#2647 [release-1.33] chore: fix helm chart index on release-1.33
  charts/index.yaml
Labels: kind/bug, size/L, approved, cncf-cla: yes

#2650 chore: upgrade snapshot image version to v8.3.0
  charts/README.md
  charts/latest/azurefile-csi-driver-v0.0.0.tgz
  charts/latest/azurefile-csi-driver/values.yaml
  deploy/csi-azurefile-controller.yaml
  deploy/csi-snapshot-controller.yaml
Labels: kind/feature, size/S, approved, cncf-cla: yes

#2651 [release-1.33] chore: upgrade snapshot image version to v8.3.0
  charts/README.md
  charts/latest/azurefile-csi-driver-1.33.3.tgz
  charts/latest/azurefile-csi-driver/values.yaml
  deploy/csi-azurefile-controller.yaml
  deploy/csi-snapshot-controller.yaml
Labels: kind/feature, size/S, approved, cncf-cla: yes

#2660 cleanup: decrease parsing volumeID log level
  pkg/azurefile/azurefile.go
Labels: kind/cleanup, size/XS, approved, cncf-cla: yes

#2666 cleanup: refine clientID parameter parsing
  pkg/azurefile/azurefile.go
  pkg/azurefile/controllerserver.go
  pkg/azurefile/controllerserver_test.go
  pkg/azurefile/nodeserver.go
Labels: kind/cleanup, size/S, approved, cncf-cla: yes

#2671 feat: support provisionedBandwidth, provisionedIops parameter for file share v2
  pkg/azurefile/azurefile.go
  pkg/azurefile/azurefile_interface.go
  pkg/azurefile/azurefile_mgmt_client.go
  pkg/azurefile/controllerserver.go
  pkg/azurefile/controllerserver_test.go
Labels: kind/feature, size/L, approved, cncf-cla: yes

#2673 cleanup: refine kataNode label matching
  pkg/azurefile/azurefile.go
  pkg/azurefile/azurefile_test.go
Labels: size/L, kind/cleanup, approved, cncf-cla: yes

#2678 [release-1.30] fix: CVE-2025-22868
  go.mod
  go.sum
  vendor/golang.org/x/oauth2/LICENSE
  vendor/golang.org/x/oauth2/README.md
  vendor/golang.org/x/oauth2/internal/doc.go
  vendor/golang.org/x/oauth2/internal/oauth2.go
  vendor/golang.org/x/oauth2/internal/token.go
  vendor/golang.org/x/oauth2/internal/transport.go
  vendor/golang.org/x/oauth2/oauth2.go
  vendor/golang.org/x/oauth2/pkce.go
  vendor/golang.org/x/oauth2/token.go
  vendor/golang.org/x/oauth2/transport.go
  vendor/modules.txt
Labels: kind/bug, size/L, approved, cncf-cla: yes

#2679 chore: make runtimeClassHandler and confidentialContainerLabel configurable
  pkg/azurefile/azurefile.go
  pkg/azurefile/azurefile_test.go
  pkg/azurefile/controllerserver.go
  pkg/azurefile/controllerserver_test.go
  pkg/azurefile/nodeserver.go
  pkg/azurefile/nodeserver_test.go
  pkg/azurefile/utils.go
  pkg/azurefile/utils_test.go
Labels: size/L, kind/cleanup, approved, cncf-cla: yes

#2688 fix: only unmount kata volume if it's kata node
  pkg/azurefile/nodeserver.go
  pkg/azurefile/nodeserver_test.go
Labels: kind/bug, size/S, approved, cncf-cla: yes

#2695 [release-1.32] chore: make runtimeClassHandler, confidentialContainerLabel configurable
  pkg/azurefile/azurefile.go
  pkg/azurefile/azurefile_test.go
  pkg/azurefile/controllerserver.go
  pkg/azurefile/controllerserver_test.go
  pkg/azurefile/nodeserver.go
  pkg/azurefile/nodeserver_test.go
  pkg/azurefile/utils.go
  pkg/azurefile/utils_test.go
Labels: size/L, kind/cleanup, approved, cncf-cla: yes
