Repository kubernetes-sigs/azurefile-csi-driver, pull requests merged in 2025-04, with the labels that each got.

#2486 cleanup: kata mount logs
  pkg/azurefile/nodeserver.go
  pkg/azurefile/utils.go
Labels: kind/cleanup, size/XS, approved, cncf-cla: yes

#2485 chore: upgrade snapshot CRD to v8.2.0
  charts/latest/azurefile-csi-driver-v0.0.0.tgz
  charts/latest/azurefile-csi-driver/templates/crd-csi-snapshot.yaml
  charts/v1.31.5/azurefile-csi-driver-1.31.5.tgz
  charts/v1.31.5/azurefile-csi-driver/templates/crd-csi-snapshot.yaml
  charts/v1.32.1/azurefile-csi-driver-1.32.1.tgz
  charts/v1.32.1/azurefile-csi-driver/templates/crd-csi-snapshot.yaml
  deploy/crd-csi-snapshot.yaml
  deploy/v1.31.5/crd-csi-snapshot.yaml
  deploy/v1.32.1/crd-csi-snapshot.yaml
Labels: kind/feature, approved, cncf-cla: yes, size/XXL

#2488 chore: increase retry-interval-max in snapshot controller
  charts/latest/azurefile-csi-driver-v0.0.0.tgz
  charts/latest/azurefile-csi-driver/templates/csi-snapshot-controller.yaml
  deploy/csi-snapshot-controller.yaml
Labels: kind/feature, size/XS, approved, cncf-cla: yes

#2490 fix: storageEndPointSuffix in on-prem cluster
  pkg/azurefile/azurefile.go
Labels: kind/bug, size/S, approved, cncf-cla: yes

#2495 doc: add linked access permissions required for subnets/write doc
  docs/driver-parameters.md
Labels: ok-to-test, kind/documentation, size/XS, lgtm, approved, cncf-cla: yes

#2498 test: fix CVE-2025-22871 in trivy action
  .github/workflows/trivy.yaml
  .trivyignore
Labels: kind/failing-test, size/XS, approved, cncf-cla: yes

#2499 [release-1.32] test: fix CVE-2025-22871 in trivy action
  .github/workflows/trivy.yaml
  .trivyignore
Labels: kind/failing-test, size/XS, approved, cncf-cla: yes

#2504 [release-1.32] chore: upgrade snapshot CRD to v8.2.0
  charts/latest/azurefile-csi-driver-1.32.1.tgz
  charts/latest/azurefile-csi-driver/templates/crd-csi-snapshot.yaml
  charts/latest/azurefile-csi-driver/templates/csi-snapshot-controller.yaml
  deploy/crd-csi-snapshot.yaml
  deploy/csi-snapshot-controller.yaml
Labels: kind/feature, approved, cncf-cla: yes, size/XXL

#2505 cleanup: remove deprecated wait.PollImediate function
  pkg/azurefile/azurefile.go
  pkg/azurefile/controllerserver.go
  pkg/azurefile/controllerserver_test.go
  test/e2e/testsuites/testsuites.go
Labels: kind/cleanup, size/S, approved, cncf-cla: yes

#2510 test: add more ut
  pkg/azurefile/azurefile.go
  pkg/azurefile/azurefile_test.go
Labels: size/L, approved, cncf-cla: yes, kind/test

#2513 doc: add missing permission using PrivateEndpoint
  docs/driver-parameters.md
Labels: kind/documentation, size/XS, approved, cncf-cla: yes

#2516 fix: goroutine leak
  go.mod
  pkg/util/util.go
  pkg/util/util_test.go
  vendor/go.uber.org/goleak/.gitignore
  vendor/go.uber.org/goleak/.golangci.yml
  vendor/go.uber.org/goleak/CHANGELOG.md
  vendor/go.uber.org/goleak/LICENSE
  vendor/go.uber.org/goleak/Makefile
  vendor/go.uber.org/goleak/README.md
  vendor/go.uber.org/goleak/doc.go
  vendor/go.uber.org/goleak/internal/stack/doc.go
  vendor/go.uber.org/goleak/internal/stack/scan.go
  vendor/go.uber.org/goleak/internal/stack/stacks.go
  vendor/go.uber.org/goleak/leaks.go
  vendor/go.uber.org/goleak/options.go
  vendor/go.uber.org/goleak/testmain.go
  vendor/go.uber.org/goleak/tracestack_new.go
  vendor/modules.txt
Labels: kind/bug, lgtm, approved, cncf-cla: yes, size/XXL

#2521 [release-1.29] fix: goroutine leak when timeout
  go.mod
  pkg/util/util.go
  pkg/util/util_test.go
  vendor/go.uber.org/goleak/.gitignore
  vendor/go.uber.org/goleak/.golangci.yml
  vendor/go.uber.org/goleak/CHANGELOG.md
  vendor/go.uber.org/goleak/LICENSE
  vendor/go.uber.org/goleak/Makefile
  vendor/go.uber.org/goleak/README.md
  vendor/go.uber.org/goleak/doc.go
  vendor/go.uber.org/goleak/internal/stack/doc.go
  vendor/go.uber.org/goleak/internal/stack/scan.go
  vendor/go.uber.org/goleak/internal/stack/stacks.go
  vendor/go.uber.org/goleak/leaks.go
  vendor/go.uber.org/goleak/options.go
  vendor/go.uber.org/goleak/testmain.go
  vendor/go.uber.org/goleak/tracestack_new.go
  vendor/modules.txt
Labels: kind/bug, approved, cncf-cla: yes, size/XXL

#2525 [release-1.28] fix: CVE-2025-22872
  go.mod
  go.sum
  vendor/golang.org/x/crypto/cryptobyte/asn1.go
  vendor/golang.org/x/crypto/internal/poly1305/mac_noasm.go
  vendor/golang.org/x/crypto/internal/poly1305/sum_asm.go
  vendor/golang.org/x/crypto/internal/poly1305/sum_loong64.s
  vendor/golang.org/x/crypto/internal/poly1305/sum_ppc64x.go
  vendor/golang.org/x/crypto/ssh/handshake.go
  vendor/golang.org/x/net/html/atom/table.go
  vendor/golang.org/x/net/html/parse.go
  vendor/golang.org/x/net/html/token.go
  vendor/golang.org/x/net/http2/frame.go
  vendor/golang.org/x/net/http2/server.go
  vendor/golang.org/x/net/websocket/websocket.go
  vendor/golang.org/x/sync/errgroup/errgroup.go
  vendor/golang.org/x/sys/cpu/cpu.go
  vendor/golang.org/x/sys/cpu/cpu_linux_loong64.go
  vendor/golang.org/x/sys/cpu/cpu_linux_noinit.go
  vendor/golang.org/x/sys/cpu/cpu_loong64.go
  vendor/golang.org/x/sys/cpu/cpu_loong64.s
  vendor/golang.org/x/sys/cpu/parse.go
  vendor/golang.org/x/sys/unix/syscall_darwin.go
  vendor/golang.org/x/sys/unix/syscall_linux.go
  vendor/golang.org/x/sys/unix/zsyscall_darwin_amd64.go
  vendor/golang.org/x/sys/unix/zsyscall_darwin_amd64.s
  vendor/golang.org/x/sys/unix/zsyscall_darwin_arm64.go
  vendor/golang.org/x/sys/unix/zsyscall_darwin_arm64.s
  vendor/golang.org/x/sys/windows/registry/key.go
  vendor/golang.org/x/sys/windows/registry/value.go
  vendor/golang.org/x/sys/windows/types_windows.go
  vendor/golang.org/x/term/terminal.go
  vendor/modules.txt
Labels: kind/bug, approved, cncf-cla: yes, size/XXL

#2524 [release-1.29] fix: CVE-2025-22872
  go.mod
  go.sum
  vendor/golang.org/x/crypto/cryptobyte/asn1.go
  vendor/golang.org/x/crypto/internal/poly1305/mac_noasm.go
  vendor/golang.org/x/crypto/internal/poly1305/sum_asm.go
  vendor/golang.org/x/crypto/internal/poly1305/sum_loong64.s
  vendor/golang.org/x/crypto/internal/poly1305/sum_ppc64x.go
  vendor/golang.org/x/crypto/ssh/handshake.go
  vendor/golang.org/x/net/html/atom/table.go
  vendor/golang.org/x/net/html/parse.go
  vendor/golang.org/x/net/html/token.go
  vendor/golang.org/x/net/http2/frame.go
  vendor/golang.org/x/net/http2/server.go
  vendor/golang.org/x/net/websocket/websocket.go
  vendor/golang.org/x/sync/errgroup/errgroup.go
  vendor/golang.org/x/sys/cpu/cpu.go
  vendor/golang.org/x/sys/cpu/cpu_linux_loong64.go
  vendor/golang.org/x/sys/cpu/cpu_linux_noinit.go
  vendor/golang.org/x/sys/cpu/cpu_loong64.go
  vendor/golang.org/x/sys/cpu/cpu_loong64.s
  vendor/golang.org/x/sys/cpu/parse.go
  vendor/golang.org/x/sys/unix/syscall_darwin.go
  vendor/golang.org/x/sys/unix/syscall_linux.go
  vendor/golang.org/x/sys/unix/zsyscall_darwin_amd64.go
  vendor/golang.org/x/sys/unix/zsyscall_darwin_amd64.s
  vendor/golang.org/x/sys/unix/zsyscall_darwin_arm64.go
  vendor/golang.org/x/sys/unix/zsyscall_darwin_arm64.s
  vendor/golang.org/x/sys/windows/registry/key.go
  vendor/golang.org/x/sys/windows/registry/value.go
  vendor/golang.org/x/sys/windows/types_windows.go
  vendor/golang.org/x/term/terminal.go
  vendor/modules.txt
Labels: kind/bug, approved, cncf-cla: yes, size/XXL

#2520 [release-1.30] fix: goroutine leak when timeout
  go.mod
  pkg/util/util.go
  pkg/util/util_test.go
  vendor/go.uber.org/goleak/.gitignore
  vendor/go.uber.org/goleak/.golangci.yml
  vendor/go.uber.org/goleak/CHANGELOG.md
  vendor/go.uber.org/goleak/LICENSE
  vendor/go.uber.org/goleak/Makefile
  vendor/go.uber.org/goleak/README.md
  vendor/go.uber.org/goleak/doc.go
  vendor/go.uber.org/goleak/internal/stack/doc.go
  vendor/go.uber.org/goleak/internal/stack/scan.go
  vendor/go.uber.org/goleak/internal/stack/stacks.go
  vendor/go.uber.org/goleak/leaks.go
  vendor/go.uber.org/goleak/options.go
  vendor/go.uber.org/goleak/testmain.go
  vendor/go.uber.org/goleak/tracestack_new.go
  vendor/modules.txt
Labels: kind/bug, approved, cncf-cla: yes, size/XXL

#2519 [release-1.31] fix: goroutine leak when timeout
  go.mod
  pkg/util/util.go
  pkg/util/util_test.go
  vendor/go.uber.org/goleak/.gitignore
  vendor/go.uber.org/goleak/.golangci.yml
  vendor/go.uber.org/goleak/CHANGELOG.md
  vendor/go.uber.org/goleak/LICENSE
  vendor/go.uber.org/goleak/Makefile
  vendor/go.uber.org/goleak/README.md
  vendor/go.uber.org/goleak/doc.go
  vendor/go.uber.org/goleak/internal/stack/doc.go
  vendor/go.uber.org/goleak/internal/stack/scan.go
  vendor/go.uber.org/goleak/internal/stack/stacks.go
  vendor/go.uber.org/goleak/leaks.go
  vendor/go.uber.org/goleak/options.go
  vendor/go.uber.org/goleak/testmain.go
  vendor/go.uber.org/goleak/tracestack_new.go
  vendor/modules.txt
Labels: kind/bug, approved, cncf-cla: yes, size/XXL

#2522 [release-1.31] fix: CVE-2025-22872
  go.mod
  go.sum
  vendor/golang.org/x/crypto/cryptobyte/asn1.go
  vendor/golang.org/x/crypto/internal/poly1305/mac_noasm.go
  vendor/golang.org/x/crypto/internal/poly1305/sum_asm.go
  vendor/golang.org/x/crypto/internal/poly1305/sum_loong64.s
  vendor/golang.org/x/crypto/internal/poly1305/sum_ppc64x.go
  vendor/golang.org/x/crypto/ssh/handshake.go
  vendor/golang.org/x/net/html/atom/table.go
  vendor/golang.org/x/net/html/parse.go
  vendor/golang.org/x/net/html/token.go
  vendor/golang.org/x/net/http2/frame.go
  vendor/golang.org/x/net/http2/server.go
  vendor/golang.org/x/net/websocket/websocket.go
  vendor/golang.org/x/sync/errgroup/errgroup.go
  vendor/golang.org/x/sys/cpu/cpu.go
  vendor/golang.org/x/sys/cpu/cpu_linux_loong64.go
  vendor/golang.org/x/sys/cpu/cpu_linux_noinit.go
  vendor/golang.org/x/sys/cpu/cpu_loong64.go
  vendor/golang.org/x/sys/cpu/cpu_loong64.s
  vendor/golang.org/x/sys/cpu/parse.go
  vendor/golang.org/x/sys/unix/syscall_darwin.go
  vendor/golang.org/x/sys/unix/syscall_linux.go
  vendor/golang.org/x/sys/unix/zsyscall_darwin_amd64.go
  vendor/golang.org/x/sys/unix/zsyscall_darwin_amd64.s
  vendor/golang.org/x/sys/unix/zsyscall_darwin_arm64.go
  vendor/golang.org/x/sys/unix/zsyscall_darwin_arm64.s
  vendor/golang.org/x/sys/windows/registry/key.go
  vendor/golang.org/x/sys/windows/registry/value.go
  vendor/golang.org/x/sys/windows/types_windows.go
  vendor/golang.org/x/term/terminal.go
  vendor/modules.txt
Labels: kind/bug, approved, cncf-cla: yes, size/XXL

#2527 test: ignore CVE-2025-22872 in azcopy
  .trivyignore
Labels: kind/failing-test, size/XS, approved, cncf-cla: yes

#2518 feat: support nfs EncryptionInTransit by azurefile-proxy
  Makefile
  charts/latest/azurefile-csi-driver-v0.0.0.tgz
  charts/latest/azurefile-csi-driver/templates/csi-azurefile-node.yaml
  charts/latest/azurefile-csi-driver/values.yaml
  deploy/csi-azurefile-node.yaml
  docs/driver-parameters.md
  hack/boilerplate/boilerplate.py
  hack/install-protoc.sh
  pkg/azurefile-proxy/README.md
  pkg/azurefile-proxy/azurefile-proxy.service
  pkg/azurefile-proxy/init.sh
  pkg/azurefile-proxy/install-proxy.sh
  pkg/azurefile-proxy/main.go
  pkg/azurefile-proxy/main_test.go
  pkg/azurefile-proxy/pb/azurefile_mount.pb.go
  pkg/azurefile-proxy/pb/azurefile_mount_grpc.pb.go
  pkg/azurefile-proxy/proto/azurefile_mount.proto
  pkg/azurefile-proxy/server/server.go
  pkg/azurefile-proxy/server/server_test.go
  pkg/azurefile/azurefile.go
  pkg/azurefile/azurefile_options.go
  pkg/azurefile/controllerserver.go
  pkg/azurefile/nodeserver.go
  pkg/azurefileplugin/Dockerfile
  pkg/csi-common/utils.go
  pkg/csi-common/utils_test.go
  vendor/github.com/stretchr/testify/require/doc.go
  vendor/github.com/stretchr/testify/require/forward_requirements.go
  vendor/github.com/stretchr/testify/require/require.go
  vendor/github.com/stretchr/testify/require/require.go.tmpl
  vendor/github.com/stretchr/testify/require/require_forward.go
  vendor/github.com/stretchr/testify/require/require_forward.go.tmpl
  vendor/github.com/stretchr/testify/require/requirements.go
  vendor/modules.txt
Labels: kind/feature, cncf-cla: yes, size/XXL

#2534 test: ut for encryptInTransit
  pkg/azurefile/controllerserver.go
  pkg/azurefile/controllerserver_test.go
Labels: size/M, lgtm, approved, cncf-cla: yes, kind/test

#2536 test: e2e test for encrypt In Transit
  Makefile
  pkg/azurefile/controllerserver.go
  test/e2e/dynamic_provisioning_test.go
  test/e2e/suite_test.go
Labels: size/M, lgtm, approved, cncf-cla: yes, kind/test

#2539 feat: add VerticalPodAutoscaler to azurefile csi controller pod
  deploy/example/vpa/README.md
  deploy/example/vpa/install-components/admission-controller-deployment.yaml
  deploy/example/vpa/install-components/delete-webhook.sh
  deploy/example/vpa/install-components/gencerts.sh
  deploy/example/vpa/install-components/recommender-deployment.yaml
  deploy/example/vpa/install-components/rmcerts.sh
  deploy/example/vpa/install-components/updater-deployment.yaml
  deploy/example/vpa/install-components/vpa-rbac.yaml
  deploy/example/vpa/install-components/vpa-v1-crd-gen.yaml
  deploy/example/vpa/install-components/warn-obsolete-vpa-objects.sh
  deploy/example/vpa/install-vpa.sh
  deploy/example/vpa/uninstall-vpa.sh
  deploy/example/vpa/vertical-pod-autoscaler.yaml
  hack/verify-yamllint.sh
Labels: kind/feature, ok-to-test, lgtm, approved, cncf-cla: yes, size/XXL

#2540 chore: upgrade snapshot sidecar image to v8.2.1
  charts/README.md
  charts/latest/azurefile-csi-driver-v0.0.0.tgz
  charts/latest/azurefile-csi-driver/values.yaml
  deploy/csi-azurefile-controller.yaml
  deploy/csi-snapshot-controller.yaml
Labels: kind/feature, size/S, approved, cncf-cla: yes

#2541 [release-1.32] chore: upgrade snapshot sidecar image to v8.2.1
  charts/README.md
  charts/latest/azurefile-csi-driver-1.32.1.tgz
  charts/latest/azurefile-csi-driver/values.yaml
  deploy/csi-azurefile-controller.yaml
  deploy/csi-snapshot-controller.yaml
Labels: kind/feature, size/S, approved, cncf-cla: yes

#2542 doc: fix snapshot crd illegal characters
  charts/latest/azurefile-csi-driver-v0.0.0.tgz
  charts/latest/azurefile-csi-driver/templates/crd-csi-snapshot.yaml
  deploy/crd-csi-snapshot.yaml
Labels: kind/bug, ok-to-test, size/XS, lgtm, approved, cncf-cla: yes

#2543 doc: add missing permission using PrivateEndpoint#2
  docs/driver-parameters.md
Labels: kind/documentation, size/XS, approved, cncf-cla: yes

#2544 chore: upgrade azcopy to v10.29.0
  .trivyignore
  pkg/azurefileplugin/Dockerfile
  test/sanity/run-test.sh
Labels: kind/feature, size/XS, approved, cncf-cla: yes
