Repository kubernetes-sigs/azurefile-csi-driver, pull requests merged in 2025-03, with the labels that each got.

#2400 fix: disable UseInstanceMetadata in controller
  pkg/azurefile/azure.go
Labels: kind/bug, size/S, approved, cncf-cla: yes

#2402 chore: upgrade Azure cloud provider lib
  go.mod
  go.sum
  vendor/github.com/AzureAD/microsoft-authentication-library-for-go/apps/internal/oauth/ops/accesstokens/accesstokens.go
  vendor/golang.org/x/exp/slices/slices.go
  vendor/golang.org/x/exp/slices/sort.go
  vendor/modules.txt
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure.go
Labels: kind/feature, size/L, lgtm, approved, cncf-cla: yes

#2401 chore: refine GetStorageAccesskey and GetFileShareClientForSub function
  pkg/azurefile/azurefile.go
  pkg/azurefile/azurefile_dataplane_client_test.go
  pkg/azurefile/azurefile_mgmt_client.go
  pkg/azurefile/azurefile_mgmt_client_test.go
  pkg/azurefile/azurefile_test.go
  pkg/azurefile/controllerserver.go
Labels: size/L, kind/cleanup, do-not-merge/hold, approved, cncf-cla: yes

#2403 fix: incomplete azcopy job state during volume snapshot restore and clone
  pkg/util/util.go
  pkg/util/util_test.go
Labels: kind/bug, size/M, approved, cncf-cla: yes

#2415 fix: account match algorithm when source account name is provided
  go.mod
  go.sum
  vendor/modules.txt
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/storage/azure_storageaccount.go
Labels: kind/bug, size/S, approved, cncf-cla: yes

#2417 doc: cut v1.32.0 release
  README.md
  charts/index.yaml
  charts/latest/azurefile-csi-driver-v0.0.0.tgz
  charts/v1.32.0/azurefile-csi-driver-1.32.0.tgz
  charts/v1.32.0/azurefile-csi-driver/Chart.yaml
  charts/v1.32.0/azurefile-csi-driver/templates/NOTES.txt
  charts/v1.32.0/azurefile-csi-driver/templates/_helpers.tpl
  charts/v1.32.0/azurefile-csi-driver/templates/crd-csi-snapshot.yaml
  charts/v1.32.0/azurefile-csi-driver/templates/csi-azurefile-controller.yaml
  charts/v1.32.0/azurefile-csi-driver/templates/csi-azurefile-driver.yaml
  charts/v1.32.0/azurefile-csi-driver/templates/csi-azurefile-node-windows-hostprocess.yaml
  charts/v1.32.0/azurefile-csi-driver/templates/csi-azurefile-node-windows.yaml
  charts/v1.32.0/azurefile-csi-driver/templates/csi-azurefile-node.yaml
  charts/v1.32.0/azurefile-csi-driver/templates/csi-snapshot-controller.yaml
  charts/v1.32.0/azurefile-csi-driver/templates/rbac-csi-azurefile-controller.yaml
  charts/v1.32.0/azurefile-csi-driver/templates/rbac-csi-azurefile-node.yaml
  charts/v1.32.0/azurefile-csi-driver/templates/rbac-csi-snapshot-controller.yaml
  charts/v1.32.0/azurefile-csi-driver/templates/serviceaccount-csi-azurefile-controller.yaml
  charts/v1.32.0/azurefile-csi-driver/templates/serviceaccount-csi-azurefile-node.yaml
  charts/v1.32.0/azurefile-csi-driver/templates/serviceaccount-csi-snapshot-controller.yaml
  charts/v1.32.0/azurefile-csi-driver/values.yaml
  deploy/v1.32.0/crd-csi-snapshot.yaml
  deploy/v1.32.0/csi-azurefile-controller.yaml
  deploy/v1.32.0/csi-azurefile-driver.yaml
  deploy/v1.32.0/csi-azurefile-node-windows-hostprocess.yaml
  deploy/v1.32.0/csi-azurefile-node-windows.yaml
  deploy/v1.32.0/csi-azurefile-node.yaml
  deploy/v1.32.0/csi-snapshot-controller.yaml
  deploy/v1.32.0/rbac-csi-azurefile-controller.yaml
  deploy/v1.32.0/rbac-csi-azurefile-node.yaml
  deploy/v1.32.0/rbac-csi-snapshot-controller.yaml
  docs/install-azurefile-csi-driver.md
  docs/install-csi-driver-v1.32.0.md
Labels: kind/documentation, approved, cncf-cla: yes, size/XXL

#2421 [release-1.31] chore: upgrade csi-resizer image version
  charts/README.md
  charts/latest/azurefile-csi-driver-1.31.4.tgz
  charts/latest/azurefile-csi-driver/values.yaml
  deploy/csi-azurefile-controller.yaml
Labels: kind/feature, size/XS, approved, cncf-cla: yes

#2420 [release-1.32] chore: upgrade csi-resizer image version
  charts/README.md
  charts/latest/azurefile-csi-driver-1.32.0.tgz
  charts/latest/azurefile-csi-driver/values.yaml
  deploy/csi-azurefile-controller.yaml
Labels: kind/feature, size/XS, approved, cncf-cla: yes

#2419 chore: upgrade csi-resizer image version
  charts/README.md
  charts/latest/azurefile-csi-driver-v0.0.0.tgz
  charts/latest/azurefile-csi-driver/values.yaml
  deploy/csi-azurefile-controller.yaml
Labels: kind/feature, size/XS, approved, cncf-cla: yes

#2426 [release-1.31] chore: increase liveness-probe timeout
  charts/latest/azurefile-csi-driver-1.31.4.tgz
  charts/latest/azurefile-csi-driver/templates/csi-azurefile-node.yaml
  charts/v1.31.4/azurefile-csi-driver-1.31.4.tgz
  charts/v1.31.4/azurefile-csi-driver/templates/csi-azurefile-node.yaml
  deploy/v1.31.4/csi-azurefile-node.yaml
Labels: kind/bug, size/S, approved, cncf-cla: yes

#2424 chore: increase liveness-probe timeout
  charts/latest/azurefile-csi-driver-v0.0.0.tgz
  charts/latest/azurefile-csi-driver/templates/csi-azurefile-node.yaml
  charts/v1.30.8/azurefile-csi-driver-v1.30.8.tgz
  charts/v1.30.8/azurefile-csi-driver/templates/csi-azurefile-node.yaml
  charts/v1.31.4/azurefile-csi-driver-1.31.4.tgz
  charts/v1.31.4/azurefile-csi-driver/templates/csi-azurefile-node.yaml
  charts/v1.32.0/azurefile-csi-driver-1.32.0.tgz
  charts/v1.32.0/azurefile-csi-driver/templates/csi-azurefile-node.yaml
  deploy/v1.30.8/csi-azurefile-node.yaml
  deploy/v1.31.4/csi-azurefile-node.yaml
  deploy/v1.32.0/csi-azurefile-node.yaml
Labels: kind/bug, size/S, approved, cncf-cla: yes

#2433 chore: fix ShareQuota nil issue
  pkg/azurefile/azurefile.go
Labels: kind/bug, size/XS, approved, cncf-cla: yes

#2436 test: fix GetAccountNumByResourceGroup timeout
  test/e2e/suite_test.go
Labels: kind/failing-test, size/XS, approved, cncf-cla: yes

#2434 chore: upgrade azure cloud provider lib
  .github/workflows/static.yaml
  .trivyignore
  go.mod
  go.sum
  pkg/azurefile/controllerserver.go
  pkg/csi-common/driver.go
  pkg/csi-common/utils.go
  pkg/csi-common/utils_test.go
  vendor/github.com/Azure/msi-dataplane/pkg/dataplane/reloadCredentials.go
  vendor/github.com/prometheus/client_golang/prometheus/atomic_update.go
  vendor/github.com/prometheus/client_golang/prometheus/counter.go
  vendor/github.com/prometheus/client_golang/prometheus/gauge.go
  vendor/github.com/prometheus/client_golang/prometheus/histogram.go
  vendor/github.com/prometheus/client_golang/prometheus/process_collector_darwin.go
  vendor/github.com/prometheus/client_golang/prometheus/process_collector_mem_cgo_darwin.c
  vendor/github.com/prometheus/client_golang/prometheus/process_collector_mem_cgo_darwin.go
  vendor/github.com/prometheus/client_golang/prometheus/process_collector_mem_nocgo_darwin.go
  vendor/github.com/prometheus/client_golang/prometheus/process_collector_not_supported.go
  vendor/github.com/prometheus/client_golang/prometheus/process_collector_procfsenabled.go
  vendor/github.com/prometheus/client_golang/prometheus/summary.go
  vendor/go.opentelemetry.io/otel/exporters/prometheus/exporter.go
  vendor/go.opentelemetry.io/otel/sdk/metric/internal/aggregate/exponential_histogram.go
  vendor/go.opentelemetry.io/otel/sdk/metric/version.go
  vendor/go.opentelemetry.io/otel/sdk/resource/os_release_darwin.go
  vendor/go.opentelemetry.io/otel/sdk/resource/resource.go
  vendor/go.opentelemetry.io/otel/sdk/trace/batch_span_processor.go
  vendor/go.opentelemetry.io/otel/sdk/trace/sampling.go
  vendor/go.opentelemetry.io/otel/sdk/trace/simple_span_processor.go
  vendor/go.opentelemetry.io/otel/sdk/version.go
  vendor/modules.txt
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azclient/accountclient/custom.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azclient/blobcontainerclient/custom.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azclient/blobservicepropertiesclient/custom.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azclient/fileservicepropertiesclient/custom.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azclient/fileshareclient/custom.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_controller_vmss.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/trace/provider.go
Labels: kind/feature, size/XL, approved, cncf-cla: yes

#2442 [release-1.28] fix: CVE-2025-30204
  .trivyignore
  go.mod
  go.sum
  vendor/github.com/golang-jwt/jwt/v4/parser.go
  vendor/modules.txt
Labels: kind/bug, size/M, approved, cncf-cla: yes

#2443 fix: CVE-2025-30204
  .trivyignore
  go.mod
  go.sum
  vendor/github.com/golang-jwt/jwt/v5/README.md
  vendor/github.com/golang-jwt/jwt/v5/SECURITY.md
  vendor/github.com/golang-jwt/jwt/v5/parser.go
  vendor/github.com/golang-jwt/jwt/v5/token.go
  vendor/modules.txt
Labels: kind/bug, size/M, approved, cncf-cla: yes

#2444 cleanup: refine DataplaneClient
  pkg/azurefile/azurefile_dataplane_client.go
  pkg/azurefile/azurefile_dataplane_client_test.go
Labels: kind/cleanup, size/S, approved, cncf-cla: yes

#2445 [release-1.32] fix: CVE-2025-30204
  .trivyignore
  go.mod
  go.sum
  vendor/github.com/golang-jwt/jwt/v5/README.md
  vendor/github.com/golang-jwt/jwt/v5/SECURITY.md
  vendor/github.com/golang-jwt/jwt/v5/parser.go
  vendor/github.com/golang-jwt/jwt/v5/token.go
  vendor/modules.txt
Labels: kind/bug, size/M, approved, cncf-cla: yes

#2451 [release-1.31] fix: CVE-2025-30204
  .trivyignore
  go.mod
  go.sum
  vendor/github.com/golang-jwt/jwt/v4/parser.go
  vendor/github.com/golang-jwt/jwt/v5/README.md
  vendor/github.com/golang-jwt/jwt/v5/SECURITY.md
  vendor/github.com/golang-jwt/jwt/v5/parser.go
  vendor/github.com/golang-jwt/jwt/v5/token.go
  vendor/modules.txt
Labels: kind/bug, size/L, approved, cncf-cla: yes

#2447 test: increase e2e test timeout
  Makefile
  test/e2e/testsuites/dynamically_provisioned_cmd_volume_tester.go
  test/e2e/testsuites/testsuites.go
Labels: size/S, kind/failing-test, approved, cncf-cla: yes

#2346 azurefile: kata/kata-cc: add kata node conditional
  charts/latest/azurefile-csi-driver-v0.0.0.tgz
  charts/latest/azurefile-csi-driver/templates/rbac-csi-azurefile-node.yaml
  deploy/example/kata-cc/statefulset.yaml
  deploy/example/kata-cc/storageclass-azurefile-kata-cc.yaml
  deploy/rbac-csi-azurefile-node.yaml
  pkg/azurefile/azurefile.go
  pkg/azurefile/azurefile_test.go
  pkg/azurefile/controllerserver.go
  pkg/azurefile/nodeserver.go
  pkg/azurefile/nodeserver_test.go
  pkg/azurefile/utils.go
Labels: size/L, ok-to-test, lgtm, approved, cncf-cla: yes

#2459 [release-1.32] feat: add kata node conditional
  charts/latest/azurefile-csi-driver-1.32.0.tgz
  charts/latest/azurefile-csi-driver/templates/rbac-csi-azurefile-node.yaml
  deploy/example/kata-cc/statefulset.yaml
  deploy/example/kata-cc/storageclass-azurefile-kata-cc.yaml
  deploy/rbac-csi-azurefile-node.yaml
  pkg/azurefile/azurefile.go
  pkg/azurefile/azurefile_test.go
  pkg/azurefile/controllerserver.go
  pkg/azurefile/nodeserver.go
  pkg/azurefile/nodeserver_test.go
  pkg/azurefile/utils.go
Labels: kind/feature, size/L, approved, cncf-cla: yes

#2463 chore: upgrade azcopy to v10.28.1
  .trivyignore
  pkg/azurefileplugin/Dockerfile
  test/sanity/run-test.sh
Labels: kind/feature, size/XS, approved, cncf-cla: yes

#2461 azurefile: add kata-cc-isolation node label check
  pkg/azurefile/azurefile.go
  pkg/azurefile/azurefile_test.go
Labels: ok-to-test, size/S, cncf-cla: yes

#2464 [release-1.32] chore: upgrade azcopy to v10.28.1
  .trivyignore
  pkg/azurefileplugin/Dockerfile
  test/sanity/run-test.sh
Labels: kind/feature, size/XS, approved, cncf-cla: yes

#2469 [release-1.28] chore: upgrade azcopy to v10.28.1
  .trivyignore
  pkg/azurefileplugin/Dockerfile
  test/sanity/run-test.sh
Labels: kind/feature, size/XS, approved, cncf-cla: yes

#2471 test: set ginkgo timeout as 180m
  Makefile
Labels: ok-to-test, size/XS, lgtm, approved, cncf-cla: yes, kind/test
