Repository kubernetes-sigs/azurefile-csi-driver, pull requests merged in 2025-02, with the labels that each got.

#2370 test: fix CVE-2025-22866 in trivy action
  .github/workflows/trivy.yaml
  .trivyignore
Labels: kind/failing-test, size/XS, approved, cncf-cla: yes

#2376 [release-1.30] fix: incorrect affinity chart config
  charts/latest/azurefile-csi-driver-v1.30.7.tgz
  charts/latest/azurefile-csi-driver/templates/csi-azurefile-controller.yaml
  charts/latest/azurefile-csi-driver/templates/csi-snapshot-controller.yaml
Labels: kind/bug, size/XS, approved, cncf-cla: yes

#2374 fix: incorrect affinity chart config
  charts/latest/azurefile-csi-driver-v0.0.0.tgz
  charts/latest/azurefile-csi-driver/templates/csi-azurefile-controller.yaml
  charts/latest/azurefile-csi-driver/templates/csi-snapshot-controller.yaml
Labels: kind/bug, size/XS, approved, cncf-cla: yes

#2375 [release-1.31] fix: incorrect affinity chart config
  charts/latest/azurefile-csi-driver-1.31.3.tgz
  charts/latest/azurefile-csi-driver/templates/csi-azurefile-controller.yaml
  charts/latest/azurefile-csi-driver/templates/csi-snapshot-controller.yaml
Labels: kind/bug, size/XS, approved, cncf-cla: yes

#2369 test: improve ut coverage
  pkg/azurefile/controllerserver_test.go
Labels: size/M, lgtm, approved, cncf-cla: yes

#2378 doc: fix volumeHandle doc
  deploy/example/pv-azurefile-csi.yaml
  deploy/example/pv-azurefile-nfs.yaml
  docs/workload-identity-static-pv-mount.md
Labels: kind/documentation, size/XS, approved, cncf-cla: yes

#2379 fix: CVE-2025-0426
  go.mod
  go.sum
  vendor/k8s.io/kubernetes/pkg/features/kube_features.go
  vendor/k8s.io/kubernetes/pkg/features/versioned_kube_features.go
  vendor/k8s.io/kubernetes/pkg/kubelet/apis/config/types.go
  vendor/k8s.io/kubernetes/pkg/volume/util/device_util_linux.go
  vendor/k8s.io/kubernetes/test/e2e/testing-manifests/storage-csi/gce-pd/controller_ss.yaml
  vendor/k8s.io/kubernetes/test/e2e/testing-manifests/storage-csi/hostpath/hostpath/csi-hostpath-plugin.yaml
  vendor/k8s.io/kubernetes/test/e2e/testing-manifests/storage-csi/mock/csi-mock-driver-attacher.yaml
  vendor/k8s.io/kubernetes/test/e2e/testing-manifests/storage-csi/mock/csi-mock-driver-resizer.yaml
  vendor/k8s.io/kubernetes/test/e2e/testing-manifests/storage-csi/mock/csi-mock-driver-snapshotter.yaml
  vendor/k8s.io/kubernetes/test/e2e/testing-manifests/storage-csi/mock/csi-mock-driver.yaml
  vendor/k8s.io/kubernetes/test/e2e/testing-manifests/storage-csi/mock/csi-mock-proxy.yaml
  vendor/k8s.io/kubernetes/test/utils/image/manifest.go
  vendor/modules.txt
Labels: kind/bug, size/M, approved, cncf-cla: yes

#2381 [release-1.30] fix: CVE-2025-0426
  go.mod
  go.sum
  vendor/k8s.io/api/admissionregistration/v1/types.go
  vendor/k8s.io/api/admissionregistration/v1alpha1/types.go
  vendor/k8s.io/api/admissionregistration/v1beta1/types.go
  vendor/k8s.io/api/batch/v1/types.go
  vendor/k8s.io/api/core/v1/generated.proto
  vendor/k8s.io/api/core/v1/types.go
  vendor/k8s.io/apimachinery/pkg/util/httpstream/httpstream.go
  vendor/k8s.io/apiserver/pkg/features/kube_features.go
  vendor/k8s.io/apiserver/pkg/server/config.go
  vendor/k8s.io/apiserver/pkg/server/filters/maxinflight.go
  vendor/k8s.io/apiserver/pkg/server/options/etcd.go
  vendor/k8s.io/apiserver/pkg/server/options/tracing.go
  vendor/k8s.io/apiserver/pkg/storage/cacher/cacher.go
  vendor/k8s.io/client-go/applyconfigurations/internal/internal.go
  vendor/k8s.io/client-go/tools/remotecommand/v4.go
  vendor/k8s.io/kubernetes/pkg/features/kube_features.go
  vendor/k8s.io/kubernetes/pkg/volume/util/atomic_writer.go
  vendor/k8s.io/kubernetes/pkg/volume/util/atomic_writer_linux.go
  vendor/k8s.io/kubernetes/pkg/volume/util/atomic_writer_unsupported.go
  vendor/k8s.io/kubernetes/pkg/volume/util/device_util_linux.go
  vendor/k8s.io/kubernetes/pkg/volume/util/recyclerclient/recycler_client.go
  vendor/k8s.io/kubernetes/pkg/volume/util/util.go
  vendor/k8s.io/kubernetes/test/e2e/framework/flake_reporting_util.go
  vendor/k8s.io/kubernetes/test/e2e/framework/framework.go
  vendor/k8s.io/kubernetes/test/e2e/framework/node/resource.go
  vendor/k8s.io/kubernetes/test/e2e/framework/skipper/skipper.go
  vendor/k8s.io/kubernetes/test/utils/density_utils.go
  vendor/k8s.io/kubernetes/test/utils/deployment.go
  vendor/k8s.io/kubernetes/test/utils/image/manifest.go
  vendor/k8s.io/kubernetes/test/utils/runners.go
  vendor/modules.txt
Labels: kind/bug, size/L, approved, cncf-cla: yes

#2380 [release-1.31] fix: CVE-2025-0426
  go.mod
  go.sum
  vendor/k8s.io/api/admissionregistration/v1/types.go
  vendor/k8s.io/api/admissionregistration/v1alpha1/types.go
  vendor/k8s.io/api/admissionregistration/v1beta1/types.go
  vendor/k8s.io/api/batch/v1/types.go
  vendor/k8s.io/api/core/v1/generated.proto
  vendor/k8s.io/api/core/v1/types.go
  vendor/k8s.io/apimachinery/pkg/util/httpstream/httpstream.go
  vendor/k8s.io/apiserver/pkg/features/kube_features.go
  vendor/k8s.io/apiserver/pkg/server/config.go
  vendor/k8s.io/apiserver/pkg/server/filters/maxinflight.go
  vendor/k8s.io/apiserver/pkg/server/options/etcd.go
  vendor/k8s.io/apiserver/pkg/server/options/tracing.go
  vendor/k8s.io/apiserver/pkg/storage/cacher/cacher.go
  vendor/k8s.io/client-go/applyconfigurations/internal/internal.go
  vendor/k8s.io/client-go/tools/remotecommand/v4.go
  vendor/k8s.io/kubernetes/pkg/features/kube_features.go
  vendor/k8s.io/kubernetes/pkg/volume/util/atomic_writer.go
  vendor/k8s.io/kubernetes/pkg/volume/util/atomic_writer_linux.go
  vendor/k8s.io/kubernetes/pkg/volume/util/atomic_writer_unsupported.go
  vendor/k8s.io/kubernetes/pkg/volume/util/device_util_linux.go
  vendor/k8s.io/kubernetes/pkg/volume/util/recyclerclient/recycler_client.go
  vendor/k8s.io/kubernetes/pkg/volume/util/util.go
  vendor/k8s.io/kubernetes/test/e2e/framework/flake_reporting_util.go
  vendor/k8s.io/kubernetes/test/e2e/framework/framework.go
  vendor/k8s.io/kubernetes/test/e2e/framework/node/resource.go
  vendor/k8s.io/kubernetes/test/e2e/framework/skipper/skipper.go
  vendor/k8s.io/kubernetes/test/utils/density_utils.go
  vendor/k8s.io/kubernetes/test/utils/deployment.go
  vendor/k8s.io/kubernetes/test/utils/image/manifest.go
  vendor/k8s.io/kubernetes/test/utils/runners.go
  vendor/modules.txt
Labels: kind/bug, size/L, approved, cncf-cla: yes

#2385 feat: optimize azcopy perf in volume snapshot restore and cloning scenario
  charts/latest/azurefile-csi-driver-v0.0.0.tgz
  charts/latest/azurefile-csi-driver/templates/csi-azurefile-controller.yaml
  deploy/csi-azurefile-controller.yaml
  pkg/azurefile/azurefile.go
Labels: kind/feature, size/S, approved, cncf-cla: yes

#2388 [release-1.30] feat: optimize azcopy perf in volume snapshot restore and cloning
  charts/latest/azurefile-csi-driver-v1.30.7.tgz
  charts/latest/azurefile-csi-driver/templates/csi-azurefile-controller.yaml
  deploy/csi-azurefile-controller.yaml
  pkg/azurefile/azurefile.go
Labels: kind/feature, size/S, approved, cncf-cla: yes

#2389 cleanup: print info error for volumeID parsing
  pkg/azurefile/azurefile.go
Labels: kind/cleanup, size/XS, approved, cncf-cla: yes

#2394 fix: cleanup azcopy jobs after job complete
  pkg/azurefile/azurefile.go
  pkg/azurefile/controllerserver.go
  pkg/util/util.go
  pkg/util/util_test.go
Labels: kind/bug, size/M, approved, cncf-cla: yes
