Repository kubernetes-sigs/azurefile-csi-driver, pull requests merged in 2025-05, with the labels that each got.

#2552 feat: add VNetLinkName and PublicNetworkAccess in account creation
  docs/driver-parameters.md
  go.mod
  go.sum
  pkg/azurefile/azurefile.go
  pkg/azurefile/azurefile_test.go
  pkg/azurefile/controllerserver.go
  pkg/azurefile/controllerserver_test.go
  test/e2e/dynamic_provisioning_test.go
  vendor/modules.txt
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azclient/utils/poller.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azclient/virtualmachinescalesetvmclient/custom.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azclient/virtualmachinescalesetvmclient/interface.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azclient/virtualmachinescalesetvmclient/mock_virtualmachinescalesetvmclient/interface.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/consts/consts.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_controller_standard.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_controller_vmss.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_controller_vmssflex.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_loadbalancer.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_local_services.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/storage/azure_storageaccount.go
Labels: kind/feature, size/L, approved, cncf-cla: yes

#2553 [release-1.32] feat: add VNetLinkName and PublicNetworkAccess in account creation
  docs/driver-parameters.md
  go.mod
  go.sum
  pkg/azurefile/azurefile.go
  pkg/azurefile/azurefile_test.go
  pkg/azurefile/controllerserver.go
  pkg/azurefile/controllerserver_test.go
  test/e2e/dynamic_provisioning_test.go
  vendor/modules.txt
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/consts/consts.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_loadbalancer.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/storage/azure_storageaccount.go
Labels: kind/feature, size/L, approved, cncf-cla: yes

#2557 doc: correct permissions for PrivateEndpoint
  docs/driver-parameters.md
Labels: ok-to-test, kind/documentation, size/XS, lgtm, approved, cncf-cla: yes

#2550 fix: install aznfs on azure linux
  charts/latest/azurefile-csi-driver-v0.0.0.tgz
  charts/latest/azurefile-csi-driver/templates/csi-azurefile-node.yaml
  pkg/azurefile-proxy/install-proxy.sh
Labels: kind/cleanup, size/S, lgtm, approved, cncf-cla: yes

#2563 [release-1.32] fix: delete snapshot should not delete file share
  go.mod
  go.sum
  pkg/azurefile/controllerserver.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/containerservice/armcontainerservice/v6/CHANGELOG.md
  vendor/github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/containerservice/armcontainerservice/v6/agentpools_client.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/containerservice/armcontainerservice/v6/assets.json
  vendor/github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/containerservice/armcontainerservice/v6/autorest.md
  vendor/github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/containerservice/armcontainerservice/v6/ci.yml
  vendor/github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/containerservice/armcontainerservice/v6/constants.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/containerservice/armcontainerservice/v6/machines_client.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/containerservice/armcontainerservice/v6/maintenanceconfigurations_client.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/containerservice/armcontainerservice/v6/managedclusters_client.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/containerservice/armcontainerservice/v6/models.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/containerservice/armcontainerservice/v6/models_serde.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/containerservice/armcontainerservice/v6/operations_client.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/containerservice/armcontainerservice/v6/privateendpointconnections_client.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/containerservice/armcontainerservice/v6/privatelinkresources_client.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/containerservice/armcontainerservice/v6/resolveprivatelinkserviceid_client.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/containerservice/armcontainerservice/v6/snapshots_client.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/containerservice/armcontainerservice/v6/trustedaccessrolebindings_client.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/containerservice/armcontainerservice/v6/trustedaccessroles_client.go
  vendor/golang.org/x/crypto/cryptobyte/asn1.go
  vendor/golang.org/x/crypto/internal/poly1305/mac_noasm.go
  vendor/golang.org/x/crypto/internal/poly1305/sum_asm.go
  vendor/golang.org/x/crypto/internal/poly1305/sum_loong64.s
  vendor/golang.org/x/crypto/internal/poly1305/sum_ppc64x.go
  vendor/golang.org/x/crypto/ssh/handshake.go
  vendor/golang.org/x/crypto/ssh/mlkem.go
  vendor/golang.org/x/sync/errgroup/errgroup.go
  vendor/golang.org/x/sys/cpu/cpu.go
  vendor/golang.org/x/sys/cpu/cpu_linux_riscv64.go
  vendor/golang.org/x/sys/cpu/cpu_riscv64.go
  vendor/golang.org/x/sys/windows/security_windows.go
  vendor/golang.org/x/sys/windows/syscall_windows.go
  vendor/golang.org/x/sys/windows/types_windows.go
  vendor/golang.org/x/sys/windows/zsyscall_windows.go
  vendor/golang.org/x/term/terminal.go
  vendor/golang.org/x/tools/go/ast/inspector/inspector.go
  vendor/golang.org/x/tools/go/ast/inspector/typeof.go
  vendor/k8s.io/utils/clock/testing/fake_clock.go
  vendor/modules.txt
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azclient/arm_conf.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azclient/fileshareclient/custom.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azclient/fileshareclient/interface.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azclient/fileshareclient/mock_fileshareclient/interface.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azclient/policy/retryaftermin/retryaftermin.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azclient/virtualnetworklinkclient/interface.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azclient/virtualnetworklinkclient/mock_virtualnetworklinkclient/interface.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azclient/virtualnetworklinkclient/zz_generated_client.go
Labels: kind/bug, approved, cncf-cla: yes, size/XXL

#2565 doc: cut v1.33.0 release
  README.md
  charts/index.yaml
  charts/latest/azurefile-csi-driver-v0.0.0.tgz
  charts/v1.33.0/azurefile-csi-driver-1.33.0.tgz
  charts/v1.33.0/azurefile-csi-driver/Chart.yaml
  charts/v1.33.0/azurefile-csi-driver/templates/NOTES.txt
  charts/v1.33.0/azurefile-csi-driver/templates/_helpers.tpl
  charts/v1.33.0/azurefile-csi-driver/templates/crd-csi-snapshot.yaml
  charts/v1.33.0/azurefile-csi-driver/templates/csi-azurefile-controller.yaml
  charts/v1.33.0/azurefile-csi-driver/templates/csi-azurefile-driver.yaml
  charts/v1.33.0/azurefile-csi-driver/templates/csi-azurefile-node-windows-hostprocess.yaml
  charts/v1.33.0/azurefile-csi-driver/templates/csi-azurefile-node-windows.yaml
  charts/v1.33.0/azurefile-csi-driver/templates/csi-azurefile-node.yaml
  charts/v1.33.0/azurefile-csi-driver/templates/csi-snapshot-controller.yaml
  charts/v1.33.0/azurefile-csi-driver/templates/rbac-csi-azurefile-controller.yaml
  charts/v1.33.0/azurefile-csi-driver/templates/rbac-csi-azurefile-node.yaml
  charts/v1.33.0/azurefile-csi-driver/templates/rbac-csi-snapshot-controller.yaml
  charts/v1.33.0/azurefile-csi-driver/templates/serviceaccount-csi-azurefile-controller.yaml
  charts/v1.33.0/azurefile-csi-driver/templates/serviceaccount-csi-azurefile-node.yaml
  charts/v1.33.0/azurefile-csi-driver/templates/serviceaccount-csi-snapshot-controller.yaml
  charts/v1.33.0/azurefile-csi-driver/values.yaml
  deploy/v1.33.0/crd-csi-snapshot.yaml
  deploy/v1.33.0/csi-azurefile-controller.yaml
  deploy/v1.33.0/csi-azurefile-driver.yaml
  deploy/v1.33.0/csi-azurefile-node-windows-hostprocess.yaml
  deploy/v1.33.0/csi-azurefile-node-windows.yaml
  deploy/v1.33.0/csi-azurefile-node.yaml
  deploy/v1.33.0/csi-snapshot-controller.yaml
  deploy/v1.33.0/rbac-csi-azurefile-controller.yaml
  deploy/v1.33.0/rbac-csi-azurefile-node.yaml
  deploy/v1.33.0/rbac-csi-snapshot-controller.yaml
  docs/install-azurefile-csi-driver.md
  docs/install-csi-driver-v1.33.0.md
Labels: kind/documentation, approved, cncf-cla: yes, size/XXL

#2577 azurefile: revert to use virtio-fs for kata pods
  pkg/azurefile/azurefile.go
  pkg/azurefile/azurefile_test.go
  pkg/azurefile/utils.go
Labels: ok-to-test, size/XS, lgtm, approved, cncf-cla: yes

#2583 chore: upgrade azcopy to v10.29.1
  .trivyignore
  pkg/azurefileplugin/Dockerfile
  test/sanity/run-test.sh
Labels: kind/feature, size/XS, approved, cncf-cla: yes
